FIND_ALL_AGENCIES {
    SELECT ROWNUM AS ID,
           AGY_LOC_ID AS AGENCY_ID,
           DESCRIPTION,
           AGENCY_LOCATION_TYPE
      FROM AGENCY_LOCATIONS
     WHERE ACTIVE_FLAG = 'Y'
           AND AGY_LOC_ID NOT IN ('OUT', 'TRN')
  ORDER BY AGY_LOC_ID
}

