
FIND_INMATES_BY_LOCATION {
    SELECT B.OFFENDER_BOOK_ID,
           B.BOOKING_NO,
           O.OFFENDER_ID_DISPLAY,
           O.FIRST_NAME,
           O.LAST_NAME,
           B.LIVING_UNIT_ID
      FROM OFFENDER_BOOKINGS B LEFT JOIN OFFENDERS O ON B.OFFENDER_ID = O.OFFENDER_ID
     WHERE B.LIVING_UNIT_ID IN (
           SELECT INTERNAL_LOCATION_ID
           FROM AGENCY_INTERNAL_LOCATIONS START WITH INTERNAL_LOCATION_ID = :locationId
           CONNECT BY PARENT_INTERNAL_LOCATION_ID = PRIOR INTERNAL_LOCATION_ID
     )
}

FIND_ALERT_CODES_BY_BOOKING_ID {
    SELECT A.ALERT_CODE
      FROM OFFENDER_ALERTS A
     WHERE A.OFFENDER_BOOK_ID = :bookingId AND A.ALERT_STATUS = 'ACTIVE'
}

