FIND_LOCATIONS_BY_AGENCY_ID {
	 -- Internal Agency Locations (PILOT VERSION)
	 SELECT A.INTERNAL_LOCATION_ID,
	  		  A.AGY_LOC_ID,
	  		  A.INTERNAL_LOCATION_TYPE,
	  		  A.DESCRIPTION,
	  		  A.PARENT_INTERNAL_LOCATION_ID,
	  		  A.NO_OF_OCCUPANT,
	  		  (SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = (SELECT HOUSING_UNIT_TYPE FROM LIVING_UNITS WHERE LIVING_UNIT_ID = A.INTERNAL_LOCATION_ID) AND DOMAIN='HOU_UN_TYPE') AS HOUSING_UNIT_TYPE
	   FROM	AGENCY_INTERNAL_LOCATIONS A
	  WHERE	A.ACTIVE_FLAG = 'Y'
			    AND A.AGY_LOC_ID = :agencyId --  This clause is for the pilot only
			    -- AND A.INTERNAL_LOCATION_TYPE != 'BLOCK' --  This clause is for the pilot only
}

FIND_ALL_LOCATIONS {
	 -- Internal Agency Locations (PILOT VERSION)
	 SELECT A.INTERNAL_LOCATION_ID,
	  		  A.AGY_LOC_ID,
	  		  A.INTERNAL_LOCATION_TYPE,
	  		  A.DESCRIPTION,
	  		  A.PARENT_INTERNAL_LOCATION_ID,
	  		  A.NO_OF_OCCUPANT,
	  		  (SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = (SELECT HOUSING_UNIT_TYPE FROM LIVING_UNITS WHERE LIVING_UNIT_ID = A.INTERNAL_LOCATION_ID) AND DOMAIN='HOU_UN_TYPE') AS HOUSING_UNIT_TYPE
	   FROM	AGENCY_INTERNAL_LOCATIONS A
	  WHERE	A.ACTIVE_FLAG = 'Y'
}

FIND_LOCATION {
	 -- Internal Agency Locations (PILOT VERSION)
	 SELECT A.INTERNAL_LOCATION_ID,
	  		  A.AGY_LOC_ID,
	  		  A.INTERNAL_LOCATION_TYPE,
	  		  A.DESCRIPTION,
	  		  A.PARENT_INTERNAL_LOCATION_ID,
	  		  A.NO_OF_OCCUPANT,
	  		  (SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = (SELECT HOUSING_UNIT_TYPE FROM LIVING_UNITS WHERE LIVING_UNIT_ID = A.INTERNAL_LOCATION_ID) AND DOMAIN='HOU_UN_TYPE') AS HOUSING_UNIT_TYPE
	   FROM	AGENCY_INTERNAL_LOCATIONS A
	  WHERE	A.INTERNAL_LOCATION_ID = :locationId AND A.ACTIVE_FLAG = 'Y'
}
