/{agencyId}/groups/{name}:
  (javaOperationName): getGroupEvents
  uriParameters:
    agencyId:
      type: string
      description: The prison.
    name:
      type: string
      description: The location list name.
  get:
    queryParameters:
      date?:
        type : date-only
        description: Date of whereabouts list, default today
      timeSlot?:
        type : enum
        (javaType): TimeSlot
        description: AM, PM or ED
  type: { readOnlyCollection: { type: PrisonerSchedule, description: Get all events for given date for prisoners in listed cells. Note secondary sort is by start time} }
  is: [
      sortable: {fieldsList : "cellLocation or lastName"},
  ]

/{agencyId}/locations/{locationId}/usage/{usage}:
  (javaOperationName): getLocationEvents
  uriParameters:
    agencyId:
      type: string
      description: The prison.
    locationId:
      (javaType): Long
      description: The location id where event is held.
    usage:
      type: string
      description: The locationUsage code from the location object - one of the INTERNAL_LOCATION_USAGE reference codes.
  get:
    queryParameters:
      date?:
        type : date-only
        description: Date of whereabouts list, default today
      timeSlot?:
        type : enum
        (javaType): TimeSlot
        description: AM, PM or ED
  type: { readOnlyCollection: { type: PrisonerSchedule, description: Get all Prisoner events for given date at location. } }
  is: [
      sortable: {fieldsList : "cellLocation or lastName"},
  ]

/{agencyId}/visits:
  post:
    (javaOperationName): getVisits
    uriParameters:
      agencyId:
        type: string
        description: The prison.
    queryParameters:
      date?:
        type : date-only
        description: Date of whereabouts list, default today
      timeSlot?:
        type : enum
        (javaType): TimeSlot
        description: AM, PM or ED
    body:
      application/json:
           (javaType): List<String>
           description: The required offender numbers (mandatory)
    responses:
          200:
            body:
              application/json:
                 type: PrisonerSchedule[]

/{agencyId}/appointments:
  post:
    (javaOperationName): getAppointments
    uriParameters:
      agencyId:
        type: string
        description: The prison.
    queryParameters:
      date?:
        type : date-only
        description: Date of whereabouts list, default today
      timeSlot?:
        type : enum
        (javaType): TimeSlot
        description: AM, PM or ED
    body:
      application/json:
           (javaType): List<String>
           description: The required offender numbers (mandatory)
    responses:
          200:
            body:
              application/json:
                 type: PrisonerSchedule[]

/{agencyId}/activities:
  post:
    (javaOperationName): getActivities
    uriParameters:
      agencyId:
        type: string
        description: The prison.
    queryParameters:
      date?:
        type : date-only
        description: Date of whereabouts list, default today
      timeSlot?:
        type : enum
        (javaType): TimeSlot
        description: AM, PM or ED
    body:
      application/json:
           (javaType): List<String>
           description: The required offender numbers (mandatory)
    responses:
          200:
            body:
              application/json:
                 type: PrisonerSchedule[]

/{agencyId}/courtEvents:
  post:
    (javaOperationName): getCourtEvents
    uriParameters:
      agencyId:
        type: string
        description: The prison.
    queryParameters:
      date?:
        type : date-only
        description: Date of whereabouts list, default today
      timeSlot?:
        type : enum
        (javaType): TimeSlot
        description: AM, PM or ED
    body:
      application/json:
           (javaType): List<String>
           description: The required offender numbers (mandatory)
    responses:
          200:
            body:
              application/json:
                 type: PrisonerSchedule[]

/{agencyId}/externalTransfers:
  post:
    (javaOperationName): getExternalTransfers
    uriParameters:
      agencyId:
        type: string
        description: The prison.
    queryParameters:
      date?:
        type : date-only
        description: Date of scheduled transfer
    body:
      application/json:
           (javaType): List<String>
           description: The required offender numbers (mandatory)
    responses:
          200:
            body:
              application/json:
                 type: PrisonerSchedule[]
