FIND_AGENCIES_BY_USERNAME {
    SELECT DISTINCT A.AGY_LOC_ID,
           A.DESCRIPTION,
           A.AGENCY_LOCATION_TYPE
    FROM AGENCY_LOCATIONS A
        INNER JOIN CASELOAD_AGENCY_LOCATIONS C ON A.AGY_LOC_ID = C.AGY_LOC_ID
     WHERE A.ACTIVE_FLAG = 'Y'
       AND A.AGY_LOC_ID NOT IN ('OUT', 'TRN')
       AND C.CASELOAD_ID IN (
           SELECT UCR.CASELOAD_ID
           FROM USER_CASELOAD_ROLES UCR
           WHERE UCR.USERNAME = :username)
}

GET_AGENCY {
    SELECT A.AGY_LOC_ID,
           A.DESCRIPTION,
           A.AGENCY_LOCATION_TYPE
    WHERE A.ACTIVE_FLAG = 'Y'
      AND A.AGY_LOC_ID = :agencyId
}
