FIND_CASE_LOADS_BY_USERNAME {
	SELECT DISTINCT CL.CASELOAD_ID,
	       CL.DESCRIPTION,
		     CL.CASELOAD_TYPE
	  FROM CASELOADS CL
	       INNER JOIN USER_CASELOAD_ROLES SC ON CL.CASELOAD_ID = SC.CASELOAD_ID
	 WHERE SC.USERNAME = :username
}

FIND_ACTIVE_CASE_LOAD_BY_USERNAME {
	SELECT CL.CASELOAD_ID CASE_LOAD_ID,
		CL.DESCRIPTION,
		CL.CASELOAD_TYPE TYPE
	FROM CASELOADS CL JOIN STAFF_USER_ACCOUNTS SUA on CL.CASELOAD_ID = SUA.WORKING_CASELOAD_ID
	WHERE SUA.USERNAME = :username
}
