FIND_CASE_LOADS_BY_STAFF_ID {
	SELECT DISTINCT CL.CASELOAD_ID,
	       CL.DESCRIPTION
	  FROM CASELOADS CL
	       INNER JOIN USER_CASELOAD_ROLES SC ON CL.CASELOAD_ID = SC.CASELOAD_ID
			    INNER JOIN STAFF_USER_ACCOUNTS SUA ON SUA.USERNAME = SC.USERNAME
	 WHERE SUA.STAFF_ID = :staffId
}



