GET_RECENT_MOVEMENTS {
 SELECT OFFENDERS.OFFENDER_ID_DISPLAY AS OFFENDER_NO,
        OEM.CREATE_DATETIME           AS CREATE_DATE_TIME
  FROM OFFENDER_EXTERNAL_MOVEMENTS OEM
    INNER JOIN OFFENDER_BOOKINGS OB ON OB.OFFENDER_BOOK_ID = OEM.OFFENDER_BOOK_ID AND OB.BOOKING_SEQ = 1
    INNER JOIN OFFENDERS ON OFFENDERS.OFFENDER_ID = OB.OFFENDER_ID
  WHERE OEM.MOVEMENT_DATE > :fromDateTime - INTERVAL '30' DAY -- MOVEMENT_DATE has index: rough filter
    --AND TO_DATE(TO_CHAR(oem.movement_date,'DD/MM/YYYY')|| ' '|| TO_CHAR(oem.movement_time,'HH24:MI'), 'DD/MM/YYYY HH24:MI') <= SYSDATE -- ignore future movements?
    AND OEM.CREATE_DATETIME >= :fromDateTime
    AND OEM.MOVEMENT_TYPE IN ('TRN','REL','ADM')
    AND OEM.MOVEMENT_SEQ = (SELECT MAX(OEM2.MOVEMENT_SEQ) FROM OFFENDER_EXTERNAL_MOVEMENTS OEM2
                                        Where OEM2.OFFENDER_BOOK_ID = OEM.OFFENDER_BOOK_ID);
}
