
FIND_IMAGE_DETAIL {
    SELECT I.OFFENDER_IMAGE_ID AS IMAGE_ID,
           I.CAPTURE_DATETIME AS CAPTURE_DATE,
           I.IMAGE_VIEW_TYPE,
           I.ORIENTATION_TYPE,
           I.IMAGE_OBJECT_TYPE,
           I.IMAGE_OBJECT_ID
      FROM OFFENDER_IMAGES I
     WHERE I.OFFENDER_IMAGE_ID = :imageId
}

FIND_IMAGE_CONTENT {
    SELECT I.THUMBNAIL_IMAGE
      FROM OFFENDER_IMAGES I
     WHERE I.OFFENDER_IMAGE_ID = :imageId
}

