
FIND_IMAGE_DETAIL {
    SELECT I.OFFENDER_IMAGE_ID  IMAGE_ID,
           I.CAPTURE_DATETIME   CAPTURE_DATE,
           I.IMAGE_VIEW_TYPE    IMAGE_VIEW,
           I.ORIENTATION_TYPE   IMAGE_ORIENTATION,
           I.IMAGE_OBJECT_TYPE  IMAGE_TYPE,
           I.IMAGE_OBJECT_ID    OBJECT_ID
      FROM OFFENDER_IMAGES I
     WHERE I.OFFENDER_IMAGE_ID = :imageId
}

FIND_IMAGE_CONTENT {
    SELECT I.THUMBNAIL_IMAGE
      FROM OFFENDER_IMAGES I
     WHERE I.OFFENDER_IMAGE_ID = :imageId
}

