FIND_ALL_LOCATIONS {
	    SELECT A.INTERNAL_LOCATION_ID,
	  		     A.INTERNAL_LOCATION_TYPE,
	  		     A.DESCRIPTION,
	  		     A.PARENT_INTERNAL_LOCATION_ID,
	  		     A.NO_OF_OCCUPANT
	    FROM AGENCY_INTERNAL_LOCATIONS A
        INNER JOIN CASELOAD_AGENCY_LOCATIONS C ON A.AGY_LOC_ID = C.AGY_LOC_ID
        INNER JOIN STAFF_USER_ACCOUNTS SUA ON C.CASELOAD_ID = SUA.WORKING_CASELOAD_ID
	    WHERE A.ACTIVE_FLAG = 'Y' AND SUA.USERNAME = :username
}

FIND_LOCATION {
  SELECT A.INTERNAL_LOCATION_ID,
         A.INTERNAL_LOCATION_TYPE,
         A.DESCRIPTION,
         A.PARENT_INTERNAL_LOCATION_ID,
         A.NO_OF_OCCUPANT
  FROM	AGENCY_INTERNAL_LOCATIONS A
    INNER JOIN CASELOAD_AGENCY_LOCATIONS C ON A.AGY_LOC_ID = C.AGY_LOC_ID
    INNER JOIN STAFF_USER_ACCOUNTS SUA ON C.CASELOAD_ID = SUA.WORKING_CASELOAD_ID
  WHERE A.INTERNAL_LOCATION_ID = :locationId AND A.ACTIVE_FLAG = 'Y' AND SUA.USERNAME = :username
}
