FIND_ALL_LOCATIONS {
  SELECT AIL.INTERNAL_LOCATION_ID LOCATION_ID,
         AIL.INTERNAL_LOCATION_TYPE LOCATION_TYPE,
         AIL.DESCRIPTION,
         AIL.PARENT_INTERNAL_LOCATION_ID PARENT_LOCATION_ID,
         AIL.NO_OF_OCCUPANT CURRENT_OCCUPANCY,
         AIL.AGY_LOC_ID AGENCY_ID,
         AIL.USER_DESC USER_DESCRIPTION,
         AL.AGENCY_LOCATION_TYPE AGENCY_TYPE
  FROM AGENCY_INTERNAL_LOCATIONS AIL
	  INNER JOIN AGENCY_LOCATIONS AL ON AIL.AGY_LOC_ID = AL.AGY_LOC_ID
    INNER JOIN CASELOAD_AGENCY_LOCATIONS C ON AIL.AGY_LOC_ID = C.AGY_LOC_ID
    INNER JOIN STAFF_USER_ACCOUNTS SUA ON C.CASELOAD_ID = SUA.WORKING_CASELOAD_ID
	WHERE AIL.ACTIVE_FLAG = 'Y'
	  AND SUA.USERNAME = :username
}

FIND_LOCATION {
  SELECT A.INTERNAL_LOCATION_ID LOCATION_ID,
         A.INTERNAL_LOCATION_TYPE LOCATION_TYPE,
         A.DESCRIPTION,
         A.PARENT_INTERNAL_LOCATION_ID PARENT_LOCATION_ID,
         A.NO_OF_OCCUPANT CURRENT_OCCUPANCY,
         A.AGY_LOC_ID AGENCY_ID,
         A.USER_DESC USER_DESCRIPTION
  FROM AGENCY_INTERNAL_LOCATIONS A
    INNER JOIN CASELOAD_AGENCY_LOCATIONS C ON A.AGY_LOC_ID = C.AGY_LOC_ID
    INNER JOIN STAFF_USER_ACCOUNTS SUA ON C.CASELOAD_ID = SUA.WORKING_CASELOAD_ID
  WHERE A.ACTIVE_FLAG = 'Y'
    AND A.INTERNAL_LOCATION_ID = :locationId
    AND SUA.USERNAME = :username
}
