FIND_ALL_LOCATIONS {
    SELECT AIL.INTERNAL_LOCATION_ID,
           AIL.INTERNAL_LOCATION_TYPE,
           AIL.DESCRIPTION,
           AIL.PARENT_INTERNAL_LOCATION_ID,
           AIL.NO_OF_OCCUPANT,
           AIL.AGY_LOC_ID,
           AL.AGENCY_LOCATION_TYPE
    FROM AGENCY_INTERNAL_LOCATIONS AIL
	      INNER JOIN AGENCY_LOCATIONS AL ON AIL.AGY_LOC_ID = AL.AGY_LOC_ID
        INNER JOIN CASELOAD_AGENCY_LOCATIONS C ON AIL.AGY_LOC_ID = C.AGY_LOC_ID
        INNER JOIN STAFF_USER_ACCOUNTS SUA ON C.CASELOAD_ID = SUA.WORKING_CASELOAD_ID
	  WHERE AIL.ACTIVE_FLAG = 'Y' AND SUA.USERNAME = :username
}

FIND_LOCATION {
  SELECT A.INTERNAL_LOCATION_ID,
         A.INTERNAL_LOCATION_TYPE,
         A.DESCRIPTION,
         A.PARENT_INTERNAL_LOCATION_ID,
         A.NO_OF_OCCUPANT
  FROM	AGENCY_INTERNAL_LOCATIONS A
    INNER JOIN CASELOAD_AGENCY_LOCATIONS C ON A.AGY_LOC_ID = C.AGY_LOC_ID
    INNER JOIN STAFF_USER_ACCOUNTS SUA ON C.CASELOAD_ID = SUA.WORKING_CASELOAD_ID
  WHERE A.INTERNAL_LOCATION_ID = :locationId AND A.ACTIVE_FLAG = 'Y' AND SUA.USERNAME = :username
}

FIND_LOCATIONS_BY_AGENCY_AND_TYPE {
  SELECT A.INTERNAL_LOCATION_ID,
    A.INTERNAL_LOCATION_TYPE,
    A.DESCRIPTION as LOCATION_PREFIX,
    initcap(SUBSTR(SYS_CONNECT_BY_PATH(INTERNAL_LOCATION_TYPE || ' ' || A.INTERNAL_LOCATION_CODE, '|'),2)) as DESCRIPTION,
    A.PARENT_INTERNAL_LOCATION_ID,
    A.NO_OF_OCCUPANT,
    LEVEL,
    LIST_SEQ
  FROM AGENCY_INTERNAL_LOCATIONS A
  WHERE A.ACTIVE_FLAG = 'Y'
        AND A.AGY_LOC_ID = :agencyId
        AND LEVEL = :depth
        AND A.INTERNAL_LOCATION_TYPE = :locationType
  CONNECT BY PRIOR A.PARENT_INTERNAL_LOCATION_ID  = A.INTERNAL_LOCATION_ID
  }