FIND_USER_BY_STAFF_ID {
SELECT SM.STAFF_ID,
  AUA.USERNAME AS USER_ID,
  SM.FIRST_NAME,
  SM.LAST_NAME,
  AUA.WORKING_CASELOAD_ID AS ASSIGNED_CASELOAD_ID,
  (   SELECT INTERNET_ADDRESS
      FROM  INTERNET_ADDRESSES
      WHERE OWNER_CLASS = 'STF' AND INTERNET_ADDRESS_CLASS = 'EMAIL' AND OWNER_ID = SM.STAFF_ID
  ) EMAIL,
  NULL  IMAGE_ID
FROM STAFF_MEMBERS SM JOIN STAFF_USER_ACCOUNTS AUA ON SM.STAFF_ID = AUA.STAFF_ID
        AND SM.STAFF_ID = :staffId
}

FIND_USER_BY_USERNAME {
  SELECT SM.STAFF_ID,
    AUA.USERNAME AS USER_ID,
    SM.FIRST_NAME,
    SM.LAST_NAME,
    AUA.WORKING_CASELOAD_ID AS ASSIGNED_CASELOAD_ID,
    (   SELECT INTERNET_ADDRESS
        FROM  INTERNET_ADDRESSES
        WHERE OWNER_CLASS = 'STF' AND INTERNET_ADDRESS_CLASS = 'EMAIL' AND OWNER_ID = SM.STAFF_ID
    ) EMAIL,
    NULL  IMAGE_ID
  FROM STAFF_MEMBERS SM JOIN STAFF_USER_ACCOUNTS AUA ON SM.STAFF_ID = AUA.STAFF_ID
                                                        AND AUA.USERNAME = :username
}



FIND_ROLES_BY_USERNAME {
  SELECT DISTINCT REPLACE(RL.ROLE_CODE, '-', '_') ROLE_CODE
  FROM STAFF_USER_ACCOUNTS SUA
    INNER JOIN STAFF_MEMBER_ROLES RL ON SUA.STAFF_ID = RL.STAFF_ID
  WHERE SUA.USERNAME = :username
  ORDER BY 1
}

UPDATE_STAFF_ACTIVE_CASE_LOAD {
  UPDATE STAFF_USER_ACCOUNTS
  SET WORKING_CASELOAD_ID = :caseLoadId
  WHERE STAFF_ID = :staffId
}







