GROUP_BY_TYPES_AND_OFFENDERS {
  SELECT  CASE_NOTE_TYPE,
          CASE_NOTE_SUB_TYPE,
          O.OFFENDER_ID_DISPLAY OFFENDER_NO,
          COUNT(*) NUM_CASE_NOTES,
          MAX(OCS.CONTACT_TIME) LATEST_CASE_NOTE
  FROM OFFENDER_CASE_NOTES OCS JOIN OFFENDER_BOOKINGS OB
      ON OB.OFFENDER_BOOK_ID = OCS.OFFENDER_BOOK_ID JOIN OFFENDERS O
      ON O.OFFENDER_ID = OB.OFFENDER_ID
  WHERE OCS.AUDIT_TIMESTAMP between :fromDate and :toDate
        AND O.OFFENDER_ID_DISPLAY IN (:offenderNos)
        AND OCS.STAFF_ID = COALESCE(:staffId, OCS.STAFF_ID)
        AND CASE_NOTE_TYPE = COALESCE(:type, CASE_NOTE_TYPE)
        AND CASE_NOTE_SUB_TYPE = COALESCE(:subType, CASE_NOTE_SUB_TYPE)
  GROUP BY CASE_NOTE_TYPE, CASE_NOTE_SUB_TYPE, O.OFFENDER_ID_DISPLAY
}

GROUP_BY_TYPES_AND_STAFF {
  SELECT  STAFF_ID,
    CASE_NOTE_TYPE,
    CASE_NOTE_SUB_TYPE,
    COUNT(*) NUM_CASE_NOTES,
    MAX(OCS.CONTACT_TIME) LATEST_CASE_NOTE
  FROM OFFENDER_CASE_NOTES OCS
  WHERE OCS.AUDIT_TIMESTAMP between :fromDate and :toDate
        AND STAFF_ID IN (:staffIds)
        AND CASE_NOTE_TYPE = COALESCE(:type, CASE_NOTE_TYPE)
        AND CASE_NOTE_SUB_TYPE = COALESCE(:subType, CASE_NOTE_SUB_TYPE)
  GROUP BY STAFF_ID, CASE_NOTE_TYPE, CASE_NOTE_SUB_TYPE
}