INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-1, systimestamp,  'A00111', -1, 'N', 'IN', 'Y', 'N', 'LEI', -1, -2, -3);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-2, systimestamp,  'A00112', -2, 'N', 'IN', 'Y', 'N', 'LEI', -2, -2, -19);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-3, systimestamp,  'A00113', -3, 'N', 'IN', 'Y', 'N', 'LEI', -3, -2, -1);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-4, systimestamp,  'A00114', -4, 'N', 'IN', 'Y', 'N', 'LEI', -4, -2, -2);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-5, systimestamp,  'A00115', -5, 'N', 'IN', 'Y', 'N', 'LEI', -5, -2, -12);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-6, systimestamp,  'A00116', -6, 'N', 'IN', 'Y', 'N', 'LEI', -6, -2, -4);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-7, systimestamp,  'A00117', -7, 'N', 'IN', 'Y', 'N', 'LEI', -7, -2, -5);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-8, systimestamp,  'A00118', -8, 'N', 'IN', 'Y', 'N', 'LEI', -8, -2, -6);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-9, systimestamp,  'A00119', -9, 'N', 'IN', 'Y', 'N', 'LEI', -9, -2, -7);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-10, systimestamp,  'A00120', -10, 'N', 'IN', 'Y', 'N', 'LEI', -10, -2, -8);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-11, systimestamp,  'A00121', -11, 'N', 'IN', 'Y', 'N', 'LEI', -11, -4, -9);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-12, systimestamp,  'A00122', -12, 'N', 'IN', 'Y', 'N', 'LEI', -12, -4, -10);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-13, systimestamp,  'A00123', -13, 'N', 'IN', 'Y', 'N', 'LEI', -12, -4, -11);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-14, systimestamp,  'A00124', -14, 'N', 'IN', 'Y', 'N', 'LEI', -9, -4, -13);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-15, systimestamp,  'A00125', -15, 'N', 'IN', 'Y', 'N', 'LEI', -9, -4, -14);

