FIND_ALL_INMATES {
SELECT
  B.OFFENDER_BOOK_ID,
  B.BOOKING_NO,
  O.OFFENDER_ID_DISPLAY,
  B.AGY_LOC_ID,
  O.FIRST_NAME,
  O.MIDDLE_NAME,
  O.LAST_NAME,
  O.BIRTH_DATE,
  TRUNC(MONTHS_BETWEEN(sysdate, O.BIRTH_DATE)/12) AS AGE,
  (SELECT WM_CONCAT(DISTINCT(ALERT_TYPE))
   FROM OFFENDER_ALERTS A
   WHERE B.OFFENDER_BOOK_ID = A.OFFENDER_BOOK_ID
         AND A.ALERT_STATUS = 'ACTIVE') AS ALERT_TYPES,
  (SELECT WM_CONCAT(concat(AO.LAST_NAME, concat(' ', AO.FIRST_NAME)))
   FROM OFFENDERS AO
   WHERE  AO.ROOT_OFFENDER_ID = B.ROOT_OFFENDER_ID
          AND AO.OFFENDER_ID != B.OFFENDER_ID) AS ALIASES,
  B.LIVING_UNIT_ID,
  AIL.DESCRIPTION AS LIVING_UNIT_DESC,
  (
    SELECT OI.OFFENDER_IMAGE_ID
    FROM OFFENDER_IMAGES OI
    WHERE OI.ACTIVE_FLAG = 'Y'
          AND IMAGE_OBJECT_TYPE = 'OFF_BKG'
          AND OI.OFFENDER_BOOK_ID = B.OFFENDER_BOOK_ID
          AND OI.IMAGE_VIEW_TYPE = 'FACE'
          AND OI.ORIENTATION_TYPE = 'FRONT'
          AND CREATE_DATETIME = (SELECT MAX(CREATE_DATETIME)
                                 FROM OFFENDER_IMAGES
                                 WHERE ACTIVE_FLAG = 'Y'
                                       AND IMAGE_OBJECT_TYPE = 'OFF_BKG'
                                       AND OFFENDER_BOOK_ID = OI.OFFENDER_BOOK_ID
                                       AND IMAGE_VIEW_TYPE = 'FACE'
                                       AND ORIENTATION_TYPE = 'FRONT')
  ) AS FACE_IMAGE_ID,
  NULL AS ASSIGNED_OFFICER_ID
FROM OFFENDER_BOOKINGS B
  INNER JOIN OFFENDERS O ON B.OFFENDER_ID = O.OFFENDER_ID
  LEFT JOIN AGENCY_INTERNAL_LOCATIONS AIL ON B.LIVING_UNIT_ID = AIL.INTERNAL_LOCATION_ID
WHERE B.ACTIVE_FLAG = 'Y'
      AND EXISTS (select 1 from CASELOAD_AGENCY_LOCATIONS C WHERE B.AGY_LOC_ID = C.AGY_LOC_ID AND C.CASELOAD_ID IN (:caseLoadId))
}