
FIND_ALL_INMATES {
  SELECT OB.OFFENDER_BOOK_ID,
         OB.BOOKING_NO,
         O.OFFENDER_ID_DISPLAY,
         OB.AGY_LOC_ID,
         O.FIRST_NAME,
         O.MIDDLE_NAME,
         O.LAST_NAME,
         O.BIRTH_DATE,
        (SELECT WM_CONCAT(DISTINCT(ALERT_TYPE))
         FROM OFFENDER_ALERTS A
         WHERE OB.OFFENDER_BOOK_ID = A.OFFENDER_BOOK_ID
               AND A.ALERT_STATUS = 'ACTIVE') AS ALERT_TYPES,
        (SELECT WM_CONCAT(ALERT_CODE)
         FROM OFFENDER_ALERTS A
         WHERE OB.OFFENDER_BOOK_ID = A.OFFENDER_BOOK_ID
           AND A.ALERT_STATUS = 'ACTIVE'
           AND (A.EXPIRY_DATE IS NULL OR A.EXPIRY_DATE > SYSDATE)) AS ALERT_DETAILS,
        (SELECT WM_CONCAT(concat(AO.LAST_NAME, concat(' ', AO.FIRST_NAME)))
         FROM OFFENDERS AO
         WHERE  AO.ROOT_OFFENDER_ID = OB.ROOT_OFFENDER_ID
                AND AO.OFFENDER_ID != OB.OFFENDER_ID) AS ALIASES,
         OB.LIVING_UNIT_ID,
         AIL.DESCRIPTION AS LIVING_UNIT_DESC,
         (SELECT OI.OFFENDER_IMAGE_ID
           FROM OFFENDER_IMAGES OI
           WHERE OI.ACTIVE_FLAG = 'Y'
             AND IMAGE_OBJECT_TYPE = 'OFF_BKG'
             AND OI.OFFENDER_BOOK_ID = OB.OFFENDER_BOOK_ID
             AND OI.IMAGE_VIEW_TYPE = 'FACE'
             AND OI.ORIENTATION_TYPE = 'FRONT'
             AND CREATE_DATETIME = (SELECT MAX(CREATE_DATETIME)
                                    FROM OFFENDER_IMAGES
                                    WHERE ACTIVE_FLAG = 'Y'
                                      AND IMAGE_OBJECT_TYPE = 'OFF_BKG'
                                      AND OFFENDER_BOOK_ID = OI.OFFENDER_BOOK_ID
                                      AND IMAGE_VIEW_TYPE = 'FACE'
                                      AND ORIENTATION_TYPE = 'FRONT')
         ) AS FACE_IMAGE_ID,
         S.USER_ID AS ASSIGNED_OFFICER_ID
  FROM OFFENDER_BOOKINGS OB
    INNER JOIN OFFENDERS O ON OB.OFFENDER_ID = O.OFFENDER_ID
    LEFT JOIN AGENCY_INTERNAL_LOCATIONS AIL ON OB.LIVING_UNIT_ID = AIL.INTERNAL_LOCATION_ID
    LEFT JOIN STAFF_MEMBERS S ON OB.ASSIGNED_STAFF_ID = S.STAFF_ID
  WHERE OB.ACTIVE_FLAG = 'Y'
}

FIND_INMATES_BY_LOCATION {
     SELECT B.OFFENDER_BOOK_ID,
            B.BOOKING_NO,
            O.OFFENDER_ID_DISPLAY,
            B.AGY_LOC_ID,
            O.FIRST_NAME,
            O.MIDDLE_NAME,
            O.LAST_NAME,
            O.BIRTH_DATE,
            (SELECT WM_CONCAT(DISTINCT(ALERT_TYPE))
              FROM OFFENDER_ALERTS A
              WHERE B.OFFENDER_BOOK_ID = A.OFFENDER_BOOK_ID
                    AND A.ALERT_STATUS = 'ACTIVE') AS ALERT_TYPES,
             (SELECT WM_CONCAT(concat(AO.LAST_NAME, concat(' ', AO.FIRST_NAME)))
              FROM OFFENDERS AO
              WHERE  AO.ROOT_OFFENDER_ID = B.ROOT_OFFENDER_ID
                     AND AO.OFFENDER_ID != B.OFFENDER_ID) AS ALIASES,
            B.LIVING_UNIT_ID,
            (
                SELECT * FROM (
                    SELECT IMAGE_ID
                      FROM IMAGES
                     WHERE ACTIVE_FLAG = 'Y'
                           AND IMAGE_OBJECT_TYPE = 'OFF_BKG'
                           AND IMAGE_OBJECT_ID = B.OFFENDER_BOOK_ID
                           AND IMAGE_VIEW_TYPE = 'FACE'
                           AND ORIENTATION_TYPE = 'FRONT'
                     ORDER BY CREATE_DATETIME DESC
                )
                WHERE ROWNUM <= 1
            ) AS FACE_IMAGE_ID
       FROM OFFENDER_BOOKINGS B
            INNER JOIN CASELOAD_AGENCY_LOCATIONS C ON C.CASELOAD_ID = :caseLoadId AND B.AGY_LOC_ID = C.AGY_LOC_ID
            LEFT JOIN OFFENDERS O ON B.OFFENDER_ID = O.OFFENDER_ID
      WHERE B.ACTIVE_FLAG = 'Y'
            AND B.LIVING_UNIT_ID IN (
                SELECT INTERNAL_LOCATION_ID
                  FROM AGENCY_INTERNAL_LOCATIONS START WITH INTERNAL_LOCATION_ID = :locationId
               CONNECT BY PRIOR INTERNAL_LOCATION_ID = PARENT_INTERNAL_LOCATION_ID
            )
}
