searchable:
  usage: Apply this to any endpoint that needs searching
  queryParameters:
    query:
      type: string
      description: |
        Search parameters with the format [connector]:&lt;fieldName&gt;:&lt;operator&gt;:&lt;value&gt;:[format],...
        <p>Connector operators - and, or
        <p>Supported Operators - eq, neq, gt, gteq, lt, lteq, like, in</p>
        <p>Supported Fields - <<fieldsList>></p>
      example: query=creationDateTime:gt:'07-12-2013':'MM-DD-YYYY',and:type:in:'CNOTE'|'PROG_NOTE'

pageable:
  usage: Apply this to any endpoint that needs pagination
  headers:
    Page-Offset:
      displayName: Page Offset
      description: Requested offset of first record in returned collection of <<resourcePathName|!singularize>> records.
      type: integer
      (javaType): Long
      required: false
      example: 20
      default: 0
    Page-Limit:
      displayName: Page Limit
      description: Requested limit to number of <<resourcePathName|!singularize>> records returned.
      type: integer
      (javaType): Long
      required: false
      example: 80
      default: 10

hasResponsePagination:
  responses:
    200:
      (headersWithType_Long): Total-Records,Page-Offset,Page-Limit
      headers:
        Total-Records:
          description: Total number of <<resourcePathName|!singularize>> records available.
        Page-Offset:
          description: Offset of first record in returned page of <<resourcePathName|!singularize>> records.
        Page-Limit:
          description: Maximum number of <<resourcePathName|!singularize>> records in returned page.

sortable:
  usage: Apply this to any endpoint that needs to be sortable
  headers:
    Sort-Fields:
      description: Comma separated list of one or more of the following fields - <b><<fieldsList>></b>
      type: string
      required: false
    Sort-Order:
      description: Sort order (ASC or DESC) - defaults to ASC.
      (javaType): Order
      required: false
      default: ASC
