CREATE USER ITAG_USER PASSWORD 'password';
CREATE USER ELITE2_API_USER PASSWORD 'password';
CREATE USER API_TEST_USER PASSWORD 'password';
CREATE USER CA_USER PASSWORD 'password';
CREATE USER RO_USER PASSWORD 'password';
CREATE USER DM_USER PASSWORD 'password';
CREATE USER RENEGADE PASSWORD 'password';
CREATE USER NONWEB PASSWORD 'password';