CREATE OR REPLACE FUNCTION converttoxid ( p_xid IN VARCHAR2 )
  RETURN RAW
IS
  L_USN VARCHAR2(5)	:= LTRIM(TO_CHAR(SUBSTR(p_xid,1,INSTR(p_xid,'.')-1),'0XXX'),4);
  L_TS VARCHAR2(5)	:= LTRIM(TO_CHAR(SUBSTR(p_xid,INSTR(P_xid,'.',1)+1,INSTR(p_xid,'.')),'0XXX'),4);
  L_SN VARCHAR2(9)	:= LTRIM(TO_CHAR(SUBSTR(p_xid,INSTR(P_xid,'.',-1)+1),'0XXXXXXX'),8);
  BEGIN
    RETURN(LTRIM(L_USN)||LTRIM(L_TS)||LTRIM(L_SN));
  END;
/

