#%RAML 0.8
title: elite2-web
version: v1
baseUri: /api
/api: 
    displayName: Api Resource
    description: Api Resource
    /agencies: 
        displayName: Agencies Resource
        description: Agencies Resource
        get: 
            description: getAgencies
            queryParameters: 
                arg0: 
                    displayName: arg0
                    type: string
                    required: false
                    repeat: false
                arg1: 
                    displayName: arg1
                    type: string
                    required: false
                    repeat: false
            responses: 
                "200": 
                    description: Successful Response
                    body: 
                        application/json: 
                            schema: |
                                {
                                  "type" : "any"
                                }
        /{startingWith}: 
            displayName: "{startingWith} Resource"
            description: "{startingWith} Resource"
            get: 
                description: getAgencyByStartingWith
                queryParameters: 
                    arg1: 
                        displayName: arg1
                        type: string
                        required: false
                        repeat: false
                    arg2: 
                        displayName: arg2
                        type: string
                        required: false
                        repeat: false
                responses: 
                    "200": 
                        description: Successful Response
                        body: 
                            application/json: 
                                schema: |
                                    {
                                      "type" : "any"
                                    }
