-- Offender summary information
SELECT
  B.OFFENDER_BOOK_ID, -- bookingId
  B.BOOKING_NO,  -- bookingNo
  O.OFFENDER_ID_DISPLAY, -- offenderNo
  O.FIRST_NAME,
  O.MIDDLE_NAME,
  O.LAST_NAME,
  (SELECT LISTAGG(ALERT_TYPE, ',') WITHIN GROUP (ORDER BY ALERT_TYPE) FROM
    (SELECT 
      DISTINCT( ALERT_TYPE) 
    FROM 
      OFFENDER_ALERTS A 
    WHERE B.OFFENDER_BOOK_ID = A.OFFENDER_BOOK_ID AND A.ALERT_STATUS = 'ACTIVE')) AS ALERT_TYPES,
  B.AGY_LOC_ID,
  -- CURRENT LOCATION ID (tbd)
  B.LIVING_UNIT_ID,
  (SELECT * FROM
    (
      SELECT IMAGE_ID
      FROM IMAGES
      WHERE
        ACTIVE_FLAG = 'Y'
        AND IMAGE_OBJECT_TYPE = 'OFF_BKG'
        AND IMAGE_OBJECT_ID = B.OFFENDER_BOOK_ID
        AND IMAGE_VIEW_TYPE = 'FACE'
        AND ORIENTATION_TYPE = 'FRONT'
      ORDER BY CREATE_DATETIME DESC
    )
    WHERE ROWNUM <= 1
  ) AS FACE_IMAGE_ID
FROM
  OFFENDER_BOOKINGS B 
  LEFT JOIN OFFENDERS O ON B.OFFENDER_ID = O.OFFENDER_ID
WHERE
  B.ACTIVE_FLAG = 'Y';

-- Basic offender information. Need to calcuate age.
SELECT
  B.OFFENDER_BOOK_ID,
  B.BOOKING_NO,
  O.OFFENDER_ID_DISPLAY,
  O.FIRST_NAME,
  O.MIDDLE_NAME,
  O.LAST_NAME,
  (SELECT LISTAGG(ALERT_TYPE, ',') WITHIN GROUP (ORDER BY ALERT_TYPE) FROM
    (SELECT 
      DISTINCT( ALERT_TYPE) 
    FROM 
      OFFENDER_ALERTS A 
    WHERE B.OFFENDER_BOOK_ID = A.OFFENDER_BOOK_ID AND A.ALERT_STATUS = 'ACTIVE')) AS ALERT_TYPES,
  B.AGY_LOC_ID,
  -- CURRENT LOCATION ID (tbd)
  B.LIVING_UNIT_ID,
  (SELECT * FROM
    (
      SELECT IMAGE_ID
      FROM IMAGES
      WHERE
        ACTIVE_FLAG = 'Y'
        AND IMAGE_OBJECT_TYPE = 'OFF_BKG'
        AND IMAGE_OBJECT_ID = B.OFFENDER_BOOK_ID
        AND IMAGE_VIEW_TYPE = 'FACE'
        AND ORIENTATION_TYPE = 'FRONT'
      ORDER BY CREATE_DATETIME DESC
    )
    WHERE ROWNUM <= 1
  ) AS FACE_IMAGE_ID,
  O.BIRTH_DATE
FROM
  OFFENDER_BOOKINGS B LEFT JOIN
  OFFENDERS O ON B.OFFENDER_ID = O.OFFENDER_ID
WHERE
  B.ACTIVE_FLAG = 'Y';
  
-- Alert codes
SELECT DISTINCT
  B.OFFENDER_BOOK_ID,
  B.BOOKING_NO,
  A.ALERT_TYPE
FROM
  OFFENDER_BOOKINGS B LEFT JOIN
  OFFENDER_ALERTS A ON B.OFFENDER_BOOK_ID = A.OFFENDER_BOOK_ID
WHERE
  B.ACTIVE_FLAG = 'Y' AND
  A.ALERT_STATUS = 'ACTIVE'
ORDER BY
  B.OFFENDER_BOOK_ID,
  B.BOOKING_NO;
  
-- Physical Attributes
SELECT
  B.OFFENDER_BOOK_ID,
  O.SEX_CODE,
  O.RACE_CODE,
  P.HEIGHT_FT,
  P.HEIGHT_IN,
  P.HEIGHT_CM,
  P.WEIGHT_LBS,
  P.WEIGHT_KG
FROM
  OFFENDER_BOOKINGS B 
  LEFT JOIN OFFENDERS O ON B.OFFENDER_ID = O.OFFENDER_ID
  LEFT JOIN OFFENDER_PHYSICAL_ATTRIBUTES P ON B.OFFENDER_BOOK_ID = P.OFFENDER_BOOK_ID  
WHERE
  B.ACTIVE_FLAG = 'Y';

-- Physical Characteristics
SELECT
  B.OFFENDER_BOOK_ID,
  (SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = P.PROFILE_TYPE AND DOMAIN='BODY_PART') AS CHARACTERISTIC,
  (SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = P.PROFILE_CODE AND DOMAIN='PPTY_COLOR') AS DETAIL,
  (SELECT * FROM -- there is a chance that this will return two rows instead of one, in this case return the most recent image.
    (SELECT I.IMAGE_ID 
      FROM IMAGES I 
      WHERE 
        B.OFFENDER_BOOK_ID = I.IMAGE_OBJECT_ID 
        AND I.ACTIVE_FLAG = 'Y' 
        AND I.IMAGE_OBJECT_TYPE = 'OFF_BKG' 
        AND I.IMAGE_VIEW_TYPE = P.PROFILE_TYPE
      ORDER BY I.CREATE_DATETIME DESC
    )
    WHERE ROWNUM <= 1
  ) AS IMAGE_ID
FROM
  OFFENDER_BOOKINGS B 
  LEFT JOIN OFFENDER_PROFILE_DETAILS P ON B.OFFENDER_BOOK_ID = P.OFFENDER_BOOK_ID
WHERE
  B.ACTIVE_FLAG = 'Y' AND
  P.PROFILE_TYPE IN (SELECT CODE FROM REFERENCE_CODES WHERE DOMAIN='BODY_PART')
ORDER BY B.OFFENDER_BOOK_ID; 

-- Physical Marks
SELECT
  B.OFFENDER_BOOK_ID,
  (SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = M.MARK_TYPE AND DOMAIN='MARK_TYPE') AS TYPE,
  (SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = M.SIDE_CODE AND DOMAIN='SIDE') AS SIDE,
  (SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = M.BODY_PART_CODE AND DOMAIN='BODY_PART') AS BODY_PART,
  (SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = M.PART_ORIENTATION_CODE AND DOMAIN='PART_ORIENT') AS ORENTIATION,
  M.COMMENT_TEXT,
  (SELECT I.IMAGE_ID  
      FROM IMAGES I 
      WHERE 
        B.OFFENDER_BOOK_ID = I.IMAGE_OBJECT_ID AND 
        I.ACTIVE_FLAG = 'Y' AND
        M.MARK_TYPE = I.IMAGE_VIEW_TYPE AND
        M.BODY_PART_CODE = I.ORIENTATION_TYPE AND
        M.ID_MARK_SEQ = I.IMAGE_OBJECT_SEQ
  ) AS IMAGE_ID
FROM
  OFFENDER_BOOKINGS B 
  INNER JOIN offender_identifying_marks M ON B.OFFENDER_BOOK_ID = M.OFFENDER_BOOK_ID
WHERE
  B.ACTIVE_FLAG = 'Y'
  and m.body_part_code != 'CONV';

  
  