base:
  get?:
    responses: &standardResponses
      200:
        description: OK
      400:
        body:
          application/json:
            type: ErrorResponse
            description: Invalid request.
            example: !include ../examples/ouput/400.sample.json
      404:
        body:
          application/json:
            type: ErrorResponse
            description: Requested resource not found.
            example:  !include ../examples/ouput/404.sample.json
      500:
        body:
          application/json:
            type: ErrorResponse
            description: Unrecoverable error occurred whilst processing request.
            example: !include ../examples/ouput/500.sample.json

readOnlyItem:
  type:
    base:
  get:
    description: <<description>>
    responses:
      200:
        body:
          application/json:
            type: <<type>>

readOnlyCollection:
  type:
    base:
  get:
    description: <<description>>
    responses:
      200:
        body:
          application/json:
            <<type>>[]

readOnlyCollectionPaged:
  type:
    readOnlyCollection:
  is: [ pageable, hasResponsePagination ]
  get:
    description: <<description>>
    responses:
      200:
        body:
          application/json:
            <<type>>[]

userPicture:
  type:
    base:
  get:
    description: <<description>>
    responses:
      200:
        (mediaType): image/jpeg
        body:
          image/jpeg:
            type: file
            fileTypes: ['image/jpeg']
            maxLength: 307200
