base:
  get?:
    responses: &standardResponses
      200:
        description: OK
      400:
        body:
          application/json:
            type: ErrorResponse
            example: !include ../examples/ouput/400.sample.json
      404:
        body:
          application/json:
            type: ErrorResponse
            example:  !include ../examples/ouput/404.sample.json
      500:
        body:
          application/json:
            type: ErrorResponse
            example: !include ../examples/ouput/500.sample.json

readOnlyItem:
  type:
    base:
  get:
    description: Get the specified <<resourcePathName | !singularize>>.
    responses:
      200:
        body:
          application/json:
            type: <<type>>

readOnlyCollection:
  type:
    base:
  get:
    description: Get all <<resourcePathName | !pluralize>>.
    headers:
      Page-Offset:
        description: Requested offset of first record in returned collection of <<resourcePathName>> records.
        type: integer
      Page-Limit:
        description: Requested limit to number of <<resourcePathName>> records returned.
        type: integer
    responses:
      200:
        headers:
          Total-Records:
            description: Total number of <<resourcePathName>> records available.
            type: integer
          Page-Offset:
            description: Offset of first record in returned 'page' of <<resourcePathName>> records.
            type: integer
          Page-Limit:
            description: Maximum number of <<resourcePathName>> records in returned 'page'.
            type: integer
        body:
          application/json:
            <<type>>[]
