CREATE TABLE "OFFENDER_SENT_CALCULATIONS"
(
  "OFFENDER_SENT_CALCULATION_ID"   NUMBER(10, 0)                     NOT NULL ,
  "OFFENDER_BOOK_ID"               NUMBER(10, 0)                     NOT NULL ,
  "CALCULATION_DATE"               DATE                              NOT NULL ,
  "STAFF_ID"                       NUMBER(10, 0),
  "COMMENT_TEXT"                   VARCHAR2(240 CHAR),
  "HDCED_CALCULATED_DATE"          DATE,
  "HDCED_OVERRIDED_DATE"           DATE,
  "HDCAD_CALCULATED_DATE"          DATE,
  "HDCAD_OVERRIDED_DATE"           DATE,
  "ETD_CALCULATED_DATE"            DATE,
  "ETD_OVERRIDED_DATE"             DATE,
  "MTD_CALCULATED_DATE"            DATE,
  "MTD_OVERRIDED_DATE"             DATE,
  "LTD_CALCULATED_DATE"            DATE,
  "LTD_OVERRIDED_DATE"             DATE,
  "ARD_CALCULATED_DATE"            DATE,
  "ARD_OVERRIDED_DATE"             DATE,
  "CRD_CALCULATED_DATE"            DATE,
  "CRD_OVERRIDED_DATE"             DATE,
  "PED_CALCULATED_DATE"            DATE,
  "PED_OVERRIDED_DATE"             DATE,
  "APD_CALCULATED_DATE"            DATE,
  "APD_OVERRIDED_DATE"             DATE,
  "NPD_CALCULATED_DATE"            DATE,
  "NPD_OVERRIDED_DATE"             DATE,
  "LED_CALCULATED_DATE"            DATE,
  "LED_OVERRIDED_DATE"             DATE,
  "SED_CALCULATED_DATE"            DATE,
  "SED_OVERRIDED_DATE"             DATE,
  "PRRD_CALCULATED_DATE"           DATE,
  "PRRD_OVERRIDED_DATE"            DATE,
  "TARIFF_CALCULATED_DATE"         DATE,
  "TARIFF_OVERRIDED_DATE"          DATE,
  "CALC_REASON_CODE"               VARCHAR2(32 CHAR)                 NOT NULL ,
  "CREATE_DATETIME"                TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                 VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"                TIMESTAMP(9),
  "MODIFY_USER_ID"                 VARCHAR2(32 CHAR),
  "RECORD_DATETIME"                DATE              DEFAULT sysdate,
  "RECORD_USER_ID"                 VARCHAR2(30 CHAR) DEFAULT user,
  "AUDIT_TIMESTAMP"                TIMESTAMP(9),
  "AUDIT_USER_ID"                  VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"              VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"           VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"        VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME"  VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"          VARCHAR2(256 CHAR),
  "EFFECTIVE_SENTENCE_END_DATE"    DATE,
  "HDC_ELIGIBLE_WF"                VARCHAR2(1 CHAR)  DEFAULT 'N',
  "WORKFLOW_HISTORY_ID"            NUMBER(32, 0),
  "EFFECTIVE_SENTENCE_LENGTH"      VARCHAR2(12 CHAR),
  "JUDICIALLY_IMPOSED_SENT_LENGTH" VARCHAR2(12 CHAR),
  "DPRRD_CALCULATED_DATE"          DATE,
  "DPRRD_OVERRIDED_DATE"           DATE,
  "ERSED_OVERRIDED_DATE"           DATE,
  "TERSED_OVERRIDED_DATE"          DATE,
  "ROTL_OVERRIDED_DATE"            DATE,
  "TUSED_CALCULATED_DATE"          DATE,
  "TUSED_OVERRIDED_DATE"           DATE,
  CONSTRAINT "OFFENDER_SENT_CALCULATIONS_PK" PRIMARY KEY ("OFFENDER_SENT_CALCULATION_ID"),
  CONSTRAINT "OFF_SENT_CALC_OFF_BKG_FK" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID")
);


COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."OFFENDER_BOOK_ID" IS 'The Related Offender Book Identifier';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."COMMENT_TEXT" IS 'Free text comment data';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."DPRRD_CALCULATED_DATE" IS 'DTO Post Recall calculated Release Date';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."DPRRD_OVERRIDED_DATE" IS 'DTO Post Recall Release Date override';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."ERSED_OVERRIDED_DATE" IS 'Early Release Scheme date.';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."TERSED_OVERRIDED_DATE" IS 'Tariff Expiry Removal Scheme date.';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."ROTL_OVERRIDED_DATE" IS 'Release on Temporary License date.';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."TUSED_CALCULATED_DATE" IS 'Top up Supervision Expiry Date - Calculated Date.';

COMMENT ON COLUMN "OFFENDER_SENT_CALCULATIONS"."TUSED_OVERRIDED_DATE" IS 'Top up Supervision Overrided Date - Overrided Date.';


CREATE INDEX "OFFENDER_SENT_CALCULATIONS_NI1"
  ON "OFFENDER_SENT_CALCULATIONS" ("OFFENDER_BOOK_ID");

