CREATE TABLE "PERSON_IDENTIFIERS"
(
  "PERSON_ID"                     NUMBER(10, 0)                     NOT NULL,
  "ID_SEQ"                        NUMBER(6, 0)                      NOT NULL,
  "IDENTIFIER_TYPE"               VARCHAR2(12)                      NOT NULL,
  "IDENTIFIER"                    VARCHAR2(20)                      NOT NULL,
  "ISSUED_AUTHORITY_TEXT"         VARCHAR2(40),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL,
  "CREATE_USER_ID"                VARCHAR2(32) DEFAULT USER         NOT NULL,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32),
  "ISSUED_DATE"                   DATE,
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32),
  "AUDIT_MODULE_NAME"             VARCHAR2(65),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256),
  CONSTRAINT "PERSON_IDENTIFIERS_PK" PRIMARY KEY ("PERSON_ID", "ID_SEQ"),
  CONSTRAINT "PERSON_IDENTIFIERS_PERSONS_FK" FOREIGN KEY ("PERSON_ID")
  REFERENCES "PERSONS" ("PERSON_ID")
);

CREATE UNIQUE INDEX "PERSON_IDENTIFIERS_UI1" ON "PERSON_IDENTIFIERS" ("PERSON_ID", "IDENTIFIER_TYPE", "IDENTIFIER");
CREATE INDEX "PERSON_IDENTIFIERS_NI1" ON "PERSON_IDENTIFIERS" ("IDENTIFIER", "IDENTIFIER_TYPE");