CREATE TABLE INT_LOC_USAGE_LOCATIONS 
(   INTERNAL_LOCATION_USAGE_ID    NUMBER(10)                             NOT NULL, 
    INTERNAL_LOCATION_ID          NUMBER(10)                             NOT NULL, 
    CAPACITY                      NUMBER(5), 
    USAGE_LOCATION_TYPE           VARCHAR2(12 CHAR), 
    CREATE_DATETIME               TIMESTAMP(9)      DEFAULT systimestamp NOT NULL, 
    CREATE_USER_ID                VARCHAR2(32 CHAR) DEFAULT USER         NOT NULL, 
    MODIFY_DATETIME               TIMESTAMP(9), 
    MODIFY_USER_ID                VARCHAR2(32 CHAR), 
    LIST_SEQ                      NUMBER(6), 
    USAGE_LOCATION_ID             NUMBER(10)                             NOT NULL, 
    PARENT_USAGE_LOCATION_ID      NUMBER(10), 
    AUDIT_TIMESTAMP               TIMESTAMP (9), 
    AUDIT_USER_ID                 VARCHAR2(32 CHAR), 
    AUDIT_MODULE_NAME             VARCHAR2(65 CHAR), 
    AUDIT_CLIENT_USER_ID          VARCHAR2(64 CHAR), 
    AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39 CHAR), 
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64 CHAR), 
    AUDIT_ADDITIONAL_INFO         VARCHAR2(256 CHAR)
);

CREATE INDEX INT_LOC_USAGE_LOCATIONS_NI1 ON INT_LOC_USAGE_LOCATIONS (PARENT_USAGE_LOCATION_ID) ;
CREATE UNIQUE INDEX INT_LOC_USAGE_LOCATIONS_PK ON INT_LOC_USAGE_LOCATIONS (USAGE_LOCATION_ID)  ;
CREATE UNIQUE INDEX INT_LOC_USAGE_LOCATIONS_UK ON INT_LOC_USAGE_LOCATIONS (INTERNAL_LOCATION_USAGE_ID, INTERNAL_LOCATION_ID) ;
CREATE INDEX INT_LOC_USAGE_LOCATIONS_NI2 ON INT_LOC_USAGE_LOCATIONS (INTERNAL_LOCATION_ID) ;

ALTER TABLE INT_LOC_USAGE_LOCATIONS ADD CONSTRAINT INT_LOC_USAGE_LOCATIONS_PK PRIMARY KEY (USAGE_LOCATION_ID);
ALTER TABLE INT_LOC_USAGE_LOCATIONS ADD CONSTRAINT INT_LOC_USAGE_LOCATIONS_UK UNIQUE (INTERNAL_LOCATION_USAGE_ID, INTERNAL_LOCATION_ID);
