description: Returns the list of agencies viewable by the user
type: { get-collection: { collectionSchema: agencies } }
is: [ pageable ]


/{agencyId}:
  description: Returns the list of agencies viewable by the user
  type: { get-item: { schema: agency } }


/{agencyId}/locations:
  description: The collection of scheduled movements associated to the inmate.
  type: { get-collection: { collectionSchema: locations } }
  is: [
    orderable: {fieldsList : "moveCategory, moveDateTime, fromAgencyId, toAgencyId, moveType, moveReason, fromLocationId, or toLocation"},
    pageable
  ]
