/{locationPrefix}/{keywords}:
  (deprecated): Use <b>/locations/description/{locationPrefix}/inmates</b> instead. This API will be removed in a future release.
  (javaOperationName): searchForOffendersLocationAndKeyword
  description: Search for Offender Bookings in the system by location and keywords
    uriParameters:
      locationPrefix:
        type: string
        description: The location description of location
      keywords?:
        type: string
        description: offender name or id to match
  get:
    queryParameters:
      returnIep?:
        type: boolean
        description: return IEP data
        default: false
        example: false
      returnAlerts?:
        type: boolean
        description: return Alert data
        default: false
        example: false
  type: { readOnlyCollectionPaged: { type: OffenderBooking, description: List offenders by location (matching keywords). } }
  is: [ sortable ]