CREATE TABLE OFFENDERS
(
  OFFENDER_ID                   NUMBER(10)                        NOT NULL
    CONSTRAINT OFFENDERS_PK
    PRIMARY KEY,
  OFFENDER_NAME_SEQ             NUMBER(38),
  ID_SOURCE_CODE                VARCHAR2(12)                      NOT NULL,
  LAST_NAME                     VARCHAR2(35)                      NOT NULL,
  NAME_TYPE                     VARCHAR2(12),
  FIRST_NAME                    VARCHAR2(35),
  MIDDLE_NAME                   VARCHAR2(35),
  BIRTH_DATE                    DATE,
  SEX_CODE                      VARCHAR2(12)                      NOT NULL,
  SUFFIX                        VARCHAR2(12),
  LAST_NAME_SOUNDEX             VARCHAR2(6),
  BIRTH_PLACE                   VARCHAR2(25),
  BIRTH_COUNTRY_CODE            VARCHAR2(12),
  CREATE_DATE                   DATE                              NOT NULL,
  LAST_NAME_KEY                 VARCHAR2(35)                      NOT NULL,
  ALIAS_OFFENDER_ID             NUMBER(10)
    CONSTRAINT OFF_OFF_F1
    REFERENCES OFFENDERS,
  FIRST_NAME_KEY                VARCHAR2(35),
  MIDDLE_NAME_KEY               VARCHAR2(35),
  OFFENDER_ID_DISPLAY           VARCHAR2(10)                      NOT NULL,
  ROOT_OFFENDER_ID              NUMBER(10),
  CASELOAD_TYPE                 VARCHAR2(12),
  MODIFY_USER_ID                VARCHAR2(32),
  MODIFY_DATETIME               TIMESTAMP(9),
  ALIAS_NAME_TYPE               VARCHAR2(12),
  PARENT_OFFENDER_ID            NUMBER(10),
  UNIQUE_OBLIGATION_FLAG        VARCHAR2(1) DEFAULT NULL,
  SUSPENDED_FLAG                VARCHAR2(1) DEFAULT NULL,
  SUSPENDED_DATE                DATE,
  RACE_CODE                     VARCHAR2(12),
  REMARK_CODE                   VARCHAR2(12),
  ADD_INFO_CODE                 VARCHAR2(12),
  BIRTH_COUNTY                  VARCHAR2(20),
  BIRTH_STATE                   VARCHAR2(20),
  MIDDLE_NAME_2                 VARCHAR2(35),
  TITLE                         VARCHAR2(12),
  AGE                           NUMBER(3),
  CREATE_USER_ID                VARCHAR2(40) DEFAULT USER         NOT NULL,
  LAST_NAME_ALPHA_KEY           VARCHAR2(1) DEFAULT NULL,
  CREATE_DATETIME               TIMESTAMP(9) DEFAULT systimestamp NOT NULL,
  NAME_SEQUENCE                 VARCHAR2(12),
  AUDIT_TIMESTAMP               TIMESTAMP(9),
  AUDIT_USER_ID                 VARCHAR2(32),
  AUDIT_MODULE_NAME             VARCHAR2(65),
  AUDIT_CLIENT_USER_ID          VARCHAR2(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR2(256),
  SINGLE_OFFENDER_IDENTITY_ID   VARCHAR2(36)
);


CREATE INDEX "OFFENDERS_FK10" ON "OFFENDERS" ("PARENT_OFFENDER_ID");
CREATE INDEX "OFFENDERS_NI1" ON "OFFENDERS" ("LAST_NAME", "OFFENDER_ID");
CREATE INDEX "OFFENDERS_NI2" ON "OFFENDERS" ("LAST_NAME_SOUNDEX", "LAST_NAME");
CREATE INDEX "OFFENDERS_NI3" ON "OFFENDERS" ("LAST_NAME_KEY");
CREATE INDEX "OFFENDERS_NI4" ON "OFFENDERS" ("ALIAS_OFFENDER_ID");
CREATE INDEX "OFFENDERS_NI5" ON "OFFENDERS" ("OFFENDER_ID_DISPLAY");
CREATE INDEX "OFFENDERS_NI6" ON "OFFENDERS" ("ROOT_OFFENDER_ID");
CREATE INDEX "OFFENDERS_NI7" ON "OFFENDERS" ("BIRTH_DATE");
CREATE INDEX "OFFENDERS_NI8_IDS" ON "OFFENDERS" ("OFFENDER_ID", "SEX_CODE");
CREATE INDEX "OFFENDERS_NI9" ON "OFFENDERS" ("LAST_NAME_ALPHA_KEY");
CREATE INDEX "OFFENDERS_X01" ON "OFFENDERS" ("FIRST_NAME", "OFFENDER_ID");
CREATE INDEX "OFFENDERS_X02" ON "OFFENDERS" ("MIDDLE_NAME", "OFFENDER_ID");
 