CREATE TABLE "OFFENDER_SUB_ACCOUNTS"
(
  "CASELOAD_ID"                   VARCHAR2(6 CHAR)                  NOT NULL ENABLE,
  "OFFENDER_ID"                   NUMBER(10, 0)                     NOT NULL ENABLE,
  "TRUST_ACCOUNT_CODE"            NUMBER(6, 0)                      NOT NULL ENABLE,
  "BALANCE"                       NUMBER(11, 2),
  "MINIMUM_BALANCE"               NUMBER(11, 2),
  "HOLD_BALANCE"                  NUMBER(11, 2),
  "LAST_TXN_ID"                   NUMBER(10, 0),
  "MODIFY_DATE"                   DATE                              NOT NULL ENABLE,
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "LIST_SEQ"                      NUMBER(6, 0) DEFAULT 99,
  "IND_DATE"                      DATE,
  "IND_DAYS"                      NUMBER(9, 0),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ENABLE,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ENABLE,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "OFFENDER_SUB_ACCOUNTS_PK" PRIMARY KEY ("CASELOAD_ID", "OFFENDER_ID", "TRUST_ACCOUNT_CODE"),
  CONSTRAINT "OFFENDER_SUB_ACCOUNTS_FK10" FOREIGN KEY ("OFFENDER_ID")
  REFERENCES "OFFENDERS" ("OFFENDER_ID") ENABLE,
  CONSTRAINT "OFF_SUBA_OFF_TA_F3" FOREIGN KEY ("CASELOAD_ID", "OFFENDER_ID")
  REFERENCES "OFFENDER_TRUST_ACCOUNTS" ("CASELOAD_ID", "OFFENDER_ID") ENABLE
);


COMMENT ON COLUMN "OFFENDER_SUB_ACCOUNTS"."CASELOAD_ID" IS 'The Case Load Identifier';

COMMENT ON COLUMN "OFFENDER_SUB_ACCOUNTS"."OFFENDER_ID" IS 'The Related Offender Identifier';

COMMENT ON COLUMN "OFFENDER_SUB_ACCOUNTS"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "OFFENDER_SUB_ACCOUNTS"."LIST_SEQ" IS 'The sequence in which the data should be shown';

COMMENT ON COLUMN "OFFENDER_SUB_ACCOUNTS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_SUB_ACCOUNTS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "OFFENDER_SUB_ACCOUNTS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';


CREATE INDEX "OFFENDER_SUB_ACCOUNTS_NI1"
  ON "OFFENDER_SUB_ACCOUNTS" ("OFFENDER_ID", "TRUST_ACCOUNT_CODE");


