CREATE TABLE "OFFENDER_TRUST_ACCOUNTS"
(
  "CASELOAD_ID"                   VARCHAR2(6 CHAR)                  NOT NULL ENABLE,
  "OFFENDER_ID"                   NUMBER(10, 0)                     NOT NULL ENABLE,
  "ACCOUNT_CLOSED_FLAG"           VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ENABLE,
  "HOLD_BALANCE"                  NUMBER(11, 2),
  "CURRENT_BALANCE"               NUMBER(11, 2),
  "MODIFY_DATE"                   DATE                              NOT NULL ENABLE,
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "LIST_SEQ"                      NUMBER(6, 0) DEFAULT 99,
  "NOTIFY_DATE"                   DATE,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ENABLE,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ENABLE,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "OFFENDER_TRUST_ACCOUNT_PK" PRIMARY KEY ("CASELOAD_ID", "OFFENDER_ID"),
  CONSTRAINT "OFF_TA_OFF_NAME_F2" FOREIGN KEY ("OFFENDER_ID")
  REFERENCES "OFFENDERS" ("OFFENDER_ID") ENABLE
);


COMMENT ON COLUMN "OFFENDER_TRUST_ACCOUNTS"."CASELOAD_ID" IS 'The Case Load Identifier';
COMMENT ON COLUMN "OFFENDER_TRUST_ACCOUNTS"."OFFENDER_ID" IS 'The Related Offender Identifier';
COMMENT ON COLUMN "OFFENDER_TRUST_ACCOUNTS"."MODIFY_DATE" IS 'Modify Date';
COMMENT ON COLUMN "OFFENDER_TRUST_ACCOUNTS"."MODIFY_USER_ID" IS 'The user who modifies the record';
COMMENT ON COLUMN "OFFENDER_TRUST_ACCOUNTS"."LIST_SEQ" IS 'The sequence in which the data should be shown';
COMMENT ON COLUMN "OFFENDER_TRUST_ACCOUNTS"."CREATE_DATETIME" IS 'The timestamp when the record is created';
COMMENT ON COLUMN "OFFENDER_TRUST_ACCOUNTS"."CREATE_USER_ID" IS 'The user who creates the record';
COMMENT ON COLUMN "OFFENDER_TRUST_ACCOUNTS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';


CREATE INDEX "OFFENDER_TRUST_ACCOUNTS_NI1"
  ON "OFFENDER_TRUST_ACCOUNTS" ("OFFENDER_ID");


