CREATE TABLE "OFFENDER_TRANSACTIONS"
(
  "TXN_ID"                        NUMBER(10, 0)                     NOT NULL ENABLE,
  "TXN_ENTRY_SEQ"                 NUMBER(6, 0) DEFAULT 99           NOT NULL ENABLE,
  "CASELOAD_ID"                   VARCHAR2(6 CHAR)                  NOT NULL ENABLE,
  "OFFENDER_ID"                   NUMBER(10, 0)                     NOT NULL ENABLE,
  "OFFENDER_BOOK_ID"              NUMBER(10, 0),
  "TXN_POSTING_TYPE"              VARCHAR2(12 CHAR)                 NOT NULL ENABLE,
  "TXN_TYPE"                      VARCHAR2(6 CHAR)                  NOT NULL ENABLE,
  "TXN_ENTRY_DESC"                VARCHAR2(240 CHAR),
  "TXN_ENTRY_AMOUNT"              NUMBER(11, 2)                     NOT NULL ENABLE,
  "TXN_ENTRY_DATE"                DATE                              NOT NULL ENABLE,
  "SUB_ACCOUNT_TYPE"              VARCHAR2(12 CHAR)                 NOT NULL ENABLE,
  "TXN_REFERENCE_NUMBER"          VARCHAR2(12 CHAR),
  "MODIFY_DATE"                   DATE                              NOT NULL ENABLE,
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "RECEIPT_NUMBER"                VARCHAR2(13 CHAR),
  "SLIP_PRINTED_FLAG"             VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ENABLE,
  "TRANSFER_CASELOAD_ID"          VARCHAR2(6 CHAR),
  "RECEIPT_PRINTED_FLAG"          VARCHAR2(1 CHAR) DEFAULT 'N',
  "PRE_WITHHOLD_AMOUNT"           NUMBER(11, 2),
  "DEDUCTION_FLAG"                VARCHAR2(1 CHAR) DEFAULT 'N',
  "CLOSING_CHEQUE_NUMBER"         VARCHAR2(12 CHAR),
  "REMITTER_NAME"                 VARCHAR2(60 CHAR),
  "PAYEE_CODE"                    VARCHAR2(12 CHAR),
  "PAYEE_NAME_TEXT"               VARCHAR2(60 CHAR),
  "PAYEE_CORPORATE_ID"            NUMBER(10, 0),
  "PAYEE_PERSON_ID"               NUMBER(10, 0),
  "ADJUST_TXN_ID"                 NUMBER(10, 0),
  "ADJUST_TXN_ENTRY_ID"           NUMBER(6, 0)     DEFAULT 99,
  "ADJUST_OFFENDER_ID"            NUMBER(10, 0),
  "ADJUST_ACCOUNT_CODE"           NUMBER(6, 0),
  "TXN_ADJUSTED_FLAG"             VARCHAR2(1 CHAR) DEFAULT 'N',
  "DEDUCTION_TYPE"                VARCHAR2(6 CHAR),
  "INFO_NUMBER"                   VARCHAR2(32 CHAR),
  "HOLD_CLEAR_FLAG"               VARCHAR2(1 CHAR) DEFAULT 'N',
  "HOLD_UNTIL_DATE"               DATE,
  "HOLD_NUMBER"                   NUMBER(9, 0),
  "GROSS_AMOUNT"                  NUMBER(11, 2),
  "GROSS_NET_FLAG"                VARCHAR2(1 CHAR) DEFAULT 'N',
  "REMITTER_ID"                   NUMBER(10, 0),
  "APPLY_SPENDING_LIMIT_AMOUNT"   NUMBER(12, 2),
  "RECEIPT_PENDING_PRINT_FLAG"    VARCHAR2(1 CHAR) DEFAULT 'N',
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ENABLE,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ENABLE,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "EVENT_ID"                      NUMBER(10, 0),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  "FROM_DATE"                     DATE,
  "TO_DATE"                       DATE,
  "CLIENT_UNIQUE_REF"             VARCHAR2(100 CHAR),
  CHECK ( txn_adjusted_flag IN ('Y', 'N')  ) ENABLE,
  CHECK ( hold_clear_flag IN ('Y', 'N')  ) ENABLE,
  CHECK ( slip_printed_flag IN ('Y', 'N')  ) ENABLE,
  CONSTRAINT "OFFENDER_TRANSACTIONS_PK" PRIMARY KEY ("TXN_ID", "TXN_ENTRY_SEQ") ENABLE,
  CONSTRAINT "OFFENDER_TRANSACTIONS_UK1" UNIQUE ("CLIENT_UNIQUE_REF") ENABLE,
  CONSTRAINT "OFF_TXN_OFF_TA_F1" FOREIGN KEY ("CASELOAD_ID", "OFFENDER_ID")
  REFERENCES "OFFENDER_TRUST_ACCOUNTS" ("CASELOAD_ID", "OFFENDER_ID") ENABLE
);


COMMENT ON COLUMN "OFFENDER_TRANSACTIONS"."TXN_ID" IS 'Transaction Identifier';

COMMENT ON COLUMN "OFFENDER_TRANSACTIONS"."CASELOAD_ID" IS 'The Case Load Identifier';

COMMENT ON COLUMN "OFFENDER_TRANSACTIONS"."OFFENDER_ID" IS 'Offender ID';

COMMENT ON COLUMN "OFFENDER_TRANSACTIONS"."OFFENDER_BOOK_ID" IS 'Offender Book ID';

COMMENT ON COLUMN "OFFENDER_TRANSACTIONS"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "OFFENDER_TRANSACTIONS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_TRANSACTIONS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "OFFENDER_TRANSACTIONS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON TABLE "OFFENDER_TRANSACTIONS" IS '- Retrofitted';


CREATE INDEX "OFFENDER_TRANSACTIONS_N8"
  ON "OFFENDER_TRANSACTIONS" ("OFFENDER_BOOK_ID", "TXN_TYPE", "CASELOAD_ID", "FROM_DATE", "TO_DATE");


CREATE INDEX "OFFENDER_TRANSACTIONS_NI9"
  ON "OFFENDER_TRANSACTIONS" ("SUB_ACCOUNT_TYPE", "OFFENDER_ID");


CREATE INDEX "OFFENDER_TRANSACTIONS_X01"
  ON "OFFENDER_TRANSACTIONS" ("OFFENDER_ID", "TXN_TYPE", "TXN_ID");

CREATE INDEX "OFF_TXN_OFF_TA_F1"
  ON "OFFENDER_TRANSACTIONS" ("CASELOAD_ID", "OFFENDER_ID", "TXN_ENTRY_DATE");

