CREATE TABLE "USER_CASELOAD_ROLES"
(
  "ROLE_ID"                       NUMBER(10, 0)                     NOT NULL ENABLE,
  "USERNAME"                      VARCHAR2(30 CHAR)                 NOT NULL ENABLE,
  "CASELOAD_ID"                   VARCHAR2(6 CHAR)                  NOT NULL ENABLE,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ENABLE,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ENABLE,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "USER_CASELOAD_ROLES_PK" PRIMARY KEY ("USERNAME", "CASELOAD_ID", "ROLE_ID"),
  CONSTRAINT "USER_CASELOAD_ROLES_FK1" FOREIGN KEY ("CASELOAD_ID", "USERNAME")
  REFERENCES "USER_ACCESSIBLE_CASELOADS" ("CASELOAD_ID", "USERNAME") ENABLE,
  CONSTRAINT "USER_CASELOAD_ROLES_FK2" FOREIGN KEY ("ROLE_ID")
  REFERENCES "OMS_ROLES" ("ROLE_ID") ENABLE NOVALIDATE
);


CREATE INDEX "USER_CASELOAD_ROLES_FK1"
  ON "USER_CASELOAD_ROLES" ("CASELOAD_ID", "USERNAME");


CREATE INDEX "USER_CASELOAD_ROLES_FK2"
  ON "USER_CASELOAD_ROLES" ("ROLE_ID");

