CREATE TABLE "OFFENDER_PROFILE_DETAILS"
(
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ENABLE,
  "PROFILE_SEQ"                   NUMBER(6, 0)                      NOT NULL ENABLE,
  "PROFILE_TYPE"                  VARCHAR2(12 CHAR)                 NOT NULL ENABLE,
  "PROFILE_CODE"                  VARCHAR2(40 CHAR),
  "LIST_SEQ"                      NUMBER(6, 0)                      NOT NULL ENABLE,
  "COMMENT_TEXT"                  VARCHAR2(240 CHAR),
  "CASELOAD_TYPE"                 VARCHAR2(12 CHAR),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ENABLE,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ENABLE,
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "OFFENDER_PROFILE_DETAILS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "PROFILE_SEQ", "PROFILE_TYPE"),
  CONSTRAINT "OFFENDER_PROFILE_DETAILS_FK9" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID") ENABLE
);


COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."OFFENDER_BOOK_ID" IS ' System generated identifier for an offender booking.';

COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."PROFILE_SEQ" IS ' Sequence number forming part of primary key.';

COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."PROFILE_TYPE" IS 'The type of profile ie. Hair Colour, Eye Colour, Religion..';

COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."PROFILE_CODE" IS 'Code associated with profile type ie. Hair Colour codes would be Black, Brown..';

COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."LIST_SEQ" IS 'Sequencing on list of values.';

COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."COMMENT_TEXT" IS 'Comment for profile information.';

COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."CASELOAD_TYPE" IS 'The Case Load Type';

COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_PROFILE_DETAILS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON TABLE "OFFENDER_PROFILE_DETAILS" IS 'Offender Profile Details';


CREATE INDEX "OFFENDER_PROFILE_DETAILS_N1"
  ON "OFFENDER_PROFILE_DETAILS" ("PROFILE_TYPE", "PROFILE_CODE");


CREATE UNIQUE INDEX "OFFENDER_PROFILE_DETAILS_U1"
  ON "OFFENDER_PROFILE_DETAILS" ("OFFENDER_BOOK_ID", "PROFILE_TYPE", "PROFILE_CODE");


