CREATE TABLE "OFFENDER_EXCLUDE_ACTS_SCHDS"
(
  "OFFENDER_EXCLUDE_ACT_SCHD_ID"  NUMBER(10, 0)                     NOT NULL ENABLE,
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ENABLE,
  "OFF_PRGREF_ID"                 NUMBER(10, 0)                     NOT NULL ENABLE,
  "SLOT_CATEGORY_CODE"            VARCHAR2(12 CHAR),
  "EXCLUDE_DAY"                   VARCHAR2(12 CHAR)                 NOT NULL ENABLE,
  "CRS_ACTY_ID"                   NUMBER(10, 0)                     NOT NULL ENABLE,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ENABLE,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ENABLE,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "OFF_EXCLUDE_ACTS_SCHDS_FK1" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID") ENABLE,
  CONSTRAINT "OFF_EXCLUDE_ACTS_SCHDS_FK3" FOREIGN KEY ("CRS_ACTY_ID")
  REFERENCES "COURSE_ACTIVITIES" ("CRS_ACTY_ID") ENABLE,
  CONSTRAINT "OFF_EXCLUDE_ACTS_SCHDS_FK4" FOREIGN KEY ("OFF_PRGREF_ID")
  REFERENCES "OFFENDER_PROGRAM_PROFILES" ("OFF_PRGREF_ID") ENABLE
);


CREATE UNIQUE INDEX "OFFENDER_EXCLUDE_ACT_SCHDS_PK"
  ON "OFFENDER_EXCLUDE_ACTS_SCHDS" ("OFFENDER_EXCLUDE_ACT_SCHD_ID");


CREATE UNIQUE INDEX "OFF_EXCLUDE_ACTS_SCHDS_UK1"
  ON "OFFENDER_EXCLUDE_ACTS_SCHDS" ("OFF_PRGREF_ID", "EXCLUDE_DAY", "SLOT_CATEGORY_CODE");


CREATE INDEX "OFF_EXCLUDE_ACT_SCHDS_FK1"
  ON "OFFENDER_EXCLUDE_ACTS_SCHDS" ("OFFENDER_BOOK_ID");


CREATE INDEX "OFF_EXCLUDE_ACT_SCHDS_FK3"
  ON "OFFENDER_EXCLUDE_ACTS_SCHDS" ("CRS_ACTY_ID");


CREATE INDEX "OFF_EXCLUDE_ACT_SCHDS_FK4"
  ON "OFFENDER_EXCLUDE_ACTS_SCHDS" ("OFF_PRGREF_ID");

