spring:
  datasource:
    url: jdbc:hsqldb:mem:nomis-db;sql.syntax_ora=true;get_column_name=false;shutdown=false;sql.nulls_first=false;sql.nulls_order=false
    username: sa
    password:

    hikari:
      maximum-pool-size: 2

  jpa:
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:/db/migration/nomis/ddl,classpath:/db/migration/data,classpath:/db/migration/nomis/data,classpath:/db/migration/nomis/data-hsqldb

server.shutdown: immediate
