spring:
  datasource:
    url: jdbc:h2:mem:nomisdb;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH
    # url: jdbc:h2:tcp://localhost:9092/~/nomisdb;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    hikari:
      maximum-pool-size: 2
  replica:
    datasource:
      url: jdbc:h2:mem:nomisdb;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH
      username: sa
      hikari:
        maximum-pool-size: 2

  jpa:
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:/db/migration/nomis/ddl,classpath:/db/migration/data,classpath:/db/migration/nomis/data,classpath:/db/migration/nomis/data-h2

server.shutdown: immediate
