spring:
  datasource:
    url: jdbc:hsqldb:mem:nomis-db;sql.syntax_ora=true;get_column_name=false;shutdown=false;sql.nulls_first=false;sql.nulls_order=false
    username: sa
    password:

    hikari:
      maximum-pool-size: 2

  flyway:
    enabled: true
    locations: classpath:/db/migration/nomis/ddl,classpath:/db/migration/data,classpath:/db/migration/nomis/data,classpath:/db/migration/nomis/data-hsqldb

data.compliance:

  db:
    enable.parallel.hints: false

  response:
    sqs:
      provider: localstack
      queue.name: data_compliance_response_queue
      queue.url: http://localstack:4576/queue/data_compliance_response_queue
      dlq.name: data_compliance_response_dead_letter_queue
      endpoint.url: http://localstack:4576
      region: eu-west-2

  request:
    sqs:
      provider: localstack
      queue.name: data_compliance_request_queue
      dlq.name: data_compliance_request_dead_letter_queue
      endpoint.url: http://localstack:4576
      region: eu-west-2

server.shutdown: immediate
