-- Internal Agency Locations (PILOT VERSION)
SELECT
  A.INTERNAL_LOCATION_ID,
  A.AGY_LOC_ID,
  A.INTERNAL_LOCATION_TYPE,
  A.DESCRIPTION,
  A.PARENT_INTERNAL_LOCATION_ID,
  A.NO_OF_OCCUPANT,
  (SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = (SELECT HOUSING_UNIT_TYPE FROM LIVING_UNITS WHERE LIVING_UNIT_ID = A.INTERNAL_LOCATION_ID) AND DOMAIN='HOU_UN_TYPE') AS HOUSING_UNIT_TYPE
FROM
  AGENCY_INTERNAL_LOCATIONS A
WHERE
  A.ACTIVE_FLAG = 'Y' AND
  A.AGY_LOC_ID = 'SDP' AND --  This clause is for the pilot only
  A.INTERNAL_LOCATION_TYPE != 'BLOCK' AND  --  This clause is for the pilot only
  (SELECT COUNT(*) FROM AGENCY_INTERNAL_LOCATIONS B WHERE B.PARENT_INTERNAL_LOCATION_ID = A.INTERNAL_LOCATION_ID) > 0;

-- Inmates assigned to a location (or child location)
SELECT
  B.OFFENDER_BOOK_ID,
  B.BOOKING_NO,
  O.OFFENDER_ID_DISPLAY,
  O.FIRST_NAME,
  O.LAST_NAME
FROM
  OFFENDER_BOOKINGS B LEFT JOIN
  OFFENDERS O ON B.OFFENDER_ID = O.OFFENDER_ID
WHERE
  B.LIVING_UNIT_ID IN
    (
    SELECT
      INTERNAL_LOCATION_ID
    FROM
      AGENCY_INTERNAL_LOCATIONS
    START WITH INTERNAL_LOCATION_ID = 7110 -- Replace with the desired living unit
    CONNECT BY PARENT_INTERNAL_LOCATION_ID = PRIOR INTERNAL_LOCATION_ID
    );
    
--- Agency Locations
SELECT
  ROWNUM AS ID,
  AGY_LOC_ID AS AGENCY_ID,
  DESCRIPTION,
  AGENCY_LOCATION_TYPE
FROM
  AGENCY_LOCATIONS
WHERE
  ACTIVE_FLAG = 'Y' AND
  AGY_LOC_ID NOT IN ('OUT', 'TRN')
ORDER BY AGY_LOC_ID;