CREATE TABLE "OFFENDER_IEP_LEVELS"
(
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ,
  "IEP_LEVEL_SEQ"                 NUMBER(10, 0)                     NOT NULL ,
  "IEP_DATE"                      DATE                              NOT NULL ,
  "IEP_TIME"                      DATE,
  "AGY_LOC_ID"                    VARCHAR2(6 CHAR)                  NOT NULL ,
  "IEP_LEVEL"                     VARCHAR2(12 CHAR)                 NOT NULL ,
  "COMMENT_TEXT"                  VARCHAR2(240 CHAR),
  "USER_ID"                       VARCHAR2(40 CHAR),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "OFFENDER_IEP_LEVELS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "IEP_LEVEL_SEQ"),
  CONSTRAINT "OFF_IEP_LEVELS_OFF_BKG_FK" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID") ,
  CONSTRAINT "OFF_IEP_LEVELS_IEP_LEVEL_FK" FOREIGN KEY ("IEP_LEVEL", "AGY_LOC_ID")
  REFERENCES "IEP_LEVELS" ("IEP_LEVEL", "AGY_LOC_ID")
);


COMMENT ON COLUMN "OFFENDER_IEP_LEVELS"."OFFENDER_BOOK_ID" IS 'The Related Offender Book Identifier';

COMMENT ON COLUMN "OFFENDER_IEP_LEVELS"."AGY_LOC_ID" IS 'The Related Agency Location Identifier';

COMMENT ON COLUMN "OFFENDER_IEP_LEVELS"."COMMENT_TEXT" IS 'Free text comment data';

COMMENT ON COLUMN "OFFENDER_IEP_LEVELS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_IEP_LEVELS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "OFFENDER_IEP_LEVELS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "OFFENDER_IEP_LEVELS"."MODIFY_USER_ID" IS 'The user who modifies the record';


CREATE INDEX "OFFENDER_IEP_LEVELS_IND1"
  ON "OFFENDER_IEP_LEVELS" ("OFFENDER_BOOK_ID");


CREATE INDEX "OFF_IEP_LEVELS_IEP_LEVEL_FK"
  ON "OFFENDER_IEP_LEVELS" ("IEP_LEVEL", "AGY_LOC_ID");


