
CREATE TABLE "INTERNAL_SCHEDULE_REASONS"
(
  "INTERNAL_SCHEDULE_TYPE"        VARCHAR2(12 CHAR)                 NOT NULL ,
  "INTERNAL_SCHEDULE_RSN_CODE"    VARCHAR2(12 CHAR)                 NOT NULL ,
  "DESCRIPTION"                   VARCHAR2(40 CHAR),
  "ACTIVE_FLAG"                   VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ,
  "LIST_SEQ"                      NUMBER(6, 0) DEFAULT 1,
  "EXPIRY_DATE"                   DATE,
  "UPDATE_ALLOWED_FLAG"           VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "INTERNAL_SCHEDULE_REASONS_PK" PRIMARY KEY ("INTERNAL_SCHEDULE_TYPE", "INTERNAL_SCHEDULE_RSN_CODE")
);

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."INTERNAL_SCHEDULE_TYPE" IS 'Refrence Code ( INT_SCH_TYPE)';

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."INTERNAL_SCHEDULE_RSN_CODE" IS 'Refrence Code ( INT_SCH_RSN )';

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."DESCRIPTION" IS ' - Column already exists';

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."ACTIVE_FLAG" IS ' - Column already exists';

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."LIST_SEQ" IS ' - Column already exists';

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."EXPIRY_DATE" IS ' - Column already exists';

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."UPDATE_ALLOWED_FLAG" IS ' - Column already exists';

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "INTERNAL_SCHEDULE_REASONS"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON TABLE "INTERNAL_SCHEDULE_REASONS"  IS '- Retrofitted';


