CREATE TABLE "OFFENDER_ASSESSMENTS"
(
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ,
  "ASSESSMENT_SEQ"                NUMBER(6, 0)                      NOT NULL ,
  "ASSESSMENT_DATE"               DATE                              NOT NULL ,
  "ASSESSMENT_TYPE_ID"            NUMBER(10, 0),
  "SCORE"                         NUMBER(8, 2),
  "ASSESS_STATUS"                 VARCHAR2(12 CHAR)                 NOT NULL ,
  "CALC_SUP_LEVEL_TYPE"           VARCHAR2(12 CHAR),
  "ASSESS_STAFF_ID"               NUMBER(10, 0)                     NOT NULL ,
  "ASSESS_COMMENT_TEXT"           VARCHAR2(4000 CHAR),
  "OVERRIDE_REASON_TEXT"          VARCHAR2(40 CHAR),
  "PLACE_AGY_LOC_ID"              VARCHAR2(6 CHAR),
  "OVERRIDED_SUP_LEVEL_TYPE"      VARCHAR2(12 CHAR),
  "OVERRIDE_COMMENT_TEXT"         VARCHAR2(240 CHAR),
  "OVERRIDE_STAFF_ID"             NUMBER(10, 0),
  "EVALUATION_DATE"               DATE,
  "NEXT_REVIEW_DATE"              DATE,
  "EVALUATION_RESULT_CODE"        VARCHAR2(12 CHAR),
  "REVIEW_SUP_LEVEL_TYPE"         VARCHAR2(12 CHAR),
  "REVIEW_PLACEMENT_TEXT"         VARCHAR2(240 CHAR),
  "REVIEW_COMMITTE_CODE"          VARCHAR2(12 CHAR),
  "COMMITTE_COMMENT_TEXT"         VARCHAR2(240 CHAR),
  "REVIEW_PLACE_AGY_LOC_ID"       VARCHAR2(6 CHAR),
  "REVIEW_SUP_LEVEL_TEXT"         VARCHAR2(240 CHAR),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "ASSESS_COMMITTE_CODE"          VARCHAR2(12 CHAR),
  "CREATION_DATE"                 DATE,
  "CREATION_USER"                 VARCHAR2(32 CHAR),
  "APPROVED_SUP_LEVEL_TYPE"       VARCHAR2(12 CHAR),
  "ASSESSMENT_CREATE_LOCATION"    VARCHAR2(6 CHAR),
  "ASSESSOR_STAFF_ID"             NUMBER(10, 0),
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "OVERRIDE_USER_ID"              VARCHAR2(32 CHAR),
  "OVERRIDE_REASON"               VARCHAR2(12 CHAR),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "OFFENDER_ASSESSMENTS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "ASSESSMENT_SEQ"),
  CONSTRAINT "OFF_ASS_STAFF_F2" FOREIGN KEY ("ASSESSOR_STAFF_ID")
  REFERENCES "STAFF_MEMBERS" ("STAFF_ID") ,
  CONSTRAINT "OFF_ASS_OFF_BKG_F1" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID") ,
  CONSTRAINT "OFF_ASS_ASS_F1" FOREIGN KEY ("ASSESSMENT_TYPE_ID")
  REFERENCES "ASSESSMENTS" ("ASSESSMENT_ID") ,
  CONSTRAINT "OFF_ASS_AGY_LOC_F3" FOREIGN KEY ("ASSESSMENT_CREATE_LOCATION")
  REFERENCES "AGENCY_LOCATIONS" ("AGY_LOC_ID") ,
  CONSTRAINT "OFF_ASS_AGY_LOC_F2" FOREIGN KEY ("REVIEW_PLACE_AGY_LOC_ID")
  REFERENCES "AGENCY_LOCATIONS" ("AGY_LOC_ID") ,
  CONSTRAINT "OFF_ASS_AGY_LOC_F1" FOREIGN KEY ("PLACE_AGY_LOC_ID")
  REFERENCES "AGENCY_LOCATIONS" ("AGY_LOC_ID")
);


COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."OFFENDER_BOOK_ID" IS 'Unique identifier for an offender booking.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."ASSESSMENT_SEQ" IS ' System generated sequence number forming part of primary key.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."ASSESSMENT_DATE" IS 'Assessment date.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."ASSESSMENT_TYPE_ID" IS 'Assessment ID where Assessment Class = "TYPE"';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."SCORE" IS 'This calculated score will determine the offender"s security level.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."ASSESS_STATUS" IS 'Reference Code ( STATUS ) - ie. A-Active, P-Pending, I-Inactive.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."CALC_SUP_LEVEL_TYPE" IS 'Reference Code ( SUP_LVL_TYPE )';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."ASSESS_STAFF_ID" IS 'Userid performing assessment.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."ASSESS_COMMENT_TEXT" IS 'Offender assessment comment.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."OVERRIDE_REASON_TEXT" IS ' Reason for override.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."PLACE_AGY_LOC_ID" IS 'Agency location of placement.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."OVERRIDED_SUP_LEVEL_TYPE" IS 'Override security level ie. Minimum, Medium, Maximum..';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."OVERRIDE_COMMENT_TEXT" IS 'Override Reason Text';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."OVERRIDE_STAFF_ID" IS 'Override userid.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."EVALUATION_DATE" IS 'Date the evaluation occurrred.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."NEXT_REVIEW_DATE" IS 'Next scheduled review based upon number of days since last review.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."EVALUATION_RESULT_CODE" IS 'Evaluation result ie. Approved, Rejected, Approved with Changes.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."REVIEW_SUP_LEVEL_TYPE" IS 'Approved security level.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."REVIEW_PLACEMENT_TEXT" IS 'Reviewed placement comment.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."REVIEW_COMMITTE_CODE" IS 'Assessment committe ie. Reception, Program Review, Classification..';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."COMMITTE_COMMENT_TEXT" IS 'Assessment committee comments.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."REVIEW_PLACE_AGY_LOC_ID" IS 'Revised agency location placement.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."REVIEW_SUP_LEVEL_TEXT" IS ' Approved security level comment.';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."CREATION_DATE" IS 'The Creation Date of the data';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."CREATION_USER" IS 'The Creation User Identifier of the data';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."ASSESSMENT_CREATE_LOCATION" IS 'Recording the location where assessment was performed';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."ASSESSOR_STAFF_ID" IS 'Recording of the staff id  who performed the assessment';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_ASSESSMENTS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON TABLE "OFFENDER_ASSESSMENTS" IS 'The outcome of a process by which an offender was assessed on a number of dimensions by means of a type of structured interview or check list in which the intention was to identify certain features of the offender so as to provide the basis for decisions made about the offender during his/her period of supervision (for example, cell-sharing, security level, medical)';


CREATE INDEX "OFFENDER_ASSESSMENTS_NI1"
  ON "OFFENDER_ASSESSMENTS" ("ASSESSMENT_TYPE_ID");


CREATE INDEX "OFFENDER_ASSESSMENTS_NI2"
  ON "OFFENDER_ASSESSMENTS" ("PLACE_AGY_LOC_ID");


CREATE INDEX "OFFENDER_ASSESSMENTS_NI3"
  ON "OFFENDER_ASSESSMENTS" ("REVIEW_PLACE_AGY_LOC_ID");


CREATE INDEX "OFF_ASS_AGY_LOC_F3"
  ON "OFFENDER_ASSESSMENTS" ("ASSESSMENT_CREATE_LOCATION");


CREATE INDEX "OFF_ASS_STAFF_F2"
  ON "OFFENDER_ASSESSMENTS" ("ASSESSOR_STAFF_ID");


