CREATE TABLE "OFFENDER_VISITS"
(
  "OFFENDER_VISIT_ID"             NUMBER(10, 0)                     NOT NULL ,
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ,
  "COMMENT_TEXT"                  VARCHAR2(240 CHAR),
  "OVERRIDE_BAN_STAFF_ID"         NUMBER(10, 0),
  "SEARCH_TYPE"                   VARCHAR2(12 CHAR),
  "RAISED_INCIDENT_TYPE"          VARCHAR2(12 CHAR),
  "RAISED_INCIDENT_NUMBER"        NUMBER(10, 0),
  "VISITOR_CONCERN_TEXT"          VARCHAR2(240 CHAR),
  "VISIT_DATE"                    DATE                              NOT NULL ,
  "START_TIME"                    DATE                              NOT NULL ,
  "END_TIME"                      DATE                              NOT NULL ,
  "EVENT_OUTCOME"                 VARCHAR2(12 CHAR),
  "VISIT_TYPE"                    VARCHAR2(12 CHAR)                 NOT NULL ,
  "VISIT_STATUS"                  VARCHAR2(12 CHAR)                 NOT NULL ,
  "OUTCOME_REASON_CODE"           VARCHAR2(12 CHAR),
  "VISIT_INTERNAL_LOCATION_ID"    NUMBER(10, 0),
  "AGENCY_VISIT_SLOT_ID"          NUMBER(10, 0),
  "AGY_LOC_ID"                    VARCHAR2(6 CHAR)                  NOT NULL ,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "RECORD_USER_ID"                VARCHAR2(30 CHAR) DEFAULT USER    NOT NULL ,
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  "OFFENDER_VISIT_ORDER_ID"       NUMBER(10, 0),
  "CLIENT_UNIQUE_REF"             VARCHAR2(100 CHAR),
  CONSTRAINT "OFFENDER_VISIT_PK" PRIMARY KEY ("OFFENDER_VISIT_ID"),
  CONSTRAINT "OFFENDER_VISITS_UK1" UNIQUE ("CLIENT_UNIQUE_REF"),
  CONSTRAINT "OFF_VIST_OFF_BKG_FK" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID")
);

COMMENT ON COLUMN "OFFENDER_VISITS"."OFFENDER_VISIT_ID" IS 'A unique ID for each Visit Order.';
COMMENT ON COLUMN "OFFENDER_VISITS"."OFFENDER_BOOK_ID" IS 'A unique ID for each offender booking.';
COMMENT ON COLUMN "OFFENDER_VISITS"."COMMENT_TEXT" IS 'Free text entry to stores comments against a Visit Order.';
COMMENT ON COLUMN "OFFENDER_VISITS"."OVERRIDE_BAN_STAFF_ID" IS 'The staff who authorises the banned visitor';
COMMENT ON COLUMN "OFFENDER_VISITS"."SEARCH_TYPE" IS 'Reference Code(SEARCH_TYPE)';
COMMENT ON COLUMN "OFFENDER_VISITS"."RAISED_INCIDENT_TYPE" IS 'Reference Code(INC_TYPE)';
COMMENT ON COLUMN "OFFENDER_VISITS"."RAISED_INCIDENT_NUMBER" IS 'The reference number of the raised incident';
COMMENT ON COLUMN "OFFENDER_VISITS"."VISITOR_CONCERN_TEXT" IS 'The concern visitor raised';
COMMENT ON COLUMN "OFFENDER_VISITS"."VISIT_DATE" IS 'The date of the visit';
COMMENT ON COLUMN "OFFENDER_VISITS"."START_TIME" IS 'The start time of the visit';
COMMENT ON COLUMN "OFFENDER_VISITS"."END_TIME" IS 'The end Time of the visit';
COMMENT ON COLUMN "OFFENDER_VISITS"."EVENT_OUTCOME" IS 'The outcome of the visit event.  REference Codes (VIS_COMPLETE)';
COMMENT ON COLUMN "OFFENDER_VISITS"."VISIT_TYPE" IS 'The visit type.  Reference Codes(VISIT_TYPE)';
COMMENT ON COLUMN "OFFENDER_VISITS"."VISIT_STATUS" IS 'The status of visit arrangements.  Reference Codes (VIS_STS)';
COMMENT ON COLUMN "OFFENDER_VISITS"."OUTCOME_REASON_CODE" IS 'The reason of the event outcome.  Reference Codes(MOVE_CANC_RS)';
COMMENT ON COLUMN "OFFENDER_VISITS"."AGY_LOC_ID" IS 'The Related Agency Location Identifier';
COMMENT ON COLUMN "OFFENDER_VISITS"."CREATE_DATETIME" IS 'The timestamp when the record is created';
COMMENT ON COLUMN "OFFENDER_VISITS"."CREATE_USER_ID" IS 'The user who creates the record';
COMMENT ON COLUMN "OFFENDER_VISITS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';
COMMENT ON COLUMN "OFFENDER_VISITS"."MODIFY_USER_ID" IS 'The user who modifies the record';
COMMENT ON TABLE "OFFENDER_VISITS"  IS 'This table will store all the visit orders for an offender.';

CREATE INDEX "OFENDER_VISITS_FK1" ON "OFFENDER_VISITS" ("VISIT_INTERNAL_LOCATION_ID");
CREATE INDEX "OFFENDER_VISITS_NI1" ON "OFFENDER_VISITS" ("OFFENDER_BOOK_ID");
CREATE INDEX "OFFENDER_VISITS_NI10" ON "OFFENDER_VISITS" ("AGY_LOC_ID", "VISIT_DATE", "START_TIME", "END_TIME");
CREATE INDEX "OFFENDER_VISITS_NI4" ON "OFFENDER_VISITS" ("VISIT_DATE");
CREATE INDEX "OFFENDER_VISITS_NI5" ON "OFFENDER_VISITS" ("RAISED_INCIDENT_NUMBER");
CREATE INDEX "OFFENDER_VISITS_NI6" ON "OFFENDER_VISITS" ("AGENCY_VISIT_SLOT_ID");
CREATE INDEX "OFFENDER_VISITS_NI7" ON "OFFENDER_VISITS" ("OFFENDER_VISIT_ORDER_ID");
CREATE INDEX "OFFENDER_VISITS_NI8" ON "OFFENDER_VISITS" ("AGY_LOC_ID", "VISIT_DATE");
CREATE INDEX "OFFENDER_VISITS_X01" ON "OFFENDER_VISITS" ("OFFENDER_BOOK_ID", "VISIT_DATE");
 
