create table HDC_STATUS_TRACKINGS
(
  HDC_STATUS_TRACKING_ID NUMBER(10) not null constraint HDC_STATUS_TRACKINGS_PK primary key,
  OFFENDER_CURFEW_ID NUMBER(10) not null constraint HDC_STATUS_TRACKINGS_FK1 references OFFENDER_CURFEWS,
  STATUS_CODE VARCHAR2(12 char) not null,
  UPDATE_DATE DATE not null,
  CREATE_DATETIME TIMESTAMP(9) default systimestamp not null,
  CREATE_USER_ID VARCHAR2(32 char) default USER not null,
  MODIFY_DATETIME TIMESTAMP(9),
  MODIFY_USER_ID VARCHAR2(32 char),
  AUDIT_TIMESTAMP TIMESTAMP(9),
  AUDIT_USER_ID VARCHAR2(32 char),
  AUDIT_MODULE_NAME VARCHAR2(65 char),
  AUDIT_CLIENT_USER_ID VARCHAR2(64 char),
  AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39 char),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64 char),
  AUDIT_ADDITIONAL_INFO VARCHAR2(256 char)
);

comment on table HDC_STATUS_TRACKINGS is 'This table tracks the status changes for HDC';

