CREATE OR REPLACE TRIGGER "AGENCY_LOCATIONS_T2"
AFTER
DELETE
  ON agency_locations
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
  DECLARE V_numrows INTEGER;
  BEGIN
    -- Lines added by GJC 21/12/2007 to check if the trigger code should be executed or not
    IF SYS_CONTEXT('NOMIS', 'AUDIT_MODULE_NAME', 50) = 'MERGE'
    THEN
      RETURN;
    END IF;
    -- Change added by GJC 21/12/2007 to check if the trigger code should be executed or not
    /* =========================================================
       Version Number = 2.2          Date Modified = 21-Dec-2007
       ========================================================= */
    /* MODIFICATION HISTORY
       Person     	 Date      Version     	 Comments
       ---------    ------     ---------  	 ------------------------------
       Graham       21/12/2007  2.2          #7775: Code added for Merge, fix versioning
       GJC          14/10/2006  2.1          Remove DBMS_OUTPUT call
       David Ng     06/21/2005  1.0          NOMIS new addresses table
    */
    SELECT count(*)
    INTO v_numrows
    FROM addresses
    WHERE owner_Class = 'AGY'
          AND Owner_code = :old.agy_loc_id;
    IF (v_numrows > 0)
    THEN
      raise_application_error(
          -20001,
          'Cannot DELETE the agency location record because agency location address records exists.'
      );
    END IF;

    SELECT count(*)
    INTO v_numrows
    FROM phones
    WHERE owner_Class = 'AGY'
          AND Owner_code = :old.agy_loc_id;
    IF (v_numrows > 0)
    THEN
      raise_application_error(
          -20001,
          'Cannot DELETE the agency location record because agency location phone records exists.'
      );
    END IF;

    SELECT count(*)
    INTO v_numrows
    FROM internet_addresses
    WHERE owner_Class = 'AGY'
          AND Owner_code = :old.agy_loc_id;
    IF (v_numrows > 0)
    THEN
      raise_application_error(
          -20001,
          'Cannot DELETE the agency location record because agency location internet addresses records exists.'
      );
    END IF;

    EXCEPTION
    WHEN OTHERS THEN
    tag_error.handle();

  END;

/



CREATE OR REPLACE TRIGGER "AGENCY_LOCATIONS_TA"
BEFORE INSERT OR UPDATE OR DELETE ON AGENCY_LOCATIONS
REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
    l_scn NUMBER;
    l_tid VARCHAR2(32);
  BEGIN
    /*
    ============================================================
       Generated by 2.3  Date Generation 10-NOV-2008
    ============================================================
      MODIFICATION HISTORY
       Person       Date      version      Comments
    -----------  --------- -----------  -------------------------------
        GJC      05/03/2007  2.3          Allow application setting some columns
        GJC      23/10/2006  2.2          Audit DELETE statements
       David Ng  18/04/2006  2.0.1        Audit column trigger
    */
    IF INSERTING
    THEN
      :NEW.create_datetime := NVL(:NEW.create_datetime, systimestamp);
      :NEW.create_user_id := NVL(:NEW.create_user_id, user);
    ELSIF UPDATING
      THEN
        :NEW.modify_datetime := systimestamp;
        :NEW.modify_user_id := user;
    END IF;
    IF NOT DELETING
    THEN
      :NEW.Audit_timestamp := systimestamp;
      :NEW.Audit_User_ID := SYS_CONTEXT('NOMIS', 'AUDIT_USER_ID', 30);
      :NEW.Audit_Module_Name := SYS_CONTEXT('NOMIS', 'AUDIT_MODULE_NAME', 65);
      :NEW.Audit_Client_User_ID := SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_USER_ID', 64);
      :NEW.Audit_Client_IP_Address := SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_IP_ADDRESS', 39);
      :NEW.Audit_Client_Workstation_Name := SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_WORKSTATION_NAME', 64);
      :NEW.Audit_Additional_Info := SYS_CONTEXT('NOMIS', 'AUDIT_ADDITIONAL_INFO', 256);
    ELSE
      l_tid := DBMS_TRANSACTION.local_transaction_id(create_transaction=>FALSE);
      SELECT current_scn
      INTO l_scn
      FROM v$database;
      INSERT INTO OMS_DELETED_ROWS
      (
        table_name,
        xid,
        scn,
        audit_timestamp,
        audit_user_id,
        audit_module_name,
        audit_client_user_id,
        audit_client_ip_address,
        audit_client_workstation_name,
        audit_additional_info
      )
      VALUES
        (
          'AGENCY_LOCATIONS',
          converttoxid(l_tid),
          l_scn,
          systimestamp,
          SYS_CONTEXT('NOMIS', 'AUDIT_USER_ID', 30),
          SYS_CONTEXT('NOMIS', 'AUDIT_MODULE_NAME', 65),
          SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_USER_ID', 64),
          SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_IP_ADDRESS', 39),
          SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_WORKSTATION_NAME', 64),
          SYS_CONTEXT('NOMIS', 'AUDIT_ADDITIONAL_INFO', 256)
        );
    END IF;
  END;

/



CREATE OR REPLACE TRIGGER "AGENCY_LOCATIONS_T1"
AFTER
INSERT OR UPDATE
  ON agency_locations
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
  BEGIN
    -- Lines added by GJC 21/12/2007 to check if the trigger code should be executed or not
    IF SYS_CONTEXT('NOMIS', 'AUDIT_MODULE_NAME', 50) = 'MERGE'
    THEN
      RETURN;
    END IF;
    -- Change added by GJC 21/12/2007 to check if the trigger code should be executed or not
    /* =========================================================
       Version Number = 2.1  Date Modified = 21-DEC-2007
       ========================================================= */

    /* MODIFICATION HISTORY
       Person      Date            Version       Comments
       ---------   ------       ------------  ------------------------------
       Graham      21-DEC-2007          2.1   #7775: Code added for Merge, fix versioning
       Patrick     27-JUN-2005          1.1   Changed for more history tracking.
       Patrick     21-JUN-2005    	    1.0   Initial Version

    */

    IF oumagyht.check_changed(:OLD.agy_loc_id, :NEW.agy_loc_id)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'AGY_LOC_ID', :OLD.agy_loc_id, :NEW.agy_loc_id, '', '');
    END IF;

    IF oumagyht.check_changed(:OLD.description, :NEW.description)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'DESCRIPTION', :OLD.description, :NEW.description, '',
                                              'AGY');
    END IF;

    IF oumagyht.check_changed(:OLD.agency_location_type, :NEW.agency_location_type)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'AGENCY_LOCATION_TYPE', :OLD.agency_location_type,
                                              :NEW.agency_location_type, 'AGY_LOC_TYPE', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.district_code, :NEW.district_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'DISTRICT_CODE', :OLD.district_code, :NEW.district_code,
                                              'DISTRICT', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.updated_allowed_flag, :NEW.updated_allowed_flag)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'UPDATED_ALLOWED_FLAG', :OLD.updated_allowed_flag,
                                              :NEW.updated_allowed_flag, '', '');
    END IF;

    IF oumagyht.check_changed(:OLD.abbreviation, :NEW.abbreviation)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'ABBREVIATION', :OLD.abbreviation, :NEW.abbreviation, '',
                                              '');
    END IF;

    IF oumagyht.check_changed(:OLD.deactivation_date, :NEW.deactivation_date)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'DEACTIVATION_DATE', :OLD.deactivation_date,
                                              :NEW.deactivation_date, '', 'DATE');
    END IF;

    IF oumagyht.check_changed(:OLD.contact_name, :NEW.contact_name)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'CONTACT_NAME', :OLD.contact_name, :NEW.contact_name, '',
                                              '');
    END IF;

    IF oumagyht.check_changed(:OLD.print_queue, :NEW.print_queue)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'PRINT_QUEUE', :OLD.print_queue, :NEW.print_queue, '',
                                              '');
    END IF;

    IF oumagyht.check_changed(:OLD.jurisdiction_code, :NEW.jurisdiction_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'JURISDICTION_CODE', :OLD.jurisdiction_code,
                                              :NEW.jurisdiction_code, 'JURISDICTION', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.bail_office_flag, :NEW.bail_office_flag)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'BAIL_OFFICE_FLAG', :OLD.bail_office_flag,
                                              :NEW.bail_office_flag, '', '');
    END IF;

    IF oumagyht.check_changed(:OLD.list_seq, :NEW.list_seq)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'LIST_SEQ', :OLD.list_seq, :NEW.list_seq, '', '');
    END IF;

    IF oumagyht.check_changed(:OLD.housing_lev_1_code, :NEW.housing_lev_1_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'HOUSING_LEV_1_CODE', :OLD.housing_lev_1_code,
                                              :NEW.housing_lev_1_code, 'LIVING_UNIT', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.housing_lev_2_code, :NEW.housing_lev_2_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'HOUSING_LEV_2_CODE', :OLD.housing_lev_2_code,
                                              :NEW.housing_lev_2_code, 'LIVING_UNIT', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.housing_lev_3_code, :NEW.housing_lev_3_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'HOUSING_LEV_3_CODE', :OLD.housing_lev_3_code,
                                              :NEW.housing_lev_3_code, 'LIVING_UNIT', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.housing_lev_4_code, :NEW.housing_lev_4_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'HOUSING_LEV_4_CODE', :OLD.housing_lev_4_code,
                                              :NEW.housing_lev_4_code, 'LIVING_UNIT', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.property_lev_1_code, :NEW.property_lev_1_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'PROPERTY_LEV_1_CODE', :OLD.property_lev_1_code,
                                              :NEW.property_lev_1_code, 'PPTY_STG', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.property_lev_2_code, :NEW.property_lev_2_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'PROPERTY_LEV_2_CODE', :OLD.property_lev_2_code,
                                              :NEW.property_lev_2_code, 'PPTY_STG', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.property_lev_3_code, :NEW.property_lev_3_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'PROPERTY_LEV_3_CODE', :OLD.property_lev_3_code,
                                              :NEW.property_lev_3_code, 'PPTY_STG', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.last_booking_no, :NEW.last_booking_no)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'LAST_BOOKING_NO', :OLD.last_booking_no, '',
                                              :NEW.last_booking_no, '');
    END IF;

    IF oumagyht.check_changed(:OLD.commissary_privilege, :NEW.commissary_privilege)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'COMMISSARY_PRIVILEGE', :OLD.commissary_privilege, '',
                                              :NEW.commissary_privilege, '');
    END IF;

    IF oumagyht.check_changed(:OLD.business_hours, :NEW.business_hours)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'BUSINESS_HOURS', :OLD.business_hours, '',
                                              :NEW.business_hours, '');
    END IF;

    IF oumagyht.check_changed(:OLD.address_type, :NEW.address_type)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'ADDRESS_TYPE', :OLD.address_type, :NEW.address_type,
                                              'ADDR_TYPE', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.service_required_flag, :NEW.service_required_flag)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'SERVICE_REQUIRED_FLAG', :OLD.service_required_flag,
                                              :NEW.service_required_flag, '', '');
    END IF;

    IF oumagyht.check_changed(:OLD.cjit_code, :NEW.cjit_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'CJIT_CODE', :OLD.cjit_code, :NEW.cjit_code, '', '');
    END IF;

    IF oumagyht.check_changed(:OLD.active_flag, :NEW.active_flag)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'ACTIVE_FLAG', :OLD.active_flag, :NEW.active_flag, '',
                                              '');
    END IF;

    IF oumagyht.check_changed(:OLD.disability_access_code, :NEW.disability_access_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'DISABILITY_ACCESS_CODE', :OLD.disability_access_code,
                                              :NEW.disability_access_code, 'DISABILITY', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.intake_flag, :NEW.intake_flag)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'INTAKE_FLAG', :OLD.intake_flag, :NEW.intake_flag, '',
                                              '');
    END IF;

    IF oumagyht.check_changed(:OLD.long_description, :NEW.long_description)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'LONG_DESCRIPTION', :OLD.long_description,
                                              :NEW.long_description, '', '');
    END IF;

    IF oumagyht.check_changed(:OLD.sub_area_code, :NEW.sub_area_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'SUB_AREA_CODE', :OLD.sub_area_code, :NEW.sub_area_code,
                                              'SUB_AREA', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.area_code, :NEW.area_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'AREA_CODE', :OLD.area_code, :NEW.area_code, 'AREA',
                                              'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.noms_region_code, :NEW.noms_region_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'NOMS_REGION_CODE', :OLD.noms_region_code,
                                              :NEW.noms_region_code, 'REGION', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.geographic_region_code, :NEW.geographic_region_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'GEOGRAPHIC_REGION_CODE', :OLD.geographic_region_code,
                                              :NEW.geographic_region_code, 'GEOGRAPHIC', 'REF_CODE');
    END IF;

    IF oumagyht.check_changed(:OLD.justice_area_code, :NEW.justice_area_code)
    THEN
      oumagyht.insert_into_agy_loc_amendments(:NEW.agy_loc_id, 'JUSTICE_AREA_CODE', :OLD.justice_area_code,
                                              :NEW.justice_area_code, 'LOCAL_AREA', 'REF_CODE');
    END IF;
  END;

/


