
CREATE OR REPLACE TRIGGER "OFFENDER_CHARGES_T1"
BEFORE INSERT
  ON offender_charges
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
  BEGIN
    -- Lines added by GJC 21/12/2007 to check if the trigger code should be executed or not
    IF SYS_CONTEXT('NOMIS', 'AUDIT_MODULE_NAME', 50) = 'MERGE'
    THEN
      RETURN;
    END IF;
    -- Change added by GJC 21/12/2007 to check if the trigger code should be executed or not
    /*
       ============================================================
       Version Number = 2.5  Date Modified = 09/05/2008
       ============================================================
       MODIFICATION HISTORY
       Person       Date        version      Comments
       -----------  ---------   -----------  ------------------------------------------
       Laurence     09/05/2008  2.5          Removed context check when populating
                                             lids_offence_number.  Now only does this
                                             when the value is null (and is hence not
                                             been passed in from migration).
       Graham       21/12/2007  2.4          #7775: Code added for Merge, fix versioning
       Surya        05/07/2006  2.3          Def#3125: Added additional audit module names, as
                                             it was not getting different module name
                                             for one particular XML file.
       Surya        05/06/2006  2.2          Modified, as lids_charge_number is moved to
                                             agency_incident_charges as per the design change.
       Surya        31/05/2006  2.1          The LIDS numbers should be populated
                                             from the Application and Interface but not
                                             from xTag Data migration.
       Surya        30/05/2006  2.0          Initial Draft.
                                             1.Lids Offence Number increments
                                             with in the current booking and case.
                                             2.Lids Charge Number increments
                                             with in establishment and year.
       */

    IF :new.lids_offence_number IS NULL
    THEN
      SELECT NVL(MAX(lids_offence_number), 0) + 1
      INTO :NEW.lids_offence_number
      FROM offender_charges
      WHERE offender_book_id = :NEW.offender_book_id
            AND case_id = :NEW.case_id;
    END IF;
    EXCEPTION
    WHEN OTHERS
    THEN
    tag_error.handle;
  END offender_charges_t1;

/



CREATE OR REPLACE TRIGGER "OFFENDER_CHARGES_TA"
BEFORE INSERT OR UPDATE OR DELETE ON OFFENDER_CHARGES
REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
    l_scn NUMBER;
    l_tid VARCHAR2(32);
  BEGIN
    /*
    ============================================================
       Generated by 2.3  Date Generation 10-NOV-2008
    ============================================================
      MODIFICATION HISTORY
       Person       Date      version      Comments
    -----------  --------- -----------  -------------------------------
        GJC      05/03/2007  2.3          Allow application setting some columns
        GJC      23/10/2006  2.2          Audit DELETE statements
       David Ng  18/04/2006  2.0.1        Audit column trigger
    */
    IF INSERTING
    THEN
      :NEW.create_datetime := NVL(:NEW.create_datetime, systimestamp);
      :NEW.create_user_id := NVL(:NEW.create_user_id, user);
    ELSIF UPDATING
      THEN
        :NEW.modify_datetime := systimestamp;
        :NEW.modify_user_id := user;
    END IF;
    IF NOT DELETING
    THEN
      :NEW.Audit_timestamp := systimestamp;
      :NEW.Audit_User_ID := SYS_CONTEXT('NOMIS', 'AUDIT_USER_ID', 30);
      :NEW.Audit_Module_Name := SYS_CONTEXT('NOMIS', 'AUDIT_MODULE_NAME', 65);
      :NEW.Audit_Client_User_ID := SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_USER_ID', 64);
      :NEW.Audit_Client_IP_Address := SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_IP_ADDRESS', 39);
      :NEW.Audit_Client_Workstation_Name := SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_WORKSTATION_NAME', 64);
      :NEW.Audit_Additional_Info := SYS_CONTEXT('NOMIS', 'AUDIT_ADDITIONAL_INFO', 256);
    ELSE
      l_tid := DBMS_TRANSACTION.local_transaction_id(create_transaction=>FALSE);
      SELECT current_scn
      INTO l_scn
      FROM v$database;
      INSERT INTO OMS_DELETED_ROWS
      (
        table_name,
        xid,
        scn,
        audit_timestamp,
        audit_user_id,
        audit_module_name,
        audit_client_user_id,
        audit_client_ip_address,
        audit_client_workstation_name,
        audit_additional_info
      )
      VALUES
        (
          'OFFENDER_CHARGES',
          converttoxid(l_tid),
          l_scn,
          systimestamp,
          SYS_CONTEXT('NOMIS', 'AUDIT_USER_ID', 30),
          SYS_CONTEXT('NOMIS', 'AUDIT_MODULE_NAME', 65),
          SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_USER_ID', 64),
          SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_IP_ADDRESS', 39),
          SYS_CONTEXT('NOMIS', 'AUDIT_CLIENT_WORKSTATION_NAME', 64),
          SYS_CONTEXT('NOMIS', 'AUDIT_ADDITIONAL_INFO', 256)
        );
    END IF;
  END;

/


