CREATE USER MICK_NOMIS_OWNER IDENTIFIED BY MICK_NOMIS_OWNER TEMPORARY TABLESPACE temp DEFAULT TABLESPACE users;
GRANT CONNECT TO MICK_NOMIS_OWNER;
GRANT RESOURCE TO MICK_NOMIS_OWNER;
ALTER USER MICK_NOMIS_OWNER QUOTA 20G ON USERS;
GRANT UNLIMITED TABLESPACE TO MICK_NOMIS_OWNER;
grant select on v$database to MICK_NOMIS_OWNER;



