CREATE USER MWILLIS_NOMIS_OWNER IDENTIFIED BY MWILLIS_NOMIS_OWNER TEMPORARY TABLESPACE temp DEFAULT TABLESPACE users;
GRANT CONNECT TO MWILLIS_NOMIS_OWNER;
GRANT RESOURCE TO MWILLIS_NOMIS_OWNER;
ALTER USER MWILLIS_NOMIS_OWNER QUOTA 20G ON USERS;
GRANT UNLIMITED TABLESPACE TO MWILLIS_NOMIS_OWNER;
grant select on v$database to MWILLIS_NOMIS_OWNER;

CREATE USER CI_BUILD_NOMIS_OWNER IDENTIFIED BY MWILLIS_NOMIS_OWNER TEMPORARY TABLESPACE temp DEFAULT TABLESPACE users;
GRANT CONNECT TO CI_BUILD_NOMIS_OWNER;
GRANT RESOURCE TO CI_BUILD_NOMIS_OWNER;
ALTER USER CI_BUILD_NOMIS_OWNER QUOTA 20G ON USERS;
GRANT UNLIMITED TABLESPACE TO CI_BUILD_NOMIS_OWNER;
grant select on v$database to CI_BUILD_NOMIS_OWNER;




