#%RAML 1.0
title: Elite2 Public API
baseUri: http://api.elite2.syscon.net/v2
version: v2
mediaType: application/json
annotationTypes:
  javaOperationName:
    type: string
    description: Hint to downstream code generator of name to use for Java method that implements operation.
  javaType:
    type: string
    description: override type to specified java type
  headersWithType:
    type: string
    description: override the type used in a reponse headers (e.g. headersWithType_Long: Page-Offset,Page-Limit will apply a Long to the listed headers)
securedBy: [jwt]
types:
  Agency:          !include types/Agency.raml
  ErrorResponse:   !include types/ErrorResponse.raml
  Location:        !include types/Location.raml
  OffenderBooking: !include types/OffenderBooking.raml
  PrisonerDetail:  !include types/PrisonerDetail.raml
  SentenceDetail:  !include types/SentenceDetail.raml
  ImageDetail:     !include types/ImageDetail.raml

securitySchemes:
  jwt:
    description: Elite API uses Json Web Token (JWT) to authenticate most requests
    type: x-jwt
    describedBy:
      headers:
        Authorization:
          description: Used to send a valid JWT. Do not use  query string parameter.
          type: string
          example: "Authorization: Bearer eyJpc3MiOiJzY290Y2guaW8iLCJleHAiOjEzMDA4MTkzODAsIm5hbWUiOiJDaHJpcyBTZXZpbGxlamEiLCJhZG1pbiI6dHJ1ZX0"

  basic:
    description: Each request must contain the headers necessary for basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password" credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

traits: !include traits/traits.raml
resourceTypes: !include resourceTypes/generic-resource-types.raml

/agencies:          !include resources/agencies.raml
/images:            !include resources/images.raml
/bookings:          !include resources/bookings.raml
/prisoners:         !include resources/prisoners.raml
/search-offenders:  !include resources/search-offenders.raml
/users:             !include resources/users.raml

