---
# Values here are the same across all environments
generic-service:
  nameOverride: prison-api
  productId: DPS060
  replicaCount: 5 # One per node

  image:
    repository: quay.io/hmpps/prison-api
    tag: latest
    port: 8080

  service:
    enabled: false

  ingress:
    enabled: false
    modsecurity_snippet: |
      SecRuleEngine On
      # team here grants access to the OpenSearch logs to delve into the cause of the blockage
      SecDefaultAction "phase:2,pass,log,tag:github_team=dps-tech"
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
      # Missing User Agent Header
      SecRuleRemoveById 920320
      # Request Missing an Accept Header
      SecRuleRemoveById 920300
      # Restrict file extension
      SecRuleRemoveById 920440
      # SQL Injection Attack: Common Injection Testing Detected
      SecRuleRemoveById 942110
      # Found User-Agent associated with scripting/generic HTTP client
      SecRuleRemoveById 913101
      SecRuleUpdateTargetById 921110 "!ARGS:/.*comment/"
      SecRuleUpdateTargetById 932150 "!ARGS:/.*comment/"
      SecRuleUpdateTargetById 932150 "!ARGS:/keywords/"
      SecRuleUpdateTargetById 933210 "!ARGS:/.*description/"
      SecRuleUpdateTargetById 942100 "!ARGS:/.*description/"
      SecRuleUpdateTargetById 942330 "!ARGS:/keywords/"
      SecRuleUpdateTargetById 942130 "!ARGS:/text/"
      SecRuleUpdateTargetById 942130 "!ARGS:/.*comment/"
      SecRuleUpdateTargetById 942130 "!ARGS:/statement/"
      SecRuleUpdateTargetById 942130 "!ARGS:/.*description/"
      SecRuleUpdateTargetById 942150 "!ARGS:/outcomeComment/"
      SecRuleUpdateTargetById 942230 "!ARGS:/.*description/"
      SecRuleUpdateTargetById 942410 "!ARGS:/outcomeComment/"
      # Disable rule 932110 as it only applies to Windows host servers
      SecRuleRemoveById 932110
      # Disable rule 942360 (SQL Injection) for create and update alert - /api/bookings/:bookingId/alert and /api/bookings/:bookingId/alert/:alertId
      SecRule REQUEST_URI "@rx ^\/api\/bookings\/[\w|\d]*\/(alert$|alert\/[\w|\d|-]+)" "id:800001,phase:1,pass,t:none,nolog,ctl:ruleRemoveById=942360"
      # Disable rule 942360 (SQL Injection) for create and update case note - /api/offenders/:offenderNo/case-notes and /api/offenders/:offenderNo/case-notes/:caseNoteId
      SecRule REQUEST_URI "@rx ^\/api\/offenders\/[\w|\d]*\/(case-notes$|case-notes\/[\w|\d|-]+)" "id:800002,phase:1,pass,t:none,nolog,ctl:ruleRemoveById=942360"
      # Change default denial to be a 406 so that we can tell easily that it is modsecurity doing the blocking
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"

  livenessProbe:
    periodSeconds: 30
    initialDelaySeconds: 90
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  resources:
    requests:
      cpu: 500m
      memory: 1600Mi
    limits:
      cpu: 3000m
      memory: 2048Mi

  env:
    JAVA_OPTS: "-Xms1024m -Xmx1024m"
    SERVER_PORT: 8080
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

    SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 15
    SPRING_REPLICA_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 50
    SMOKE_TEST_AWARE: false
    SPRING_PROFILES_ACTIVE: "nomis"

  namespace_secrets:
    prison-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SPRING_DATASOURCE_PASSWORD: "SPRING_DATASOURCE_PASSWORD"
      SPRING_DATASOURCE_URL: "SPRING_DATASOURCE_URL"
      SPRING_REPLICA_DATASOURCE_PASSWORD: "SPRING_REPLICA_DATASOURCE_PASSWORD"
      SPRING_REPLICA_DATASOURCE_URL: "SPRING_REPLICA_DATASOURCE_URL"
      SPRING_REPLICA_DATASOURCE_USERNAME: "SPRING_REPLICA_DATASOURCE_USERNAME"

generic-prometheus-alerts:
  targetApplication: prison-api
  alertSeverity: syscon
  applicationAlertsEnabled: false
  ingressAlertsEnabled: false
