---
# Values here are the same across all environments
generic-service:
  nameOverride: prison-api
  replicaCount: 6

  image:
    repository: quay.io/hmpps/prison-api
    tag: latest
    port: 8080

  service:
    enabled: false

  livenessProbe:
    periodSeconds: 30
    initialDelaySeconds: 90
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  resources:
    requests:
      cpu: 100m
      memory: 640Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

  env:
    JAVA_OPTS: "-Xmx1024m"
    SERVER_PORT: 8080
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

    SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 15
    SPRING_REPLICA_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 50
    SMOKE_TEST_AWARE: false
    SPRING_PROFILES_ACTIVE: "nomis"

  namespace_secrets:
    prison-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SPRING_DATASOURCE_PASSWORD: "SPRING_DATASOURCE_PASSWORD"
      SPRING_DATASOURCE_URL: "SPRING_DATASOURCE_URL"
      SPRING_REPLICA_DATASOURCE_PASSWORD: "SPRING_REPLICA_DATASOURCE_PASSWORD"
      SPRING_REPLICA_DATASOURCE_URL: "SPRING_REPLICA_DATASOURCE_URL"
      SPRING_REPLICA_DATASOURCE_USERNAME: "SPRING_REPLICA_DATASOURCE_USERNAME"
