---
# Values here are the same across all environments
generic-service:
  nameOverride: prison-api
  replicaCount: 3

  image:
    repository: quay.io/hmpps/prison-api
    tag: latest
    port: 8080

  service:
    enabled: false

  livenessProbe:
    periodSeconds: 30
    initialDelaySeconds: 90
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  env:
    JAVA_OPTS: "-Xmx1024m"
    SERVER_PORT: 8080
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

    DATA_COMPLIANCE_DELETION_ENABLED: false
    DATA_COMPLIANCE_DECEASED_DELETION_ENABLED: false
    SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 15
    SPRING_REPLICA_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 50
    SMOKE_TEST_AWARE: false
    SPRING_PROFILES_ACTIVE: "nomis"

  namespace_secrets:
    prison-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      DATA_COMPLIANCE_REQUEST_SQS_AWS_ACCESS_KEY_ID: "DATA_COMPLIANCE_REQUEST_SQS_AWS_ACCESS_KEY_ID"
      DATA_COMPLIANCE_REQUEST_SQS_AWS_SECRET_ACCESS_KEY: "DATA_COMPLIANCE_REQUEST_SQS_AWS_SECRET_ACCESS_KEY"
      DATA_COMPLIANCE_REQUEST_SQS_DLQ_AWS_ACCESS_KEY_ID: "DATA_COMPLIANCE_REQUEST_SQS_DLQ_AWS_ACCESS_KEY_ID"
      DATA_COMPLIANCE_REQUEST_SQS_DLQ_AWS_SECRET_ACCESS_KEY: "DATA_COMPLIANCE_REQUEST_SQS_DLQ_AWS_SECRET_ACCESS_KEY"
      DATA_COMPLIANCE_REQUEST_SQS_DLQ_NAME: "DATA_COMPLIANCE_REQUEST_SQS_DLQ_NAME"
      DATA_COMPLIANCE_REQUEST_SQS_PROVIDER: "DATA_COMPLIANCE_REQUEST_SQS_PROVIDER"
      DATA_COMPLIANCE_REQUEST_SQS_QUEUE_NAME: "DATA_COMPLIANCE_REQUEST_SQS_QUEUE_NAME"
      DATA_COMPLIANCE_REQUEST_SQS_REGION: "DATA_COMPLIANCE_REQUEST_SQS_REGION"
      DATA_COMPLIANCE_RESPONSE_SQS_AWS_ACCESS_KEY_ID: "DATA_COMPLIANCE_RESPONSE_SQS_AWS_ACCESS_KEY_ID"
      DATA_COMPLIANCE_RESPONSE_SQS_AWS_SECRET_ACCESS_KEY: "DATA_COMPLIANCE_RESPONSE_SQS_AWS_SECRET_ACCESS_KEY"
      DATA_COMPLIANCE_RESPONSE_SQS_DLQ_AWS_ACCESS_KEY_ID: "DATA_COMPLIANCE_RESPONSE_SQS_DLQ_AWS_ACCESS_KEY_ID"
      DATA_COMPLIANCE_RESPONSE_SQS_DLQ_AWS_SECRET_ACCESS_KEY: "DATA_COMPLIANCE_RESPONSE_SQS_DLQ_AWS_SECRET_ACCESS_KEY"
      DATA_COMPLIANCE_RESPONSE_SQS_DLQ_NAME: "DATA_COMPLIANCE_RESPONSE_SQS_DLQ_NAME"
      DATA_COMPLIANCE_RESPONSE_SQS_PROVIDER: "DATA_COMPLIANCE_RESPONSE_SQS_PROVIDER"
      DATA_COMPLIANCE_RESPONSE_SQS_QUEUE_NAME: "DATA_COMPLIANCE_RESPONSE_SQS_QUEUE_NAME"
      DATA_COMPLIANCE_RESPONSE_SQS_QUEUE_URL: "DATA_COMPLIANCE_RESPONSE_SQS_QUEUE_URL"
      DATA_COMPLIANCE_RESPONSE_SQS_REGION: "DATA_COMPLIANCE_RESPONSE_SQS_REGION"
      SPRING_DATASOURCE_PASSWORD: "SPRING_DATASOURCE_PASSWORD"
      SPRING_DATASOURCE_URL: "SPRING_DATASOURCE_URL"
      SPRING_REPLICA_DATASOURCE_PASSWORD: "SPRING_REPLICA_DATASOURCE_PASSWORD"
      SPRING_REPLICA_DATASOURCE_URL: "SPRING_REPLICA_DATASOURCE_URL"
      SPRING_REPLICA_DATASOURCE_USERNAME: "SPRING_REPLICA_DATASOURCE_USERNAME"
