FIND_AWARDS {
  SELECT S.OIC_SANCTION_CODE   AS SANCTION_CODE,
         RC1.DESCRIPTION       AS SANCTION_CODE_DESCRIPTION,
         S.SANCTION_MONTHS     AS MONTHS,
         S.SANCTION_DAYS       AS DAYS,
         S.COMPENSATION_AMOUNT AS LIMIT,
         S.COMMENT_TEXT        AS "COMMENT",
         S.EFFECTIVE_DATE      AS EFFECTIVE_DATE,
         S.STATUS,
         RC2.DESCRIPTION       AS STATUS_DESCRIPTION,
         S.OIC_HEARING_ID      AS HEARING_ID,
         S.RESULT_SEQ          AS HEARING_SEQUENCE
  FROM OFFENDER_OIC_SANCTIONS S
    INNER JOIN OIC_HEARING_RESULTS H ON S.OIC_HEARING_ID = H.OIC_HEARING_ID AND S.RESULT_SEQ = H.RESULT_SEQ
    LEFT JOIN REFERENCE_CODES RC1 ON S.OIC_SANCTION_CODE = RC1.CODE AND RC1.DOMAIN = 'OIC_SANCT'
    LEFT JOIN REFERENCE_CODES RC2 ON S.STATUS = RC2.CODE AND RC2.DOMAIN = 'OIC_SANCT_ST'
  WHERE S.OFFENDER_BOOK_ID = :bookingId
    AND H.FINDING_CODE = 'PROVED'
  ORDER BY S.OIC_HEARING_ID, S.RESULT_SEQ
}
