
FIND_AGENCY {
    SELECT A.AGY_LOC_ID,
           A.DESCRIPTION,
           A.AGENCY_LOCATION_TYPE
      FROM AGENCY_LOCATIONS A JOIN CASELOAD_AGENCY_LOCATIONS C
         ON A.AGY_LOC_ID = C.AGY_LOC_ID
     WHERE A.ACTIVE_FLAG = 'Y'
           AND A.AGY_LOC_ID NOT IN ('OUT', 'TRN')
           AND A.AGY_LOC_ID = :agencyId
           AND C.CASELOAD_ID = :caseLoadId
  ORDER BY A.AGY_LOC_ID
}

FIND_ALL_AGENCIES {
    SELECT A.AGY_LOC_ID,
           A.DESCRIPTION,
           A.AGENCY_LOCATION_TYPE
      FROM AGENCY_LOCATIONS A JOIN CASELOAD_AGENCY_LOCATIONS C
        ON A.AGY_LOC_ID = C.AGY_LOC_ID
     WHERE A.ACTIVE_FLAG = 'Y'
           AND A.AGY_LOC_ID NOT IN ('OUT', 'TRN')
           AND C.CASELOAD_ID = :caseLoadId
  ORDER BY A.AGY_LOC_ID
}

