FIND_CASE_LOADS_BY_STAFF_ID {
	SELECT CL.CASELOAD_ID,
	       CL.DESCRIPTION
	  FROM CASELOADS CL
	       INNER JOIN STAFF_ACCESSIBLE_CASELOADS SC ON CL.CASELOAD_ID = SC.CASELOAD_ID
	 WHERE SC.STAFF_ID = :staffId
}

FIND_CASE_LOAD_BY_ID {
	SELECT CL.CASELOAD_ID,
	       CL.DESCRIPTION
	  FROM CASELOADS CL
	 WHERE CL.CASELOAD_ID = :caseLoadId  
}


