
FIND_IMAGE_DETAIL {
    SELECT I.IMAGE_ID,
           I.CAPTURE_DATE,
           I.IMAGE_VIEW_TYPE   IMAGE_VIEW,
           I.ORIENTATION_TYPE  IMAGE_ORIENTATION,
           I.IMAGE_OBJECT_TYPE IMAGE_TYPE,
           I.IMAGE_OBJECT_ID   OBJECT_ID
      FROM IMAGES I
     WHERE I.IMAGE_ID = :imageId
}

FIND_IMAGE_CONTENT {
    SELECT I.IMAGE_THUMBNAIL
      FROM IMAGES I
     WHERE I.IMAGE_ID = :imageId
}

