FIND_INMATE_ALERTS {
	select ALERT_SEQ, ALERT_DATE, ALERT_TYPE,
		COALESCE(alType.DESCRIPTION, ALERT_TYPE) as ALERT_TYPE_DESC,
		ALERT_CODE,
		COALESCE(alCode.DESCRIPTION, ALERT_CODE) as ALERT_CODE_DESC,
		EXPIRY_DATE, COMMENT_TEXT
	from offender_alerts
		LEFT JOIN REFERENCE_CODES altype ON altype.DOMAIN = 'ALERT' and altype.CODE = ALERT_TYPE
		LEFT JOIN REFERENCE_CODES alCode ON alCode.DOMAIN = 'ALERT_CODE' and alCode.CODE = ALERT_CODE
	where OFFENDER_BOOK_ID = :bookingId
}
FIND_INMATE_ALERT {
	select ALERT_SEQ, ALERT_DATE, ALERT_TYPE,
		COALESCE(alType.DESCRIPTION, ALERT_TYPE) as ALERT_TYPE_DESC,
		ALERT_CODE,
		COALESCE(alCode.DESCRIPTION, ALERT_CODE) as ALERT_CODE_DESC,
		EXPIRY_DATE, COMMENT_TEXT
	from offender_alerts
	  LEFT JOIN REFERENCE_CODES altype ON altype.DOMAIN = 'ALERT' and altype.CODE = ALERT_TYPE
		LEFT JOIN REFERENCE_CODES alCode ON alCode.DOMAIN = 'ALERT_CODE' and alCode.CODE = ALERT_CODE
	where OFFENDER_BOOK_ID = :bookingId and ALERT_SEQ = :alertSeqId
}

ALERT_COUNTS {
  SELECT COUNT(*) FROM OFFENDER_ALERTS A WHERE A.OFFENDER_BOOK_ID = :bookingId AND ALERT_STATUS = :status
}