FIND_INMATE_ALERTS {
	select ALERT_SEQ, ALERT_DATE, ALERT_TYPE,
		alType.DESCRIPTION as ALERT_TYPE_DESC,
		ALERT_CODE,
		alCode.DESCRIPTION as ALERT_CODE_DESC,
		EXPIRY_DATE, COMMENT_TEXT
	from offender_alerts
		JOIN REFERENCE_CODES altype ON altype.DOMAIN = 'ALERT' and altype.CODE = ALERT_TYPE
		JOIN REFERENCE_CODES alCode ON alCode.DOMAIN = 'ALERT_CODE' and alCode.CODE = ALERT_CODE
	where OFFENDER_BOOK_ID = :bookingId
}
FIND_INMATE_ALERT {
	select ALERT_SEQ, ALERT_DATE, ALERT_TYPE,
		alType.DESCRIPTION as ALERT_TYPE_DESC,
		ALERT_CODE,
		alCode.DESCRIPTION as ALERT_CODE_DESC,
		EXPIRY_DATE, COMMENT_TEXT
	from offender_alerts
		JOIN REFERENCE_CODES altype ON altype.DOMAIN = 'ALERT' and altype.CODE = ALERT_TYPE
		JOIN REFERENCE_CODES alCode ON alCode.DOMAIN = 'ALERT_CODE' and alCode.CODE = ALERT_CODE
	where OFFENDER_BOOK_ID = :bookingId and ALERT_SEQ = :alertSeqId
}