FIND_INMATE_ALERTS {
	select ALERT_SEQ, ALERT_DATE, ALERT_TYPE, ALERT_CODE, EXPIRY_DATE, COMMENT_TEXT from offender_alerts where OFFENDER_BOOK_ID = :bookingId 
}
FIND_INMATE_ALERT {
	select ALERT_SEQ, ALERT_DATE, ALERT_TYPE, ALERT_CODE, EXPIRY_DATE, COMMENT_TEXT from offender_alerts where OFFENDER_BOOK_ID = :bookingId and ALERT_SEQ = :alertSeqId
}