FIND_REFERENCE_DOMAIN {
  SELECT DOMAIN,
         DESCRIPTION,
         DOMAIN_STATUS,
         OWNER_CODE,
         APPLN_CODE,
         PARENT_DOMAIN
  FROM REFERENCE_DOMAINS
  WHERE DOMAIN = :domain
}

FIND_REFERENCE_CODES_BY_DOMAIN {
  SELECT CODE,
         DOMAIN,
         DESCRIPTION,
         PARENT_DOMAIN,
         PARENT_CODE,
         ACTIVE_FLAG
	FROM REFERENCE_CODES
	WHERE DOMAIN = :domain
}

FIND_REFERENCE_CODES_BY_DOMAIN_HAVING_SUB_CODES {
SELECT RC1.CODE,
       RC1.DOMAIN,
       RC1.DESCRIPTION,
       RC1.PARENT_DOMAIN,
       RC1.PARENT_CODE,
       RC1.ACTIVE_FLAG
FROM REFERENCE_CODES RC1
WHERE RC1.DOMAIN = :domain
  AND EXISTS (SELECT 1 FROM REFERENCE_CODES RC2 WHERE RC2.PARENT_DOMAIN = RC1.DOMAIN AND RC2.PARENT_CODE = RC1.CODE)
}

FIND_REFERENCE_CODES_BY_PARENT_DOMAIN_AND_CODE {
  SELECT CODE,
         DOMAIN,
         DESCRIPTION,
         PARENT_DOMAIN,
         PARENT_CODE,
         ACTIVE_FLAG
	FROM REFERENCE_CODES
	WHERE PARENT_DOMAIN = :parentDomain
	  AND PARENT_CODE IN (:parentCodes)
}

FIND_REFERENCE_CODES_BY_DOMAIN_AND_CODE_WITH_CHILDREN {
	SELECT RC.CODE,
	       RC.DOMAIN,
	       RC.DESCRIPTION,
	       RC.PARENT_DOMAIN,
	       RC.PARENT_CODE,
	       RC.ACTIVE_FLAG,
	       RCSUB.CODE SUB_CODE,
	       RCSUB.DOMAIN SUB_DOMAIN,
	       RCSUB.DESCRIPTION SUB_DESCRIPTION,
	       RCSUB.ACTIVE_FLAG SUB_ACTIVE_FLAG
	FROM REFERENCE_CODES RC
    INNER JOIN REFERENCE_CODES RCSUB ON RCSUB.PARENT_CODE = RC.CODE AND RCSUB.PARENT_DOMAIN = RC.DOMAIN
    INNER JOIN REFERENCE_DOMAINS RD ON RCSUB.DOMAIN = RD.DOMAIN AND RC.DOMAIN = RD.PARENT_DOMAIN
	WHERE RC.DOMAIN = :domain
  	AND RC.CODE = :code
}

FIND_REFERENCE_CODE_BY_DOMAIN_AND_CODE {
  SELECT RC.CODE,
         RC.DOMAIN,
         RC.DESCRIPTION,
         RC.PARENT_DOMAIN,
         RC.PARENT_CODE,
         RC.ACTIVE_FLAG
	FROM REFERENCE_CODES RC
	  INNER JOIN REFERENCE_DOMAINS RD ON RC.DOMAIN = RD.DOMAIN
	WHERE RC.DOMAIN = :domain
	  AND RC.CODE = :code
}

GET_AVAILABLE_EVENT_SUBTYPES {
 --- For INSERT_APPOINTMENT
  SELECT internal_schedule_rsn_code AS code,
       description AS description
  FROM internal_schedule_reasons WHERE internal_schedule_type = :eventType AND active_flag = 'Y'
  ORDER BY description
}
