FIND_REFERENCE_CODES_BY_DOMAIN {
  SELECT CODE,
         DOMAIN,
         DESCRIPTION,
         PARENT_DOMAIN PARENT_DOMAIN_ID,
         PARENT_CODE,
         ACTIVE_FLAG
	FROM REFERENCE_CODES
	WHERE DOMAIN = :domain
}

FIND_REFERENCE_CODES_BY_DOMAIN_HAVING_SUB_CODES {
SELECT RC1.CODE,
       RC1.DOMAIN,
       RC1.DESCRIPTION,
       RC1.PARENT_DOMAIN PARENT_DOMAIN_ID,
       RC1.PARENT_CODE,
       RC1.ACTIVE_FLAG
FROM REFERENCE_CODES RC1
WHERE RC1.DOMAIN = :domain
  AND EXISTS (SELECT 1 FROM REFERENCE_CODES RC2 WHERE RC2.PARENT_DOMAIN = RC1.DOMAIN AND RC2.PARENT_CODE = RC1.CODE)
}

FIND_REFERENCE_CODES_BY_PARENT_DOMAIN_AND_CODE {
  SELECT CODE,
         DOMAIN,
         DESCRIPTION,
         PARENT_DOMAIN PARENT_DOMAIN_ID,
         PARENT_CODE,
         ACTIVE_FLAG
	FROM REFERENCE_CODES
	WHERE PARENT_DOMAIN = :parentDomain
	  AND PARENT_CODE IN (:parentCodes)
}

FIND_REFERENCE_CODES_BY_DOMAIN_AND_CODE_WITH_CHILDREN {
	SELECT RC.CODE,
	       RC.DOMAIN,
	       RC.DESCRIPTION,
	       RC.PARENT_DOMAIN PARENT_DOMAIN_ID,
	       RC.PARENT_CODE,
	       RC.ACTIVE_FLAG,
	       RCSUB.CODE SUB_CODE,
	       RCSUB.DOMAIN SUB_DOMAIN,
	       RCSUB.DESCRIPTION SUB_DESCRIPTION,
	       RCSUB.ACTIVE_FLAG SUB_ACTIVE_FLAG
	FROM REFERENCE_CODES RC
	  LEFT JOIN REFERENCE_CODES RCSUB ON RCSUB.PARENT_CODE = RC.CODE AND RCSUB.PARENT_DOMAIN = RC.DOMAIN
	WHERE RC.DOMAIN = :domain
	AND RC.CODE = :code
}

FIND_REFERENCE_CODE_BY_DOMAIN_AND_CODE {
  SELECT CODE,
         DOMAIN,
         DESCRIPTION,
         PARENT_DOMAIN PARENT_DOMAIN_ID,
         PARENT_CODE,
         ACTIVE_FLAG
	FROM REFERENCE_CODES
	WHERE DOMAIN = :domain
	  AND CODE = :code
}
