FIND_USER_BY_STAFF_ID {
  SELECT SM.STAFF_ID,
         SM.FIRST_NAME,
         SM.LAST_NAME,
         (SELECT IA.INTERNET_ADDRESS
          FROM INTERNET_ADDRESSES IA
          WHERE IA.OWNER_ID = SM.STAFF_ID
            AND IA.OWNER_CLASS = 'STF'
            AND IA.INTERNET_ADDRESS_CLASS = 'EMAIL') EMAIL,
         (SELECT MAX(I.IMAGE_ID)
          FROM IMAGES I
          WHERE SM.STAFF_ID = I.IMAGE_OBJECT_ID
            AND I.IMAGE_OBJECT_TYPE = 'STAFF'
            AND I.ACTIVE_FLAG = 'Y') THUMBNAIL_ID
  FROM STAFF_MEMBERS SM
  WHERE SM.STAFF_ID = :staffId
}
