FIND_USER_BY_STAFF_ID {
  SELECT SM.STAFF_ID,
         SM.FIRST_NAME,
         SM.LAST_NAME,
         (SELECT IA.INTERNET_ADDRESS
          FROM INTERNET_ADDRESSES IA
          WHERE IA.OWNER_ID = SM.STAFF_ID
            AND IA.OWNER_CLASS = 'STF'
            AND IA.INTERNET_ADDRESS_CLASS = 'EMAIL') EMAIL,
         (SELECT MAX(I.IMAGE_ID)
          FROM IMAGES I
          WHERE SM.STAFF_ID = I.IMAGE_OBJECT_ID
            AND I.IMAGE_OBJECT_TYPE = 'STAFF'
            AND I.ACTIVE_FLAG = 'Y') THUMBNAIL_ID
  FROM STAFF_MEMBERS SM
  WHERE SM.STAFF_ID = :staffId
}

FIND_STAFF_BY_AGENCY_AND_ROLE {
  SELECT SM.STAFF_ID,
         SM.FIRST_NAME,
         SM.LAST_NAME
  FROM STAFF_MEMBERS SM
  WHERE SM.STATUS = 'ACTIVE'
    AND SM.STAFF_ID IN
      (SELECT DISTINCT(SLR.SAC_STAFF_ID)
       FROM STAFF_LOCATION_ROLES SLR
       WHERE SLR.CAL_AGY_LOC_ID = :agencyId
         AND SLR.ROLE = :role
         AND TRUNC(SYSDATE) BETWEEN TRUNC(SLR.FROM_DATE) AND TRUNC(COALESCE(SLR.TO_DATE,SYSDATE))
         AND SLR.FROM_DATE = (SELECT MAX(SLR2.FROM_DATE)
                              FROM STAFF_LOCATION_ROLES SLR2
                              WHERE SLR2.SAC_STAFF_ID = SLR.SAC_STAFF_ID
                                AND SLR2.CAL_AGY_LOC_ID = SLR.CAL_AGY_LOC_ID
                                AND SLR2.ROLE = SLR.ROLE))
}

FIND_STAFF_BY_AGENCY_POSITION_ROLE {
  SELECT SM.LAST_NAME,
         SM.FIRST_NAME,
         SM.STAFF_ID
  FROM STAFF_LOCATION_ROLES SLR
    INNER JOIN STAFF_MEMBERS SM ON SM.STAFF_ID = SLR.SAC_STAFF_ID
      AND SM.STATUS = 'ACTIVE'
  WHERE SLR.CAL_AGY_LOC_ID = :agencyId
    AND SLR.POSITION = :position
    AND SLR.ROLE = :role
    AND TRUNC(SYSDATE) BETWEEN TRUNC(SLR.FROM_DATE) AND TRUNC(COALESCE(SLR.TO_DATE,SYSDATE))
    AND SLR.FROM_DATE = (SELECT MAX(SLR2.FROM_DATE)
                         FROM STAFF_LOCATION_ROLES SLR2
                         WHERE SLR2.SAC_STAFF_ID = SLR.SAC_STAFF_ID
                           AND SLR2.CAL_AGY_LOC_ID = SLR.CAL_AGY_LOC_ID
                           AND SLR2.POSITION = SLR.POSITION
                           AND SLR2.ROLE = SLR.ROLE)
}
