-- Offender Language and numeracy skills
CREATE TABLE LAA_GENERAL_USERS
(
    USERNAME VARCHAR2(30) NOT NULL
  , LOCAL_AUTHORITY_CODE VARCHAR2(6) NOT NULL
  , START_DATE DATE NOT NULL
  , ACTIVE_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
  , EXPIRY_DATE DATE
  , CREATE_DATETIME TIMESTAMP(9) DEFAULT systimestamp NOT NULL
  , CREATE_USER_ID VARCHAR2(32) DEFAULT USER NOT NULL
  , MODIFY_DATETIME TIMESTAMP(9)
  , MODIFY_USER_ID VARCHAR2(32)
  , AUDIT_TIMESTAMP TIMESTAMP(9)
  , AUDIT_USER_ID VARCHAR2(32)
  , AUDIT_MODULE_NAME VARCHAR2(65)
  , AUDIT_CLIENT_USER_ID VARCHAR2(64)
  , AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39)
  , AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64)
  , AUDIT_ADDITIONAL_INFO VARCHAR2(256),
CONSTRAINT LAA_GENERAL_USERS_PK PRIMARY KEY ( USERNAME, LOCAL_AUTHORITY_CODE )
);

ALTER TABLE LAA_GENERAL_USERS ADD CONSTRAINT LAA_GEN_STAFF_USER_F1 FOREIGN KEY(USERNAME) REFERENCES STAFF_USER_ACCOUNTS(USERNAME);
