CREATE TABLE "OFFENDER_KEY_DATE_ADJUSTS"
(
  "OFFENDER_KEY_DATE_ADJUST_ID"   NUMBER(10, 0)                     NOT NULL ,
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ,
  "SENTENCE_ADJUST_CODE"          VARCHAR2(12 CHAR)                 NOT NULL ,
  "ADJUST_FROM_DATE"              DATE,
  "ADJUST_TO_DATE"                DATE,
  "ADJUST_DAYS"                   NUMBER(6, 0),
  "ADJUST_STATUS"                 VARCHAR2(12 CHAR),
  "COMMENT_TEXT"                  VARCHAR2(240 CHAR),
  "ADJUST_DATE"                   DATE,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  "ACTIVE_FLAG"                   VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ,
  CONSTRAINT "OFFENDER_KEY_DATE_ADJUSTS_PK" PRIMARY KEY ("OFFENDER_KEY_DATE_ADJUST_ID"),
  CONSTRAINT "OFFENDER_KEY_DATE_ADJUSTS_FK9" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID")
);


COMMENT ON COLUMN "OFFENDER_KEY_DATE_ADJUSTS"."OFFENDER_BOOK_ID" IS 'The Related Offender Book Identifier';

COMMENT ON COLUMN "OFFENDER_KEY_DATE_ADJUSTS"."COMMENT_TEXT" IS 'Free text comment data';

COMMENT ON COLUMN "OFFENDER_KEY_DATE_ADJUSTS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_KEY_DATE_ADJUSTS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "OFFENDER_KEY_DATE_ADJUSTS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "OFFENDER_KEY_DATE_ADJUSTS"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "OFFENDER_KEY_DATE_ADJUSTS"."ACTIVE_FLAG" IS 'Active flag to store if the record is active or inactive.';


CREATE INDEX "OFFENDER_KEY_DATE_ADJUSTS_FK9"
  ON "OFFENDER_KEY_DATE_ADJUSTS" ("OFFENDER_BOOK_ID");


