CREATE TABLE "OFFENCES"
(
  "OFFENCE_CODE"                  VARCHAR2(25 CHAR)                 NOT NULL ,
  "STATUTE_CODE"                  VARCHAR2(12 CHAR)                 NOT NULL ,
  "DESCRIPTION"                   VARCHAR2(1000 CHAR)               NOT NULL ,
  "OLD_STATUTE_CODE"              VARCHAR2(12 CHAR),
  "SEVERITY_RANKING"              VARCHAR2(12 CHAR),
  "DEFAULT_OFFENCE_TYPE"          VARCHAR2(12 CHAR),
  "MAX_SENTENCE_LENGTH"           NUMBER(3, 0),
  "SENTENCE_UNIT_CODE"            VARCHAR2(12 CHAR),
  "OFFENCE_GROUP"                 VARCHAR2(12 CHAR),
  "UPDATE_ALLOWED_FLAG"           VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ,
  "REPEALED_DATE"                 DATE,
  "ACTIVE_FLAG"                   VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ,
  "LIST_SEQ"                      NUMBER(6, 0),
  "EXPIRY_DATE"                   DATE,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "CHECK_BOX1"                    VARCHAR2(1 CHAR) DEFAULT 'N',
  "CHECK_BOX2"                    VARCHAR2(1 CHAR) DEFAULT 'N',
  "CHECK_BOX3"                    VARCHAR2(1 CHAR) DEFAULT 'N',
  "OFFENSE_DEGREE"                VARCHAR2(12 CHAR),
  "MAX_GOOD_TIME_PERC"            NUMBER(3, 0),
  "CREATE_DATE"                   DATE DEFAULT SYSDATE              NOT NULL ,
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "HO_CODE"                       VARCHAR2(12 CHAR),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "OFFENCES_PK" PRIMARY KEY ("OFFENCE_CODE", "STATUTE_CODE"),
  CONSTRAINT "OFN_STT_F2" FOREIGN KEY ("OLD_STATUTE_CODE")
  REFERENCES "STATUTES" ("STATUTE_CODE") ,
  CONSTRAINT "OFN_STT_F1" FOREIGN KEY ("STATUTE_CODE")
  REFERENCES "STATUTES" ("STATUTE_CODE") ,
  CONSTRAINT "OFFEN_HO_CODES_FK" FOREIGN KEY ("HO_CODE")
  REFERENCES "HO_CODES" ("HO_CODE")
);


COMMENT ON COLUMN "OFFENCES"."OFFENCE_CODE" IS 'Reference Code ( OFFENCE )';
COMMENT ON COLUMN "OFFENCES"."STATUTE_CODE" IS ' - Column already exists';
COMMENT ON COLUMN "OFFENCES"."DESCRIPTION" IS ' - Column already exists';
COMMENT ON COLUMN "OFFENCES"."OLD_STATUTE_CODE" IS 'Previous Statue Code';
COMMENT ON COLUMN "OFFENCES"."SEVERITY_RANKING" IS 'The severity ranking of Offence';
COMMENT ON COLUMN "OFFENCES"."DEFAULT_OFFENCE_TYPE" IS 'The default offence type';
COMMENT ON COLUMN "OFFENCES"."MAX_SENTENCE_LENGTH" IS 'Maximum Sentence';
COMMENT ON COLUMN "OFFENCES"."SENTENCE_UNIT_CODE" IS 'Reference Code ( PERIOD_TYPE ) : Sentence unit of the max sentence';
COMMENT ON COLUMN "OFFENCES"."UPDATE_ALLOWED_FLAG" IS ' - Column already exists';
COMMENT ON COLUMN "OFFENCES"."REPEALED_DATE" IS ' - Column already exists';
COMMENT ON COLUMN "OFFENCES"."ACTIVE_FLAG" IS ' The flag derives whether Offence is active or not';
COMMENT ON COLUMN "OFFENCES"."LIST_SEQ" IS ' - Column already exists';
COMMENT ON COLUMN "OFFENCES"."EXPIRY_DATE" IS ' - Column already exists';
COMMENT ON COLUMN "OFFENCES"."CREATE_USER_ID" IS 'The user who creates the record';
COMMENT ON COLUMN "OFFENCES"."CREATE_DATE" IS 'The date when Offence gets Created';
COMMENT ON COLUMN "OFFENCES"."MODIFY_USER_ID" IS 'The user who modifies the record';
COMMENT ON COLUMN "OFFENCES"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';
COMMENT ON COLUMN "OFFENCES"."HO_CODE" IS ' This column stores the value of Home Office Class and Home Office sub class';
COMMENT ON COLUMN "OFFENCES"."CREATE_DATETIME" IS 'The timestamp when the record is created';
COMMENT ON TABLE "OFFENCES" IS '- Retrofitted';


CREATE INDEX "OFFEN_HO_CODES_FK"
  ON "OFFENCES" ("HO_CODE");


CREATE INDEX "OFN_STT_F1"
  ON "OFFENCES" ("STATUTE_CODE");


CREATE INDEX "OFN_STT_F2"
  ON "OFFENCES" ("OLD_STATUTE_CODE");


