CREATE TABLE "AGENCY_INTERNAL_LOCATIONS"
(
  "INTERNAL_LOCATION_ID"          NUMBER(10, 0)                     NOT NULL ,
  "INTERNAL_LOCATION_CODE"        VARCHAR2(12 CHAR)                 NOT NULL ,
  "AGY_LOC_ID"                    VARCHAR2(6 CHAR)                  NOT NULL ,
  "INTERNAL_LOCATION_TYPE"        VARCHAR2(12 CHAR)                 NOT NULL ,
  "DESCRIPTION"                   VARCHAR2(240 CHAR)                NOT NULL ,
  "SECURITY_LEVEL_CODE"           VARCHAR2(12 CHAR),
  "CAPACITY"                      NUMBER(5, 0),
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "PARENT_INTERNAL_LOCATION_ID"   NUMBER(10, 0),
  "ACTIVE_FLAG"                   VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ,
  "LIST_SEQ"                      NUMBER(6, 0),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "CNA_NO"                        NUMBER(10, 0),
  "CERTIFIED_FLAG"                VARCHAR2(1 CHAR) DEFAULT 'N'      NOT NULL ,
  "DEACTIVATE_DATE"               DATE,
  "REACTIVATE_DATE"               DATE,
  "DEACTIVATE_REASON_CODE"        VARCHAR2(12 CHAR),
  "COMMENT_TEXT"                  VARCHAR2(240 CHAR),
  "USER_DESC"                     VARCHAR2(40 CHAR),
  "ACA_CAP_RATING"                NUMBER(5, 0),
  "UNIT_TYPE"                     VARCHAR2(12 CHAR),
  "OPERATION_CAPACITY"            NUMBER(5, 0),
  "NO_OF_OCCUPANT"                NUMBER(10, 0) DEFAULT 0,
  "TRACKING_FLAG"                 VARCHAR2(1 CHAR) DEFAULT 'N'      NOT NULL ,
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "AGENCY_INTERNAL_LOCATIONS_UK" UNIQUE ("AGY_LOC_ID", "DESCRIPTION"),
  CONSTRAINT "INTERNAL_LOCATIONS_PK" PRIMARY KEY ("INTERNAL_LOCATION_ID"),
  CONSTRAINT "AGY_INC_LOC_AGY_INT_LOC_FK" FOREIGN KEY ("PARENT_INTERNAL_LOCATION_ID")
  REFERENCES "AGENCY_INTERNAL_LOCATIONS" ("INTERNAL_LOCATION_ID") ,
  CONSTRAINT "AGY_INT_LOC_AGY_LOC_FK" FOREIGN KEY ("AGY_LOC_ID")
  REFERENCES "AGENCY_LOCATIONS" ("AGY_LOC_ID")
);


CREATE INDEX "AGENCY_INTERNAL_LOCATIONS_NI3"
  ON "AGENCY_INTERNAL_LOCATIONS" ("AGY_LOC_ID");


CREATE INDEX "AGENCY_INTERNAL_LOCATIONS_X01"
  ON "AGENCY_INTERNAL_LOCATIONS" ("AGY_LOC_ID", "PARENT_INTERNAL_LOCATION_ID");


CREATE INDEX "INTERNAL_LOCATIONS_NI1"
  ON "AGENCY_INTERNAL_LOCATIONS" ("DESCRIPTION");


CREATE INDEX "INTERNAL_LOCATIONS_NI2"
  ON "AGENCY_INTERNAL_LOCATIONS" ("PARENT_INTERNAL_LOCATION_ID");



