CREATE TABLE "USER_ACCESSIBLE_CASELOADS"
(
  "CASELOAD_ID"                   VARCHAR2(6 CHAR)                  NOT NULL ,
  "USERNAME"                      VARCHAR2(30 CHAR)                 NOT NULL ,
  "START_DATE"                    DATE,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "USER_ACCESSIBLE_CASELOADS_PK" PRIMARY KEY ("CASELOAD_ID", "USERNAME"),
  CONSTRAINT "STAFF_USER_ACCESSIBLE_CLS_FK1" FOREIGN KEY ("USERNAME")
  REFERENCES "STAFF_USER_ACCOUNTS" ("USERNAME") ,
  CONSTRAINT "STAFF_USER_ACCESSIBLE_CLS_FK2" FOREIGN KEY ("CASELOAD_ID")
  REFERENCES "CASELOADS" ("CASELOAD_ID")
);


CREATE INDEX "USER_ACCESSIBLE_CLS_FK1"
  ON "USER_ACCESSIBLE_CASELOADS" ("USERNAME");


CREATE INDEX "USER_ACCESSIBLE_CLS_FK2"
  ON "USER_ACCESSIBLE_CASELOADS" ("CASELOAD_ID");

