CREATE TABLE "OFFENDER_RELEASE_DETAILS"
(
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ,
  "RELEASE_DATE"                  DATE,
  "COMMENT_TEXT"                  VARCHAR2(240 CHAR),
  "MOVEMENT_TYPE"                 VARCHAR2(12 CHAR)                 NOT NULL ,
  "MOVEMENT_REASON_CODE"          VARCHAR2(12 CHAR),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  "EVENT_ID"                      NUMBER(10, 0) DEFAULT NULL        NOT NULL ,
  "EVENT_STATUS"                  VARCHAR2(12 CHAR) DEFAULT 'SCH'   NOT NULL ,
  "APPROVED_RELEASE_DATE"         DATE,
  "AUTO_RELEASE_DATE"             DATE,
  "DTO_APPROVED_DATE"             DATE,
  "DTO_MID_TERM_DATE"             DATE,
  "VERIFIED_FLAG"                 VARCHAR2(1 CHAR) DEFAULT 'N',

  CONSTRAINT "OFFENDER_RELEASE_DETAILS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID"),

  CONSTRAINT "OFF_RELDE_OFF_BK_FK1" FOREIGN KEY ("OFFENDER_BOOK_ID") REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID") ,
  CONSTRAINT "OFF_RELDE_MOV_RSN_FK1" FOREIGN KEY ("MOVEMENT_TYPE", "MOVEMENT_REASON_CODE") REFERENCES "MOVEMENT_REASONS" ("MOVEMENT_TYPE", "MOVEMENT_REASON_CODE")
);


COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."OFFENDER_BOOK_ID" IS 'The Offender Book ID';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."RELEASE_DATE" IS 'The Actual Release date';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."COMMENT_TEXT" IS 'The general comment text';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."MOVEMENT_TYPE" IS 'The Movement Type.  Default ''REL''';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."MOVEMENT_REASON_CODE" IS 'The Movement reason. Reference Code(MOVE_RSN)';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."EVENT_ID" IS 'The Event ID';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."EVENT_STATUS" IS 'The event Status';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."APPROVED_RELEASE_DATE" IS 'The approved release date';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."AUTO_RELEASE_DATE" IS 'The auto release date';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."DTO_APPROVED_DATE" IS 'The Term approved date';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."DTO_MID_TERM_DATE" IS 'The mid-term date';

COMMENT ON COLUMN "OFFENDER_RELEASE_DETAILS"."VERIFIED_FLAG" IS '?If the release schedule verified';

COMMENT ON TABLE "OFFENDER_RELEASE_DETAILS" IS 'The release details of offenders';


CREATE INDEX "OFFENDER_RELEASE_DETAILS_NI1"
  ON "OFFENDER_RELEASE_DETAILS" ("RELEASE_DATE");


CREATE INDEX "OFFENDER_RELEASE_DETAILS_NI2"
  ON "OFFENDER_RELEASE_DETAILS" ("APPROVED_RELEASE_DATE");


CREATE INDEX "OFFENDER_RELEASE_DETAILS_NI3"
  ON "OFFENDER_RELEASE_DETAILS" ("AUTO_RELEASE_DATE");


CREATE INDEX "OFFENDER_RELEASE_DETAILS_NI4"
  ON "OFFENDER_RELEASE_DETAILS" ("DTO_APPROVED_DATE");


CREATE INDEX "OFFENDER_RELEASE_DETAILS_NI5"
  ON "OFFENDER_RELEASE_DETAILS" ("DTO_MID_TERM_DATE");


CREATE UNIQUE INDEX "OFFENDER_RELEASE_DETAILS_UK"
  ON "OFFENDER_RELEASE_DETAILS" ("EVENT_ID");


CREATE UNIQUE INDEX "OFFENDER_RELEASE_DETAILS_X01"
  ON "OFFENDER_RELEASE_DETAILS" ("OFFENDER_BOOK_ID", "RELEASE_DATE", "AUTO_RELEASE_DATE");


CREATE INDEX "OFF_RELDE_MOV_RSN_FK1"
  ON "OFFENDER_RELEASE_DETAILS" ("MOVEMENT_TYPE", "MOVEMENT_REASON_CODE", "RELEASE_DATE");

