CREATE TABLE "OFFENDER_IDENTIFIERS"
(
  "OFFENDER_ID"                   NUMBER(10, 0)                     NOT NULL ,
  "OFFENDER_ID_SEQ"               NUMBER(10, 0),
  "IDENTIFIER_TYPE"               VARCHAR2(12 CHAR)                 NOT NULL ,
  "IDENTIFIER"                    VARCHAR2(20 CHAR)                 NOT NULL ,
  "ISSUED_AUTHORITY_TEXT"         VARCHAR2(240 CHAR),
  "ISSUED_DATE"                   DATE,
  "ROOT_OFFENDER_ID"              NUMBER(10, 0),
  "CASELOAD_TYPE"                 VARCHAR2(12 CHAR),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "VERIFIED_FLAG"                 VARCHAR2(1 CHAR) DEFAULT 'N',
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "OFFENDER_NAME_IDENTIFIERS_PK" PRIMARY KEY ("OFFENDER_ID", "OFFENDER_ID_SEQ"),
  CONSTRAINT "OFFENDER_IDENTIFIERS_C1" CHECK ( verified_flag IN ('Y', 'N') ) ,
  CONSTRAINT "OFFENDER_IDENTIFIERS_UK1" UNIQUE ("ROOT_OFFENDER_ID", "IDENTIFIER_TYPE", "IDENTIFIER"),
  CONSTRAINT "OFF_ID_OFF_F1" FOREIGN KEY ("OFFENDER_ID") REFERENCES "OFFENDERS" ("OFFENDER_ID")
);


COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."OFFENDER_ID" IS 'Unique identifier for an offender.';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."OFFENDER_ID_SEQ" IS 'System generated number forming part of primary key.';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."IDENTIFIER_TYPE" IS 'Reference Code ( ID_TYPE ) :  Type of identifier to be associated with offender.';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."IDENTIFIER" IS 'The number associated with the type of identifier.';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."ISSUED_AUTHORITY_TEXT" IS ' The authority issuing the identification.';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."ISSUED_DATE" IS ' The date the identification was issued.';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."ROOT_OFFENDER_ID" IS 'The Root Offender Identifier';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."CASELOAD_TYPE" IS 'The Case Load Type';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_IDENTIFIERS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON TABLE "OFFENDER_IDENTIFIERS" IS 'The identifier of the offender name such as SIN card, Driving Licence';


CREATE INDEX "OFFENDER_IDENTIFIERS_IN2"
  ON "OFFENDER_IDENTIFIERS" ("ROOT_OFFENDER_ID");


CREATE INDEX "OFFENDER_IDENTIFIERS_NI1"
  ON "OFFENDER_IDENTIFIERS" ("IDENTIFIER", "IDENTIFIER_TYPE");


