CREATE TABLE "OFFENDER_PHYSICAL_ATTRIBUTES"
(
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ,
  "ATTRIBUTE_SEQ"                 NUMBER(6, 0)                      NOT NULL ,
  "HEIGHT_FT"                     NUMBER(6, 0),
  "HEIGHT_IN"                     NUMBER(6, 0),
  "HEIGHT_CM"                     NUMBER(6, 0),
  "WEIGHT_LBS"                    NUMBER(6, 0),
  "WEIGHT_KG"                     NUMBER(6, 0),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "OFFENDER_PHYSICAL_ATTRIBUTE_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "ATTRIBUTE_SEQ"),
  CONSTRAINT "OFF_PHYSICAL_ATTRIBUTES_FK9" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID")
);


COMMENT ON COLUMN "OFFENDER_PHYSICAL_ATTRIBUTES"."OFFENDER_BOOK_ID" IS 'The Related Offender Book Identifier';

COMMENT ON COLUMN "OFFENDER_PHYSICAL_ATTRIBUTES"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_PHYSICAL_ATTRIBUTES"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "OFFENDER_PHYSICAL_ATTRIBUTES"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "OFFENDER_PHYSICAL_ATTRIBUTES"."MODIFY_USER_ID" IS 'The user who modifies the record';

