CREATE TABLE "OFFENDER_EXTERNAL_MOVEMENTS" (
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ,
  "MOVEMENT_SEQ"                  NUMBER(6, 0) DEFAULT 99           NOT NULL ,
  "MOVEMENT_DATE"                 DATE                              NOT NULL ,
  "MOVEMENT_TIME"                 DATE                              NOT NULL ,
  "INTERNAL_SCHEDULE_TYPE"        VARCHAR2(12 CHAR),
  "INTERNAL_SCHEDULE_REASON_CODE" VARCHAR2(12 CHAR),
  "MOVEMENT_TYPE"                 VARCHAR2(12 CHAR),
  "MOVEMENT_REASON_CODE"          VARCHAR2(12 CHAR),
  "DIRECTION_CODE"                VARCHAR2(12 CHAR),
  "ARREST_AGENCY_LOC_ID"          VARCHAR2(6 CHAR),
  "TO_PROV_STAT_CODE"             VARCHAR2(6 CHAR),
  "ESCORT_CODE"                   VARCHAR2(12 CHAR),
  "FROM_AGY_LOC_ID"               VARCHAR2(6 CHAR),
  "TO_AGY_LOC_ID"                 VARCHAR2(6 CHAR),
  "ACTIVE_FLAG"                   VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ,
  "ESCORT_TEXT"                   VARCHAR2(240 CHAR),
  "COMMENT_TEXT"                  VARCHAR2(240 CHAR),
  "REPORTING_DATE"                DATE,
  "TO_CITY"                       VARCHAR2(12 CHAR),
  "FROM_CITY"                     VARCHAR2(12 CHAR),
  "REPORTING_TIME"                DATE,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "EVENT_ID"                      NUMBER(10, 0),
  "PARENT_EVENT_ID"               NUMBER(10, 0),
  "TO_COUNTRY_CODE"               VARCHAR2(12 CHAR),
  "OJ_LOCATION_CODE"              VARCHAR2(12 CHAR),
  "APPLICATION_DATE"              DATE,
  "APPLICATION_TIME"              DATE,
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  "TO_ADDRESS_ID"                 NUMBER(10, 0),
  "FROM_ADDRESS_ID"               NUMBER(10, 0),

  CONSTRAINT "OFFENDER_EXTERNAL_MOVEMENTS_UK" UNIQUE ("EVENT_ID"),

  CONSTRAINT "OFFENDER_EXTERNAL_MOVEMENTS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "MOVEMENT_SEQ"),

  CONSTRAINT "OFF_EXT_MOV_ADDR_FK"      FOREIGN KEY ("TO_ADDRESS_ID")                                           REFERENCES "ADDRESSES" ("ADDRESS_ID") ,
  CONSTRAINT "OFF_EM_OFF_BKG_F1"        FOREIGN KEY ("OFFENDER_BOOK_ID")                                        REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID") ,
  CONSTRAINT "OFF_EM_MOVE_RSN_F1"       FOREIGN KEY ("MOVEMENT_TYPE", "MOVEMENT_REASON_CODE")                   REFERENCES "MOVEMENT_REASONS" ("MOVEMENT_TYPE", "MOVEMENT_REASON_CODE") ,
  CONSTRAINT "OFF_EM_INT_SR_F1"         FOREIGN KEY ("INTERNAL_SCHEDULE_TYPE", "INTERNAL_SCHEDULE_REASON_CODE") REFERENCES "INTERNAL_SCHEDULE_REASONS" ("INTERNAL_SCHEDULE_TYPE", "INTERNAL_SCHEDULE_RSN_CODE") ,
  CONSTRAINT "OFF_EM_AGY_LOC_F3"        FOREIGN KEY ("TO_AGY_LOC_ID")                                           REFERENCES "AGENCY_LOCATIONS" ("AGY_LOC_ID") ,
  CONSTRAINT "OFF_EM_AGY_LOC_F2"        FOREIGN KEY ("FROM_AGY_LOC_ID")                                         REFERENCES "AGENCY_LOCATIONS" ("AGY_LOC_ID") ,
  CONSTRAINT "OFF_EXT_MOV_FROM_ADDR_FK" FOREIGN KEY ("FROM_ADDRESS_ID")                                         REFERENCES "ADDRESSES" ("ADDRESS_ID")
);


COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."OFFENDER_BOOK_ID" IS 'System generated unique identifer for an offender booking.';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."MOVEMENT_SEQ" IS 'The movement seq for the PK';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."MOVEMENT_DATE" IS 'Date of the external movement.';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."MOVEMENT_TIME" IS 'Movement time.';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."INTERNAL_SCHEDULE_TYPE" IS 'The type of internal schedule ie. Appointment, Parole Review..';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."INTERNAL_SCHEDULE_REASON_CODE" IS 'The reason for the internal schedule ie. OIC hearing, Medical..';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."MOVEMENT_TYPE" IS ' The type of movement.';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."MOVEMENT_REASON_CODE" IS 'Reason for movement.';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."DIRECTION_CODE" IS 'Reference Code (MOVE_DIRECT). Direction of movement In or Out.';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."ARREST_AGENCY_LOC_ID" IS ' The identifer for arresting agency noted on admission.';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."TO_PROV_STAT_CODE" IS 'Transfer to state relevant in a transfer outside jurisdiction.';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."ESCORT_CODE" IS 'Reference Code (ESCORT). Agency escorting offender to inst.';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."FROM_AGY_LOC_ID" IS 'The agency location offender is coming from on admission.';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."TO_AGY_LOC_ID" IS 'The destination of the movement (Agency Locations';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."ACTIVE_FLAG" IS '?If the movement is a active one';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."ESCORT_TEXT" IS 'The Escort details';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."COMMENT_TEXT" IS 'The general comment text';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."REPORTING_DATE" IS 'The date of the reporting';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."TO_CITY" IS 'The city of the destination';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."FROM_CITY" IS 'The city of the offender from';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."REPORTING_TIME" IS 'The time of the reporting';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."EVENT_ID" IS 'The reference ID of the events';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."PARENT_EVENT_ID" IS 'pointing to the previous movement for Temporary Absence';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."TO_COUNTRY_CODE" IS 'the country of the destination. REference Code(COUNTRY)';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."OJ_LOCATION_CODE" IS 'the OJ Location. REference Code(OJ_LOCATION)';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."APPLICATION_DATE" IS 'The date of the application';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."APPLICATION_TIME" IS 'The time of the application';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."TO_ADDRESS_ID" IS 'The address of the movement destination';

COMMENT ON COLUMN "OFFENDER_EXTERNAL_MOVEMENTS"."FROM_ADDRESS_ID" IS 'The address of the movement source';

COMMENT ON TABLE "OFFENDER_EXTERNAL_MOVEMENTS" IS 'An event scheduled to occur which will require a movement either into or out of an establishment. Subtype Identifying Attribute(s): - Event Class = EXT_MOV';


CREATE INDEX "OFFENDER_EXTERNAL_MOVEMENTS_N2"
  ON "OFFENDER_EXTERNAL_MOVEMENTS" ("TO_AGY_LOC_ID", "MOVEMENT_TYPE", "ACTIVE_FLAG");


CREATE INDEX "OFFENDER_EXTERNAL_MOVEMENTS_N4"
  ON "OFFENDER_EXTERNAL_MOVEMENTS" ("FROM_AGY_LOC_ID");


CREATE INDEX "OFFENDER_EXT_MOVEMENTS_NI5"
  ON "OFFENDER_EXTERNAL_MOVEMENTS" ("OFFENDER_BOOK_ID", "MOVEMENT_DATE", "MOVEMENT_TYPE", "MOVEMENT_SEQ");


CREATE INDEX "OFFENDER_EXT_MOVEMENTS_X01"
  ON "OFFENDER_EXTERNAL_MOVEMENTS" ("MOVEMENT_DATE", "OFFENDER_BOOK_ID");


CREATE INDEX "OFF_EM_INT_SR_F1"
  ON "OFFENDER_EXTERNAL_MOVEMENTS" ("INTERNAL_SCHEDULE_TYPE", "INTERNAL_SCHEDULE_REASON_CODE");


CREATE INDEX "OFF_EM_MOVE_RSN_F1"
  ON "OFFENDER_EXTERNAL_MOVEMENTS" ("MOVEMENT_TYPE", "MOVEMENT_REASON_CODE");


CREATE INDEX "OFF_EXT_MOV_ADDR_FK"
  ON "OFFENDER_EXTERNAL_MOVEMENTS" ("TO_ADDRESS_ID");


CREATE INDEX "OFF_EXT_MOV_FROM_ADDR_FK"
  ON "OFFENDER_EXTERNAL_MOVEMENTS" ("FROM_ADDRESS_ID");

