CREATE TABLE "OFFENDER_SENTENCE_ADJUSTS"
(
  "OFFENDER_SENTENCE_ADJUST_ID"   NUMBER(10, 0)                     NOT NULL ,
  "SENTENCE_ADJUST_CODE"          VARCHAR2(12 CHAR)                 NOT NULL ,
  "ADJUST_DATE"                   DATE,
  "ADJUST_DAYS"                   NUMBER(6, 0),
  "ADJUST_STATUS"                 VARCHAR2(12 CHAR),
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ,
  "SENTENCE_SEQ"                  NUMBER(6, 0)                      NOT NULL ,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "OFFENDER_KEY_DATE_ADJUST_ID"   NUMBER(10, 0),
  "ADJUST_FROM_DATE"              DATE,
  "ADJUST_TO_DATE"                DATE,
  "COMMENT_TEXT"                  VARCHAR2(240 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  "ACTIVE_FLAG"                   VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ,
  CONSTRAINT "OFFENDER_SENTENCE_ADJUSTS_PK" PRIMARY KEY ("OFFENDER_SENTENCE_ADJUST_ID"),
  CONSTRAINT "OFF_SENT_ADJ_OFF_KD_ADJ_FK" FOREIGN KEY ("OFFENDER_KEY_DATE_ADJUST_ID")
  REFERENCES "OFFENDER_KEY_DATE_ADJUSTS" ("OFFENDER_KEY_DATE_ADJUST_ID") ,
  CONSTRAINT "OFFENDER_SENTENCE_ADJUSTS_FK9" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID") ,
  CONSTRAINT "OFF_SENT_ADJ_OFF_SENT_FK" FOREIGN KEY ("OFFENDER_BOOK_ID", "SENTENCE_SEQ")
  REFERENCES "OFFENDER_SENTENCES" ("OFFENDER_BOOK_ID", "SENTENCE_SEQ")
);


COMMENT ON COLUMN "OFFENDER_SENTENCE_ADJUSTS"."ACTIVE_FLAG" IS 'Active flag to store if the record is active or inactive.';


CREATE INDEX "OFF_SENT_ADJ_OFF_KD_ADJ_FK"
  ON "OFFENDER_SENTENCE_ADJUSTS" ("OFFENDER_KEY_DATE_ADJUST_ID");


CREATE INDEX "OFF_SENT_ADJ_OFF_SENT_FK"
  ON "OFFENDER_SENTENCE_ADJUSTS" ("OFFENDER_BOOK_ID", "SENTENCE_SEQ");

