CREATE TABLE STAFF_LOCATION_ROLES -- A Staff Member holding an Agency Location specific role & position.
(   CAL_AGY_LOC_ID                VARCHAR2(6 CHAR)                        NOT NULL,
    SAC_STAFF_ID                  NUMBER(10)                              NOT NULL,
    FROM_DATE                     DATE                                    NOT NULL,
    TO_DATE                       DATE,
    POSITION                      VARCHAR2(12 CHAR)                       NOT NULL,
    ROLE                          VARCHAR2(12 CHAR)                       NOT NULL,
    SCHEDULE_TYPE                 VARCHAR2(12 CHAR),
    HOURS_PER_WEEK                NUMBER(4,2),
    SUPERVISOR_AGY_LOC_ID         VARCHAR2(6 CHAR),
    SUPERVISOR_STAFF_ID           NUMBER(10),
    SUPERVISOR_FROM_DATE          DATE,
    SUPERVISOR_POSITION           VARCHAR2(12 CHAR),
    SUPERVISOR_ROLE               VARCHAR2(12 CHAR),
    STAFF_UNIT                    VARCHAR2(12 CHAR),
    CREATE_DATETIME               TIMESTAMP(9)       DEFAULT systimestamp NOT NULL,
    CREATE_USER_ID                VARCHAR2(32 CHAR)  DEFAULT USER         NOT NULL,
    MODIFY_DATETIME               TIMESTAMP(9),
    MODIFY_USER_ID                VARCHAR2(32 CHAR),
    AUDIT_TIMESTAMP               TIMESTAMP(9),
    AUDIT_USER_ID                 VARCHAR2(32 CHAR),
    AUDIT_MODULE_NAME             VARCHAR2(65 CHAR),
    AUDIT_CLIENT_USER_ID          VARCHAR2(64 CHAR),
    AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39 CHAR),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64 CHAR),
    AUDIT_ADDITIONAL_INFO         VARCHAR2(256 CHAR),
    CONSTRAINT CHK_DATES CHECK (from_date <= nvl(to_date,from_date)),
    CONSTRAINT STAFF_LOCATION_ROLES_PK PRIMARY KEY (SAC_STAFF_ID, CAL_AGY_LOC_ID, FROM_DATE, POSITION, ROLE)
);

CREATE INDEX STAFF_LOCATION_ROLES_NI1 ON STAFF_LOCATION_ROLES (SAC_STAFF_ID);
CREATE INDEX STAFF_LOCATION_ROLES_NI2 ON STAFF_LOCATION_ROLES (CAL_AGY_LOC_ID, FROM_DATE, TO_DATE);
CREATE INDEX STAFF_LOCATION_ROLES_NI3 ON STAFF_LOCATION_ROLES (SUPERVISOR_STAFF_ID, SUPERVISOR_AGY_LOC_ID, SUPERVISOR_FROM_DATE, SUPERVISOR_POSITION, SUPERVISOR_ROLE);
