CREATE TABLE LIVING_UNITS_MV (
  AGY_LOC_ID                    VARCHAR2(6)                       NOT NULL,
  ROOT_LIVING_UNIT_ID           NUMBER,
  LIVING_UNIT_ID                NUMBER(10)                        NOT NULL,
  PARENT_LIVING_UNIT_ID         NUMBER(10),
  RESERVED_BEDS                 NUMBER,
  DESCRIPTION                   VARCHAR2(240)                     NOT NULL,
  TRACKING_FLAG                 VARCHAR2(1)                       NOT NULL,
  CREATE_DATETIME               TIMESTAMP(9) DEFAULT systimestamp NOT NULL,
  CREATE_USER_ID                VARCHAR2(32) DEFAULT USER         NOT NULL,
  MODIFY_DATETIME               TIMESTAMP(9),
  MODIFY_USER_ID                VARCHAR2(32),
  AUDIT_TIMESTAMP               TIMESTAMP(9),
  AUDIT_USER_ID                 VARCHAR2(32),
  AUDIT_MODULE_NAME             VARCHAR2(65),
  AUDIT_CLIENT_USER_ID          VARCHAR2(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR2(256)
);
-- Note not actually a PK as it can contain nulls!
CREATE UNIQUE INDEX LIVING_UNITS_MV_PK ON LIVING_UNITS_MV (PARENT_LIVING_UNIT_ID ASC, LIVING_UNIT_ID ASC, ROOT_LIVING_UNIT_ID ASC);
CREATE INDEX LIVING_UNITS_MV_I1 ON LIVING_UNITS_MV (AGY_LOC_ID ASC);
CREATE INDEX LIVING_UNITS_MV_I2 ON LIVING_UNITS_MV (ROOT_LIVING_UNIT_ID ASC);
CREATE INDEX LIVING_UNITS_MV_I3 ON LIVING_UNITS_MV (LIVING_UNIT_ID ASC);
