ALTER TABLE "OFFENDER_KEY_WORKERS" ADD "ALLOC_REASON"   VARCHAR2(12) DEFAULT 'MANUAL' NOT NULL;
ALTER TABLE "OFFENDER_KEY_WORKERS" ADD "ALLOC_TYPE"     VARCHAR2(1)  DEFAULT 'M'       NOT NULL;
ALTER TABLE "OFFENDER_KEY_WORKERS" ADD "DEALLOC_REASON" VARCHAR2(12);
ALTER TABLE "OFFENDER_KEY_WORKERS" ADD CONSTRAINT OFFENDER_KEY_WORKERS_C1 CHECK (ALLOC_TYPE IN ('A','M'));

COMMENT ON COLUMN "OFFENDER_KEY_WORKERS"."ALLOC_REASON" IS 'Reason for allocation';

COMMENT ON COLUMN "OFFENDER_KEY_WORKERS"."ALLOC_REASON" IS 'Reason for deallocation';

COMMENT ON COLUMN "OFFENDER_KEY_WORKERS"."ALLOC_TYPE" IS 'Type of allocation, M for manual, A for auto';


