ALTER TABLE STAFF_LOCATION_ROLES ADD TO_DATE_REASON_CODE VARCHAR2(12 CHAR);

--ALTER TABLE STAFF_LOCATION_ROLES ADD CONSTRAINT STAFF_LOCATION_ROLES_C1 CHECK (TO_DATE_REASON_CODE IN ('LONG_TERM', 'NO_CONTACT', ...?));

COMMENT ON COLUMN STAFF_LOCATION_ROLES.TO_DATE_REASON_CODE IS 'Reason for subsequent unavailability';
