#%RAML 1.0 DataType
type: SentenceDetail
description: Offender Sentence Detail Dto
properties:
  offenderNo:
    type: string
    description: Offender Unique Reference
  firstName:
    type: string
    description: First Name
  lastName:
    type: string
    description: Last Name
  dateOfBirth:
    type: date-only
    description: Offender date of birth.
  agencyLocationId:
    type: string
    description: Agency Id
  agencyLocationDesc:
    type: string
    description: Agency Description
  internalLocationDesc:
    type: string
    description: Description of the location within the prison
  facialImageId?:
    type: number
    (javaType): Long
    description: Identifier of facial image of offender.

