package uk.gov.justice.hmpps.prison.repository.sql

enum class AdjudicationsRepositorySql(val sql: String) {
  FIND_LATEST_ADJUDICATION_OFFENCE_TYPES_FOR_OFFENDER(
    """
        SELECT  OO.OIC_OFFENCE_ID   ID
        ,       OO.OIC_OFFENCE_CODE CODE
        ,       OO.DESCRIPTION      DESCRIPTION
                FROM (
                        SELECT DISTINCT AIC.CHARGED_OIC_OFFENCE_ID AS OFFENCE_IDS
                        FROM AGENCY_INCIDENTS AI
                                INNER JOIN AGENCY_INCIDENT_PARTIES AIP ON AIP.AGENCY_INCIDENT_ID = AI.AGENCY_INCIDENT_ID
                                INNER JOIN AGENCY_LOCATIONS AL ON AL.AGY_LOC_ID = AI.AGY_LOC_ID
                                INNER JOIN AGENCY_INCIDENT_CHARGES AIC ON AIC.AGENCY_INCIDENT_ID = AIP.AGENCY_INCIDENT_ID AND AIC.PARTY_SEQ = AIP.PARTY_SEQ
                                INNER JOIN OFFENDER_BOOKINGS OB ON OB.OFFENDER_BOOK_ID = AIP.OFFENDER_BOOK_ID
                                INNER JOIN OFFENDERS OFF ON OFF.OFFENDER_ID = OB.OFFENDER_ID
                        WHERE OFF.OFFENDER_ID_DISPLAY = :offenderNo
                              AND OB.BOOKING_SEQ = 1
                )
        INNER JOIN OIC_OFFENCES OO ON OO.OIC_OFFENCE_ID = OFFENCE_IDS
        ORDER BY DESCRIPTION
    """,
  ),

  FIND_LATEST_ADJUDICATION_AGENCIES_FOR_OFFENDER(
    """
        SELECT  AL.AGY_LOC_ID AGENCY_ID
        ,       AL.AGENCY_LOCATION_TYPE AGENCY_TYPE
        ,       AL.DESCRIPTION
        ,       CASE WHEN AL.ACTIVE_FLAG = 'Y' THEN 1 ELSE 0 END AS ACTIVE
        FROM (
                SELECT DISTINCT AI.AGY_LOC_ID AS AGENCY_LOCATION_ID
                FROM AGENCY_INCIDENTS AI
                        INNER JOIN AGENCY_INCIDENT_PARTIES AIP ON AIP.AGENCY_INCIDENT_ID = AI.AGENCY_INCIDENT_ID
                        INNER JOIN OFFENDER_BOOKINGS OB ON OB.OFFENDER_BOOK_ID = AIP.OFFENDER_BOOK_ID
                        INNER JOIN OFFENDERS OFF ON OFF.OFFENDER_ID = OB.OFFENDER_ID
                        WHERE OFF.OFFENDER_ID_DISPLAY = :offenderNo
                              AND OB.BOOKING_SEQ = 1
        )
        INNER JOIN AGENCY_LOCATIONS AL ON AL.AGY_LOC_ID = AGENCY_LOCATION_ID
        ORDER BY AL.LONG_DESCRIPTION
    """,
  ),

  FIND_LATEST_ADJUDICATIONS_FOR_OFFENDER(
    """
        SELECT  AIP.OIC_INCIDENT_ID   ADJUDICATION_NUMBER
        ,		AI.REPORT_TIME
        ,       AI.AGENCY_INCIDENT_ID
        ,       AL.AGY_LOC_ID         AGENCY_ID
        ,       AIC.OIC_CHARGE_ID
        ,		OO.DESCRIPTION        OFFENCE_DESCRIPTION
        ,       OO.OIC_OFFENCE_CODE   OFFENCE_CODE
        ,       AIP.PARTY_SEQ
        ,       OHR.FINDING_CODE
        ,       COALESCE(OH.HEARING_TIME,AI.REPORT_TIME) AS SORT_TIME
        FROM  AGENCY_INCIDENTS AI
              INNER JOIN AGENCY_INCIDENT_PARTIES AIP ON AIP.AGENCY_INCIDENT_ID = AI.AGENCY_INCIDENT_ID
              INNER JOIN AGENCY_LOCATIONS AL ON AL.AGY_LOC_ID = AI.AGY_LOC_ID
              INNER JOIN AGENCY_INCIDENT_CHARGES AIC  ON AIC.AGENCY_INCIDENT_ID = AIP.AGENCY_INCIDENT_ID AND AIC.PARTY_SEQ = AIP.PARTY_SEQ
              INNER JOIN OIC_OFFENCES OO ON OO.OIC_OFFENCE_ID = AIC.CHARGED_OIC_OFFENCE_ID
              INNER JOIN OFFENDER_BOOKINGS OB ON OB.OFFENDER_BOOK_ID = AIP.OFFENDER_BOOK_ID
              INNER JOIN OFFENDERS OFF ON OFF.OFFENDER_ID = OB.OFFENDER_ID
              LEFT JOIN OIC_HEARING_RESULTS OHR ON OHR.AGENCY_INCIDENT_ID = AIC.AGENCY_INCIDENT_ID AND OHR.CHARGE_SEQ = AIC.CHARGE_SEQ
              LEFT JOIN OIC_HEARINGS OH ON OH.OIC_INCIDENT_ID = AIP.OIC_INCIDENT_ID AND OH.OIC_HEARING_ID = OHR.OIC_HEARING_ID
        WHERE OFF.OFFENDER_ID_DISPLAY = :offenderNo
        AND OB.BOOKING_SEQ = 1
        AND (:findingCode IS NULL OR OHR.FINDING_CODE = :findingCode)
        AND (:agencyLocationId is NULL OR AL.AGY_LOC_ID = :agencyLocationId)
        AND (:offenceId IS NULL OR CHARGED_OIC_OFFENCE_ID = :offenceId)
        AND (:startDate IS NULL OR trunc(REPORT_TIME) >= :startDate)
        AND (:endDate IS NULL OR trunc(REPORT_TIME) <= :endDate)
        AND aip.oic_incident_id IS NOT NULL
        ORDER BY AI.REPORT_TIME DESC
    """,
  ),

  FIND_OFFENDER_HEARINGS(
    """
        SELECT al.AGY_LOC_ID AS AGENCY_ID
        ,      o.OFFENDER_ID_DISPLAY AS OFFENDER_NO
        ,      oh.OIC_HEARING_ID AS HEARING_ID
        ,      rc.DESCRIPTION AS HEARING_TYPE
        ,      oh.HEARING_TIME AS START_TIME
        ,      oh.INTERNAL_LOCATION_ID 
        ,      ail.DESCRIPTION AS INTERNAL_LOCATION_DESCRIPTION
        ,      oh.EVENT_STATUS
        FROM OIC_HEARINGS oh
        INNER JOIN AGENCY_INCIDENT_PARTIES aip ON aip.OIC_INCIDENT_ID = oh.OIC_INCIDENT_ID 
        INNER JOIN OFFENDER_BOOKINGS ob ON ob.OFFENDER_BOOK_ID = aip.OFFENDER_BOOK_ID
        INNER JOIN OFFENDERS o ON o.OFFENDER_ID = ob.OFFENDER_ID
        INNER JOIN AGENCY_LOCATIONS al ON al.AGY_LOC_ID = ob.AGY_LOC_ID AND al.AGY_LOC_ID = :agencyId 
        INNER JOIN AGENCY_INTERNAL_LOCATIONS ail ON ail.INTERNAL_LOCATION_ID = oh.INTERNAL_LOCATION_ID
        INNER JOIN REFERENCE_CODES rc ON rc."DOMAIN" = 'OIC_HEAR' AND rc.code = oh.OIC_HEARING_TYPE
        WHERE oh.HEARING_DATE BETWEEN :fromDate AND :toDate
        AND o.OFFENDER_ID_DISPLAY IN (:offenderNos)
    """,
  ),
}
