package uk.gov.justice.hmpps.prison.repository.sql

enum class IdentifyingMarksRepositorySql(val sql: String) {
  FIND_IDENTIFYING_MARKS_FOR_LATEST_BOOKING(
    """
        SELECT OIM.ID_MARK_SEQ,
        O.OFFENDER_ID_DISPLAY,
        OB.OFFENDER_BOOK_ID,
        OIM.BODY_PART_CODE,
        OIM.MARK_TYPE,
        OIM.SIDE_CODE,
        OIM.PART_ORIENTATION_CODE,
        OIM.COMMENT_TEXT,
        OIM.CREATE_DATETIME,
        OIM.CREATE_USER_ID
        FROM OFFENDERS O
        INNER JOIN OFFENDER_BOOKINGS OB ON O.OFFENDER_ID = OB.OFFENDER_ID
        INNER JOIN OFFENDER_IDENTIFYING_MARKS OIM ON OB.OFFENDER_BOOK_ID = OIM.OFFENDER_BOOK_ID
        LEFT JOIN OFFENDER_IMAGES OI ON OIM.OFFENDER_BOOK_ID = OI.OFFENDER_BOOK_ID AND OIM.ID_MARK_SEQ = OI.IMAGE_OBJECT_ID
        WHERE O.OFFENDER_ID_DISPLAY = :offenderId AND OB.BOOKING_SEQ = 1 AND (OI.ACTIVE_FLAG = 'Y' OR OI.ACTIVE_FLAG IS NULL)
        ORDER BY OIM.ID_MARK_SEQ
    """,
  ),

//  FIND_IDENTIFYING_MARKS_FOR_LATEST_BOOKING(
//    """
//        SELECT OIM.ID_MARK_SEQ,
//        O.OFFENDER_ID_DISPLAY,
//        OB.OFFENDER_BOOK_ID,
//        OIM.BODY_PART_CODE,
//        OIM.MARK_TYPE,
//        OIM.SIDE_CODE,
//        OIM.PART_ORIENTATION_CODE,
//        OIM.COMMENT_TEXT,
//        OIM.CREATE_DATETIME,
//        OIM.CREATE_USER_ID
//        FROM OFFENDERS O
//        INNER JOIN OFFENDER_BOOKINGS OB ON O.OFFENDER_ID = OB.OFFENDER_ID
//        INNER JOIN OFFENDER_IDENTIFYING_MARKS OIM ON OB.OFFENDER_BOOK_ID = OIM.OFFENDER_BOOK_ID
//        WHERE O.OFFENDER_ID_DISPLAY = :offenderId AND OB.BOOKING_SEQ = 1
//        ORDER BY OIM.ID_MARK_SEQ
//    """,
//  ),

  FIND_IMAGE_IDS_FOR_IDENTIFYING_MARK(
    """
        SELECT OI.OFFENDER_IMAGE_ID
        FROM OFFENDER_IMAGES OI
        WHERE OI.OFFENDER_BOOK_ID = :bookingId AND OI.ACTIVE_FLAG = 'Y' AND OI.IMAGE_OBJECT_ID = :markSeqId
        ORDER BY OI.OFFENDER_IMAGE_ID
    """,
  )
}
