package uk.gov.justice.hmpps.prison.repository.sql

enum class UserRepositorySql(val sql: String) {
  FIND_ROLE_PASSWORD(
    """
        SELECT PROFILE_VALUE ROLE_PWD
        FROM %sSYSTEM_PROFILES
        WHERE PROFILE_TYPE = 'SYS' AND PROFILE_CODE = 'ROLE_PSWD'
    """,
  ),

  FIND_USER_BY_USERNAME(
    """
        SELECT SM.STAFF_ID,
        AUA.USERNAME,
        SM.FIRST_NAME,
        SM.LAST_NAME,
        AUA.WORKING_CASELOAD_ID AS ACTIVE_CASE_LOAD_ID,
        SM.STATUS ACCOUNT_STATUS,
        (   SELECT TAG_IMAGE_ID
                FROM TAG_IMAGES
                WHERE IMAGE_OBJECT_ID = SM.STAFF_ID
                AND IMAGE_OBJECT_TYPE = 'STAFF'
        AND ACTIVE_FLAG = 'Y'
        ) THUMBNAIL_ID
        FROM STAFF_MEMBERS SM JOIN STAFF_USER_ACCOUNTS AUA ON SM.STAFF_ID = AUA.STAFF_ID
                AND AUA.USERNAME = :username
    """,
  ),

  FIND_USERS_BY_USERNAMES(
    """
        SELECT SM.STAFF_ID,
        AUA.USERNAME,
        SM.FIRST_NAME,
        SM.LAST_NAME,
        AUA.WORKING_CASELOAD_ID AS ACTIVE_CASE_LOAD_ID,
        SM.STATUS ACCOUNT_STATUS,
        (   SELECT TAG_IMAGE_ID
                FROM TAG_IMAGES
                WHERE IMAGE_OBJECT_ID = SM.STAFF_ID
                AND IMAGE_OBJECT_TYPE = 'STAFF'
        AND ACTIVE_FLAG = 'Y'
        ) THUMBNAIL_ID
        FROM STAFF_MEMBERS SM JOIN STAFF_USER_ACCOUNTS AUA ON SM.STAFF_ID = AUA.STAFF_ID
                AND AUA.USERNAME IN (:usernames)
    """,
  ),

  UPDATE_STAFF_ACTIVE_CASE_LOAD(
    """
        UPDATE STAFF_USER_ACCOUNTS
                SET WORKING_CASELOAD_ID = :caseLoadId
        WHERE USERNAME = :username
    """,
  ),

  FIND_USER_BY_STAFF_ID_STAFF_USER_TYPE(
    """
        SELECT SM.STAFF_ID,
        AUA.USERNAME,
        SM.FIRST_NAME,
        SM.LAST_NAME,
        AUA.WORKING_CASELOAD_ID AS ACTIVE_CASE_LOAD_ID,
        SM.STATUS ACCOUNT_STATUS,
        (SELECT TAG_IMAGE_ID
                FROM TAG_IMAGES
                WHERE IMAGE_OBJECT_ID = SM.STAFF_ID
                AND IMAGE_OBJECT_TYPE = 'STAFF'
        AND ACTIVE_FLAG = 'Y') THUMBNAIL_ID
        FROM STAFF_MEMBERS SM
        INNER JOIN STAFF_USER_ACCOUNTS AUA ON SM.STAFF_ID = AUA.STAFF_ID
                AND AUA.STAFF_ID = :staffId
        AND AUA.STAFF_USER_TYPE = :staffUserType
    """,
  ),

  FIND_ACTIVE_STAFF_USERS_WITH_ACCESSIBLE_CASELOAD(
    """
        SELECT SM.STAFF_ID,
        SUA.USERNAME,
        SM.FIRST_NAME,
        SM.LAST_NAME,
        SUA.WORKING_CASELOAD_ID AS ACTIVE_CASE_LOAD_ID,
        SM.STATUS ACCOUNT_STATUS
                FROM USER_ACCESSIBLE_CASELOADS UAC
        INNER JOIN STAFF_USER_ACCOUNTS SUA ON SUA.USERNAME = UAC.USERNAME
                INNER JOIN STAFF_MEMBERS SM ON SUA.STAFF_ID = SM.STAFF_ID
                WHERE UAC.CASELOAD_ID = :caseloadId
        AND SM.STATUS = 'ACTIVE'
        AND NOT EXISTS (SELECT 1 FROM USER_ACCESSIBLE_CASELOADS UAC2
                WHERE UAC2.USERNAME = SUA.USERNAME
                AND UAC2.CASELOAD_ID = :missingCaseloadId)
    """,
  ),

  FIND_USERS_BY_CASELOAD(
    """
        SELECT SM.STAFF_ID,
        SUA.USERNAME,
        SM.FIRST_NAME,
        SM.LAST_NAME,
        SM.STATUS ACCOUNT_STATUS,
        SUA.WORKING_CASELOAD_ID ACTIVE_CASE_LOAD_ID
                FROM STAFF_USER_ACCOUNTS SUA
        INNER JOIN STAFF_MEMBERS SM ON SUA.STAFF_ID = SM.STAFF_ID
                INNER JOIN USER_ACCESSIBLE_CASELOADS UAC ON SUA.USERNAME = UAC.USERNAME
                WHERE UAC.CASELOAD_ID = :caseloadId
                  AND (:status = 'ALL' or SM.STATUS = :status)
                  AND (:activeCaseloadId is null or SUA.WORKING_CASELOAD_ID = :activeCaseloadId)
    """,
  ),

  NAME_FILTER_QUERY_TEMPLATE(" AND (FIRST_NAME LIKE :searchTerm OR LAST_NAME LIKE :searchTerm OR SUA.USERNAME LIKE :searchTerm)"),

  FULL_NAME_FILTER_QUERY_TEMPLATE(" AND ((FIRST_NAME LIKE :firstName AND LAST_NAME LIKE :surname) OR (LAST_NAME LIKE :firstName AND FIRST_NAME LIKE :surname))"),

  APPLICATION_ROLE_CODE_FILTER_QUERY_TEMPLATE(
    """ 
        AND SUA.username in  (select SUA_INNER.USERNAME FROM STAFF_USER_ACCOUNTS SUA_INNER
                    INNER JOIN USER_ACCESSIBLE_CASELOADS UAC ON SUA_INNER.USERNAME = UAC.USERNAME
                    INNER JOIN User_caseload_roles UCR ON UCR.USERNAME = SUA_INNER.username and UCR.CASELOAD_ID = UAC.CASELOAD_ID
                    INNER JOIN OMS_ROLES RL ON RL.ROLE_ID = UCR.ROLE_ID
      WHERE UAC.CASELOAD_ID = :apiCaseloadId
      AND RL.ROLE_TYPE =  :applicationType
      AND RL.ROLE_CODE = :roleCode_%d )
    """,
  ),
}
