--------------------------------
-- OFFENDER_SENT_CALCULATIONS --
--------------------------------

-- Update record to include ROTL (not present in Elite Core schema).
UPDATE OFFENDER_SENT_CALCULATIONS SET ROTL_OVERRIDED_DATE = '2018-02-25' WHERE OFFENDER_SENT_CALCULATION_ID = -2;

-- Update record to include ERSED (not present in Elite Core schema).
UPDATE OFFENDER_SENT_CALCULATIONS SET ERSED_OVERRIDED_DATE = '2019-09-01' WHERE OFFENDER_SENT_CALCULATION_ID = -5;

-- Update record to include TUSED (not present in Elite Core schema).
UPDATE OFFENDER_SENT_CALCULATIONS SET TUSED_CALCULATED_DATE = '2021-03-30' WHERE OFFENDER_SENT_CALCULATION_ID = -7;
UPDATE OFFENDER_SENT_CALCULATIONS SET TUSED_CALCULATED_DATE = '2021-03-30', TUSED_OVERRIDED_DATE = '2021-03-31' WHERE OFFENDER_SENT_CALCULATION_ID = -8;

-- Update record to include sentence length (not present in Elite Core schema).
UPDATE OFFENDER_SENT_CALCULATIONS SET EFFECTIVE_SENTENCE_LENGTH = '6 months' WHERE OFFENDER_SENT_CALCULATION_ID = -1;