INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-1, now(),  'A00111', -1, 'N', 'IN', 'Y', 'N', 'LEI', 1, -1, -3);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-2, now(),  'A00112', -2, 'N', 'IN', 'Y', 'N', 'LEI', 1, -2, -19);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-3, now(),  'A00113', -3, 'N', 'IN', 'Y', 'N', 'LEI', 1, -3, -1);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-4, now(),  'A00114', -4, 'N', 'IN', 'Y', 'N', 'LEI', 1, -4, -2);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-5, now(),  'A00115', -5, 'N', 'IN', 'Y', 'N', 'LEI', 1, -5, -12);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-6, now(),  'A00116', -6, 'N', 'IN', 'Y', 'N', 'LEI', 1, -6, -4);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-7, now(),  'A00117', -7, 'N', 'IN', 'Y', 'N', 'LEI', 1, -7, -5);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-8, now(),  'A00118', -8, 'N', 'IN', 'Y', 'N', 'LEI', 1, -8, -6);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-9, now(),  'A00119', -9, 'N', 'IN', 'Y', 'N', 'LEI', 1, -9, -7);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-10, now(),  'A00120', -10, 'N', 'IN', 'Y', 'N', 'LEI', 1, -10, -8);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-11, now(),  'A00121', -11, 'N', 'IN', 'Y', 'N', 'LEI', 1, -11, -9);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-12, now(),  'A00122', -12, 'N', 'IN', 'Y', 'N', 'LEI', 1, -12, -10);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-13, now(),  'A00123', -13, 'N', 'IN', 'Y', 'N', 'LEI', 1, -12, -11);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-14, now(),  'A00124', -14, 'N', 'IN', 'Y', 'N', 'LEI', 1, -9, -13);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-15, now(),  'A00125', -15, 'N', 'IN', 'Y', 'N', 'LEI', 1, -9, -14);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID)
VALUES (-16, now(),  'A00126', -16, 'N', 'IN', 'Y', 'N', 'MUL', 1, -16, -15);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ, ROOT_OFFENDER_ID, LIVING_UNIT_ID, BOOKING_STATUS)
    VALUES  (-17, now(), 'Z00017', -17, 'N', 'IN',  'Y', 'N', 'LEI', 1, -9, -14, 'O'),
            (-18, now(), 'Z00018', -18, 'N', 'IN',  'Y', 'N', 'LEI', 1, -9, -14, 'O'),
            (-19, now(), 'Z00019', -19, 'N', 'IN',  'N', 'N', 'LEI', 1, -9, -14, 'O'),
            (-20, now(), 'Z00020', -20, 'N', 'OUT', 'N', 'N', 'LEI', 1, -9, -14, 'O'),
            (-21, now(), 'Z00021', -21, 'N', 'OUT', 'N', 'N', 'LEI', 1, -9, -14, 'O'),
            (-22, now(), 'Z00022', -22, 'N', 'OUT', 'N', 'N', 'LEI', 1, -9, -14, 'O'),
            (-23, now(), 'Z00023', -23, 'N', 'OUT', 'N', 'N', 'LEI', 1, -9, -14, 'O'),
            (-24, now(), 'Z00024', -24, 'N', 'IN',  'Y', 'N', 'LEI', 1, -9, -14, 'O'),
            (-25, now(), 'Z00025', -25, 'N', 'IN',  'Y', 'N', 'LEI', 1, -9, -14, 'O'),
            (-26, now(), 'Z00026', -26, 'N', 'IN',  'Y', 'N', 'ZZGHI', 1, -9, -30, 'O');
