CREATE TABLE OFFENDER_BOOKINGS
(
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                          NOT NULL,
  "BOOKING_BEGIN_DATE"            DATE                                   NOT NULL,
  "BOOKING_END_DATE"              DATE,
  "BOOKING_NO"                    VARCHAR2(14 CHAR),
  "OFFENDER_ID"                   NUMBER(10, 0)                          NOT NULL,
  "AGY_LOC_ID"                    VARCHAR2(6 CHAR),
  "LIVING_UNIT_ID"                NUMBER(10, 0),
  "DISCLOSURE_FLAG"               VARCHAR2(1 CHAR)  DEFAULT 'Y'          NOT NULL,
  "IN_OUT_STATUS"                 VARCHAR2(12 CHAR)                      NOT NULL,
  "ACTIVE_FLAG"                   VARCHAR2(1 CHAR)  DEFAULT 'N',
  "BOOKING_STATUS"                VARCHAR2(12 CHAR),
  "YOUTH_ADULT_CODE"              VARCHAR2(12 CHAR)                      NOT NULL,
  "FINGER_PRINTED_STAFF_ID"       NUMBER(6, 0),
  "SEARCH_STAFF_ID"               NUMBER(6, 0),
  "PHOTO_TAKING_STAFF_ID"         NUMBER(6, 0),
  "ASSIGNED_STAFF_ID"             NUMBER(6, 0),
  "CREATE_AGY_LOC_ID"             VARCHAR2(6 CHAR),
  "BOOKING_TYPE"                  VARCHAR2(12 CHAR),
  "BOOKING_CREATED_DATE"          DATE,
  "ROOT_OFFENDER_ID"              NUMBER(10, 0),
  "AGENCY_IML_ID"                 NUMBER(10, 0),
  "SERVICE_FEE_FLAG"              VARCHAR2(1 CHAR)  DEFAULT 'N',
  "EARNED_CREDIT_LEVEL"           VARCHAR2(12 CHAR),
  "EKSTRAND_CREDIT_LEVEL"         VARCHAR2(12 CHAR),
  "INTAKE_AGY_LOC_ID"             VARCHAR2(6 CHAR),
  "ACTIVITY_DATE"                 DATE,
  "INTAKE_CASELOAD_ID"            VARCHAR2(6 CHAR),
  "INTAKE_USER_ID"                VARCHAR2(32 CHAR),
  "CASE_OFFICER_ID"               NUMBER(6, 0),
  "CASE_DATE"                     DATE,
  "CASE_TIME"                     DATE,
  "COMMUNITY_ACTIVE_FLAG"         VARCHAR2(1 CHAR)  DEFAULT 'N',
  "CREATE_INTAKE_AGY_LOC_ID"      VARCHAR2(6 CHAR),
  "COMM_STAFF_ID"                 NUMBER(6, 0),
  "COMM_STATUS"                   VARCHAR2(12 CHAR),
  "COMMUNITY_AGY_LOC_ID"          VARCHAR2(6 CHAR),
  "NO_COMM_AGY_LOC_ID"            NUMBER(6, 0),
  "COMM_STAFF_ROLE"               VARCHAR2(12 CHAR),
  "AGY_LOC_ID_LIST"               VARCHAR2(80 CHAR),
  "STATUS_REASON"                 VARCHAR2(32 CHAR),
  "TOTAL_UNEXCUSED_ABSENCES"      NUMBER(6, 0),
  "REQUEST_NAME"                  VARCHAR2(240 CHAR),
  "RECORD_USER_ID"                VARCHAR2(30 CHAR),
  "INTAKE_AGY_LOC_ASSIGN_DATE"    DATE,
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp NOT NULL,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER         NOT NULL,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "SEAL_FLAG"                     VARCHAR2(1 CHAR)
);

CREATE UNIQUE INDEX "OFFENDER_BOOKINGS_PK" ON "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID");

ALTER TABLE OFFENDER_BOOKINGS
  ADD CONSTRAINT OFFENDER_BOOKINGS_PK PRIMARY KEY (OFFENDER_BOOK_ID);

ALTER TABLE OFFENDER_BOOKINGS
  ADD CONSTRAINT "OFF_BKG_OFF_F1"     FOREIGN KEY (OFFENDER_ID) REFERENCES OFFENDERS (OFFENDER_ID);

ALTER TABLE OFFENDER_BOOKINGS
  ADD CONSTRAINT "OFF_BKG_AGY_LOC_F1" FOREIGN KEY (AGY_LOC_ID)  REFERENCES AGENCY_LOCATIONS(AGY_LOC_ID);

ALTER TABLE OFFENDER_BOOKINGS
  ADD CONSTRAINT OFF_BKG_AGY_INT_LOC_FK FOREIGN KEY (LIVING_UNIT_ID) REFERENCES AGENCY_INTERNAL_LOCATIONS(INTERNAL_LOCATION_ID);
