CREATE TABLE OFFENDERS
(
  "OFFENDER_ID"                   NUMBER(10, 0),
  "OFFENDER_NAME_SEQ"             NUMBER(12, 0),
  "ID_SOURCE_CODE"                VARCHAR2(12 CHAR),
  "LAST_NAME"                     VARCHAR2(35 CHAR),
  "NAME_TYPE"                     VARCHAR2(12 CHAR),
  "FIRST_NAME"                    VARCHAR2(35 CHAR),
  "MIDDLE_NAME"                   VARCHAR2(35 CHAR),
  "BIRTH_DATE"                    DATE,
  "SEX_CODE"                      VARCHAR2(12 CHAR),
  "SUFFIX"                        VARCHAR2(12 CHAR),
  "LAST_NAME_SOUNDEX"             VARCHAR2(6 CHAR),
  "BIRTH_PLACE"                   VARCHAR2(25 CHAR),
  "BIRTH_COUNTRY_CODE"            VARCHAR2(12 CHAR),
  "CREATE_DATE"                   DATE,
  "LAST_NAME_KEY"                 VARCHAR2(35 CHAR),
  "ALIAS_OFFENDER_ID"             NUMBER(10, 0),
  "FIRST_NAME_KEY"                VARCHAR2(35 CHAR),
  "MIDDLE_NAME_KEY"               VARCHAR2(35 CHAR),
  "OFFENDER_ID_DISPLAY"           VARCHAR2(10 CHAR),
  "ROOT_OFFENDER_ID"              NUMBER(10, 0),
  "CASELOAD_TYPE"                 VARCHAR2(12 CHAR),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "ALIAS_NAME_TYPE"               VARCHAR2(12 CHAR),
  "PARENT_OFFENDER_ID"            NUMBER(10, 0),
  "UNIQUE_OBLIGATION_FLAG"        VARCHAR2(1 CHAR)  DEFAULT NULL,
  "SUSPENDED_FLAG"                VARCHAR2(1 CHAR)  DEFAULT NULL,
  "SUSPENDED_DATE"                DATE,
  "RACE_CODE"                     VARCHAR2(12 CHAR),
  "REMARK_CODE"                   VARCHAR2(12 CHAR),
  "ADD_INFO_CODE"                 VARCHAR2(12 CHAR),
  "BIRTH_COUNTY"                  VARCHAR2(20 CHAR),
  "BIRTH_STATE"                   VARCHAR2(20 CHAR),
  "MIDDLE_NAME_2"                 VARCHAR2(35 CHAR),
  "TITLE"                         VARCHAR2(12 CHAR),
  "AGE"                           NUMBER(3, 0),
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "LAST_NAME_ALPHA_KEY"           VARCHAR2(1 CHAR)  DEFAULT NULL,
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "NAME_SEQUENCE"                 VARCHAR2(12 CHAR),
  "SEAL_FLAG"                     VARCHAR2(1 CHAR)
);

CREATE UNIQUE INDEX "OFFENDERS_PK" ON "OFFENDERS" ("OFFENDER_ID");

ALTER TABLE "OFFENDERS" ALTER "OFFENDER_ID" SET NOT NULL;
ALTER TABLE "OFFENDERS" ALTER "ID_SOURCE_CODE" SET NOT NULL;
ALTER TABLE "OFFENDERS" ALTER "LAST_NAME" SET NOT NULL;
ALTER TABLE "OFFENDERS" ALTER "SEX_CODE" SET NOT NULL;
ALTER TABLE "OFFENDERS" ALTER "CREATE_DATE" SET NOT NULL;
ALTER TABLE "OFFENDERS" ALTER "LAST_NAME_KEY" SET NOT NULL;
ALTER TABLE "OFFENDERS" ALTER "CREATE_DATETIME" SET NOT NULL;
ALTER TABLE "OFFENDERS" ALTER "CREATE_USER_ID" SET NOT NULL;

