CREATE TABLE OFFENDER_PHYSICAL_ATTRIBUTES
(
  OFFENDER_BOOK_ID NUMBER(10)                         NOT NULL,
  ATTRIBUTE_SEQ    NUMBER(6)                          NOT NULL,
  HEIGHT_FT        NUMBER(6),
  HEIGHT_IN        NUMBER(6),
  HEIGHT_CM        NUMBER(6),
  WEIGHT_LBS       NUMBER(6),
  WEIGHT_KG        NUMBER(6),
  CREATE_DATETIME  TIMESTAMP(9) DEFAULT SYSTIMESTAMP  NOT NULL,
  CREATE_USER_ID   VARCHAR2(32) DEFAULT user          NOT NULL,
  MODIFY_DATETIME  TIMESTAMP(9) DEFAULT SYSTIMESTAMP,
  MODIFY_USER_ID   VARCHAR2(32),
  SEAL_FLAG        VARCHAR2(1),
  CONSTRAINT OFFENDER_PHYSICAL_ATTRIBUTE_PK
  PRIMARY KEY (OFFENDER_BOOK_ID, ATTRIBUTE_SEQ)
);