CREATE TABLE AGENCY_LOCATIONS
(
  "AGY_LOC_ID"                    VARCHAR2(6 CHAR),
  "DESCRIPTION"                   VARCHAR2(40 CHAR),
  "AGENCY_LOCATION_TYPE"          VARCHAR2(12 CHAR),
  "DISTRICT_CODE"                 VARCHAR2(12 CHAR),
  "ABBREVIATION"                  VARCHAR2(12 CHAR),
  "DEACTIVATION_DATE"             DATE,
  "CONTACT_NAME"                  VARCHAR2(40 CHAR),
  "PRINT_QUEUE"                   VARCHAR2(240 CHAR),
  "JURISDICTION_CODE"             VARCHAR2(12 CHAR),
  "BAIL_OFFICE_FLAG"              VARCHAR2(1 CHAR)  DEFAULT 'Y',
  "LIST_SEQ"                      NUMBER(6, 0),
  "HOUSING_LEV_1_CODE"            VARCHAR2(12 CHAR),
  "HOUSING_LEV_2_CODE"            VARCHAR2(12 CHAR),
  "HOUSING_LEV_3_CODE"            VARCHAR2(12 CHAR),
  "HOUSING_LEV_4_CODE"            VARCHAR2(12 CHAR),
  "PROPERTY_LEV_1_CODE"           VARCHAR2(12 CHAR),
  "PROPERTY_LEV_2_CODE"           VARCHAR2(12 CHAR),
  "PROPERTY_LEV_3_CODE"           VARCHAR2(12 CHAR),
  "LAST_BOOKING_NO"               NUMBER(10, 0),
  "COMMISSARY_PRIVILEGE"          VARCHAR2(12 CHAR),
  "BUSINESS_HOURS"                VARCHAR2(40 CHAR),
  "ADDRESS_TYPE"                  VARCHAR2(12 CHAR),
  "ACTIVE_FLAG"                   VARCHAR2(1 CHAR)  DEFAULT NULL,
  "DISABILITY_ACCESS_CODE"        VARCHAR2(12 CHAR),
  "INTAKE_FLAG"                   VARCHAR2(1 CHAR)  DEFAULT NULL,
  "SUB_AREA_CODE"                 VARCHAR2(12 CHAR),
  "AREA_CODE"                     VARCHAR2(12 CHAR),
  "NOMS_REGION_CODE"              VARCHAR2(12 CHAR),
  "GEOGRAPHIC_REGION_CODE"        VARCHAR2(12 CHAR),
  "JUSTICE_AREA_CODE"             VARCHAR2(12 CHAR),
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "LONG_DESCRIPTION"              VARCHAR2(3000 CHAR),
  "LABCORP_CLIENT_ID"             VARCHAR2(50 CHAR),
  "SEAL_FLAG"                     VARCHAR2(1 CHAR)
);

ALTER TABLE "AGENCY_LOCATIONS" ALTER "AGY_LOC_ID" SET NOT NULL;

ALTER TABLE AGENCY_LOCATIONS
  ADD CONSTRAINT AGENCY_LOCATIONS_PK PRIMARY KEY(AGY_LOC_ID);

ALTER TABLE "AGENCY_LOCATIONS" ALTER "DESCRIPTION" SET NOT NULL;

ALTER TABLE "AGENCY_LOCATIONS" ALTER "BAIL_OFFICE_FLAG" SET NOT NULL;

ALTER TABLE "AGENCY_LOCATIONS" ALTER "CREATE_DATETIME" SET NOT NULL;

ALTER TABLE "AGENCY_LOCATIONS" ALTER "CREATE_USER_ID" SET NOT NULL;

