CREATE TABLE OFFENDER_RELEASE_DETAILS
(
  OFFENDER_BOOK_ID      NUMBER(10)                        NOT NULL
    CONSTRAINT OFFENDER_RELEASE_DETAILS_PK
    PRIMARY KEY,
  RELEASE_DATE          DATE,
  COMMENT_TEXT          VARCHAR2(240),
  MOVEMENT_TYPE         VARCHAR2(12)                      NOT NULL,
  MOVEMENT_REASON_CODE  VARCHAR2(12),
  CREATE_DATETIME       TIMESTAMP(9) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATE_USER_ID        VARCHAR2(32) DEFAULT user         NOT NULL,
  MODIFY_DATETIME       TIMESTAMP(9) DEFAULT SYSTIMESTAMP,
  MODIFY_USER_ID        VARCHAR2(32),
  EVENT_ID              NUMBER(10) DEFAULT NULL,
  EVENT_STATUS          VARCHAR2(12) DEFAULT 'SCH'        NOT NULL,
  APPROVED_RELEASE_DATE DATE,
  AUTO_RELEASE_DATE     DATE,
  DTO_APPROVED_DATE     DATE,
  DTO_MID_TERM_DATE     DATE,
  VERIFIED_FLAG         VARCHAR2(1)  DEFAULT 'N',
  SEAL_FLAG             VARCHAR2(1)
);

CREATE INDEX OFFENDER_RELEASE_DETAILS_NI1
  ON OFFENDER_RELEASE_DETAILS (RELEASE_DATE);

CREATE INDEX OFF_RELDE_MOV_RSN_FK1
  ON OFFENDER_RELEASE_DETAILS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE);

CREATE INDEX OFFENDER_RELEASE_DETAILS_NI2
  ON OFFENDER_RELEASE_DETAILS (APPROVED_RELEASE_DATE);

CREATE INDEX OFFENDER_RELEASE_DETAILS_NI3
  ON OFFENDER_RELEASE_DETAILS (AUTO_RELEASE_DATE);

CREATE INDEX OFFENDER_RELEASE_DETAILS_NI4
  ON OFFENDER_RELEASE_DETAILS (DTO_APPROVED_DATE);

CREATE INDEX OFFENDER_RELEASE_DETAILS_NI5
  ON OFFENDER_RELEASE_DETAILS (DTO_MID_TERM_DATE);
