CREATE TABLE OFFENDER_IMPRISON_STATUSES
(
  OFFENDER_BOOK_ID    NUMBER(10)                        NOT NULL,
  IMPRISON_STATUS_SEQ NUMBER(6)                         NOT NULL,
  IMPRISONMENT_STATUS VARCHAR2(12)                      NOT NULL,
  EFFECTIVE_DATE      DATE                              NOT NULL,
  EFFECTIVE_TIME      DATE,
  EXPIRY_DATE         DATE,
  AGY_LOC_ID          VARCHAR2(6),
  CREATE_DATE         DATE,
  COMMENT_TEXT        VARCHAR2(240),
  CREATE_DATETIME     TIMESTAMP(9) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATE_USER_ID      VARCHAR2(32) DEFAULT user         NOT NULL,
  MODIFY_DATETIME     TIMESTAMP(9) DEFAULT SYSTIMESTAMP,
  MODIFY_USER_ID      VARCHAR2(32),
  STATE               VARCHAR2(12),
  SEAL_FLAG           VARCHAR2(1),
  CONSTRAINT OFFENDER_IMPRISON_STATUSES_PK
  PRIMARY KEY (OFFENDER_BOOK_ID, IMPRISON_STATUS_SEQ)
);

CREATE INDEX OFF_IMPS_AGY_LOC_F1
  ON OFFENDER_IMPRISON_STATUSES (AGY_LOC_ID);

