
CREATE TABLE OFFENDER_IEP_LEVELS
(
	OFFENDER_BOOK_ID                NUMBER(10)                        NOT NULL,
	IEP_LEVEL_SEQ                   NUMBER(10)                        NOT NULL,
	IEP_DATE                        DATE                              NOT NULL,
	IEP_TIME                        DATE,
	AGY_LOC_ID                      VARCHAR2(6)                       NOT NULL,
	IEP_LEVEL                       VARCHAR2(12)                      NOT NULL,
	COMMENT_TEXT                    VARCHAR2(240),
	USER_ID                         VARCHAR2(40),
	CREATE_DATETIME                 TIMESTAMP(9) DEFAULT SYSTIMESTAMP NOT NULL,
	CREATE_USER_ID                  VARCHAR2(32) DEFAULT USER         NOT NULL,
	MODIFY_DATETIME                 TIMESTAMP(9) DEFAULT SYSTIMESTAMP,
	MODIFY_USER_ID                  VARCHAR2(32),
	SEAL_FLAG                       VARCHAR2(1),
  CONSTRAINT OFFENDER_IEP_LEVELS_PK PRIMARY KEY (OFFENDER_BOOK_ID, IEP_LEVEL_SEQ),
  CONSTRAINT OFF_IEP_LEVELS_OFF_BKG_FK   FOREIGN KEY (OFFENDER_BOOK_ID)      REFERENCES  OFFENDER_BOOKINGS(OFFENDER_BOOK_ID),
  CONSTRAINT OFF_IEP_LEVELS_IEP_LEVEL_FK FOREIGN KEY (IEP_LEVEL, AGY_LOC_ID) REFERENCES IEP_LEVELS(IEP_LEVEL, AGY_LOC_ID)
);