CREATE TABLE REFERENCE_DOMAINS
(
  DOMAIN                          VARCHAR2(12)                        NOT NULL,
  DESCRIPTION                     VARCHAR2(40)                        NOT NULL,
  DOMAIN_STATUS                   VARCHAR2(12)                        NOT NULL,
  OWNER_CODE                      VARCHAR2(12)                        NOT NULL,
  APPLN_CODE                      VARCHAR2(12)                        NOT NULL,
  OLD_CODE_TABLE                  VARCHAR2(40),
  PARENT_DOMAIN                   VARCHAR2(12),
  CODE_LENGTH                     NUMBER(3),
  CREATE_DATETIME                 TIMESTAMP(9)  DEFAULT SYSTIMESTAMP  NOT NULL,
  CREATE_USER_ID                  VARCHAR2(32)  DEFAULT USER          NOT NULL,
  MODIFY_DATETIME                 TIMESTAMP(9)  DEFAULT SYSTIMESTAMP,
  MODIFY_USER_ID                  VARCHAR2(32),
  SUPER_SET_DOMAIN                VARCHAR2(12),
  SEAL_FLAG                       VARCHAR2(1)
);

ALTER TABLE REFERENCE_DOMAINS ADD CONSTRAINT REFERENCE_DOMAINS_PK PRIMARY KEY (DOMAIN);
ALTER TABLE REFERENCE_DOMAINS ADD FOREIGN KEY (PARENT_DOMAIN) REFERENCES REFERENCE_DOMAINS;
ALTER TABLE REFERENCE_DOMAINS ADD FOREIGN KEY (SUPER_SET_DOMAIN) REFERENCES REFERENCE_DOMAINS;
