CREATE TABLE STAFF_USER_ACCOUNTS
(
  "USERNAME"                      VARCHAR2(30 CHAR),
  "STAFF_ID"                      NUMBER(6, 0),
  "STAFF_USER_TYPE"               VARCHAR2(12 CHAR),
  "ID_SOURCE"                     VARCHAR2(12 CHAR),
  "WORKING_CASELOAD_ID"           VARCHAR2(6 CHAR),
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "SEAL_FLAG"                     VARCHAR2(1 CHAR)
);

ALTER TABLE "STAFF_USER_ACCOUNTS" ALTER "USERNAME" SET NOT NULL;
ALTER TABLE "STAFF_USER_ACCOUNTS" ALTER "STAFF_ID" SET NOT NULL;
ALTER TABLE "STAFF_USER_ACCOUNTS" ALTER "STAFF_USER_TYPE" SET NOT NULL;
ALTER TABLE "STAFF_USER_ACCOUNTS" ALTER "ID_SOURCE" SET NOT NULL;
ALTER TABLE "STAFF_USER_ACCOUNTS" ALTER "CREATE_DATETIME" SET NOT NULL;
ALTER TABLE "STAFF_USER_ACCOUNTS" ALTER "CREATE_USER_ID" SET NOT NULL;

