CREATE TABLE INTERNAL_SCHEDULE_REASONS 
(   INTERNAL_SCHEDULE_TYPE     VARCHAR2(12)                      NOT NULL, --'Reference Code ( INT_SCH_TYPE)'
    INTERNAL_SCHEDULE_RSN_CODE VARCHAR2(12)                      NOT NULL, --'Reference Code ( INT_SCH_RSN )'
    DESCRIPTION                VARCHAR2(40), 
    ACTIVE_FLAG                VARCHAR2(1)  DEFAULT 'Y'          NOT NULL, 
    LIST_SEQ                   NUMBER(6)    DEFAULT 1, 
    EXPIRY_DATE                DATE, 
    CREATE_USER_ID             VARCHAR2(32) DEFAULT USER         NOT NULL, 
    CREATE_DATETIME            TIMESTAMP(9) DEFAULT SYSTIMESTAMP NOT NULL, 
    MODIFY_DATETIME            TIMESTAMP(9) DEFAULT SYSTIMESTAMP, 
    MODIFY_USER_ID             VARCHAR2(32), 
    SEAL_FLAG                  VARCHAR2(1)
);

CREATE UNIQUE INDEX INTERNAL_SCHEDULE_REASONS_PK ON 
  INTERNAL_SCHEDULE_REASONS (INTERNAL_SCHEDULE_TYPE, INTERNAL_SCHEDULE_RSN_CODE);

ALTER TABLE INTERNAL_SCHEDULE_REASONS ADD CONSTRAINT INTERNAL_SCHEDULE_REASONS_PK
  PRIMARY KEY (INTERNAL_SCHEDULE_TYPE, INTERNAL_SCHEDULE_RSN_CODE);
