CREATE TABLE SENTENCE_CALC_TYPES
(
	SENTENCE_CALC_TYPE  VARCHAR2(12)                        NOT NULL,
	DESCRIPTION         VARCHAR2(240)                       NOT NULL,
	EXPIRY_DATE         DATE,
	ACTIVE_FLAG         VARCHAR2(1)   DEFAULT 'Y'           NOT NULL,
	LIST_SEQ            NUMBER(6)     DEFAULT 99,
	SENTENCE_CATEGORY   VARCHAR2(12)                        NOT NULL,
	SENTENCE_TYPE       VARCHAR2(12)                        NOT NULL,
	PROGRAM_METHOD      VARCHAR2(12),
	HEADER_SEQ          NUMBER,
	HEADER_LABEL        VARCHAR2(6),
	MODIFY_DATETIME     TIMESTAMP(9)  DEFAULT SYSTIMESTAMP,
	MODIFY_USER_ID      VARCHAR2(32),
	CREATE_DATETIME     TIMESTAMP(9)  DEFAULT SYSTIMESTAMP  NOT NULL,
	CREATE_USER_ID      VARCHAR2(32)  DEFAULT USER          NOT NULL,
	FUNCTION_TYPE       VARCHAR2(12),
	SEAL_FLAG           VARCHAR2(1)
);

ALTER TABLE SENTENCE_CALC_TYPES
  ADD CONSTRAINT SENTENCE_CALC_TYPES_PK PRIMARY KEY (SENTENCE_CATEGORY, SENTENCE_CALC_TYPE);

ALTER TABLE SENTENCE_CALC_TYPES
  ADD CONSTRAINT SENTENCE_CALC_TYPE_UK UNIQUE (HEADER_SEQ);
