CREATE TABLE PHONES
(
  PHONE_ID NUMBER(10)                               NOT NULL CONSTRAINT PHONES_PK PRIMARY KEY,
  OWNER_CLASS VARCHAR2(12)                          NOT NULL,
  OWNER_ID NUMBER(10),
  OWNER_SEQ NUMBER(6),
  OWNER_CODE VARCHAR2(12),
  PHONE_TYPE VARCHAR2(12)                           NOT NULL,
  PHONE_NO VARCHAR2(40)                             NOT NULL,
  EXT_NO VARCHAR2(7),
  CREATE_DATETIME TIMESTAMP(9) DEFAULT systimestamp NOT NULL,
  CREATE_USER_ID VARCHAR2(32)  DEFAULT user         NOT NULL,
  MODIFY_DATETIME TIMESTAMP(9) DEFAULT systimestamp,
  MODIFY_USER_ID VARCHAR2(32),
  SEAL_FLAG VARCHAR2(1)
);

CREATE INDEX PHONES_NI1 ON PHONES (OWNER_ID);
CREATE INDEX PHONES_NI2 ON PHONES (OWNER_CODE);
CREATE INDEX PHONES_NI3 ON PHONES (PHONE_NO);
