CREATE TABLE OFFENDER_SENTENCES
(
	OFFENDER_BOOK_ID          NUMBER(10)                          NOT NULL,
	SENTENCE_SEQ              NUMBER(6)                           NOT NULL,
	ORDER_ID                  NUMBER(10),
	SENTENCE_CALC_TYPE        VARCHAR2(12)                        NOT NULL,
	SENTENCE_STATUS           VARCHAR2(12)                        NOT NULL,
	CONSEC_TO_SENTENCE_SEQ    NUMBER(6),
	START_DATE                DATE                                NOT NULL,
	END_DATE                  DATE,
	COMMENT_TEXT              VARCHAR2(240),
	TERMINATION_REASON        VARCHAR2(12),
	NO_OF_UNEXCUSED_ABSENCE   NUMBER(6),
	CASE_ID                   NUMBER(10),
	ETD_CALCULATED_DATE       DATE,
	MTD_CALCULATED_DATE       DATE,
	LTD_CALCULATED_DATE       DATE,
	ARD_CALCULATED_DATE       DATE,
	CRD_CALCULATED_DATE       DATE,
	PED_CALCULATED_DATE       DATE,
	APD_CALCULATED_DATE       DATE,
	NPD_CALCULATED_DATE       DATE,
	LED_CALCULATED_DATE       DATE,
	SED_CALCULATED_DATE       DATE,
	PRRD_CALCULATED_DATE      DATE,
	TARIFF_CALCULATED_DATE    DATE,
	AGG_SENTENCE_SEQ          NUMBER(6),
	SENTENCE_CATEGORY         VARCHAR2(12)                        NOT NULL,
	FINE_AMOUNT               NUMBER(11,2),
	HDCED_CALCULATED_DATE     DATE,
	SENTENCE_TEXT             VARCHAR2(40),
	REVOKED_DATE              DATE,
	REVOKED_STAFF_ID          NUMBER(10),
	BREACH_LEVEL              NUMBER(6),
	CREATE_DATETIME           TIMESTAMP(9)  DEFAULT SYSTIMESTAMP  NOT NULL,
	CREATE_USER_ID            VARCHAR2(32)  DEFAULT USER          NOT NULL,
	MODIFY_DATETIME           TIMESTAMP(9)  DEFAULT SYSTIMESTAMP,
	MODIFY_USER_ID            VARCHAR2(32),
	TERMINATION_DATE          DATE,
	AGGREGATE_TERM            NUMBER(10),
	AGGREGATE_ADJUST_DAYS     NUMBER(10),
	SENTENCE_LEVEL            VARCHAR2(12)  DEFAULT 'IND'         NOT NULL,
	EXTENDED_DAYS             NUMBER(6),
	COUNTS                    NUMBER(6),
	DISCHARGE_DATE            DATE,
	STATUS_UPDATE_REASON      VARCHAR2(12),
	STATUS_UPDATE_COMMENT     VARCHAR2(400),
	STATUS_UPDATE_DATE        DATE,
	STATUS_UPDATE_STAFF_ID    NUMBER(10),
	CHARGE_SEQ                NUMBER(6),
	SUPERVISION_EXPIRY_DATE   DATE,
	LINE_SEQ                  NUMBER(6),
	NOMSENTDETAILREF          NUMBER(10),
	NOMCONSTOSENTDETAILREF    NUMBER(10),
	NOMCONSFROMSENTDETAILREF  NUMBER(10),
	NOMCONCWITHSENTDETAILREF  NUMBER(10),
	WORKFLOW_ID               NUMBER(32),
	SEAL_FLAG                 VARCHAR2(1)
);

ALTER TABLE OFFENDER_SENTENCES
  ADD CONSTRAINT OFFENDER_SENTENCES_PK PRIMARY KEY (OFFENDER_BOOK_ID, SENTENCE_SEQ);

ALTER TABLE OFFENDER_SENTENCES
  ADD CONSTRAINT OFF_SENT_SENT_CALC_TYPE_FK FOREIGN KEY (SENTENCE_CATEGORY, SENTENCE_CALC_TYPE) REFERENCES SENTENCE_CALC_TYPES;

-- ALTER TABLE OFFENDER_SENTENCES
--   ADD CONSTRAINT OFF_SENT_OFF_CASE_FK FOREIGN KEY (CASE_ID) REFERENCES OFFENDER_CASES;
--
-- ALTER TABLE OFFENDER_SENTENCES
--   ADD CONSTRAINT OFF_SENT_ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS;
