create table OFFENDER_TRANSACTIONS
(
  TXN_ID                      NUMBER(10)                         not null,
  TXN_ENTRY_SEQ               NUMBER(6)     default 99           not null,
  CASELOAD_ID                 VARCHAR2(6)                        not null,
  OFFENDER_ID                 NUMBER(10)                         not null,
  OFFENDER_BOOK_ID            NUMBER(10),
  TXN_POSTING_TYPE            VARCHAR2(12)                       not null,
  TXN_TYPE                    VARCHAR2(6)                        not null,
  TXN_ENTRY_DESC              VARCHAR2(240),
  TXN_ENTRY_AMOUNT            NUMBER(11,2)                       not null,
  TXN_ENTRY_DATE              DATE                               not null,
  SUB_ACCOUNT_TYPE            VARCHAR2(12)                       not null,
  TXN_REFERENCE_NUMBER        VARCHAR2(12),
  MODIFY_DATE                 DATE                               not null,
  RECEIPT_NUMBER              VARCHAR2(13),
  SLIP_PRINTED_FLAG           VARCHAR2(1)   default 'Y'          not null ,
  TRANSFER_CASELOAD_ID        VARCHAR2(6),
  RECEIPT_PRINTED_FLAG        VARCHAR2(1),
  PRE_WITHHOLD_AMOUNT         NUMBER(11,2),
  DEDUCTION_FLAG              VARCHAR2(1)   default 'Y',
  CLOSING_CHEQUE_NUMBER       VARCHAR2(12),
  REMITTER_NAME               VARCHAR2(60),
  PAYEE_CODE                  VARCHAR2(12),
  PAYEE_NAME_TEXT             VARCHAR2(60),
  PAYEE_CORPORATE_ID          NUMBER(10),
  PAYEE_PERSON_ID             NUMBER(10),
  ADJUST_TXN_ID               NUMBER(10),
  ADJUST_TXN_ENTRY_ID         NUMBER(6)     default 99,
  ADJUST_OFFENDER_ID          NUMBER(10),
  ADJUST_ACCOUNT_CODE         NUMBER(6),
  TXN_ADJUSTED_FLAG           VARCHAR2(1)   default 'Y' ,
  DEDUCTION_TYPE              VARCHAR2(6),
  INFO_NUMBER                 VARCHAR2(32),
  HOLD_CLEAR_FLAG             VARCHAR2(1)   default 'Y' ,
  HOLD_UNTIL_DATE             DATE,
  HOLD_NUMBER                 NUMBER(9),
  GROSS_AMOUNT                NUMBER(11,2),
  GROSS_NET_FLAG              VARCHAR2(1),
  REMITTER_ID                 NUMBER(10),
  APPLY_SPENDING_LIMIT_AMOUNT NUMBER(12,2),
  RECEIPT_PENDING_PRINT_FLAG  VARCHAR2(1),
  SEAL_FLAG                   VARCHAR2(1),
  ORG_TXN_TYPE                VARCHAR2(6),
  CREATE_DATETIME             TIMESTAMP(9)  default systimestamp not null,
  CREATE_USER_ID              VARCHAR2(32)  default USER         not null,
  MODIFY_DATETIME             TIMESTAMP(9),
  MODIFY_USER_ID              VARCHAR2(32),

  CHECK ( SLIP_PRINTED_FLAG IN ( 'Y' , 'N' )),
  CHECK ( TXN_ADJUSTED_FLAG IN ( 'Y' , 'N' )),
  CHECK ( HOLD_CLEAR_FLAG   IN ( 'Y' , 'N' )),

  CONSTRAINT OFFENDER_TRANSACTIONS_PK PRIMARY KEY (TXN_ID, TXN_ENTRY_SEQ),

  CONSTRAINT OFF_TXN_OFF_TXN_F1  FOREIGN KEY (ADJUST_TXN_ID, ADJUST_TXN_ENTRY_ID) REFERENCES OFFENDER_TRANSACTIONS,
  CONSTRAINT OFF_TXN_OFF_NAME_F1 FOREIGN KEY (OFFENDER_ID)                        REFERENCES OFFENDERS(OFFENDER_ID),
--  CONSTRAINT OFF_TXN_TXN_TYPE_F1 FOREIGN KEY (TXN_TYPE)                           REFERENCES TRANSACTION_TYPES(TXN_TYPE),
  CONSTRAINT OFF_TXN_CORP_F1     FOREIGN KEY (PAYEE_CORPORATE_ID)                 REFERENCES CORPORATES(CORPORATE_ID)
);

create index OFFENDER_TRANSACTIONS_NI21 on OFFENDER_TRANSACTIONS (CASELOAD_ID, OFFENDER_ID);

create index OFFENDER_TRANSACTIONS_NI1 on OFFENDER_TRANSACTIONS (OFFENDER_ID, CASELOAD_ID);

create index OFFENDER_TRANSACTIONS_NI7 on OFFENDER_TRANSACTIONS (OFFENDER_ID, INFO_NUMBER);

create index OFFENDER_TRANSACTIONS_NI2 on OFFENDER_TRANSACTIONS (OFFENDER_BOOK_ID);

create index OFFENDER_TRANSACTIONS_NI22 on OFFENDER_TRANSACTIONS (TXN_TYPE);

create index OFFENDER_TRANSACTIONS_NI9 on OFFENDER_TRANSACTIONS (SUB_ACCOUNT_TYPE);

create index OFFENDER_TRANSACTIONS_NI6 on OFFENDER_TRANSACTIONS (RECEIPT_NUMBER);

create index OFFENDER_TRANSACTIONS_NI3 on OFFENDER_TRANSACTIONS (PAYEE_CORPORATE_ID);

create index OFFENDER_TRANSACTIONS_NI4 on OFFENDER_TRANSACTIONS (PAYEE_PERSON_ID);

create index OFFENDER_TRANSACTIONS_NI5 on OFFENDER_TRANSACTIONS (ADJUST_TXN_ID, ADJUST_TXN_ENTRY_ID);

create index OFFENDER_TRANSACTION_NI20 on OFFENDER_TRANSACTIONS (REMITTER_ID);


comment on table OFFENDER_TRANSACTIONS is '- Retrofitted';

comment on column OFFENDER_TRANSACTIONS.OFFENDER_ID is 'Offender ID';

comment on column OFFENDER_TRANSACTIONS.OFFENDER_BOOK_ID is 'Offender Book ID';