
CREATE TABLE OFFENDER_VISITS
(
  OFFENDER_VISIT_ID               NUMBER(10)                          NOT NULL,
  OFFENDER_BOOK_ID                NUMBER(10)                          NOT NULL,
  COMMENT_TEXT                    VARCHAR2(240),
  RAISED_INCIDENT_TYPE            VARCHAR2(12),
  RAISED_INCIDENT_NUMBER          NUMBER(10),
  VISIT_DATE                      DATE                                NOT NULL,
  START_TIME                      DATE                                NOT NULL,
  END_TIME                        DATE                                NOT NULL,
  EVENT_OUTCOME                   VARCHAR2(12),
  VISIT_TYPE                      VARCHAR2(12)                        NOT NULL,
  VISIT_STATUS                    VARCHAR2(12)                        NOT NULL,
  OUTCOME_REASON_CODE             VARCHAR2(12),
  VISIT_INTERNAL_LOCATION_ID      NUMBER(10),
  AGENCY_VISIT_SLOT_ID            NUMBER(10),
  AGY_LOC_ID                      VARCHAR2(6)                         NOT NULL,
  CREATE_DATETIME                 TIMESTAMP(9)  DEFAULT SYSTIMESTAMP  NOT NULL,
  CREATE_USER_ID                  VARCHAR2(32)  DEFAULT USER          NOT NULL,
  MODIFY_DATETIME                 TIMESTAMP(9)  DEFAULT SYSTIMESTAMP,
  MODIFY_USER_ID                  VARCHAR2(32),
  RECORD_USER_ID                  VARCHAR2(30)  DEFAULT USER          NOT NULL,
  SEAL_FLAG                       VARCHAR2(1),

  CONSTRAINT OFFENDER_VISIT_PK PRIMARY KEY (OFFENDER_VISIT_ID),

  CONSTRAINT OFF_VIST_OFF_BKG_FK     FOREIGN KEY (OFFENDER_BOOK_ID) REFERENCES OFFENDER_BOOKINGS(OFFENDER_BOOK_ID)
--  CONSTRAINT OFF_VIS_AGY_VIS_SLOT_FK FOREIGN KEY (AGENCY_VISIT_SLOT_ID) REFERENCES AGENCY_VISIT_SLOTS(AGENCY_VISIT_SLOT_ID)
);

CREATE INDEX OFFENDER_VISITS_NI1 ON OFFENDER_VISITS (OFFENDER_BOOK_ID);
CREATE INDEX OFFENDER_VISITS_NI5 ON OFFENDER_VISITS (RAISED_INCIDENT_NUMBER);
CREATE INDEX OFFENDER_VISITS_NI4 ON OFFENDER_VISITS (VISIT_DATE);
CREATE INDEX OFFENDER_VISITS_NI6 ON OFFENDER_VISITS (AGENCY_VISIT_SLOT_ID);

COMMENT ON TABLE OFFENDER_VISITS IS 'This table will store all the visit orders for an offender.';
COMMENT ON COLUMN OFFENDER_VISITS.OFFENDER_VISIT_ID IS 'A unique ID for each Visit Order.';
COMMENT ON COLUMN OFFENDER_VISITS.OFFENDER_BOOK_ID IS 'A unique ID for each offender booking.';
COMMENT ON COLUMN OFFENDER_VISITS.COMMENT_TEXT IS 'Free text entry to stores comments against a Visit Order.';
COMMENT ON COLUMN OFFENDER_VISITS.RAISED_INCIDENT_TYPE IS 'Reference Code(INC_TYPE)';
COMMENT ON COLUMN OFFENDER_VISITS.RAISED_INCIDENT_NUMBER IS 'The reference number of the raised incident';
COMMENT ON COLUMN OFFENDER_VISITS.VISIT_DATE IS 'The date of the visit';
COMMENT ON COLUMN OFFENDER_VISITS.START_TIME IS 'The start time of the visit';
COMMENT ON COLUMN OFFENDER_VISITS.END_TIME IS 'The end Time of the visit';
COMMENT ON COLUMN OFFENDER_VISITS.EVENT_OUTCOME IS 'The outcome of the visit event.  REference Codes (VIS_COMPLETE)';
COMMENT ON COLUMN OFFENDER_VISITS.VISIT_TYPE IS 'The visit type.  Reference Codes(VISIT_TYPE)';
COMMENT ON COLUMN OFFENDER_VISITS.VISIT_STATUS IS 'The status of visit arrangements.  Reference Codes (VIS_STS)';
COMMENT ON COLUMN OFFENDER_VISITS.OUTCOME_REASON_CODE IS 'The reason of the event outcome.  Reference Codes(MOVE_CANC_RS)';
COMMENT ON COLUMN OFFENDER_VISITS.CREATE_DATETIME IS 'The timestamp when the record is created';
COMMENT ON COLUMN OFFENDER_VISITS.CREATE_USER_ID IS 'The user who creates the record';
COMMENT ON COLUMN OFFENDER_VISITS.MODIFY_DATETIME IS 'The timestamp when the record is modified';
COMMENT ON COLUMN OFFENDER_VISITS.MODIFY_USER_ID IS 'The user who modifies the record';
