CREATE TABLE STAFF_MEMBER_ROLES
(
  "STAFF_ID"                      NUMBER(6, 0)                            NOT NULL,
  "ROLE_ID"                       NUMBER(10, 0)                           NOT NULL,
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp  NOT NULL,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER          NOT NULL,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "ROLE_CODE"                     VARCHAR2(30 CHAR)                       NOT NULL,
  "SEAL_FLAG"                     VARCHAR2(1 CHAR),
  CONSTRAINT STAFF_MEMBER_ROLES_PK         PRIMARY KEY (ROLE_ID, STAFF_ID),
  CONSTRAINT STAFF_ROLE_STAFF_F1           FOREIGN KEY (STAFF_ID)  REFERENCES STAFF_MEMBERS(STAFF_ID),
  CONSTRAINT STAFF_ROLE_OMS_ROLE_F1        FOREIGN KEY (ROLE_ID)   REFERENCES OMS_ROLES(ROLE_ID),
  CONSTRAINT STAFF_MBR_ROLES_OMS_ROLES_FK2 FOREIGN KEY (ROLE_CODE) REFERENCES OMS_ROLES(ROLE_CODE)
);
