CREATE TABLE PAYABLE_ATTENDANCE_OUTCOMES (	
  PAYABLE_ATTENDANCE_OUTCOMES_ID NUMBER(10)    NOT NULL CONSTRAINT PAYABLE_ATTENDANCE_OUTCOMES_PK PRIMARY KEY,
  EVENT_TYPE                     VARCHAR2(12),
  OUTCOME_CODE                   VARCHAR2(12),
  PAY_FLAG                       VARCHAR2(1)   DEFAULT 'N',
  AUTHORISED_ABSENCE_FLAG        VARCHAR2(1)   DEFAULT 'N',
  START_DATE                     DATE,
  END_DATE                       DATE,
  CREATE_DATETIME                TIMESTAMP (9) DEFAULT SYSTIMESTAMP,
  CREATE_USER_ID                 VARCHAR2(32),
  MODIFY_DATETIME                TIMESTAMP (9) DEFAULT SYSTIMESTAMP,
  MODIFY_USER_ID                 VARCHAR2(32),
  SEAL_FLAG                      VARCHAR2(1)
);
