CREATE TABLE PROFILE_TYPES
(
  PROFILE_TYPE          VARCHAR2(12)                      NOT NULL,
  PROFILE_CATEGORY      VARCHAR2(12),
  DESCRIPTION           VARCHAR2(40),
  LIST_SEQ              NUMBER(6)                         NOT NULL,
  MANDATORY_FLAG        VARCHAR2(1) DEFAULT 'Y'           NOT NULL,
  UPDATED_ALLOWED_FLAG  VARCHAR2(1) DEFAULT 'Y'           NOT NULL,
  CODE_VALUE_TYPE       VARCHAR2(12)                      NOT NULL,
  ACTIVE_FLAG           VARCHAR2(1) DEFAULT 'Y'           NOT NULL,
  EXPIRY_DATE           DATE,
  MODIFY_USER_ID        VARCHAR2(32),
  MODIFIED_DATE         DATE                              NOT NULL,
  CREATE_DATETIME       TIMESTAMP(9) DEFAULT systimestamp NOT NULL,
  CREATE_USER_ID        VARCHAR2(32) DEFAULT USER         NOT NULL,
  MODIFY_DATETIME       TIMESTAMP(9) DEFAULT systimestamp,
  SEAL_FLAG             VARCHAR2(1)  ,
    CONSTRAINT PROFILE_TYPES_PK PRIMARY KEY (PROFILE_TYPE)
)