CREATE TABLE OFFENDER_EXTERNAL_MOVEMENTS (
    OFFENDER_BOOK_ID              NUMBER(10)                        NOT NULL,
    MOVEMENT_SEQ                  NUMBER(6) DEFAULT 99              NOT NULL,
    MOVEMENT_DATE                 DATE                              NOT NULL,
    MOVEMENT_TIME                 DATE                              NOT NULL,
    INTERNAL_SCHEDULE_TYPE        VARCHAR2(12),
    INTERNAL_SCHEDULE_REASON_CODE VARCHAR2(12),
    MOVEMENT_TYPE                 VARCHAR2(12),
    MOVEMENT_REASON_CODE          VARCHAR2(12),
    DIRECTION_CODE                VARCHAR2(12),
    ARREST_AGENCY_LOC_ID          VARCHAR2(6),
    TO_PROV_STAT_CODE             VARCHAR2(6),
    ESCORT_CODE                   VARCHAR2(12),
    FROM_AGY_LOC_ID               VARCHAR2(6),
    TO_AGY_LOC_ID                 VARCHAR2(6),
    ACTIVE_FLAG                   VARCHAR2(1) DEFAULT 'Y'           NOT NULL,
    ESCORT_TEXT                   VARCHAR2(240),
    COMMENT_TEXT                  VARCHAR2(240),
    REPORTING_DATE                DATE,
    TO_CITY                       VARCHAR2(12),
    FROM_CITY                     VARCHAR2(12),
    REPORTING_TIME                DATE,
    EVENT_ID                      NUMBER(10),
    PARENT_EVENT_ID               NUMBER(10),
    TO_COUNTRY_CODE               VARCHAR2(12),
    OJ_LOCATION_CODE              VARCHAR2(12),
    APPLICATION_DATE              DATE,
    APPLICATION_TIME              DATE,
    TO_ADDRESS_ID                 NUMBER(10),
    FROM_ADDRESS_ID               NUMBER(10),
    SEAL_FLAG                     VARCHAR2(1),
    CREATE_DATETIME               TIMESTAMP(9) DEFAULT systimestamp NOT NULL,
    CREATE_USER_ID                VARCHAR2(32) DEFAULT USER,
    MODIFY_DATETIME               TIMESTAMP(9),
    MODIFY_USER_ID                VARCHAR2(32),

    CONSTRAINT OFFENDER_EXTERNAL_MOVEMENTS_PK PRIMARY KEY (OFFENDER_BOOK_ID, MOVEMENT_SEQ),

    CONSTRAINT OFF_EM_OFF_BKG_F1        FOREIGN KEY (OFFENDER_BOOK_ID)                                      REFERENCES OFFENDER_BOOKINGS (OFFENDER_BOOK_ID),
    CONSTRAINT OFF_EM_AGY_LOC_F2        FOREIGN KEY (FROM_AGY_LOC_ID)                                       REFERENCES AGENCY_LOCATIONS (AGY_LOC_ID),
    CONSTRAINT OFF_EM_AGY_LOC_F3        FOREIGN KEY (TO_AGY_LOC_ID)                                         REFERENCES AGENCY_LOCATIONS (AGY_LOC_ID),
    CONSTRAINT OFF_EXT_MOV_ADDR_FK      FOREIGN KEY (TO_ADDRESS_ID)                                         REFERENCES ADDRESSES (ADDRESS_ID),
    CONSTRAINT OFF_EXT_MOV_FROM_ADDR_FK FOREIGN KEY (FROM_ADDRESS_ID)                                       REFERENCES ADDRESSES (ADDRESS_ID),
    CONSTRAINT OFF_EM_INT_SR_F1         FOREIGN KEY (INTERNAL_SCHEDULE_TYPE, INTERNAL_SCHEDULE_REASON_CODE) REFERENCES INTERNAL_SCHEDULE_REASONS (INTERNAL_SCHEDULE_TYPE, INTERNAL_SCHEDULE_RSN_CODE),
    CONSTRAINT OFF_EM_MOVE_RSN_F1       FOREIGN KEY (MOVEMENT_TYPE, MOVEMENT_REASON_CODE)                   REFERENCES MOVEMENT_REASONS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE),

    CONSTRAINT OFFENDER_EXTERNAL_MOVEMENTS_UK UNIQUE (EVENT_ID)
);

CREATE INDEX OFF_EM_INT_SR_F1
  ON OFFENDER_EXTERNAL_MOVEMENTS (INTERNAL_SCHEDULE_TYPE, INTERNAL_SCHEDULE_REASON_CODE);

CREATE INDEX OFF_EM_MOVE_RSN_F1
  ON OFFENDER_EXTERNAL_MOVEMENTS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE);

CREATE INDEX OFFENDER_EXTERNAL_MOVEMENTS_N4
  ON OFFENDER_EXTERNAL_MOVEMENTS (FROM_AGY_LOC_ID);

CREATE INDEX OFFENDER_EXTERNAL_MOVEMENTS_N2
  ON OFFENDER_EXTERNAL_MOVEMENTS (TO_AGY_LOC_ID, MOVEMENT_TYPE);

CREATE INDEX OFFENDER_EXTERNAL_MOVEMENTS_N1
  ON OFFENDER_EXTERNAL_MOVEMENTS (PARENT_EVENT_ID);

CREATE INDEX OFF_EXT_MOV_ADDR_FK
  ON OFFENDER_EXTERNAL_MOVEMENTS (TO_ADDRESS_ID);

CREATE INDEX OFF_EXT_MOV_FROM_ADDR_FK
  ON OFFENDER_EXTERNAL_MOVEMENTS (FROM_ADDRESS_ID);
