CREATE TABLE MOVEMENT_REASONS
(
  MOVEMENT_TYPE            VARCHAR2(12)                        NOT NULL,
  MOVEMENT_REASON_CODE     VARCHAR2(12)                        NOT NULL,
  DESCRIPTION              VARCHAR2(40)                        NOT NULL,
  OPEN_CONTACT_FLAG        VARCHAR2(1)   DEFAULT 'Y'           NOT NULL,
  CLOSE_CONTACT_FLAG       VARCHAR2(1)   DEFAULT 'Y'           NOT NULL,
  ACTIVE_FLAG              VARCHAR2(1)   DEFAULT 'Y'           NOT NULL,
  LIST_SEQ                 NUMBER(6),
  EXPIRY_DATE              DATE,
  CREATE_USER_ID           VARCHAR2(32)  DEFAULT user          NOT NULL,
  NOTIFICATION_TYPE        VARCHAR2(1),
  NOTIFICATION_FLAG        VARCHAR2(1),
  BILLING_SERVICE_FLAG     VARCHAR2(1),
  TRANSPORTATION_FLAG      VARCHAR2(1),
  HEADER_STATUS_FLAG       VARCHAR2(1),
  IN_MOVEMENT_TYPE         VARCHAR2(12),
  IN_MOVEMENT_REASON_CODE  VARCHAR2(12),
  ESC_RECAP_FLAG           VARCHAR2(1)   DEFAULT 'N',
  CREATE_DATETIME          TIMESTAMP(9)  DEFAULT SYSTIMESTAMP  NOT NULL,
  MODIFY_DATETIME          TIMESTAMP(9)  DEFAULT SYSTIMESTAMP,
  MODIFY_USER_ID           VARCHAR2(32),
  SEAL_FLAG                VARCHAR2(1),
  UPDATE_ALLOWED_FLAG      VARCHAR2(1)   DEFAULT 'Y'           NOT NULL,
  TRN_REQ_APVL_FLAG        VARCHAR2(1)   DEFAULT 'N',
  TRN_SCHD_TRIP_FLAG       VARCHAR2(1)   DEFAULT 'N',
  TRN_ASSIGN_PRIORITY_FLAG VARCHAR2(1)   DEFAULT 'N',
  TRN_P_LIST_FLAG          VARCHAR2(1)   DEFAULT 'N',
  TRN_PRIORITY_SEQ         NUMBER(6),
  SUBSEQUENT_MV_TYPE       VARCHAR2(12),
  SUBSEQUENT_MV_RSN_CODE   VARCHAR2(12),
  REASON_FLAG              VARCHAR2(1),
  DRIVE_TO_OIDUMAPP_FLAG   VARCHAR2(1),
  INACTIVATE_SENT          VARCHAR2(1),
  SUSPEND_REACTIVATE_SENT  VARCHAR2(1),
  CONSTRAINT MOVEMENT_REASONS_PK
    PRIMARY KEY (MOVEMENT_TYPE, MOVEMENT_REASON_CODE)
);

COMMENT ON TABLE MOVEMENT_REASONS is 'Reasons associated with movement types.';

COMMENT ON COLUMN MOVEMENT_REASONS.MOVEMENT_TYPE           is 'Reference Code ( MOVE_TYPE )';
COMMENT ON COLUMN MOVEMENT_REASONS.MOVEMENT_REASON_CODE    is 'Reference Code ( MOVE_RSN ). The reason for the movement.';
COMMENT ON COLUMN MOVEMENT_REASONS.DESCRIPTION             is 'Description of movement reason.';
COMMENT ON COLUMN MOVEMENT_REASONS.OPEN_CONTACT_FLAG       is ' Flag signalling the opening of a new offender booking.';
COMMENT ON COLUMN MOVEMENT_REASONS.CLOSE_CONTACT_FLAG      is 'Signals the fact that an offender booking should be closed.';
COMMENT ON COLUMN MOVEMENT_REASONS.ACTIVE_FLAG             is 'Active flag on movement reasons.';
COMMENT ON COLUMN MOVEMENT_REASONS.LIST_SEQ                is ' Sequencing for list of values.';
COMMENT ON COLUMN MOVEMENT_REASONS.EXPIRY_DATE             is 'Date code deactivated.';
COMMENT ON COLUMN MOVEMENT_REASONS.CREATE_USER_ID          is 'The user who creates the record';
COMMENT ON COLUMN MOVEMENT_REASONS.HEADER_STATUS_FLAG      is 'For Ontario Header Status';
COMMENT ON COLUMN MOVEMENT_REASONS.IN_MOVEMENT_TYPE        is 'Domain = "MOVE_TYPE".  The Default Incoming Movement Type.';
COMMENT ON COLUMN MOVEMENT_REASONS.IN_MOVEMENT_REASON_CODE is 'Domain = "MOVE_RSN".  The Default Incoming Movement Reason.';
COMMENT ON COLUMN MOVEMENT_REASONS.ESC_RECAP_FLAG          is 'When Admission and Release screens see this flag is checked, a record will be created in Offender_Escapes table.';
COMMENT ON COLUMN MOVEMENT_REASONS.CREATE_DATETIME         is 'The timestamp when the record is created';
COMMENT ON COLUMN MOVEMENT_REASONS.MODIFY_DATETIME         is 'The timestamp when the record is modified ';
COMMENT ON COLUMN MOVEMENT_REASONS.MODIFY_USER_ID          is 'The user who modifies the record';