/{bookingId}/sentenceDetail:
  (javaOperationName): getBookingSentenceDetail
  type: {
    readOnlyItem: {
      type: SentenceDetail,
      description: Gets sentence details (e.g. key dates) for offender booking.
    }
  }
