/:
  (javaOperationName): getLocations
  description: Returns the list of locations viewable by the user
  type: { readOnlyCollectionPaged: { type: Location } }
  is: [
    searchable: {fieldsList : "locationId, agencyId, locationType, and parentLocationId"},
    sortable: {fieldsList : "locationId, agencyId, locationType, and parentLocationId"},
  ]

/{locationId}:
  (javaOperationName): getLocation
  description: Returns details about the specified location
  uriParameters:
    locationId:
      (javaType): Long
      description: The location id of location
  type: { readOnlyItem: { type: Location }}

/{locationId}/inmates:
  (javaOperationName): getOffendersAtLocation
  description: The collection of inmates present at the specified location.
  uriParameters:
    locationId:
      (javaType): Long
      description: The location id of location
  type: { readOnlyCollectionPaged: { type: OffenderBooking } }
  is: [
    searchable: {fieldsList : "bookingNo, bookingId, offenderNo, firstName, lastName, agencyId, or assignedLivingUnitId"},
    sortable: {fieldsList : "bookingNo, bookingId, offenderNo, firstName, lastName, agencyId, or assignedLivingUnitId"},
  ]
