/alertTypes:
  (javaOperationName): getAlertTypes
  description: Give all Alert types
  type: { readOnlyCollectionPaged: { type: ReferenceCode } }
  is: [
    searchable: {fieldsList: "code, description, activeFlag and parentCode"},
    sortable: {fieldsList: "code"}
  ]

/alertTypes/{alertType}:
  (javaOperationName): getAlertType
  description: Give all Alerts for specific Alert type
  type: { readOnlyItem : { type: ReferenceCode }}
  
/alertTypes/{alertType}/codes:
  (javaOperationName): getAlertTypesByType
  description: Give all Alert Codes for specific Alert type
  type: { readOnlyCollectionPaged : { type: ReferenceCode }}
  is: [
    searchable: {fieldsList: "code, description, activeFlag and parentCode"},
    sortable: {fieldsList: "code"}
  ]
  
/alertTypes/{alertType}/codes/{alertCode}:
  (javaOperationName): getAlertTypeCode
  description: Give specific code details of alerts.
  type: { readOnlyItem : { type: ReferenceCode }}

/caseNoteSources:
  (javaOperationName): getCaseNoteSources
  description: Give all Case Note Sources
  type: { readOnlyCollectionPaged : { type: ReferenceCode }}
  is: [
    searchable: {fieldsList: "code, description, activeFlag and parentCode"},
    sortable: {fieldsList: "code"}
  ]

/caseNoteSources/{sourceCode}:
  (javaOperationName): getCaseNoteSource
  description: Get the Case Note Source
  type: { readOnlyItem : { type: ReferenceCode }}

/caseNoteTypes:
  (javaOperationName): getCaseNoteTypes
  description: Give all Case Note Types
  type: { readOnlyCollectionPaged : { type: ReferenceCode }}
  is: [
    searchable: {fieldsList: "code, description, activeFlag and parentCode"},
    sortable: {fieldsList: "code"}
  ]

/caseNoteTypes/{typeCode}:
  (javaOperationName): getCaseNoteType
  description: Get the Case Note Type
  type: { readOnlyItem : { type: ReferenceCode } }

/caseNoteSubTypes/{typeCode}:
  (javaOperationName): getCaseNoteSubTypes
  description: Give all Case Note SubTypes
  type: { readOnlyCollectionPaged : { type: ReferenceCode }}

/caseNoteSubTypes/{typeCode}/subTypes/{subTypeCode}:
  (javaOperationName): getCaseNoteSubType
  description: Get the Case Note SubType
  type: { readOnlyItem : { type: ReferenceCode }}
