/{locationId}:
description:  Search for Offender Bookings in the system.
type: { readOnlyCollection: { type: OffenderBooking } }

/{locationId}/{keywords}:
description:  Search for Offender Bookings in the system.
type: { readOnlyCollection: { type: OffenderBooking } }
