FIND_AWARDS {
  SELECT S.OIC_SANCTION_CODE   AS SANCTION_CODE,
         RC1.DESCRIPTION       AS SANCTION_CODE_DESCRIPTION,
         S.SANCTION_MONTHS     AS MONTHS,
         S.SANCTION_DAYS       AS DAYS,
         S.COMPENSATION_AMOUNT AS LIMIT,
         S.COMMENT_TEXT        AS "COMMENT",
         S.EFFECTIVE_DATE      AS EFFECTIVE_DATE,
         S.STATUS,
         RC2.DESCRIPTION       AS STATUS_DESCRIPTION,
         S.OIC_HEARING_ID      AS HEARING_ID,
         S.RESULT_SEQ          AS HEARING_SEQUENCE
  FROM OFFENDER_OIC_SANCTIONS S
    INNER JOIN OIC_HEARING_RESULTS H ON S.OIC_HEARING_ID = H.OIC_HEARING_ID AND S.RESULT_SEQ = H.RESULT_SEQ
    LEFT JOIN REFERENCE_CODES RC1 ON S.OIC_SANCTION_CODE = RC1.CODE AND RC1.DOMAIN = 'OIC_SANCT'
    LEFT JOIN REFERENCE_CODES RC2 ON S.STATUS = RC2.CODE AND RC2.DOMAIN = 'OIC_SANCT_ST'
  WHERE S.OFFENDER_BOOK_ID = :bookingId
    AND H.FINDING_CODE = 'PROVED'
  ORDER BY S.OIC_HEARING_ID, S.RESULT_SEQ
}

FIND_ADJUDICATION_OFFENCE_TYPES_FOR_OFFENDER {
  SELECT  OO.OIC_OFFENCE_ID AS ID
  ,       OO.OIC_OFFENCE_CODE AS CODE
  ,       OO.DESCRIPTION AS DESCRIPTION
  FROM (
      SELECT DISTINCT AIC.CHARGED_OIC_OFFENCE_ID AS OFFENCE_IDS
      FROM AGENCY_INCIDENTS AI
        INNER JOIN AGENCY_INCIDENT_PARTIES AIP ON AIP.AGENCY_INCIDENT_ID = AI.AGENCY_INCIDENT_ID
        INNER JOIN AGENCY_LOCATIONS AL ON AL.AGY_LOC_ID = AI.AGY_LOC_ID
        INNER JOIN AGENCY_INCIDENT_CHARGES AIC ON AIC.AGENCY_INCIDENT_ID = AIP.AGENCY_INCIDENT_ID AND AIC.PARTY_SEQ = AIP.PARTY_SEQ
      WHERE AIP.OFFENDER_BOOK_ID IN (
        SELECT OFFENDER_BOOK_ID FROM OFFENDER_BOOKINGS OB
          JOIN OFFENDERS OFF ON OFF.OFFENDER_ID = OB.OFFENDER_ID
          WHERE OFF.OFFENDER_ID_DISPLAY = :offenderNo)
      )
    INNER JOIN OIC_OFFENCES OO ON OO.OIC_OFFENCE_ID = OFFENCE_IDS
  ORDER BY DESCRIPTION
}

FIND_ADJUDICATIONS_FOR_OFFENDER {
    SELECT  AIP.OIC_INCIDENT_ID AS ADJUDICATION_NUMBER
    ,		AI.REPORT_TIME
    ,       AI.AGENCY_INCIDENT_ID
    ,       AL.AGY_LOC_ID AS AGENCY_ID
    ,       AIC.OIC_CHARGE_ID
    ,		OO.DESCRIPTION AS OFFENCE_DESCRIPTION
    ,       OO.OIC_OFFENCE_CODE AS OFFENCE_CODE
    ,       AIP.PARTY_SEQ
    ,       OHR.FINDING_CODE
    FROM  AGENCY_INCIDENTS AI
      INNER JOIN AGENCY_INCIDENT_PARTIES AIP ON AIP.AGENCY_INCIDENT_ID = AI.AGENCY_INCIDENT_ID  AND AIP.INCIDENT_ROLE = 'S'
      INNER JOIN AGENCY_LOCATIONS AL ON AL.AGY_LOC_ID = AI.AGY_LOC_ID
      INNER JOIN AGENCY_INCIDENT_CHARGES AIC  ON AIC.AGENCY_INCIDENT_ID = AIP.AGENCY_INCIDENT_ID AND AIC.PARTY_SEQ = AIP.PARTY_SEQ
      INNER JOIN OIC_OFFENCES OO ON OO.OIC_OFFENCE_ID = AIC.CHARGED_OIC_OFFENCE_ID
      LEFT OUTER JOIN OIC_HEARING_RESULTS OHR ON OHR.AGENCY_INCIDENT_ID = AIC.AGENCY_INCIDENT_ID AND OHR.CHARGE_SEQ = AIC.CHARGE_SEQ
    WHERE AIP.OFFENDER_BOOK_ID IN (
      SELECT OFFENDER_BOOK_ID FROM OFFENDER_BOOKINGS OB
        JOIN OFFENDERS OFF ON OFF.OFFENDER_ID = OB.OFFENDER_ID
        WHERE OFF.OFFENDER_ID_DISPLAY = :offenderNo)
     AND (:agencyLocationId is NULL OR AL.AGY_LOC_ID = :agencyLocationId)
     AND (:offenceId IS NULL OR CHARGED_OIC_OFFENCE_ID = :offenceId)
     AND (:startDate IS NULL OR trunc(REPORT_TIME) >= :startDate)
     AND (:endDate IS NULL OR trunc(REPORT_TIME) <= :endDate)
    ORDER BY AI.REPORT_TIME DESC
}