GET_ALERT_TYPES {
SELECT CODE,
       DESCRIPTION,
       LIST_SEQ
FROM REFERENCE_CODES
WHERE DOMAIN = 'ALERT'
AND ACTIVE_FLAG = :active
}

GET_ALERT_SUBTYPES {
SELECT CODE,
       DESCRIPTION,
       LIST_SEQ,
       PARENT_CODE
FROM REFERENCE_CODES
WHERE DOMAIN = 'ALERT_CODE'
AND PARENT_CODE = :parentCode
AND ACTIVE_FLAG = :active
}