FIND_LOCATION {
  SELECT A.INTERNAL_LOCATION_ID LOCATION_ID,
         A.INTERNAL_LOCATION_TYPE LOCATION_TYPE,
         A.DESCRIPTION,
         A.PARENT_INTERNAL_LOCATION_ID PARENT_LOCATION_ID,
         A.NO_OF_OCCUPANT CURRENT_OCCUPANCY,
         A.AGY_LOC_ID AGENCY_ID,
         A.USER_DESC USER_DESCRIPTION
  FROM AGENCY_INTERNAL_LOCATIONS A
         INNER JOIN CASELOAD_AGENCY_LOCATIONS C ON A.AGY_LOC_ID = C.AGY_LOC_ID
         INNER JOIN STAFF_USER_ACCOUNTS SUA ON C.CASELOAD_ID = SUA.WORKING_CASELOAD_ID
  WHERE A.ACTIVE_FLAG = 'Y'
    AND A.INTERNAL_LOCATION_ID = :locationId
    AND SUA.USERNAME = :username
}

GET_LOCATION {
  SELECT A.INTERNAL_LOCATION_ID LOCATION_ID,
         A.INTERNAL_LOCATION_TYPE LOCATION_TYPE,
         A.DESCRIPTION,
         A.PARENT_INTERNAL_LOCATION_ID PARENT_LOCATION_ID,
         A.NO_OF_OCCUPANT CURRENT_OCCUPANCY,
         A.AGY_LOC_ID AGENCY_ID,
         A.USER_DESC USER_DESCRIPTION,
         A.INTERNAL_LOCATION_CODE
  FROM AGENCY_INTERNAL_LOCATIONS A
    WHERE A.ACTIVE_FLAG = COALESCE(:activeFlag, A.ACTIVE_FLAG)
    AND A.INTERNAL_LOCATION_ID = :locationId
}

FIND_LOCATIONS_BY_AGENCY_AND_TYPE {
  SELECT A.INTERNAL_LOCATION_ID LOCATION_ID,
         A.AGY_LOC_ID AGENCY_ID,
         A.INTERNAL_LOCATION_TYPE LOCATION_TYPE,
         A.DESCRIPTION,
         A.USER_DESC USER_DESCRIPTION,
         A.PARENT_INTERNAL_LOCATION_ID PARENT_LOCATION_ID,
         A.NO_OF_OCCUPANT CURRENT_OCCUPANCY
  FROM AGENCY_INTERNAL_LOCATIONS A
  WHERE A.ACTIVE_FLAG = 'Y'
    AND A.AGY_LOC_ID = :agencyId
    AND A.INTERNAL_LOCATION_TYPE = :locationType
}

GET_LOCATION_GROUP_DATA {
 SELECT AIL.INTERNAL_LOCATION_ID                        AS LOCATION_ID,
        AIL.DESCRIPTION,
        AIL.USER_DESC                                   AS USER_DESCRIPTION,
        AIL.INTERNAL_LOCATION_CODE,
        AIL.INTERNAL_LOCATION_TYPE                      AS LOCATION_TYPE,
        AIL.PARENT_INTERNAL_LOCATION_ID                 AS PARENT_LOCATION_ID
   FROM AGENCY_INTERNAL_LOCATIONS AIL
  WHERE AIL.INTERNAL_LOCATION_TYPE in ('WING') AND
        AIL.CERTIFIED_FLAG = 'Y'                      AND
        AIL.UNIT_TYPE IS NOT NULL                     AND
        AIL.AGY_LOC_ID = :agencyId                    AND
        AIL.ACTIVE_FLAG = 'Y'                         AND
        AIL.PARENT_INTERNAL_LOCATION_ID IS NULL
}

  GET_SUB_LOCATION_GROUP_DATA {
SELECT AIL.INTERNAL_LOCATION_ID                        AS LOCATION_ID,
       AIL.DESCRIPTION,
       AIL.USER_DESC                                   AS USER_DESCRIPTION,
       AIL.INTERNAL_LOCATION_CODE,
       AIL.INTERNAL_LOCATION_TYPE                      AS LOCATION_TYPE,
       AIL.PARENT_INTERNAL_LOCATION_ID                 AS PARENT_LOCATION_ID
  FROM AGENCY_INTERNAL_LOCATIONS AIL
 WHERE AIL.CERTIFIED_FLAG = 'Y'                      AND
       AIL.UNIT_TYPE IS NOT NULL                     AND
       AIL.ACTIVE_FLAG = 'Y'                         AND
       AIL.PARENT_INTERNAL_LOCATION_ID IN (:parentLocationIds)
  }
