
GET_OFFENDER_ADDRESSES {

   SELECT ADDR.OWNER_ID,
          ADDR.FLAT,
          ADDR.PREMISE,
          ADDR.STREET,
          RC3.DESCRIPTION AS TOWN,
          ADDR.POSTAL_CODE,
          RC1.DESCRIPTION AS COUNTY,
          RC2.DESCRIPTION AS COUNTRY,
          ADDR.COMMENT_TEXT AS "COMMENT",
          ADDR.PRIMARY_FLAG AS "PRIMARY",
          ADDR.NO_FIXED_ADDRESS_FLAG AS NO_FIXED_ADDRESS,
          ADDR.START_DATE,
          PH.PHONE_TYPE,
          PH.PHONE_NO,
          PH.EXT_NO AS PHONE_EXT
   FROM ADDRESSES ADDR
     LEFT JOIN REFERENCE_CODES RC1 ON RC1.CODE = ADDR.COUNTY_CODE AND RC1.DOMAIN = 'COUNTY'
     LEFT JOIN REFERENCE_CODES RC2 ON RC2.CODE = ADDR.COUNTRY_CODE AND RC2.DOMAIN = 'COUNTRY'
     LEFT JOIN REFERENCE_CODES RC3 ON RC3.CODE = ADDR.CITY_CODE AND RC3.DOMAIN = 'CITY'
     LEFT JOIN PHONES PH ON PH.OWNER_CLASS = 'ADDR' AND PH.OWNER_ID = ADDR.ADDRESS_ID
   WHERE ADDR.OWNER_CLASS = 'OFF'
   AND ADDR.OWNER_ID IN (
       SELECT O.ROOT_OFFENDER_ID
       FROM OFFENDERS O
       WHERE O.OFFENDER_ID_DISPLAY = :offenderNo)
   ORDER BY ADDR.START_DATE DESC

}
