OFFENDER_IDS {
SELECT OFFENDER_ID FROM OFFENDERS WHERE OFFENDER_ID_DISPLAY = :offenderNo
}

OFFENDER_BOOKING_IDS {
SELECT OFFENDER_BOOK_ID FROM OFFENDER_BOOKINGS WHERE OFFENDER_ID = :offenderId
}

DELETE_OFFENDER_COURSE_ATTENDANCES {
DELETE /*+ PARALLEL(OCA) */ FROM OFFENDER_COURSE_ATTENDANCES OCA
WHERE EXISTS (SELECT 1
              FROM OFFENDER_PROGRAM_PROFILES OPP
              WHERE OCA.OFF_PRGREF_ID = OPP.OFF_PRGREF_ID
                AND OPP.OFFENDER_BOOK_ID = :bookId)
}

DELETE_OFFENDER_PRG_PRF_PAY_BANDS {
DELETE /*+ PARALLEL(OPPPB) */ FROM OFFENDER_PRG_PRF_PAY_BANDS OPPPB
WHERE EXISTS (SELECT 1
              FROM OFFENDER_PROGRAM_PROFILES OPP
              WHERE OPPPB.OFF_PRGREF_ID = OPP.OFF_PRGREF_ID
                AND OPP.OFFENDER_BOOK_ID = :bookId)
}

DELETE_OFFENDER_PROGRAM_PROFILES {
DELETE /*+ PARALLEL(OFFENDER_PROGRAM_PROFILES) */ FROM OFFENDER_PROGRAM_PROFILES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_MEDICAL_TREATMENTS {
DELETE /*+ PARALLEL(OMT) */ FROM OFFENDER_MEDICAL_TREATMENTS OMT
WHERE EXISTS (SELECT 1
              FROM OFFENDER_HEALTH_PROBLEMS OHP
              WHERE OMT.OFFENDER_HEALTH_PROBLEM_ID = OHP.OFFENDER_HEALTH_PROBLEM_ID
                AND OHP.OFFENDER_BOOK_ID = :bookId)
}

DELETE_OFFENDER_HEALTH_PROBLEMS {
DELETE /*+ PARALLEL(OFFENDER_HEALTH_PROBLEMS) */ FROM OFFENDER_HEALTH_PROBLEMS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_INCIDENT_CASE_PARTIES {
DELETE /*+ PARALLEL(INCIDENT_CASE_PARTIES) */ FROM INCIDENT_CASE_PARTIES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_CURFEWS {
DELETE /*+ PARALLEL(OFFENDER_CURFEWS) */ FROM OFFENDER_CURFEWS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_LANGUAGES {
DELETE /*+ PARALLEL(OFFENDER_LANGUAGES) */ FROM OFFENDER_LANGUAGES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_VISIT_VISITORS {
DELETE /*+ PARALLEL(OVV) */ FROM OFFENDER_VISIT_VISITORS OVV
WHERE EXISTS (SELECT 1
              FROM OFFENDER_VISITS OV
              WHERE OVV.OFFENDER_VISIT_ID = OV.OFFENDER_VISIT_ID
                AND OV.OFFENDER_BOOK_ID = :bookId)
}

DELETE_OFFENDER_VISITS {
DELETE /*+ PARALLEL(OFFENDER_VISITS) */ FROM OFFENDER_VISITS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_VISIT_BALANCES {
DELETE /*+ PARALLEL(OFFENDER_VISIT_BALANCES) */ FROM OFFENDER_VISIT_BALANCES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_OIC_SANCTIONS {
DELETE /*+ PARALLEL(OFFENDER_OIC_SANCTIONS) */ FROM OFFENDER_OIC_SANCTIONS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_CONTACT_PERSONS {
DELETE /*+ PARALLEL(OFFENDER_CONTACT_PERSONS) */ FROM OFFENDER_CONTACT_PERSONS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_KEY_WORKERS {
DELETE /*+ PARALLEL(OFFENDER_KEY_WORKERS) */ FROM OFFENDER_KEY_WORKERS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_PHYSICAL_ATTRIBUTES {
DELETE /*+ PARALLEL(OFFENDER_PHYSICAL_ATTRIBUTES) */ FROM OFFENDER_PHYSICAL_ATTRIBUTES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_IND_SCHEDULES {
DELETE /*+ PARALLEL(OFFENDER_IND_SCHEDULES) */ FROM OFFENDER_IND_SCHEDULES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_SENT_CALCULATIONS {
DELETE /*+ PARALLEL(OFFENDER_SENT_CALCULATIONS) */ FROM OFFENDER_SENT_CALCULATIONS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_COURT_EVENTS {
DELETE /*+ PARALLEL(COURT_EVENTS) */ FROM COURT_EVENTS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_CHARGES {
DELETE /*+ PARALLEL(OFFENDER_CHARGES) */ FROM OFFENDER_CHARGES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_SENTENCE_TERMS {
DELETE /*+ PARALLEL(OFFENDER_SENTENCE_TERMS) */ FROM OFFENDER_SENTENCE_TERMS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_SENTENCES {
DELETE /*+ PARALLEL(OFFENDER_SENTENCES) */ FROM OFFENDER_SENTENCES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_ORDERS {
DELETE /*+ PARALLEL(ORDERS) */ FROM ORDERS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_CASES {
DELETE /*+ PARALLEL(OFFENDER_CASES) */ FROM OFFENDER_CASES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_RELEASE_DETAILS {
DELETE /*+ PARALLEL(OFFENDER_RELEASE_DETAILS) */ FROM OFFENDER_RELEASE_DETAILS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_ALERTS {
DELETE /*+ PARALLEL(OFFENDER_ALERTS) */ FROM OFFENDER_ALERTS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_CASE_NOTES {
DELETE /*+ PARALLEL(OFFENDER_CASE_NOTES) */ FROM OFFENDER_CASE_NOTES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_ASSESSMENTS {
DELETE /*+ PARALLEL(OFFENDER_ASSESSMENTS) */ FROM OFFENDER_ASSESSMENTS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_PROFILE_DETAILS {
DELETE /*+ PARALLEL(OFFENDER_PROFILE_DETAILS) */ FROM OFFENDER_PROFILE_DETAILS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_KEY_DATE_ADJUSTS {
DELETE /*+ PARALLEL(OFFENDER_KEY_DATE_ADJUSTS) */ FROM OFFENDER_KEY_DATE_ADJUSTS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_BED_ASSIGNMENT_HISTORIES {
DELETE /*+ PARALLEL(BED_ASSIGNMENT_HISTORIES) */ FROM BED_ASSIGNMENT_HISTORIES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_IMPRISON_STATUSES {
DELETE /*+ PARALLEL(OFFENDER_IMPRISON_STATUSES) */ FROM OFFENDER_IMPRISON_STATUSES WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_IEP_LEVELS {
DELETE /*+ PARALLEL(OFFENDER_IEP_LEVELS) */ FROM OFFENDER_IEP_LEVELS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_EXTERNAL_MOVEMENTS {
DELETE /*+ PARALLEL(OFFENDER_EXTERNAL_MOVEMENTS) */ FROM OFFENDER_EXTERNAL_MOVEMENTS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_PRG_OBLIGATIONS {
DELETE /*+ PARALLEL(OFFENDER_PRG_OBLIGATIONS) */ FROM OFFENDER_PRG_OBLIGATIONS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_BOOKING_DETAILS {
DELETE /*+ PARALLEL(OFFENDER_BOOKING_DETAILS) */ FROM OFFENDER_BOOKING_DETAILS WHERE OFFENDER_BOOK_ID = :bookId
}

DELETE_OFFENDER_TRANSACTIONS {
DELETE /*+ PARALLEL(OFFENDER_TRANSACTIONS) */ FROM OFFENDER_TRANSACTIONS WHERE OFFENDER_ID = :offenderId
}

DELETE_GL_TRANSACTIONS {
DELETE /*+ PARALLEL(GL_TRANSACTIONS) */ FROM GL_TRANSACTIONS WHERE OFFENDER_ID = :offenderId
}

DELETE_OFFENDER_TRUST_ACCOUNTS {
DELETE /*+ PARALLEL(OFFENDER_TRUST_ACCOUNTS) */ FROM OFFENDER_TRUST_ACCOUNTS WHERE OFFENDER_ID = :offenderId
}

DELETE_OFFENDER_SUB_ACCOUNTS {
DELETE /*+ PARALLEL(OFFENDER_SUB_ACCOUNTS) */ FROM OFFENDER_SUB_ACCOUNTS WHERE OFFENDER_ID = :offenderId
}

DELETE_OFFENDER_IDENTIFIERS {
DELETE /*+ PARALLEL(OFFENDER_IDENTIFIERS) */ FROM OFFENDER_IDENTIFIERS WHERE OFFENDER_ID = :offenderId
}

DELETE_OFFENDER_BOOKINGS {
DELETE /*+ PARALLEL(OFFENDER_BOOKINGS) */ FROM OFFENDER_BOOKINGS WHERE OFFENDER_ID = :offenderId
}

DELETE_OFFENDER {
DELETE /*+ PARALLEL(OFFENDERS) */ FROM OFFENDERS WHERE OFFENDER_ID = :offenderId OR ALIAS_OFFENDER_ID = :offenderId
}
