package uk.gov.justice.hmpps.prison.api.model
import java.time.LocalDateTime
data class MovementSummaryDto(
  var offenderNo: String? = null,
  var createDateTime: LocalDateTime? = null,
  var eventId: Long? = null,
  var fromAgency: String? = null,
  var fromAgencyDescription: String? = null,
  var toAgency: String? = null,
  var toAgencyDescription: String? = null,
  var fromCity: String? = null,
  var toCity: String? = null,
  var arrestAgencyLocId: String? = null,
  var internalScheduleType: String? = null,
  var internalScheduleReasonCode: String? = null,
  var toProvStatCode: String? = null,
  var escortCode: String? = null,
  var escortText: String? = null,
  var movementType: String? = null,
  var movementTypeDescription: String? = null,
  var directionCode: String? = null,
  var movementTime: LocalDateTime? = null,
  var movementReason: String? = null,
  var commentText: String? = null,
) {
  fun toMovementSummary() = MovementSummary(
    this.offenderNo,
    this.createDateTime,
    this.eventId,
    this.fromAgency,
    this.fromAgencyDescription,
    this.toAgency,
    this.toAgencyDescription,
    this.fromCity,
    this.toCity,
    this.arrestAgencyLocId,
    this.internalScheduleType,
    this.internalScheduleReasonCode,
    this.toProvStatCode,
    this.escortCode,
    this.escortText,
    this.movementType,
    this.movementTypeDescription,
    this.directionCode,
    this.movementTime,
    this.movementReason,
    this.commentText,
  )
}
