package uk.gov.justice.hmpps.prison.api.model
import java.time.LocalDateTime
data class MovementSummaryDto(
  val offenderNo: String?,
  val createDateTime: LocalDateTime?,
  val eventId: Long?,
  val fromAgency: String?,
  val fromAgencyDescription: String?,
  val toAgency: String?,
  val toAgencyDescription: String?,
  val fromCity: String?,
  val toCity: String?,
  val arrestAgencyLocId: String?,
  val internalScheduleType: String?,
  val internalScheduleReasonCode: String?,
  val toProvStatCode: String?,
  val escortCode: String?,
  val escortText: String?,
  val movementType: String?,
  val movementTypeDescription: String?,
  val directionCode: String?,
  val movementTime: LocalDateTime?,
  val movementReason: String?,
  val commentText: String?,
) {
  fun toMovementSummary() = MovementSummary(
    this.offenderNo,
    this.createDateTime,
    this.eventId,
    this.fromAgency,
    this.fromAgencyDescription,
    this.toAgency,
    this.toAgencyDescription,
    this.fromCity,
    this.toCity,
    this.arrestAgencyLocId,
    this.internalScheduleType,
    this.internalScheduleReasonCode,
    this.toProvStatCode,
    this.escortCode,
    this.escortText,
    this.movementType,
    this.movementTypeDescription,
    this.directionCode,
    this.movementTime,
    this.movementReason,
    this.commentText,
  )
}
