package uk.gov.justice.hmpps.prison.api.model
import java.time.LocalDate

data class PrisonerDetailDto(
  val offenderNo: String?,
  val title: String?,
  val suffix: String?,
  val firstName: String?,
  val middleNames: String?,
  val lastName: String?,
  val dateOfBirth: LocalDate?,
  val gender: String?,
  val sexCode: String?,
  val nationalities: String?,
  val currentlyInPrison: String?,
  val latestBookingId: Long?,
  val latestLocationId: String?,
  val latestLocation: String?,
  val internalLocation: String?,
  val pncNumber: String?,
  val croNumber: String?,
  val ethnicity: String?,
  val ethnicityCode: String?,
  val birthCountry: String?,
  val religion: String?,
  val religionCode: String?,
  val convictedStatus: String?,
  val legalStatus: LegalStatus?,
  val bandCode: String?,
  val imprisonmentStatus: String?,
  val imprisonmentStatusDesc: String?,
  val receptionDate: LocalDate?,
  val maritalStatus: String?,
  val currentWorkingFirstName: String?,
  val currentWorkingLastName: String?,
  val currentWorkingBirthDate: LocalDate?,
) {
  fun toPrisonerDetail() = PrisonerDetail(
    this.offenderNo,
    this.title,
    this.suffix,
    this.firstName,
    this.middleNames,
    this.lastName,
    this.dateOfBirth,
    this.gender,
    this.sexCode,
    this.nationalities,
    this.currentlyInPrison,
    this.latestBookingId,
    this.latestLocationId,
    this.latestLocation,
    this.internalLocation,
    this.pncNumber,
    this.croNumber,
    this.ethnicity,
    this.ethnicityCode,
    this.birthCountry,
    this.religion,
    this.religionCode,
    this.convictedStatus,
    this.legalStatus,
    this.bandCode,
    this.imprisonmentStatus,
    this.imprisonmentStatusDesc,
    this.receptionDate,
    this.maritalStatus,
    this.currentWorkingFirstName,
    this.currentWorkingLastName,
    this.currentWorkingBirthDate,
  )
}
