package uk.gov.justice.hmpps.prison.api.model

import java.time.LocalDate
import java.time.LocalDateTime

data class TransferEventDto(
  val offenderNo: String?,
  val createDateTime: LocalDateTime?,
  val eventId: Long?,
  val fromAgency: String?,
  val fromAgencyDescription: String?,
  val toAgency: String?,
  val toAgencyDescription: String?,
  val toCity: String?,
  val eventStatus: String?,
  val eventClass: String?,
  val eventType: String?,
  val eventSubType: String?,
  val eventDate: LocalDate?,
  val startTime: LocalDateTime?,
  val endTime: LocalDateTime?,
  val outcomeReasonCode: String?,
  val judgeName: String?,
  val engagementCode: String?,
  val escortCode: String?,
  val performanceCode: String?,
  val directionCode: String?,
  val bookingActiveFlag: Boolean,
  val bookingInOutStatus: String?,
) {
  fun toTransferEvent() = TransferEvent(
    this.offenderNo,
    this.createDateTime,
    this.eventId,
    this.fromAgency,
    this.fromAgencyDescription,
    this.toAgency,
    this.toAgencyDescription,
    this.toCity,
    this.eventStatus,
    this.eventClass,
    this.eventType,
    this.eventSubType,
    this.eventDate,
    this.startTime,
    this.endTime,
    this.outcomeReasonCode,
    this.judgeName,
    this.engagementCode,
    this.escortCode,
    this.performanceCode,
    this.directionCode,
    this.bookingActiveFlag,
    this.bookingInOutStatus,
  )
}
