package uk.gov.justice.hmpps.prison.api.model
import java.time.LocalDateTime

data class VisitDetailsDto(
  val id: Long?,
  val eventStatus: String?,
  val eventStatusDescription: String?,
  val completionStatus: String?,
  val completionStatusDescription: String?,
  val visitType: String?,
  val visitTypeDescription: String?,
  val leadVisitor: String?,
  val relationship: String?,
  val relationshipDescription: String?,
  val startTime: LocalDateTime?,
  val endTime: LocalDateTime?,
  val location: String?,
  val prison: String?,
  val eventOutcome: String?,
  val eventOutcomeDescription: String?,
  val cancellationReason: String?,
  val cancelReasonDescription: String?,
  val searchType: String?,
  val searchTypeDescription: String?,
) {
  fun toVisitDetails() = VisitDetails(
    this.id,
    this.eventStatus,
    this.eventStatusDescription,
    this.completionStatus,
    this.completionStatusDescription,
    this.visitType,
    this.visitTypeDescription,
    this.leadVisitor,
    this.relationship,
    this.relationshipDescription,
    this.startTime,
    this.endTime,
    this.location,
    this.prison,
    this.eventOutcome,
    this.eventOutcomeDescription,
    false,
    this.cancellationReason,
    this.cancelReasonDescription,
    null,
    this.searchType,
    this.searchTypeDescription,
  )
}
