CREATE TABLE PROFILE_TYPES
(
  PROFILE_TYPE                  VARCHAR(12)   PRIMARY KEY   NOT NULL,
  PROFILE_CATEGORY              VARCHAR(12),
  DESCRIPTION                   VARCHAR(40),
  LIST_SEQ                      INTEGER                     NOT NULL,
  MANDATORY_FLAG                VARCHAR(1)    DEFAULT 'Y'   NOT NULL,
  UPDATED_ALLOWED_FLAG          VARCHAR(1)    DEFAULT 'Y'   NOT NULL,
  CODE_VALUE_TYPE               VARCHAR(12)                 NOT NULL,
  ACTIVE_FLAG                   VARCHAR(1)    DEFAULT 'Y'   NOT NULL,
  EXPIRY_DATE                   DATE,
  MODIFY_USER_ID                VARCHAR(32),
  MODIFIED_DATE                 DATE          DEFAULT now() NOT NULL,
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);
