CREATE SEQUENCE STAFF_ID START WITH 1;
CREATE SEQUENCE INTERNET_ADDRESS_ID START WITH 1;
CREATE SEQUENCE ROLE_ID START WITH 1;
CREATE SEQUENCE OFFENDER_ID START WITH 1;
CREATE SEQUENCE OFFENDER_BOOK_ID START WITH 1;
CREATE SEQUENCE INTERNAL_LOCATION_ID START WITH 1;
CREATE SEQUENCE CASE_NOTE_ID START WITH 1000;