CREATE TABLE OFFENDERS
(
  OFFENDER_ID                   DECIMAL(10, 0),
  OFFENDER_NAME_SEQ             DECIMAL(12, 0),
  ID_SOURCE_CODE                VARCHAR(12),
  LAST_NAME                     VARCHAR(35),
  NAME_TYPE                     VARCHAR(12),
  FIRST_NAME                    VARCHAR(35),
  MIDDLE_NAME                   VARCHAR(35),
  BIRTH_DATE                    DATE,
  SEX_CODE                      VARCHAR(12),
  SUFFIX                        VARCHAR(12),
  LAST_NAME_SOUNDEX             VARCHAR(6),
  BIRTH_PLACE                   VARCHAR(25),
  BIRTH_COUNTRY_CODE            VARCHAR(12),
  CREATE_DATE                   DATE,
  LAST_NAME_KEY                 VARCHAR(35),
  ALIAS_OFFENDER_ID             DECIMAL(10, 0),
  FIRST_NAME_KEY                VARCHAR(35),
  MIDDLE_NAME_KEY               VARCHAR(35),
  OFFENDER_ID_DISPLAY           VARCHAR(10),
  ROOT_OFFENDER_ID              DECIMAL(10, 0),
  CASELOAD_TYPE                 VARCHAR(12),
  MODIFY_USER_ID                VARCHAR(32),
  MODIFY_DATETIME               TIMESTAMP(6),
  ALIAS_NAME_TYPE               VARCHAR(12),
  PARENT_OFFENDER_ID            DECIMAL(10, 0),
  UNIQUE_OBLIGATION_FLAG        VARCHAR(1)  DEFAULT NULL,
  SUSPENDED_FLAG                VARCHAR(1)  DEFAULT NULL,
  SUSPENDED_DATE                DATE,
  RACE_CODE                     VARCHAR(12),
  REMARK_CODE                   VARCHAR(12),
  ADD_INFO_CODE                 VARCHAR(12),
  BIRTH_COUNTY                  VARCHAR(20),
  BIRTH_STATE                   VARCHAR(20),
  MIDDLE_NAME_2                 VARCHAR(35),
  TITLE                         VARCHAR(12),
  AGE                           DECIMAL(3, 0),
  CREATE_USER_ID                VARCHAR(40) DEFAULT USER,
  LAST_NAME_ALPHA_KEY           VARCHAR(1)  DEFAULT NULL,
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  NAME_SEQUENCE                 VARCHAR(12),
  SINGLE_OFFENDER_IDENTITY_ID   VARCHAR(36),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE OFFENDERS ALTER OFFENDER_ID SET NOT NULL;
ALTER TABLE OFFENDERS ALTER ID_SOURCE_CODE SET NOT NULL;
ALTER TABLE OFFENDERS ALTER LAST_NAME SET NOT NULL;
ALTER TABLE OFFENDERS ALTER SEX_CODE SET NOT NULL;
ALTER TABLE OFFENDERS ALTER CREATE_DATE SET NOT NULL;
ALTER TABLE OFFENDERS ALTER LAST_NAME_KEY SET NOT NULL;
ALTER TABLE OFFENDERS ALTER OFFENDER_ID_DISPLAY SET NOT NULL;
ALTER TABLE OFFENDERS ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE OFFENDERS ALTER CREATE_USER_ID SET NOT NULL;
