CREATE TABLE OFFENDER_PHYSICAL_ATTRIBUTES
(
  OFFENDER_BOOK_ID              BIGINT                      NOT NULL,
  ATTRIBUTE_SEQ                 INTEGER                     NOT NULL,
  HEIGHT_FT                     INTEGER,
  HEIGHT_IN                     INTEGER,
  HEIGHT_CM                     INTEGER,
  WEIGHT_LBS                    INTEGER,
  WEIGHT_KG                     INTEGER,
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE OFFENDER_PHYSICAL_ATTRIBUTES ADD PRIMARY KEY (OFFENDER_BOOK_ID, ATTRIBUTE_SEQ);
