CREATE TABLE OFFENDER_BOOKINGS
(
  OFFENDER_BOOK_ID              DECIMAL(10, 0) PRIMARY KEY,
  BOOKING_BEGIN_DATE            DATE,
  BOOKING_END_DATE              DATE,
  BOOKING_NO                    VARCHAR(14),
  OFFENDER_ID                   DECIMAL(10, 0),
  AGY_LOC_ID                    VARCHAR(6),
  LIVING_UNIT_ID                DECIMAL(10, 0),
  DISCLOSURE_FLAG               VARCHAR(1)  DEFAULT 'Y',
  IN_OUT_STATUS                 VARCHAR(12),
  ACTIVE_FLAG                   VARCHAR(1)  DEFAULT 'N',
  BOOKING_STATUS                VARCHAR(12),
  YOUTH_ADULT_CODE              VARCHAR(12),
  FINGER_PRINTED_STAFF_ID       DECIMAL(10, 0),
  SEARCH_STAFF_ID               DECIMAL(10, 0),
  PHOTO_TAKING_STAFF_ID         DECIMAL(10, 0),
  ASSIGNED_STAFF_ID             DECIMAL(10, 0),
  CREATE_AGY_LOC_ID             VARCHAR(6),
  BOOKING_TYPE                  VARCHAR(12),
  BOOKING_CREATED_DATE          DATE,
  ROOT_OFFENDER_ID              DECIMAL(10, 0),
  AGENCY_IML_ID                 DECIMAL(10, 0),
  SERVICE_FEE_FLAG              VARCHAR(1)  DEFAULT 'N',
  EARNED_CREDIT_LEVEL           VARCHAR(12),
  EKSTRAND_CREDIT_LEVEL         VARCHAR(12),
  INTAKE_AGY_LOC_ID             VARCHAR(6),
  ACTIVITY_DATE                 DATE,
  INTAKE_CASELOAD_ID            VARCHAR(6),
  INTAKE_USER_ID                VARCHAR(32),
  CASE_OFFICER_ID               DECIMAL(6, 0),
  CASE_DATE                     DATE,
  CASE_TIME                     DATE,
  COMMUNITY_ACTIVE_FLAG         VARCHAR(1)  DEFAULT 'N',
  CREATE_INTAKE_AGY_LOC_ID      VARCHAR(6),
  COMM_STAFF_ID                 DECIMAL(10, 0),
  COMM_STATUS                   VARCHAR(12),
  COMMUNITY_AGY_LOC_ID          VARCHAR(6),
  NO_COMM_AGY_LOC_ID            DECIMAL(6, 0),
  COMM_STAFF_ROLE               VARCHAR(12),
  AGY_LOC_ID_LIST               VARCHAR(80),
  STATUS_REASON                 VARCHAR(32),
  TOTAL_UNEXCUSED_ABSENCES      DECIMAL(6, 0),
  REQUEST_NAME                  VARCHAR(240),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  RECORD_USER_ID                VARCHAR(30),
  INTAKE_AGY_LOC_ASSIGN_DATE    DATE,
  BOOKING_SEQ                   DECIMAL(6, 0),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

CREATE UNIQUE INDEX OFFENDER_BOOKINGS_PK ON OFFENDER_BOOKINGS (OFFENDER_BOOK_ID);

ALTER TABLE OFFENDER_BOOKINGS ALTER OFFENDER_BOOK_ID SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER BOOKING_BEGIN_DATE SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER OFFENDER_ID SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER DISCLOSURE_FLAG SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER IN_OUT_STATUS SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER YOUTH_ADULT_CODE SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER BOOKING_SEQ SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER CREATE_USER_ID SET NOT NULL;
