CREATE TABLE PROFILE_CODES
(
  PROFILE_TYPE                  VARCHAR(12)                 NOT NULL,
  PROFILE_CODE                  VARCHAR(12)                 NOT NULL,
  DESCRIPTION                   VARCHAR(40),
  LIST_SEQ                      INTEGER                     NOT NULL,
  UPDATE_ALLOWED_FLAG           VARCHAR(1)    DEFAULT 'Y'   NOT NULL,
  ACTIVE_FLAG                   VARCHAR(1)    DEFAULT 'Y'   NOT NULL,
  EXPIRY_DATE                   DATE,
  USER_ID                       VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFIED_DATE                 DATE          DEFAULT now() NOT NULL,
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE PROFILE_CODES ADD PRIMARY KEY (PROFILE_TYPE, PROFILE_CODE);
