CREATE TABLE OFFENDER_PROFILE_DETAILS
(
  OFFENDER_BOOK_ID              DECIMAL(10, 0),
  PROFILE_SEQ                   DECIMAL(6, 0),
  PROFILE_TYPE                  VARCHAR(12),
  PROFILE_CODE                  VARCHAR(40),
  LIST_SEQ                      DECIMAL(6, 0),
  COMMENT_TEXT                  VARCHAR(240),
  CASELOAD_TYPE                 VARCHAR(12),
  MODIFY_USER_ID                VARCHAR(32),
  MODIFY_DATETIME               TIMESTAMP(6),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);