CREATE TABLE OFFENDER_PROFILE_DETAILS
(
  OFFENDER_BOOK_ID              BIGINT                      NOT NULL,
  PROFILE_SEQ                   INTEGER                     NOT NULL,
  PROFILE_TYPE                  VARCHAR(12)                 NOT NULL,
  PROFILE_CODE                  VARCHAR(40),
  LIST_SEQ                      INTEGER                     NOT NULL,
  COMMENT_TEXT                  VARCHAR(240),
  CASELOAD_TYPE                 VARCHAR(12),
  MODIFY_USER_ID                VARCHAR(32),
  MODIFY_DATETIME               TIMESTAMP,
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE OFFENDER_PROFILE_DETAILS ADD PRIMARY KEY (OFFENDER_BOOK_ID, PROFILE_SEQ, PROFILE_TYPE);
ALTER TABLE OFFENDER_PROFILE_DETAILS ADD UNIQUE (OFFENDER_BOOK_ID, PROFILE_TYPE, PROFILE_CODE);
