CREATE TABLE OFFENDER_IDENTIFYING_MARKS
(
  OFFENDER_BOOK_ID              DECIMAL(10, 0),
  ID_MARK_SEQ                   DECIMAL(6, 0),
  BODY_PART_CODE                VARCHAR(12),
  MARK_TYPE                     VARCHAR(12),
  SIDE_CODE                     VARCHAR(12),
  PART_ORIENTATION_CODE         VARCHAR(12),
  COMMENT_TEXT                  VARCHAR(240),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);
