CREATE TABLE OFFENDER_IDENTIFYING_MARKS
(
  OFFENDER_BOOK_ID              BIGINT                      NOT NULL,
  ID_MARK_SEQ                   INTEGER                     NOT NULL,
  BODY_PART_CODE                VARCHAR(12)                 NOT NULL,
  MARK_TYPE                     VARCHAR(12)                 NOT NULL,
  SIDE_CODE                     VARCHAR(12),
  PART_ORIENTATION_CODE         VARCHAR(12),
  COMMENT_TEXT                  VARCHAR(240),
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE OFFENDER_IDENTIFYING_MARKS ADD PRIMARY KEY (OFFENDER_BOOK_ID, ID_MARK_SEQ);
