CREATE TABLE OFFENDER_IMPRISON_STATUSES
(
  OFFENDER_BOOK_ID              BIGINT                      NOT NULL,
  IMPRISON_STATUS_SEQ           INTEGER                     NOT NULL,
  IMPRISONMENT_STATUS           VARCHAR(12)                 NOT NULL,
  EFFECTIVE_DATE                DATE                        NOT NULL,
  EFFECTIVE_TIME                TIMESTAMP,
  EXPIRY_DATE                   TIMESTAMP,
  AGY_LOC_ID                    VARCHAR(6),
  CREATE_DATE                   DATE,
  COMMENT_TEXT                  VARCHAR(240),
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256),
  LATEST_STATUS                 VARCHAR(1)    DEFAULT 'N'
);

ALTER TABLE OFFENDER_IMPRISON_STATUSES ADD PRIMARY KEY (OFFENDER_BOOK_ID, IMPRISON_STATUS_SEQ);
ALTER TABLE OFFENDER_IMPRISON_STATUSES ADD UNIQUE (OFFENDER_BOOK_ID, IMPRISONMENT_STATUS, EFFECTIVE_DATE, EFFECTIVE_TIME, AGY_LOC_ID);
