CREATE TABLE WORKS
(
  WORK_ID                       DECIMAL(10, 0),
  WORKFLOW_TYPE                 VARCHAR(12),
  WORK_TYPE                     VARCHAR(12),
  WORK_SUB_TYPE                 VARCHAR(12),
  MANUAL_CLOSE_FLAG             VARCHAR(1)  DEFAULT 'N',
  MODULE_NAME                   VARCHAR(20),
  ACTIVE_FLAG                   VARCHAR(1)  DEFAULT 'Y',
  EXPIRY_DATE                   DATE,
  CASELOAD_TYPE                 VARCHAR(12),
  MANUAL_SELECT_FLAG            VARCHAR(1)  DEFAULT NULL,
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);
