CREATE TABLE CASELOAD_AGENCY_LOCATIONS
(
  CASELOAD_ID                   VARCHAR(6),
  AGY_LOC_ID                    VARCHAR(6),
  UPDATE_ALLOWED_FLAG           VARCHAR(1)  DEFAULT 'Y',
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE CASELOAD_AGENCY_LOCATIONS ALTER CASELOAD_ID SET NOT NULL;
ALTER TABLE CASELOAD_AGENCY_LOCATIONS ALTER AGY_LOC_ID SET NOT NULL;
ALTER TABLE CASELOAD_AGENCY_LOCATIONS ALTER UPDATE_ALLOWED_FLAG SET NOT NULL;
ALTER TABLE CASELOAD_AGENCY_LOCATIONS ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE CASELOAD_AGENCY_LOCATIONS ALTER CREATE_USER_ID SET NOT NULL;
