CREATE TABLE OFFENDER_IMPRISON_STATUSES
(
  OFFENDER_BOOK_ID              DECIMAL(10, 0)             NOT NULL,
  IMPRISON_STATUS_SEQ           DECIMAL(6, 0)              NOT NULL,
  IMPRISONMENT_STATUS           VARCHAR(12)                NOT NULL,
  EFFECTIVE_DATE                TIMESTAMP(7)               NOT NULL,
  EFFECTIVE_TIME                TIMESTAMP(7),
  EXPIRY_DATE                   TIMESTAMP(7),
  AGY_LOC_ID                    VARCHAR(6),
  CREATE_DATE                   TIMESTAMP(7),
  COMMENT_TEXT                  VARCHAR(240),
  CREATE_DATETIME               TIMESTAMP(9) DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER   NOT NULL,
  MODIFY_DATETIME               TIMESTAMP(9),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(9),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256),
  LATEST_STATUS                 VARCHAR(1) DEFAULT 'N',
  CONSTRAINT OFFENDER_IMPRISON_STATUSES_PK
  PRIMARY KEY (OFFENDER_BOOK_ID, IMPRISON_STATUS_SEQ)
);

CREATE UNIQUE INDEX OFFENDER_IMPRISON_STATUSES_UK1
  ON OFFENDER_IMPRISON_STATUSES (OFFENDER_BOOK_ID, IMPRISONMENT_STATUS, EFFECTIVE_DATE, EFFECTIVE_TIME, AGY_LOC_ID);

CREATE UNIQUE INDEX OFFENDER_IMPRISON_STATUSES_X01
  ON OFFENDER_IMPRISON_STATUSES (OFFENDER_BOOK_ID, LATEST_STATUS);
