CREATE TABLE IMPRISONMENT_STATUSES
(
  IMPRISONMENT_STATUS_ID        DECIMAL(10, 0)             NOT NULL PRIMARY KEY,
  IMPRISONMENT_STATUS           VARCHAR(12)                NOT NULL,
  DESCRIPTION                   VARCHAR(40)                NOT NULL,
  BAND_CODE                     VARCHAR(12)                NOT NULL,
  RANK_VALUE                    DECIMAL(6, 0)              NOT NULL,
  IMPRISONMENT_STATUS_SEQ       DECIMAL(6, 0),
  ACTIVE_FLAG                   VARCHAR(1) DEFAULT 'Y'     NOT NULL,
  EXPIRY_DATE                   TIMESTAMP(7),
  CREATE_DATETIME               TIMESTAMP(9) DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER   NOT NULL,
  MODIFY_DATETIME               TIMESTAMP(9),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(9),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

CREATE UNIQUE INDEX IMPRISONMENT_STATUSES_UK1
  ON IMPRISONMENT_STATUSES (IMPRISONMENT_STATUS, ACTIVE_FLAG, EXPIRY_DATE);

