CREATE TABLE OFFENDER_RELEASE_DETAILS
(
  OFFENDER_BOOK_ID              BIGINT        PRIMARY KEY   NOT NULL,
  RELEASE_DATE                  DATE,
  COMMENT_TEXT                  VARCHAR(240),
  MOVEMENT_TYPE                 VARCHAR(12)                 NOT NULL,
  MOVEMENT_REASON_CODE          VARCHAR(12),
  EVENT_ID                      BIGSERIAL                   NOT NULL,
  EVENT_STATUS                  VARCHAR(12)   DEFAULT 'SCH' NOT NULL,
  APPROVED_RELEASE_DATE         DATE,
  AUTO_RELEASE_DATE             DATE,
  DTO_APPROVED_DATE             DATE,
  DTO_MID_TERM_DATE             DATE,
  VERIFIED_FLAG                 VARCHAR(1)    DEFAULT 'N',
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE OFFENDER_RELEASE_DETAILS ADD UNIQUE (OFFENDER_BOOK_ID, RELEASE_DATE, AUTO_RELEASE_DATE);
