CREATE TABLE OFFENDER_CASE_NOTES
(
  CASE_NOTE_ID                  BIGSERIAL     PRIMARY KEY   NOT NULL,
  OFFENDER_BOOK_ID              BIGINT                      NOT NULL,
  CONTACT_DATE                  DATE                        NOT NULL,
  CONTACT_TIME                  TIMESTAMP                   NOT NULL,
  CASE_NOTE_TYPE                VARCHAR(12)                 NOT NULL,
  CASE_NOTE_SUB_TYPE            VARCHAR(12)                 NOT NULL,
  STAFF_ID                      BIGINT                      NOT NULL,
  CASE_NOTE_TEXT                VARCHAR(4000),
  AMENDMENT_FLAG                VARCHAR(1)    DEFAULT 'N'   NOT NULL,
  IWP_FLAG                      VARCHAR(1)    DEFAULT 'N'   NOT NULL,
  CHECK_BOX1                    VARCHAR(1)    DEFAULT 'N'   NOT NULL,
  CHECK_BOX2                    VARCHAR(1)    DEFAULT 'N'   NOT NULL,
  CHECK_BOX3                    VARCHAR(1)    DEFAULT 'N'   NOT NULL,
  CHECK_BOX4                    VARCHAR(1)    DEFAULT 'N'   NOT NULL,
  CHECK_BOX5                    VARCHAR(1)    DEFAULT 'N'   NOT NULL,
  EVENT_ID                      BIGINT,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  MODIFY_USER_ID                VARCHAR(32),
  NOTE_SOURCE_CODE              VARCHAR(12),
  DATE_CREATION                 DATE          DEFAULT now(),
  TIME_CREATION                 TIMESTAMP,
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);
