CREATE TABLE CASELOAD_AGENCY_LOCATIONS
(
  CASELOAD_ID                   VARCHAR(6)                  NOT NULL,
  AGY_LOC_ID                    VARCHAR(6)                  NOT NULL,
  UPDATE_ALLOWED_FLAG           VARCHAR(1)    DEFAULT 'Y'   NOT NULL,
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE CASELOAD_AGENCY_LOCATIONS ADD PRIMARY KEY (CASELOAD_ID, AGY_LOC_ID);
