CREATE TABLE AGENCY_INTERNAL_LOCATIONS
(
  INTERNAL_LOCATION_ID          DECIMAL(10, 0),
  INTERNAL_LOCATION_CODE        VARCHAR(12),
  AGY_LOC_ID                    VARCHAR(6),
  INTERNAL_LOCATION_TYPE        VARCHAR(12),
  DESCRIPTION                   VARCHAR(240),
  SECURITY_LEVEL_CODE           VARCHAR(12),
  CAPACITY                      DECIMAL(5, 0),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  PARENT_INTERNAL_LOCATION_ID   DECIMAL(10, 0),
  ACTIVE_FLAG                   VARCHAR(1)  DEFAULT 'Y',
  LIST_SEQ                      DECIMAL(6, 0),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  CNA_NO                        DECIMAL(10, 0),
  CERTIFIED_FLAG                VARCHAR(1)  DEFAULT 'N',
  DEACTIVATE_DATE               DATE,
  REACTIVATE_DATE               DATE,
  DEACTIVATE_REASON_CODE        VARCHAR(12),
  COMMENT_TEXT                  VARCHAR(240),
  USER_DESC                     VARCHAR(40),
  ACA_CAP_RATING                DECIMAL(5, 0),
  UNIT_TYPE                     VARCHAR(12),
  OPERATION_CAPACITY            DECIMAL(5, 0),
  NO_OF_OCCUPANT                DECIMAL(10, 0)     DEFAULT 0,
  TRACKING_FLAG                 VARCHAR(1)  DEFAULT 'N',
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

CREATE UNIQUE INDEX AGENCY_INTERNAL_LOCATIONS_UK ON AGENCY_INTERNAL_LOCATIONS (AGY_LOC_ID, DESCRIPTION);

ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER INTERNAL_LOCATION_ID SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER INTERNAL_LOCATION_CODE SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER AGY_LOC_ID SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER INTERNAL_LOCATION_TYPE SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER DESCRIPTION SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER ACTIVE_FLAG SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER CERTIFIED_FLAG SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER TRACKING_FLAG SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER CREATE_USER_ID SET NOT NULL;
