CREATE TABLE OFFENDER_SENTENCE_ADJUSTS
(
	OFFENDER_SENTENCE_ADJUST_ID     DECIMAL(10)                NOT NULL,
	SENTENCE_ADJUST_CODE            VARCHAR(12)                NOT NULL,
	ADJUST_DATE                     DATE,
	ADJUST_DAYS                     DECIMAL(6),
	ADJUST_STATUS                   VARCHAR(12),
	OFFENDER_BOOK_ID                DECIMAL(10)                NOT NULL,
	SENTENCE_SEQ                    DECIMAL(6)                 NOT NULL,
	CREATE_DATETIME                 TIMESTAMP(9) DEFAULT now() NOT NULL,
	CREATE_USER_ID                  VARCHAR(32)  DEFAULT USER  NOT NULL,
	MODIFY_DATETIME                 TIMESTAMP(9),
	MODIFY_USER_ID                  VARCHAR(32),
	OFFENDER_KEY_DATE_ADJUST_ID     DECIMAL(10),
	ADJUST_FROM_DATE                DATE,
	ADJUST_TO_DATE                  DATE,
	COMMENT_TEXT                    VARCHAR(240),
	AUDIT_TIMESTAMP                 TIMESTAMP(9),
	AUDIT_USER_ID                   VARCHAR(32),
	AUDIT_MODULE_NAME               VARCHAR(65),
	AUDIT_CLIENT_USER_ID            VARCHAR(64),
	AUDIT_CLIENT_IP_ADDRESS         VARCHAR(39),
	AUDIT_CLIENT_WORKSTATION_NAME   VARCHAR(64),
	AUDIT_ADDITIONAL_INFO           VARCHAR(256),
	ACTIVE_FLAG                     VARCHAR(1)   DEFAULT 'Y'   NOT NULL,
	CONSTRAINT OFFENDER_SENTENCE_ADJUSTS_PK
		PRIMARY KEY (OFFENDER_SENTENCE_ADJUST_ID)
)