CREATE TABLE STAFF_USER_ACCOUNTS
(
  USERNAME                      VARCHAR(30)   PRIMARY KEY   NOT NULL,
  STAFF_ID                      BIGINT                      NOT NULL,
  STAFF_USER_TYPE               VARCHAR(12)                 NOT NULL,
  ID_SOURCE                     VARCHAR(12)                 NOT NULL,
  WORKING_CASELOAD_ID           VARCHAR(6),
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE STAFF_USER_ACCOUNTS ADD UNIQUE (STAFF_ID, STAFF_USER_TYPE);
