CREATE TABLE OFFENDER_CONTACT_PERSONS
( OFFENDER_BOOK_ID BIGINT NOT NULL,                       --OFFENDER_BOOK_ID IS 'System generated identifier for an offender booking.';
  PERSON_ID BIGINT,                                       --PERSON_ID IS 'System generated identider for a person.';
  CONTACT_TYPE VARCHAR(12) NOT NULL,                      --CONTACT_TYPE IS 'The contact type with offender ie. Emergency, Professional..';
  RELATIONSHIP_TYPE VARCHAR(12) NOT NULL,                 --RELATIONSHIP_TYPE IS 'The relationship with offender ie. Friend, Wife, Brother..';
  APPROVED_VISITOR_FLAG VARCHAR(1) DEFAULT 'N',           --APPROVED_VISITOR_FLAG IS 'Is this person an approved visitor?';
  CASELOAD_TYPE VARCHAR(12),                              --CASELOAD_TYPE IS 'Caseload Type';
  MODIFY_DATETIME TIMESTAMP,                              --MODIFY_DATETIME IS 'The timestamp when the record is modified ';
  MODIFY_USER_ID VARCHAR(32),                             --MODIFY_USER_ID IS 'The user who modifies the record';
  COMMENT_TEXT VARCHAR(240),                              --COMMENT_TEXT IS 'Comment Text';
  CASE_INFO_NUMBER VARCHAR(60),                           --CASE_INFO_NUMBER IS 'Case Info Number';
  AWARE_OF_CHARGES_FLAG VARCHAR(1) DEFAULT 'N',           --AWARE_OF_CHARGES_FLAG IS 'Is the person aware of theges';
  CAN_BE_CONTACTED_FLAG VARCHAR(1) DEFAULT 'N',           --CAN_BE_CONTACTED_FLAG IS 'Can be contacted ?';
  CREATE_DATETIME TIMESTAMP NOT NULL DEFAULT now(),       --CREATE_DATETIME IS 'The timestamp when the record is created';
  CREATE_USER_ID VARCHAR(32) NOT NULL DEFAULT USER,       --CREATE_USER_ID IS 'The user who creates the record';
  EMERGENCY_CONTACT_FLAG VARCHAR(1) NOT NULL DEFAULT 'N', --EMERGENCY_CONTACT_FLAG IS 'Is the person emergency contact';
  NEXT_OF_KIN_FLAG VARCHAR(1) NOT NULL DEFAULT 'N',       --NEXT_OF_KIN_FLAG IS 'Is the person next of Kin';
  ACTIVE_FLAG VARCHAR(1) NOT NULL DEFAULT 'N',            --ACTIVE_FLAG IS 'Is it a active record';
  EXPIRY_DATE DATE,                                       --EXPIRY_DATE IS 'Expiry date for the data';
  OFFENDER_CONTACT_PERSON_ID BIGINT PRIMARY KEY,
  CONTACT_ROOT_OFFENDER_ID BIGINT,
  AUDIT_TIMESTAMP TIMESTAMP,
  AUDIT_USER_ID VARCHAR(32),
  AUDIT_MODULE_NAME VARCHAR(65),
  AUDIT_CLIENT_USER_ID VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO VARCHAR(256)
);

CREATE INDEX OFF_CP_CONT_PT_F1 ON OFFENDER_CONTACT_PERSONS (CONTACT_TYPE, RELATIONSHIP_TYPE);
CREATE INDEX OFFENDER_CONTACT_PERSONS_NI1 ON OFFENDER_CONTACT_PERSONS (PERSON_ID);
CREATE INDEX OFFENDER_CONTACT_PERSONS_NI2 ON OFFENDER_CONTACT_PERSONS (OFFENDER_BOOK_ID);
CREATE INDEX OFFENDER_CONTACT_PERSONS_NI3 ON OFFENDER_CONTACT_PERSONS (CONTACT_ROOT_OFFENDER_ID);
ALTER TABLE OFFENDER_CONTACT_PERSONS ADD UNIQUE (OFFENDER_BOOK_ID, CONTACT_TYPE, RELATIONSHIP_TYPE, PERSON_ID, CONTACT_ROOT_OFFENDER_ID);
