
CREATE TABLE OFFENDER_SUB_ACCOUNTS
(	CASELOAD_ID VARCHAR(6) NOT NULL,
	OFFENDER_ID BIGINT NOT NULL,
	TRUST_ACCOUNT_CODE INTEGER NOT NULL,
	BALANCE DECIMAL(11,2),
	MINIMUM_BALANCE DECIMAL(11,2),
	HOLD_BALANCE DECIMAL(11,2),
	LAST_TXN_ID BIGINT,
	MODIFY_DATE DATE NOT NULL,
	MODIFY_USER_ID VARCHAR(32),
	LIST_SEQ INTEGER DEFAULT 99,
	IND_DATE DATE,
	IND_DAYS INTEGER,
	CREATE_DATETIME TIMESTAMP DEFAULT now() NOT NULL,
	CREATE_USER_ID VARCHAR(32) DEFAULT USER NOT NULL,
	MODIFY_DATETIME TIMESTAMP,
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR(32),
	AUDIT_MODULE_NAME VARCHAR(65),
	AUDIT_CLIENT_USER_ID VARCHAR(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
	AUDIT_ADDITIONAL_INFO VARCHAR(256)
);

ALTER TABLE OFFENDER_SUB_ACCOUNTS ADD PRIMARY KEY (CASELOAD_ID, OFFENDER_ID, TRUST_ACCOUNT_CODE);
CREATE INDEX OFFENDER_SUB_ACCOUNTS_IX1 ON OFFENDER_SUB_ACCOUNTS (OFFENDER_ID, TRUST_ACCOUNT_CODE);
