CREATE TABLE OFFENDER_KEY_DATE_ADJUSTS
(
	OFFENDER_KEY_DATE_ADJUST_ID     BIGSERIAL   PRIMARY KEY   NOT NULL,
	OFFENDER_BOOK_ID                BIGINT                    NOT NULL,
	SENTENCE_ADJUST_CODE            VARCHAR(12)               NOT NULL,
	ADJUST_FROM_DATE                DATE,
	ADJUST_TO_DATE                  DATE,
	ADJUST_DAYS                     INTEGER,
	ADJUST_STATUS                   VARCHAR(12),
	COMMENT_TEXT                    VARCHAR(240),
	ADJUST_DATE                     DATE,
	CREATE_DATETIME                 TIMESTAMP   DEFAULT NOW() NOT NULL,
	CREATE_USER_ID                  VARCHAR(32) DEFAULT USER  NOT NULL,
	MODIFY_DATETIME                 TIMESTAMP,
	MODIFY_USER_ID                  VARCHAR(32),
	AUDIT_TIMESTAMP                 TIMESTAMP,
	AUDIT_USER_ID                   VARCHAR(32),
	AUDIT_MODULE_NAME               VARCHAR(65),
	AUDIT_CLIENT_USER_ID            VARCHAR(64),
	AUDIT_CLIENT_IP_ADDRESS         VARCHAR(39),
	AUDIT_CLIENT_WORKSTATION_NAME   VARCHAR(64),
	AUDIT_ADDITIONAL_INFO           VARCHAR(256),
	ACTIVE_FLAG                     VARCHAR(1)  DEFAULT 'Y'   NOT NULL
);

--ALTER TABLE OFFENDER_KEY_DATE_ADJUSTS ADD FOREIGN KEY (OFFENDER_BOOK_ID) REFERENCES OFFENDER_BOOKINGS;


CREATE TABLE OFFENDER_SENTENCE_ADJUSTS
(
	OFFENDER_SENTENCE_ADJUST_ID     BIGSERIAL   PRIMARY KEY   NOT NULL,
	SENTENCE_ADJUST_CODE            VARCHAR(12)               NOT NULL,
	ADJUST_DATE                     DATE,
	ADJUST_DAYS                     INTEGER,
	ADJUST_STATUS                   VARCHAR(12),
	OFFENDER_BOOK_ID                BIGINT                    NOT NULL,
	SENTENCE_SEQ                    INTEGER                   NOT NULL,
	CREATE_DATETIME                 TIMESTAMP   DEFAULT now() NOT NULL,
	CREATE_USER_ID                  VARCHAR(32) DEFAULT USER  NOT NULL,
	MODIFY_DATETIME                 TIMESTAMP,
	MODIFY_USER_ID                  VARCHAR(32),
	OFFENDER_KEY_DATE_ADJUST_ID     BIGINT,
	ADJUST_FROM_DATE                DATE,
	ADJUST_TO_DATE                  DATE,
	COMMENT_TEXT                    VARCHAR(240),
	AUDIT_TIMESTAMP                 TIMESTAMP,
	AUDIT_USER_ID                   VARCHAR(32),
	AUDIT_MODULE_NAME               VARCHAR(65),
	AUDIT_CLIENT_USER_ID            VARCHAR(64),
	AUDIT_CLIENT_IP_ADDRESS         VARCHAR(39),
	AUDIT_CLIENT_WORKSTATION_NAME   VARCHAR(64),
	AUDIT_ADDITIONAL_INFO           VARCHAR(256),
	ACTIVE_FLAG                     VARCHAR(1)  DEFAULT 'Y'   NOT NULL
);

--ALTER TABLE OFFENDER_SENTENCE_ADJUSTS ADD FOREIGN KEY (OFFENDER_BOOK_ID) REFERENCES OFFENDER_BOOKINGS;
--ALTER TABLE OFFENDER_SENTENCE_ADJUSTS ADD FOREIGN KEY (OFFENDER_KEY_DATE_ADJUST_ID) REFERENCES OFFENDER_KEY_DATE_ADJUSTS;
--ALTER TABLE OFFENDER_SENTENCE_ADJUSTS ADD FOREIGN KEY (OFFENDER_BOOK_ID, SENTENCE_SEQ) REFERENCES OFFENDER_SENTENCES;
