
CREATE TABLE OFFENDER_SUB_ACCOUNTS 
(	CASELOAD_ID VARCHAR(6) NOT NULL, 
	OFFENDER_ID DECIMAL(10,0) NOT NULL, 
	TRUST_ACCOUNT_CODE DECIMAL(6,0) NOT NULL, 
	BALANCE DECIMAL(11,2), 
	MINIMUM_BALANCE DECIMAL(11,2), 
	HOLD_BALANCE DECIMAL(11,2), 
	LAST_TXN_ID DECIMAL(10,0), 
	MODIFY_DATE DATE NOT NULL, 
	MODIFY_USER_ID VARCHAR(32), 
	LIST_SEQ DECIMAL(6,0) DEFAULT 99, 
	IND_DATE DATE, 
	IND_DAYS DECIMAL(9,0), 
	CREATE_DATETIME TIMESTAMP (9) DEFAULT now() NOT NULL, 
	CREATE_USER_ID VARCHAR(32) DEFAULT USER NOT NULL, 
	MODIFY_DATETIME TIMESTAMP (9), 
	AUDIT_TIMESTAMP TIMESTAMP (9), 
	AUDIT_USER_ID VARCHAR(32), 
	AUDIT_MODULE_NAME VARCHAR(65), 
	AUDIT_CLIENT_USER_ID VARCHAR(64), 
	AUDIT_CLIENT_IP_ADDRESS VARCHAR(39), 
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64), 
	AUDIT_ADDITIONAL_INFO VARCHAR(256)
);

ALTER TABLE OFFENDER_SUB_ACCOUNTS ADD PRIMARY KEY (CASELOAD_ID, OFFENDER_ID, TRUST_ACCOUNT_CODE);
CREATE INDEX OFFENDER_SUB_ACCOUNTS_IX1 ON OFFENDER_SUB_ACCOUNTS (OFFENDER_ID, TRUST_ACCOUNT_CODE);

-- Note there are also triggers for this table
