CREATE TABLE OFFENDER_IDENTIFIERS
(
  OFFENDER_ID                   BIGINT                      NOT NULL,
  OFFENDER_ID_SEQ               BIGINT                      NOT NULL,
  IDENTIFIER_TYPE               VARCHAR(12)                 NOT NULL,
  IDENTIFIER                    VARCHAR(20)                 NOT NULL,
  ISSUED_AUTHORITY_TEXT         VARCHAR(240),
  ISSUED_DATE                   DATE,
  ROOT_OFFENDER_ID              BIGINT,
  CASELOAD_TYPE                 VARCHAR(12),
  MODIFY_USER_ID                VARCHAR(32),
  MODIFY_DATETIME               TIMESTAMP,
  VERIFIED_FLAG                 VARCHAR(1)    DEFAULT 'N',
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE OFFENDER_IDENTIFIERS ADD PRIMARY KEY (OFFENDER_ID, OFFENDER_ID_SEQ);
ALTER TABLE OFFENDER_IDENTIFIERS ADD UNIQUE (ROOT_OFFENDER_ID, IDENTIFIER_TYPE, IDENTIFIER);
ALTER TABLE OFFENDER_IDENTIFIERS ADD CHECK (VERIFIED_FLAG IN ('Y','N'));
