CREATE TABLE OFFENDER_IDENTIFIERS
(
  OFFENDER_ID                   DECIMAL(10, 0)             NOT NULL,
  OFFENDER_ID_SEQ               DECIMAL(10, 0)             NOT NULL,
  IDENTIFIER_TYPE               VARCHAR(12)                NOT NULL,
  IDENTIFIER                    VARCHAR(20)                NOT NULL,
  ISSUED_AUTHORITY_TEXT         VARCHAR(240),
  ISSUED_DATE                   TIMESTAMP(7),
  ROOT_OFFENDER_ID              DECIMAL(10),
  CASELOAD_TYPE                 VARCHAR(12),
  MODIFY_USER_ID                VARCHAR(32),
  MODIFY_DATETIME               TIMESTAMP(9),
  VERIFIED_FLAG                 VARCHAR(1) DEFAULT 'N',
  CREATE_DATETIME               TIMESTAMP(9) DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER   NOT NULL,
  AUDIT_TIMESTAMP               TIMESTAMP(9),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256),
  CONSTRAINT OFFENDER_NAME_IDENTIFIERS_PK
  PRIMARY KEY (OFFENDER_ID, OFFENDER_ID_SEQ)
);

CREATE UNIQUE INDEX OFFENDER_IDENTIFIERS_NI1
  ON OFFENDER_IDENTIFIERS (IDENTIFIER, IDENTIFIER_TYPE);

CREATE UNIQUE INDEX OFFENDER_IDENTIFIERS_UK1
  ON OFFENDER_IDENTIFIERS (ROOT_OFFENDER_ID, IDENTIFIER_TYPE, IDENTIFIER);

CREATE UNIQUE INDEX OFFENDER_IDENTIFIERS_IN2
  ON OFFENDER_IDENTIFIERS (ROOT_OFFENDER_ID);

