CREATE TABLE REFERENCE_DOMAINS
(
	DOMAIN                        VARCHAR(12)                 NOT NULL,
	DESCRIPTION                   VARCHAR(40)                 NOT NULL,
	DOMAIN_STATUS                 VARCHAR(12)                 NOT NULL,
	OWNER_CODE                    VARCHAR(12)                 NOT NULL,
	APPLN_CODE                    VARCHAR(12)                 NOT NULL,
	OLD_CODE_TABLE                VARCHAR(40),
	PARENT_DOMAIN                 VARCHAR(12),
	CODE_LENGTH                   SMALLINT,
	CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
	CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
	MODIFY_DATETIME               TIMESTAMP,
	MODIFY_USER_ID                VARCHAR(32),
	SUPER_SET_DOMAIN              VARCHAR(12),
	AUDIT_TIMESTAMP               TIMESTAMP,
	AUDIT_USER_ID                 VARCHAR(32),
	AUDIT_MODULE_NAME             VARCHAR(65),
	AUDIT_CLIENT_USER_ID          VARCHAR(64),
	AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
	AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE REFERENCE_DOMAINS ADD PRIMARY KEY (DOMAIN);
ALTER TABLE REFERENCE_DOMAINS ADD FOREIGN KEY (PARENT_DOMAIN) REFERENCES REFERENCE_DOMAINS;
ALTER TABLE REFERENCE_DOMAINS ADD FOREIGN KEY (SUPER_SET_DOMAIN) REFERENCES REFERENCE_DOMAINS;


CREATE TABLE REFERENCE_CODES
(
  DOMAIN                        VARCHAR(12)                 NOT NULL,
  CODE                          VARCHAR(12)                 NOT NULL,
  DESCRIPTION                   VARCHAR(40)                 NOT NULL,
  LIST_SEQ                      INTEGER,
  ACTIVE_FLAG                   VARCHAR(1)    DEFAULT 'Y'   NOT NULL,
  SYSTEM_DATA_FLAG              VARCHAR(1)    DEFAULT 'Y'   NOT NULL,
  MODIFY_USER_ID                VARCHAR(32),
  EXPIRED_DATE                  DATE,
  NEW_CODE                      VARCHAR(12),
  PARENT_CODE                   VARCHAR(12),
  PARENT_DOMAIN                 VARCHAR(12),
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT user  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE REFERENCE_CODES ADD PRIMARY KEY (DOMAIN, CODE);
ALTER TABLE REFERENCE_CODES ADD UNIQUE (DOMAIN, CODE, DESCRIPTION, ACTIVE_FLAG);
ALTER TABLE REFERENCE_CODES ADD FOREIGN KEY (DOMAIN) REFERENCES REFERENCE_DOMAINS;
