CREATE TABLE STAFF_MEMBER_ROLES
(
  STAFF_ID                      DECIMAL(10, 0),
  ROLE_ID                       DECIMAL(10, 0),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  ROLE_CODE                     VARCHAR(30),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

CREATE UNIQUE INDEX STAFF_MEMBER_ROLES_PK ON STAFF_MEMBER_ROLES (ROLE_ID, STAFF_ID);

ALTER TABLE STAFF_MEMBER_ROLES ALTER STAFF_ID SET NOT NULL;
ALTER TABLE STAFF_MEMBER_ROLES ALTER ROLE_ID SET NOT NULL;
ALTER TABLE STAFF_MEMBER_ROLES ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE STAFF_MEMBER_ROLES ALTER CREATE_USER_ID SET NOT NULL;
ALTER TABLE STAFF_MEMBER_ROLES ALTER ROLE_CODE SET NOT NULL;
