CREATE TABLE "OFFENDER_CHARGES"
(
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ,
  "OFFENDER_CHARGE_ID"            NUMBER(10, 0)                     NOT NULL ,
  "STATUTE_CODE"                  VARCHAR2(12 CHAR)                 NOT NULL ,
  "OFFENCE_CODE"                  VARCHAR2(25 CHAR)                 NOT NULL ,
  "NO_OF_OFFENCES"                NUMBER(3, 0),
  "OFFENCE_DATE"                  DATE,
  "OFFENCE_RANGE_DATE"            DATE,
  "PLEA_CODE"                     VARCHAR2(12 CHAR),
  "PROPERTY_VALUE"                NUMBER(10, 2),
  "TOTAL_PROPERTY_VALUE"          NUMBER(10, 2),
  "CJIT_OFFENCE_CODE_1"           VARCHAR2(21 CHAR),
  "CJIT_OFFENCE_CODE_2"           VARCHAR2(8 CHAR),
  "CJIT_OFFENCE_CODE_3"           VARCHAR2(3 CHAR),
  "CHARGE_STATUS"                 VARCHAR2(12 CHAR),
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "RESULT_CODE_1"                 VARCHAR2(12 CHAR),
  "RESULT_CODE_2"                 VARCHAR2(12 CHAR),
  "RESULT_CODE_1_INDICATOR"       VARCHAR2(12 CHAR),
  "RESULT_CODE_2_INDICATOR"       VARCHAR2(12 CHAR),
  "CASE_ID"                       NUMBER(10, 0)                     NOT NULL ,
  "MOST_SERIOUS_FLAG"             VARCHAR2(1 CHAR) DEFAULT 'N'      NOT NULL ,
  "CHARGE_SEQ"                    NUMBER(6, 0),
  "ORDER_ID"                      NUMBER(10, 0),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  "LIDS_OFFENCE_NUMBER"           NUMBER(6, 0),
  CONSTRAINT "OFFENDER_CHARGES_PK" PRIMARY KEY ("OFFENDER_CHARGE_ID"),
  CONSTRAINT "OFFENDER_CHARGES_FK1" FOREIGN KEY ("RESULT_CODE_1")
  REFERENCES "OFFENCE_RESULT_CODES" ("RESULT_CODE") ,
  CONSTRAINT "OFFENDER_CHARGES_FK2" FOREIGN KEY ("RESULT_CODE_2")
  REFERENCES "OFFENCE_RESULT_CODES" ("RESULT_CODE") ,
  CONSTRAINT "OFF_CHG_OFF_BKG_FK" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID") ,
  CONSTRAINT "OFF_CHG_OFF_CASE_FK" FOREIGN KEY ("CASE_ID")
  REFERENCES "OFFENDER_CASES" ("CASE_ID") ,
  CONSTRAINT "OFF_CHG_OFN_FK" FOREIGN KEY ("OFFENCE_CODE", "STATUTE_CODE")
  REFERENCES "OFFENCES" ("OFFENCE_CODE", "STATUTE_CODE")
);


COMMENT ON COLUMN "OFFENDER_CHARGES"."OFFENDER_BOOK_ID" IS 'The Offender Book ID';

COMMENT ON COLUMN "OFFENDER_CHARGES"."OFFENDER_CHARGE_ID" IS 'PK The offender charge ID';

COMMENT ON COLUMN "OFFENDER_CHARGES"."STATUTE_CODE" IS 'The Statute Code';

COMMENT ON COLUMN "OFFENDER_CHARGES"."OFFENCE_CODE" IS 'The Offence Code';

COMMENT ON COLUMN "OFFENDER_CHARGES"."NO_OF_OFFENCES" IS 'No of offences';

COMMENT ON COLUMN "OFFENDER_CHARGES"."OFFENCE_DATE" IS 'The date of the offence';

COMMENT ON COLUMN "OFFENDER_CHARGES"."OFFENCE_RANGE_DATE" IS 'The end date of the offence';

COMMENT ON COLUMN "OFFENDER_CHARGES"."PLEA_CODE" IS 'The plea.  Reference Code(PLEA_STATUS)';

COMMENT ON COLUMN "OFFENDER_CHARGES"."PROPERTY_VALUE" IS 'The value of the property of the offence';

COMMENT ON COLUMN "OFFENDER_CHARGES"."TOTAL_PROPERTY_VALUE" IS 'The total value of the property of the offence';

COMMENT ON COLUMN "OFFENDER_CHARGES"."CJIT_OFFENCE_CODE_1" IS 'CJIT Code 1';

COMMENT ON COLUMN "OFFENDER_CHARGES"."CJIT_OFFENCE_CODE_2" IS 'CJIT Code 2';

COMMENT ON COLUMN "OFFENDER_CHARGES"."CJIT_OFFENCE_CODE_3" IS 'CJIT Code 3';

COMMENT ON COLUMN "OFFENDER_CHARGES"."CHARGE_STATUS" IS 'The charge status.  Reference Code(CHARGE_STS)';

COMMENT ON COLUMN "OFFENDER_CHARGES"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "OFFENDER_CHARGES"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "OFFENDER_CHARGES"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "OFFENDER_CHARGES"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "OFFENDER_CHARGES"."RESULT_CODE_1" IS 'The result Code 1of the offender';

COMMENT ON COLUMN "OFFENDER_CHARGES"."RESULT_CODE_2" IS 'The result code 2 of the offender';

COMMENT ON COLUMN "OFFENDER_CHARGES"."RESULT_CODE_1_INDICATOR" IS 'The indicator of the result code 1';

COMMENT ON COLUMN "OFFENDER_CHARGES"."RESULT_CODE_2_INDICATOR" IS 'The indicator of the result code 2';

COMMENT ON COLUMN "OFFENDER_CHARGES"."CASE_ID" IS 'The Offender Cases';

COMMENT ON COLUMN "OFFENDER_CHARGES"."MOST_SERIOUS_FLAG" IS '?The most serious offence out of all offences';

COMMENT ON TABLE "OFFENDER_CHARGES" IS 'The offences charged ';


CREATE INDEX "OFFENDER_CHARGES_FK1"
  ON "OFFENDER_CHARGES" ("RESULT_CODE_1");


CREATE INDEX "OFFENDER_CHARGES_FK2"
  ON "OFFENDER_CHARGES" ("RESULT_CODE_2");


CREATE INDEX "OFFENDER_CHARGES_NI1"
  ON "OFFENDER_CHARGES" ("OFFENDER_BOOK_ID");


CREATE INDEX "OFFENDER_CHARGES_NI2"
  ON "OFFENDER_CHARGES" ("CJIT_OFFENCE_CODE_1", "CJIT_OFFENCE_CODE_2", "CJIT_OFFENCE_CODE_3");


CREATE INDEX "OFFENDER_CHARGES_NI3"
  ON "OFFENDER_CHARGES" ("STATUTE_CODE", "OFFENCE_CODE");


CREATE INDEX "OFF_CHG_OFF_CASE_FK"
  ON "OFFENDER_CHARGES" ("CASE_ID");


CREATE INDEX "OFF_CHG_OFN_FK"
  ON "OFFENDER_CHARGES" ("OFFENCE_CODE", "STATUTE_CODE");

