CREATE TABLE "OFFENDER_COURSE_ATTENDANCES"
(
  "EVENT_ID"                      NUMBER(10, 0),
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                     NOT NULL ,
  "EVENT_DATE"                    DATE                              NOT NULL ,
  "START_TIME"                    DATE,
  "END_TIME"                      DATE,
  "EVENT_SUB_TYPE"                VARCHAR2(12 CHAR)                 NOT NULL ,
  "EVENT_STATUS"                  VARCHAR2(12 CHAR) DEFAULT 'SCH'   NOT NULL ,
  "COMMENT_TEXT"                  VARCHAR2(4000 CHAR),
  "HIDDEN_COMMENT_TEXT"           VARCHAR2(240 CHAR),
  "TO_INTERNAL_LOCATION_ID"       NUMBER(10, 0),
  "CRS_SCH_ID"                    NUMBER(10, 0),
  "OUTCOME_REASON_CODE"           VARCHAR2(12 CHAR),
  "PIECE_WORK"                    NUMBER(11, 2),
  "ENGAGEMENT_CODE"               VARCHAR2(12 CHAR),
  "UNDERSTANDING_CODE"            VARCHAR2(12 CHAR),
  "DETAILS"                       VARCHAR2(40 CHAR),
  "CREDITED_HOURS"                NUMBER(6, 2),
  "AGREED_TRAVEL_HOUR"            NUMBER(6, 2),
  "SUPERVISOR_NAME"               VARCHAR2(30 CHAR),
  "BEHAVIOUR_CODE"                VARCHAR2(12 CHAR),
  "ACTION_CODE"                   VARCHAR2(12 CHAR),
  "SICK_NOTE_RECEIVED_DATE"       DATE,
  "SICK_NOTE_EXPIRY_DATE"         DATE,
  "OFF_PRGREF_ID"                 NUMBER(10, 0),
  "IN_TIME"                       DATE,
  "OUT_TIME"                      DATE,
  "PERFORMANCE_CODE"              VARCHAR2(12 CHAR),
  "REFERENCE_ID"                  NUMBER(20, 0),
  "TO_ADDRESS_OWNER_CLASS"        VARCHAR2(12 CHAR),
  "TO_ADDRESS_ID"                 NUMBER(10, 0),
  "EVENT_OUTCOME"                 VARCHAR2(12 CHAR),
  "OFF_CRS_SCH_REF_ID"            NUMBER(20, 0),
  "SUPERVISOR_STAFF_ID"           NUMBER(10, 0),
  "CRS_APPT_ID"                   NUMBER(20, 0),
  "OFFENDER_COURSE_APPT_RULE_ID"  NUMBER(10, 0),
  "CRS_ACTY_ID"                   NUMBER(10, 0),
  "EVENT_TYPE"                    VARCHAR2(12 CHAR)                 NOT NULL ,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AGY_LOC_ID"                    VARCHAR2(6 CHAR),
  "EVENT_CLASS"                   VARCHAR2(12 CHAR)                 NOT NULL ,
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  "UNEXCUSED_ABSENCE_FLAG"        VARCHAR2(1 CHAR) DEFAULT 'N',
  "TO_AGY_LOC_ID"                 VARCHAR2(6 CHAR),
  "SESSION_NO"                    NUMBER(6, 0),
  "OFFENDER_PRG_OBLIGATION_ID"    NUMBER(10, 0),
  "PROGRAM_ID"                    NUMBER(10, 0),
  "BONUS_PAY"                     NUMBER(11, 3),
  "TXN_ID"                        NUMBER(10, 0),
  "TXN_ENTRY_SEQ"                 NUMBER(6, 0),
  "PAY_FLAG"                      VARCHAR2(1 CHAR) DEFAULT 'N',
  "AUTHORISED_ABSENCE_FLAG"       VARCHAR2(1 CHAR) DEFAULT 'N',
  CONSTRAINT "OFFENDER_COURSE_ATTENDANCES_C1" CHECK (EVENT_CLASS IN ('INT_MOV', 'COMM', 'EXT_MOV')) ,
  CONSTRAINT "OFFENDER_COURSE_ATTENDANCES_PK" PRIMARY KEY ("EVENT_ID"),
  CONSTRAINT "OFF_CRS_ATTD_OFF_BKG_FK" FOREIGN KEY ("OFFENDER_BOOK_ID")
  REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID") ,
  CONSTRAINT "OFF_CRS_ATTD_OFF_PRG_PROF_FK" FOREIGN KEY ("OFF_PRGREF_ID")
  REFERENCES "OFFENDER_PROGRAM_PROFILES" ("OFF_PRGREF_ID") ,
  CONSTRAINT "OFF_CRS_ATT_CRS_ACTY_FK" FOREIGN KEY ("CRS_ACTY_ID")
  REFERENCES "COURSE_ACTIVITIES" ("CRS_ACTY_ID") ,
  CONSTRAINT "OFF_CRS_ATT_OFF_PRG_OB_FK" FOREIGN KEY ("OFFENDER_PRG_OBLIGATION_ID")
  REFERENCES "OFFENDER_PRG_OBLIGATIONS" ("OFFENDER_PRG_OBLIGATION_ID") ,
  CONSTRAINT "OFF_CRS_ATT_PRG_SERV_FK" FOREIGN KEY ("PROGRAM_ID")
  REFERENCES "PROGRAM_SERVICES" ("PROGRAM_ID")   ,
  CONSTRAINT "OFFENDER_COURSE_ATT_FK2" FOREIGN KEY ("TXN_ID", "TXN_ENTRY_SEQ")
  REFERENCES "OFFENDER_TRANSACTIONS" ("TXN_ID", "TXN_ENTRY_SEQ")
);


CREATE INDEX "OFFENDER_COURSE_ATTENDANCES_N1"
  ON "OFFENDER_COURSE_ATTENDANCES" ("REFERENCE_ID");


CREATE INDEX "OFFENDER_COURSE_ATTENDANCES_N3"
  ON "OFFENDER_COURSE_ATTENDANCES" ("CRS_ACTY_ID", "EVENT_DATE");


CREATE INDEX "OFFENDER_COURSE_ATTENDANCES_N4"
  ON "OFFENDER_COURSE_ATTENDANCES" ("CRS_SCH_ID");


CREATE INDEX "OFFENDER_COURSE_ATTENDANCES_N5"
  ON "OFFENDER_COURSE_ATTENDANCES" ("CRS_APPT_ID");


CREATE INDEX "OFFENDER_COURSE_ATTENDANCES_N6"
  ON "OFFENDER_COURSE_ATTENDANCES" ("EVENT_DATE", "PAY_FLAG");


CREATE INDEX "OFFENDER_COURSE_ATTENDANCES_N7"
  ON "OFFENDER_COURSE_ATTENDANCES" ("OFF_PRGREF_ID", "EVENT_OUTCOME");


CREATE INDEX "OFFENDER_COURSE_ATTENDANCES_N8"
  ON "OFFENDER_COURSE_ATTENDANCES" ("OFFENDER_PRG_OBLIGATION_ID");


CREATE INDEX "OFFENDER_COURSE_ATT_FK2"
  ON "OFFENDER_COURSE_ATTENDANCES" ("TXN_ID", "TXN_ENTRY_SEQ");


CREATE INDEX "OFFENDER_COURSE_ATT_NI10"
  ON "OFFENDER_COURSE_ATTENDANCES" ("AGY_LOC_ID", "EVENT_DATE", "TO_INTERNAL_LOCATION_ID");


CREATE INDEX "OFFENDER_CRS_ATTENDANCES_NI9"
  ON "OFFENDER_COURSE_ATTENDANCES" ("OFFENDER_BOOK_ID", "EVENT_DATE", "EVENT_TYPE", "CRS_ACTY_ID", "PAY_FLAG");


CREATE INDEX "OFF_CRS_ATT_PRG_SERV_FK"
  ON "OFFENDER_COURSE_ATTENDANCES" ("PROGRAM_ID");

