CREATE TABLE INTERNET_ADDRESSES
(
  INTERNET_ADDRESS_ID           DECIMAL(10, 0),
  OWNER_CLASS                   VARCHAR(12),
  OWNER_ID                      DECIMAL(10, 0),
  OWNER_SEQ                     DECIMAL(6, 0),
  OWNER_CODE                    VARCHAR(12),
  INTERNET_ADDRESS_CLASS        VARCHAR(12) DEFAULT 'EMAIL',
  INTERNET_ADDRESS              VARCHAR(240),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

CREATE UNIQUE INDEX INTERNET_ADDRESSES_PK ON INTERNET_ADDRESSES (INTERNET_ADDRESS_ID);

ALTER TABLE INTERNET_ADDRESSES ALTER INTERNET_ADDRESS_ID SET NOT NULL;
ALTER TABLE INTERNET_ADDRESSES ALTER OWNER_CLASS SET NOT NULL;
ALTER TABLE INTERNET_ADDRESSES ALTER INTERNET_ADDRESS_CLASS SET NOT NULL;
ALTER TABLE INTERNET_ADDRESSES ALTER INTERNET_ADDRESS SET NOT NULL;
ALTER TABLE INTERNET_ADDRESSES ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE INTERNET_ADDRESSES ALTER CREATE_USER_ID SET NOT NULL;
