CREATE TABLE USER_CASELOAD_ROLES
(
  ROLE_ID                       DECIMAL(10, 0),
  USERNAME                      VARCHAR(30),
  CASELOAD_ID                   VARCHAR(6),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE USER_CASELOAD_ROLES ALTER ROLE_ID SET NOT NULL;
ALTER TABLE USER_CASELOAD_ROLES ALTER USERNAME SET NOT NULL;
ALTER TABLE USER_CASELOAD_ROLES ALTER CASELOAD_ID SET NOT NULL;
ALTER TABLE USER_CASELOAD_ROLES ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE USER_CASELOAD_ROLES ALTER CREATE_USER_ID SET NOT NULL;
