CREATE TABLE "INTERNET_ADDRESSES"
(
  "INTERNET_ADDRESS_ID"           NUMBER(10, 0)                     NOT NULL ,
  "OWNER_CLASS"                   VARCHAR2(12 CHAR)                 NOT NULL ,
  "OWNER_ID"                      NUMBER(10, 0),
  "OWNER_SEQ"                     NUMBER(6, 0),
  "OWNER_CODE"                    VARCHAR2(12 CHAR),
  "INTERNET_ADDRESS_CLASS"        VARCHAR2(12 CHAR) DEFAULT 'EMAIL' NOT NULL ,
  "INTERNET_ADDRESS"              VARCHAR2(240 CHAR)                NOT NULL ,
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "INTERNET_ADDRESSES_PK" PRIMARY KEY ("INTERNET_ADDRESS_ID")
);


COMMENT ON COLUMN "INTERNET_ADDRESSES"."INTERNET_ADDRESS_ID" IS 'PK of the internet addess ID';

COMMENT ON COLUMN "INTERNET_ADDRESSES"."OWNER_CLASS" IS 'Ref Domain (OWNER_CLASS)';

COMMENT ON COLUMN "INTERNET_ADDRESSES"."OWNER_ID" IS 'FK to the Owner ID';

COMMENT ON COLUMN "INTERNET_ADDRESSES"."OWNER_SEQ" IS 'FK to the Owner Seq';

COMMENT ON COLUMN "INTERNET_ADDRESSES"."OWNER_CODE" IS 'FK to the Owner Code';

COMMENT ON COLUMN "INTERNET_ADDRESSES"."INTERNET_ADDRESS_CLASS" IS 'Ref Domain (IADDR_CLASS)';

COMMENT ON COLUMN "INTERNET_ADDRESSES"."INTERNET_ADDRESS" IS 'The internet address';

COMMENT ON COLUMN "INTERNET_ADDRESSES"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "INTERNET_ADDRESSES"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "INTERNET_ADDRESSES"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON COLUMN "INTERNET_ADDRESSES"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON TABLE "INTERNET_ADDRESSES" IS 'Internet Address (i.e. e-mail or URL) details categorised by Internet Address Class (e.g. e-mail). This is a generic entity which can be owned by a number of entities (e.g. Staff Member, Offender, Person).';


CREATE INDEX "INTERNET_ADDRESSES_NI1"
  ON "INTERNET_ADDRESSES" ("OWNER_ID");


CREATE INDEX "INTERNET_ADDRESSES_NI2"
  ON "INTERNET_ADDRESSES" ("OWNER_CODE");


