CREATE TABLE OMS_ROLES
(
  ROLE_ID                       BIGSERIAL     PRIMARY KEY       NOT NULL,
  ROLE_NAME                     VARCHAR(30)                     NOT NULL,
  ROLE_SEQ                      SMALLINT                        NOT NULL,
  CREATE_DATETIME               TIMESTAMP     DEFAULT now()     NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER      NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  MODIFY_USER_ID                VARCHAR(32),
  ROLE_CODE                     VARCHAR(30)                     NOT NULL,
  PARENT_ROLE_CODE              VARCHAR(30),
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256),
  ROLE_TYPE                     VARCHAR(12),
  ROLE_FUNCTION                 VARCHAR(12)   DEFAULT 'GENERAL' NOT NULL,
  SYSTEM_DATA_FLAG              VARCHAR(1)    DEFAULT 'N'       NOT NULL
);

ALTER TABLE OMS_ROLES ADD UNIQUE (ROLE_CODE);
