CREATE TABLE SYSTEM_PROFILES
(
  PROFILE_TYPE                  VARCHAR(12)                 NOT NULL,
  PROFILE_CODE                  VARCHAR(12)                 NOT NULL,
  DESCRIPTION                   VARCHAR(80),
  PROFILE_VALUE                 VARCHAR(40),
  PROFILE_VALUE_2               VARCHAR(12),
  MODIFY_USER_ID                VARCHAR(32),
  OLD_TABLE_NAME                VARCHAR(50),
  CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
  CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE SYSTEM_PROFILES ADD PRIMARY KEY (PROFILE_TYPE, PROFILE_CODE);
