CREATE TABLE OFFENDER_KEY_WORKERS
(
  OFFENDER_BOOK_ID      DECIMAL(10)     NOT NULL,
  OFFICER_ID            DECIMAL(6)      NOT NULL,
  ASSIGNED_DATE         DATE           NOT NULL,
  ASSIGNED_TIME         TIME           NOT NULL,
  USER_ID               VARCHAR(32),
  AGY_LOC_ID            VARCHAR(6),
  ACTIVE_FLAG           VARCHAR (1) DEFAULT 'Y' NOT NULL,
  EXPIRY_DATE           DATE
);


CREATE INDEX OFF_KEY_WORKERS_BOOK_ID_FK
  ON OFFENDER_KEY_WORKERS (OFFENDER_BOOK_ID);

CREATE INDEX OFF_KEY_WORKERS_OFFICER_ID_FK
  ON OFFENDER_KEY_WORKERS (OFFICER_ID);

ALTER TABLE OFFENDER_KEY_WORKERS ADD
  CONSTRAINT OFFENDER_KEY_WORKERS_PK
  PRIMARY KEY (OFFENDER_BOOK_ID, OFFICER_ID, ASSIGNED_DATE, ASSIGNED_TIME);

