CREATE TABLE OFFENDER_KEY_WORKERS
(
  OFFENDER_BOOK_ID              BIGINT                      NOT NULL,
  OFFICER_ID                    INTEGER                     NOT NULL,
  ASSIGNED_DATE                 DATE                        NOT NULL,
  ASSIGNED_TIME                 TIMESTAMP                   NOT NULL,
  USER_ID                       VARCHAR(32)   DEFAULT USER  NOT NULL,
  AGY_LOC_ID                    VARCHAR(6)                  NOT NULL,
  ACTIVE_FLAG                   VARCHAR(1)    DEFAULT 'Y'   NOT NULL,
  EXPIRY_DATE                   TIMESTAMP,
	CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
	CREATE_USER_ID                VARCHAR(32)   DEFAULT USER  NOT NULL,
	MODIFY_DATETIME               TIMESTAMP,
	MODIFY_USER_ID                VARCHAR(32),
	AUDIT_TIMESTAMP               TIMESTAMP,
	AUDIT_USER_ID                 VARCHAR(32),
	AUDIT_MODULE_NAME             VARCHAR(65),
	AUDIT_CLIENT_USER_ID          VARCHAR(64),
	AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
	AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE OFFENDER_KEY_WORKERS ADD PRIMARY KEY (OFFENDER_BOOK_ID, OFFICER_ID, ASSIGNED_DATE, ASSIGNED_TIME);
