CREATE TABLE OFFENDER_EXTERNAL_MOVEMENTS
(
    OFFENDER_BOOK_ID              INTEGER,
    MOVEMENT_SEQ                  INTEGER    DEFAULT 99,
    MOVEMENT_DATE                 DATE,
    MOVEMENT_TIME                 DATE,
    INTERNAL_SCHEDULE_TYPE        VARCHAR(12),
    INTERNAL_SCHEDULE_REASON_CODE VARCHAR(12),
    MOVEMENT_TYPE                 VARCHAR(12),
    MOVEMENT_REASON_CODE          VARCHAR(12),
    DIRECTION_CODE                VARCHAR(12),
    ARREST_AGENCY_LOC_ID          VARCHAR(6),
    TO_PROV_STAT_CODE             VARCHAR(6),
    ESCORT_CODE                   VARCHAR(12),
    FROM_AGY_LOC_ID               VARCHAR(6),
    TO_AGY_LOC_ID                 VARCHAR(6),
    ACTIVE_FLAG                   VARCHAR(1)    DEFAULT 'Y',
    ESCORT_TEXT                   VARCHAR(240),
    COMMENT_TEXT                  VARCHAR(240),
    REPORTING_DATE                DATE,
    TO_CITY                       VARCHAR(12),
    FROM_CITY                     VARCHAR(12),
    REPORTING_TIME                DATE,
	CREATE_DATETIME               TIMESTAMP     DEFAULT now() NOT NULL,
    CREATE_USER_ID                VARCHAR(32)   DEFAULT USER,
    MODIFY_DATETIME               TIMESTAMP,
    MODIFY_USER_ID                VARCHAR(32),
    EVENT_ID                      INTEGER,
    PARENT_EVENT_ID               INTEGER,
    TO_COUNTRY_CODE               VARCHAR(12),
    OJ_LOCATION_CODE              VARCHAR(12),
    APPLICATION_DATE              DATE,
    APPLICATION_TIME              DATE,
    AUDIT_TIMESTAMP               TIMESTAMP,
    AUDIT_USER_ID                 VARCHAR(32),
    AUDIT_MODULE_NAME             VARCHAR(65),
    AUDIT_CLIENT_USER_ID          VARCHAR(64),
    AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
    AUDIT_ADDITIONAL_INFO         VARCHAR(256),
    TO_ADDRESS_ID                 INTEGER,
    FROM_ADDRESS_ID               INTEGER
);
