CREATE TABLE OFFENDER_EXTERNAL_MOVEMENTS (
    OFFENDER_BOOK_ID              BIGINT        NOT NULL,
    MOVEMENT_SEQ                  INTEGER       DEFAULT 99      NOT NULL,
    MOVEMENT_DATE                 DATE,
    MOVEMENT_TIME                 TIMESTAMP,
    INTERNAL_SCHEDULE_TYPE        VARCHAR(12),
    INTERNAL_SCHEDULE_REASON_CODE VARCHAR(12),
    MOVEMENT_TYPE                 VARCHAR(12),
    MOVEMENT_REASON_CODE          VARCHAR(12),
    DIRECTION_CODE                VARCHAR(12),
    ARREST_AGENCY_LOC_ID          VARCHAR(6),
    TO_PROV_STAT_CODE             VARCHAR(6),
    ESCORT_CODE                   VARCHAR(12),
    FROM_AGY_LOC_ID               VARCHAR(6),
    TO_AGY_LOC_ID                 VARCHAR(6),
    ACTIVE_FLAG                   VARCHAR(1)    DEFAULT 'Y'   NOT NULL,
    ESCORT_TEXT                   VARCHAR(240),
    COMMENT_TEXT                  VARCHAR(240),
    REPORTING_DATE                DATE,
    TO_CITY                       VARCHAR(12),
    FROM_CITY                     VARCHAR(12),
    REPORTING_TIME                TIMESTAMP,
    CREATE_DATETIME               TIMESTAMP(9)  DEFAULT now() NOT NULL,
    CREATE_USER_ID                VARCHAR(32)   DEFAULT USER NOT NULL,
    MODIFY_DATETIME               TIMESTAMP(9),
    MODIFY_USER_ID                VARCHAR(32),
    EVENT_ID                      BIGINT,
    PARENT_EVENT_ID               BIGINT,
    TO_COUNTRY_CODE               VARCHAR(12),
    OJ_LOCATION_CODE              VARCHAR(12),
    APPLICATION_DATE              DATE,
    APPLICATION_TIME              TIMESTAMP,
    AUDIT_TIMESTAMP               TIMESTAMP,
    AUDIT_USER_ID                 VARCHAR(32),
    AUDIT_MODULE_NAME             VARCHAR(65),
    AUDIT_CLIENT_USER_ID          VARCHAR(64),
    AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
    AUDIT_ADDITIONAL_INFO         VARCHAR(256),
    TO_ADDRESS_ID                 BIGINT,
    FROM_ADDRESS_ID               BIGINT
);
/*
CREATE UNIQUE INDEX OFFENDER_EXT_MOVEMENTS_NI5
  ON OFFENDER_EXTERNAL_MOVEMENTS (OFFENDER_BOOK_ID, MOVEMENT_DATE, MOVEMENT_TYPE, MOVEMENT_SEQ);

CREATE UNIQUE INDEX OFFENDER_EXT_MOVEMENTS_X01
  ON OFFENDER_EXTERNAL_MOVEMENTS (MOVEMENT_DATE, OFFENDER_BOOK_ID);

CREATE UNIQUE INDEX OFF_EM_INT_SR_F1
  ON OFFENDER_EXTERNAL_MOVEMENTS (INTERNAL_SCHEDULE_TYPE, INTERNAL_SCHEDULE_REASON_CODE);

CREATE UNIQUE INDEX OFF_EM_MOVE_RSN_F1
  ON OFFENDER_EXTERNAL_MOVEMENTS (MOVEMENT_TYPE, MOVEMENT_REASON_CODE);

CREATE UNIQUE INDEX OFFENDER_EXTERNAL_MOVEMENTS_N2
  ON OFFENDER_EXTERNAL_MOVEMENTS (TO_AGY_LOC_ID, MOVEMENT_TYPE, ACTIVE_FLAG);

CREATE UNIQUE INDEX OFFENDER_EXTERNAL_MOVEMENTS_UK
  ON OFFENDER_EXTERNAL_MOVEMENTS (EVENT_ID);
*/