description: Returns the list of Agencies
type:
  get-agencies-list:
    is: [
      orderable: {fieldsList : "agencyId, description"}
    ]
    responseSchemaCollection: AgencyResponse
    responseExampleCollection: !include ../examples/output/agencies-list.sample.json
/{startingWith}:
  description: Returns the list of agencies bye the description "startinWith"
  type:
    get-agencies-list:
      is: [orderable]
      responseSchemaCollection: AgencyResponse
      responseExampleCollection: !include ../examples/output/agencies-list.sample.json
