description: Returns the list of agencies viewable by the user
type: { get-collection: { collectionSchema: inmateSummaries } }
is: [ pageable ]

/inmates:
  description: The collection of inmates within the system.
  get:
    description: Returns the within the system.
