description: Returns the list of locations viewable by the user
type: { get-collection: { collectionSchema: locations } }
is: [ pageable ]

/{locationId}:
  description: Returns details about the specified location
  type: { get-item: { schema: location }}

/{locationId}/movements:
  description: The collection of scheduled movements associated to the inmate.
  type: { get-collection: { collectionSchema: movements } }
  is: [
    orderable: {fieldsList : "moveCategory, moveDateTime, fromAgencyId, toAgencyId, moveType, moveReason, fromLocationId, or toLocation"},
    pageable
  ]

/{locationId}/inmates:
  description: The collection of inmates present at the specified location.
  type: { get-collection: { collectionSchema: inmateSummaries } }
  is: [
    orderable: {fieldsList : "inmateId, bookingId, offenderId, firstName, lastName, alertCodes, agencyId, currentLocationId, or assignedLivingUnitId"},
    pageable
  ]

