INSERT INTO AGENCY_LOCATIONS (AGY_LOC_ID, DESCRIPTION) VALUES ('LEI', 'LEEDS');

INSERT INTO CASELOAD_AGENCY_LOCATIONS (CASELOAD_ID, AGY_LOC_ID) VALUES ('LEI', 'LEI');

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-1, 'A', 'WING', 'LEI', 'LEI-A', null, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-2, '1', 'LAND', 'LEI', 'LEI-A-1', -1, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-3, '1', 'CELL', 'LEI', 'LEI-A-1-1', -2, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-4, '2', 'CELL', 'LEI', 'LEI-A-1-2', -2, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-5, '3', 'CELL', 'LEI', 'LEI-A-1-3', -2, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-6, '4', 'CELL', 'LEI', 'LEI-A-1-4', -2, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-7, '5', 'CELL', 'LEI', 'LEI-A-1-5', -2, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-8, '6', 'CELL', 'LEI', 'LEI-A-1-6', -2, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-9, '7', 'CELL', 'LEI', 'LEI-A-1-7', -2, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-10, '8', 'CELL', 'LEI', 'LEI-A-1-8', -2, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-11, '9', 'CELL', 'LEI', 'LEI-A-1-9', -2, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-12, '10', 'CELL', 'LEI', 'LEI-A-1-10', -2, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-13, 'H', 'WING', 'LEI', 'LEI-H', null, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-14, '1', 'LAND', 'LEI', 'LEI-H-1', -13, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-15, '1', 'CELL', 'LEI', 'LEI-H-1-1', -14, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-16, '2', 'CELL', 'LEI', 'LEI-H-1-2', -14, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-17, '3', 'CELL', 'LEI', 'LEI-H-1-3', -14, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-18, '4', 'CELL', 'LEI', 'LEI-H-1-4', -14, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-19, '5', 'CELL', 'LEI', 'LEI-H-1-5', -14, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-20, '6', 'CELL', 'LEI', 'LEI-H-1-6', -14, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-21, '7', 'CELL', 'LEI', 'LEI-H-1-7', -14, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-22, '8', 'CELL', 'LEI', 'LEI-H-1-8', -14, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-23, '9', 'CELL', 'LEI', 'LEI-H-1-9', -14, 0);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT)
VALUES (-24, '10', 'CELL', 'LEI', 'LEI-H-1-10', -14, 0);
