INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY)
VALUES (-1, 'SEQ', 'ANDERSON', 'M', systimestamp, 'ANDERSON', 'A1234AA');

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ)
VALUES (-1, systimestamp,  'A00111', -1, 'N', 'IN', 'Y', 'N', 'LEI', 1);
