INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY)
VALUES (-1, 'SEQ', 'ANDERSON', 'BORIS', 'ARTHUR', 'M', systimestamp, 'ANDERSON', 'A1234AA');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY)
VALUES (-2, 'SEQ', 'ANDERSON', 'EVE', 'GILLIAN', 'F', systimestamp, 'ANDERSON', 'A1234AB');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY)
VALUES (-3, 'SEQ', 'BATES', 'JOHN', 'NORMAN', 'M', systimestamp, 'BATES', 'A1234AC');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY)
VALUES (-4, 'SEQ', 'CHAPLIN', 'JAMES', 'CHARLES', 'M', systimestamp, 'CHAPLIN', 'A1234AD');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY)
VALUES (-5, 'SEQ', 'DUCK', null, 'DONALD', 'M', systimestamp, 'DUCK', 'A1234AE');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY)
VALUES (-6, 'SEQ', 'ANDREWS', null, 'ANTHONY', 'M', systimestamp, 'ANDREWS', 'A1234AF');

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ)
VALUES (-1, systimestamp,  'A00111', -1, 'N', 'IN', 'Y', 'N', 'LEI', 1);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ)
VALUES (-2, systimestamp,  'A00111', -2, 'N', 'IN', 'Y', 'N', 'LEI', 1);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ)
VALUES (-3, systimestamp,  'A00111', -3, 'N', 'IN', 'Y', 'N', 'LEI', 1);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ)
VALUES (-4, systimestamp,  'A00111', -4, 'N', 'IN', 'Y', 'N', 'LEI', 1);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ)
VALUES (-5, systimestamp,  'A00111', -5, 'N', 'IN', 'Y', 'N', 'LEI', 1);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, BOOKING_SEQ)
VALUES (-6, systimestamp,  'A00111', -6, 'N', 'IN', 'Y', 'N', 'LEI', 1);
