INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'A', 'Social Care', 12, 'Y', 'N', null, null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'C', 'Child Communication Measures', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'H', 'Self Harm', 1, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'L', 'Care Leaver', 11, 'Y', 'N', null, null, null, 'L', null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'M', 'Medical', 5, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'O', 'Other', 10, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'P', 'MAPPP Case', 4, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'R', 'Risk', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'S', 'Sexual Offence', 7, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'T', 'Hold Against Transfer', 8, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'V', 'Vulnerability', 6, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'W', 'Warrant', 9, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'X', 'Security', 2, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'W1', 'White: British', 1, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'W2', 'White: Irish', 1, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'M1', 'Mixed: White and Black Caribbean', 2, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'M2', 'Mixed: White and Black African', 2, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'A1', 'Asian/Asian British: Indian', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'A2', 'Asian/Asian British: Pakistani', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NAME_TYPE', 'A', 'Alias Name', 2, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NAME_TYPE', 'CN', 'Common Name', 1, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NAME_TYPE', 'MAID', 'Maiden Name', 4, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NAME_TYPE', 'NICK', 'Nickname', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NOTE_SOURCE', 'AUTO', 'System', null, 'Y', 'Y', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NOTE_SOURCE', 'COMM', 'Community', null, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NOTE_SOURCE', 'EXT', 'External', null, 'Y', 'Y', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NOTE_SOURCE', 'INST', 'Prison', null, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('SEX', 'F', 'Female', 2, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('SEX', 'M', 'Male', 1, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('SEX', 'NK', 'Not Known / Not Recorded', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('SEX', 'NS', 'Not Specified (Indeterminate)', 4, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('SEX', 'REF', 'Refused', 5, 'Y', 'N', 'OMS_OWNER', null, null, null, null);
