CREATE SEQUENCE INTERNAL_LOCATION_ID START WITH 1 NOCYCLE;

CREATE TABLE AGENCY_LOCATIONS
(
  "AGY_LOC_ID"                    VARCHAR2(6 CHAR),
  "DESCRIPTION"                   VARCHAR2(40 CHAR),
  "AGENCY_LOCATION_TYPE"          VARCHAR2(12 CHAR),
  "DISTRICT_CODE"                 VARCHAR2(12 CHAR),
  "UPDATED_ALLOWED_FLAG"          VARCHAR2(1 CHAR)  DEFAULT 'Y',
  "ABBREVIATION"                  VARCHAR2(12 CHAR),
  "DEACTIVATION_DATE"             DATE,
  "CONTACT_NAME"                  VARCHAR2(40 CHAR),
  "PRINT_QUEUE"                   VARCHAR2(240 CHAR),
  "JURISDICTION_CODE"             VARCHAR2(12 CHAR),
  "BAIL_OFFICE_FLAG"              VARCHAR2(1 CHAR)  DEFAULT 'Y',
  "LIST_SEQ"                      NUMBER(6, 0),
  "HOUSING_LEV_1_CODE"            VARCHAR2(12 CHAR),
  "HOUSING_LEV_2_CODE"            VARCHAR2(12 CHAR),
  "HOUSING_LEV_3_CODE"            VARCHAR2(12 CHAR),
  "HOUSING_LEV_4_CODE"            VARCHAR2(12 CHAR),
  "PROPERTY_LEV_1_CODE"           VARCHAR2(12 CHAR),
  "PROPERTY_LEV_2_CODE"           VARCHAR2(12 CHAR),
  "PROPERTY_LEV_3_CODE"           VARCHAR2(12 CHAR),
  "LAST_BOOKING_NO"               NUMBER(10, 0),
  "COMMISSARY_PRIVILEGE"          VARCHAR2(12 CHAR),
  "BUSINESS_HOURS"                VARCHAR2(40 CHAR),
  "ADDRESS_TYPE"                  VARCHAR2(12 CHAR),
  "SERVICE_REQUIRED_FLAG"         VARCHAR2(1 CHAR)  DEFAULT NULL,
  "ACTIVE_FLAG"                   VARCHAR2(1 CHAR)  DEFAULT NULL,
  "DISABILITY_ACCESS_CODE"        VARCHAR2(12 CHAR),
  "INTAKE_FLAG"                   VARCHAR2(1 CHAR)  DEFAULT NULL,
  "SUB_AREA_CODE"                 VARCHAR2(12 CHAR),
  "AREA_CODE"                     VARCHAR2(12 CHAR),
  "NOMS_REGION_CODE"              VARCHAR2(12 CHAR),
  "GEOGRAPHIC_REGION_CODE"        VARCHAR2(12 CHAR),
  "JUSTICE_AREA_CODE"             VARCHAR2(12 CHAR),
  "CJIT_CODE"                     VARCHAR2(12 CHAR),
  "LONG_DESCRIPTION"              VARCHAR2(3000 CHAR),
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR)
);

ALTER TABLE "AGENCY_LOCATIONS" ALTER "AGY_LOC_ID" SET NOT NULL;
ALTER TABLE "AGENCY_LOCATIONS" ALTER "DESCRIPTION" SET NOT NULL;
ALTER TABLE "AGENCY_LOCATIONS" ALTER "UPDATED_ALLOWED_FLAG" SET NOT NULL;
ALTER TABLE "AGENCY_LOCATIONS" ALTER "BAIL_OFFICE_FLAG" SET NOT NULL;
ALTER TABLE "AGENCY_LOCATIONS" ALTER "CREATE_DATETIME" SET NOT NULL;
ALTER TABLE "AGENCY_LOCATIONS" ALTER "CREATE_USER_ID" SET NOT NULL;


CREATE TABLE AGENCY_INTERNAL_LOCATIONS
(
  "INTERNAL_LOCATION_ID"          NUMBER(10, 0),
  "INTERNAL_LOCATION_CODE"        VARCHAR2(12 CHAR),
  "AGY_LOC_ID"                    VARCHAR2(6 CHAR),
  "INTERNAL_LOCATION_TYPE"        VARCHAR2(12 CHAR),
  "DESCRIPTION"                   VARCHAR2(240 CHAR),
  "SECURITY_LEVEL_CODE"           VARCHAR2(12 CHAR),
  "CAPACITY"                      NUMBER(5, 0),
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "PARENT_INTERNAL_LOCATION_ID"   NUMBER(10, 0),
  "ACTIVE_FLAG"                   VARCHAR2(1 CHAR)  DEFAULT 'Y',
  "LIST_SEQ"                      NUMBER(6, 0),
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "CNA_NO"                        NUMBER(10, 0),
  "CERTIFIED_FLAG"                VARCHAR2(1 CHAR)  DEFAULT 'N',
  "DEACTIVATE_DATE"               DATE,
  "REACTIVATE_DATE"               DATE,
  "DEACTIVATE_REASON_CODE"        VARCHAR2(12 CHAR),
  "COMMENT_TEXT"                  VARCHAR2(240 CHAR),
  "USER_DESC"                     VARCHAR2(40 CHAR),
  "ACA_CAP_RATING"                NUMBER(5, 0),
  "UNIT_TYPE"                     VARCHAR2(12 CHAR),
  "OPERATION_CAPACITY"            NUMBER(5, 0),
  "NO_OF_OCCUPANT"                NUMBER(10, 0)     DEFAULT 0,
  "TRACKING_FLAG"                 VARCHAR2(1 CHAR)  DEFAULT 'N',
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR)
);

CREATE UNIQUE INDEX "AGENCY_INTERNAL_LOCATIONS_UK" ON "AGENCY_INTERNAL_LOCATIONS" ("AGY_LOC_ID", "DESCRIPTION");

ALTER TABLE "AGENCY_INTERNAL_LOCATIONS" ALTER "INTERNAL_LOCATION_ID" SET NOT NULL;
ALTER TABLE "AGENCY_INTERNAL_LOCATIONS" ALTER "INTERNAL_LOCATION_CODE" SET NOT NULL;
ALTER TABLE "AGENCY_INTERNAL_LOCATIONS" ALTER "AGY_LOC_ID" SET NOT NULL;
ALTER TABLE "AGENCY_INTERNAL_LOCATIONS" ALTER "INTERNAL_LOCATION_TYPE" SET NOT NULL;
ALTER TABLE "AGENCY_INTERNAL_LOCATIONS" ALTER "DESCRIPTION" SET NOT NULL;
ALTER TABLE "AGENCY_INTERNAL_LOCATIONS" ALTER "ACTIVE_FLAG" SET NOT NULL;
ALTER TABLE "AGENCY_INTERNAL_LOCATIONS" ALTER "CERTIFIED_FLAG" SET NOT NULL;
ALTER TABLE "AGENCY_INTERNAL_LOCATIONS" ALTER "TRACKING_FLAG" SET NOT NULL;
ALTER TABLE "AGENCY_INTERNAL_LOCATIONS" ALTER "CREATE_DATETIME" SET NOT NULL;
ALTER TABLE "AGENCY_INTERNAL_LOCATIONS" ALTER "CREATE_USER_ID" SET NOT NULL;


CREATE TABLE CASELOAD_AGENCY_LOCATIONS
(
  "CASELOAD_ID"                   VARCHAR2(6 CHAR),
  "AGY_LOC_ID"                    VARCHAR2(6 CHAR),
  "UPDATE_ALLOWED_FLAG"           VARCHAR2(1 CHAR)  DEFAULT 'Y',
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR)
);

ALTER TABLE "CASELOAD_AGENCY_LOCATIONS" ALTER "CASELOAD_ID" SET NOT NULL;
ALTER TABLE "CASELOAD_AGENCY_LOCATIONS" ALTER "AGY_LOC_ID" SET NOT NULL;
ALTER TABLE "CASELOAD_AGENCY_LOCATIONS" ALTER "UPDATE_ALLOWED_FLAG" SET NOT NULL;
ALTER TABLE "CASELOAD_AGENCY_LOCATIONS" ALTER "CREATE_DATETIME" SET NOT NULL;
ALTER TABLE "CASELOAD_AGENCY_LOCATIONS" ALTER "CREATE_USER_ID" SET NOT NULL;
