CREATE TABLE OFFENDER_KEY_WORKERS
(
  OFFENDER_BOOK_ID      NUMBER(10)     NOT NULL,
  OFFICER_ID            NUMBER(6)      NOT NULL,
  ASSIGNED_DATE         DATE           NOT NULL,
  ASSIGNED_TIME         DATE           NOT NULL,
  USER_ID               VARCHAR2(32),
  AGY_LOC_ID            VARCHAR2(6),
  ACTIVE_FLAG           VARCHAR2 (1) DEFAULT 'Y' NOT NULL,
  EXPIRY_DATE           DATE
);


CREATE UNIQUE INDEX OFFENDER_KEY_WORKERS_PK
  ON OFFENDER_KEY_WORKERS (OFFENDER_BOOK_ID, OFFICER_ID, ASSIGNED_DATE, ASSIGNED_TIME);

CREATE INDEX OFF_KEY_WORKERS_BOOK_ID_FK
  ON OFFENDER_KEY_WORKERS (OFFENDER_BOOK_ID);

CREATE INDEX OFF_KEY_WORKERS_OFFICER_ID_FK
  ON OFFENDER_KEY_WORKERS (OFFICER_ID);

ALTER TABLE OFFENDER_KEY_WORKERS ADD
  CONSTRAINT OFFENDER_KEY_WORKERS_PK
  PRIMARY KEY (OFFENDER_BOOK_ID, OFFICER_ID, ASSIGNED_DATE, ASSIGNED_TIME);

-- ALTER TABLE OFFENDER_KEY_WORKERS ADD
--   CONSTRAINT OFF_KEY_WORKERS_BOOK_ID_FK
--   FOREIGN KEY (OFFENDER_BOOK_ID)
--   REFERENCES OFFENDER_BOOKINGS (OFFENDER_BOOK_ID);

-- ALTER TABLE OFFENDER_KEY_WORKERS ADD
--   CONSTRAINT OFF_KEY_WORKERS_OFFICER_ID_FK
--   FOREIGN KEY (OFFICER_ID)
--   REFERENCES STAFF_MEMBERS (STAFF_ID);