#%RAML 1.0 DataType
description: Access Role
properties:
  roleId?:
    type: number
    (javaType): Long
    description: internal role id
    example: 123
  roleCode:
    type: string
    description: unique code for the access role
    example: CUSTODIAL_MGR
  roleName?:
    type: string
    description: name of the access role
    example: Custodial Manager
  parentRoleCode?:
    type: string
    description: role code of the parent role
  roleFunction?:
    type: string
    description: ADMIN or GENERAL
