#%RAML 1.0 DataType
description: Prisoner Account Balance
properties:
  spends:
    type: number
    description: Spends sub account balance.
  cash:
    type: number
    description: Cash sub account balance.
  savings:
    type: number
    description: Saves sub account balance.
