#%RAML 1.0 DataType
description: Prisoner Account Balance
properties:
  spends:
    type: long
    description: Spends sub account balance in pence.
  cash:
    type: long
    description: Cash sub account balance in pence.
  savings:
    type: long
    description: Saves sub account balance in pence.
