#%RAML 1.0 DataType
description: Alert
properties:
  alertId:
    type: number
    (javaType): Long
    description: Alert Id
  alertType:
    type: string
    description: Alert Type
  alertTypeDescription:
    type: string
    description: Alert Type Description
  alertCode:
    type: string
    description: Alert Code
  alertCodeDescription:
    type: string
    description: Alert Code Description
  comment:
    type: string
    description: Alert comments
  dateCreated:
    type: date-only
    description: Date Alert created
  dateExpires?:
    type: date-only
    description: Date the alert expires
  expired:
    type: boolean
    description: True / False indicated expired
  active:
    type: boolean
    description: Status is active
  addedByFirstName?:
    type: string
    description: First name of the user who added the alert
  addedByLastName?:
    type: string
    description: Last name of the user who added the alert
  expiredByFirstName?:
    type: string
    description: First name of the user who expired the alert
  expiredByLastName?:
    type: string
    description: Last name of the user who expired the alert
