#%RAML 1.0 DataType
description: Alias
properties:
  firstName:
    type: string
    description: First name of offender alias
  middleName?:
    type: string
    description: Middle names of offender alias
  lastName:
    type: string
    description: Last name of offender alias
  age:
    type: integer
    description: Age of Offender
  dob:
    type: date-only
    description: Date of Birth of Offender
  gender:
    type: string
    description: Gender
  ethinicity?:
    type: string
    description: Ethnicity
  nameType:
    type: string
    description: Type of Alias
  createDate:
    type: date-only
    description: Date of creation
