#%RAML 1.0 DataType
description: Assessment
properties:
  classification:
    type: string
    description: Classification
  assessmentCode:
    type: string
    description: Assessment Code
  assessmentDesc:
    type: string
    description: Assessment Desc
