#%RAML 1.0 DataType
description: Assessment
properties:
  classification:
    type: string
    description: Classification
  assessmentCode:
    type: string
    description: Assessment Code
  assessmentDescription:
    type: string
    description: Assessment Desc
  cellSharingAlertFlag:
    type: boolean
    description: Cell Sharing Alert Flag
  assessmentDate:
    type: date-only
    description: Assessment Date