#%RAML 1.0 DataType
description: Assigned Living Unit
properties:
  agencyId:
    type: string
    description: Agency Id
  locationId:
    (javaType): Long
    description: location Id
  description:
    type: string
    description: Living Unit Desc
  agencyName:
    type: string
    description: Name of the agency where this living unit resides
