#%RAML 1.0 DataType
description: Adjudication award / sanction
properties:
  sanctionCode:
    type: string
    description: Type of award
  sanctionCodeDescription?:
    type: string
    description: Award type description
  months?:
    type: int
    description: Number of months duration
  days?:
    type: int
    description: Number of days duration
  limit?:
    type: number
    description: Compensation amount
  comment?:
    type: string
    description: Optional details
  effectiveDate:
    type: date-only
    description: Start of sanction
  hearingId:
    type: number
    (javaType): Long
    description: Id of hearing
  hearingSequence:
    type: int
    description: hearing record sequence number
