#%RAML 1.0 DataType
description: Case Note Type Usage Request
properties:
  offenderNos:
    type: string[]
    description: a list of offender numbers to search.
  numMonths?:
    type: integer
    description: Number of month to look forward (if fromDate only defined), or back (if toDate only defined). Default is 1 month
    default: 1
  fromDate?:
    type: date-only
    description: Only case notes occurring on or after this date (in YYYY-MM-DD format) will be considered.  If not defined then the numMonth before the current date, unless a toDate is defined when it will be numMonths before toDate
    example: 2017-06-01
  toDate?:
    type: date-only
    description: Only case notes occurring on or before this date (in YYYY-MM-DD format) will be considered. If not defined then the current date will be used, unless a fromDate is defined when it will be numMonths after fromDate
    example: 2017-09-01
  type?:
    type: string
    description: Case note type.
  subType?:
    type: string
    description: Case note sub-type.