#%RAML 1.0 DataType
description: Case Note Type Staff Usage
properties:
  staffId:
    type: integer
    description: staff ID
  caseNoteType:
    type: string
    description: Case Note Type
  caseNoteSubType:
    type: string
    description: Case Note Sub Type
  numCaseNotes:
    type: integer
    description: Number of case notes of this type/subtype
  latestCaseNote:
    type: datetime
    description: Last case note of this type
