#%RAML 1.0 DataType
description: Case Load
properties:
  caseLoadId:
    type: string
    description: Case Load ID
  description:
    type: string
    description: Full description of the case load
  type:
    type: string
    description: Type of case load
