#%RAML 1.0 DataType
description: Case Note Count Detail
properties:
  bookingId:
    type: number
    (javaType): Long
    description: Offender booking id
    example: 48765
  type:
    type: string
    description: Case note type.
    example: POS
  subType:
    type: string
    description: Case note sub-type.
    example: IEP_ENC
  count:
    type: number
    (javaType): Long
    description: Number of case notes of defined type and subType for offender.
  fromDate?:
    type: date-only
    description: Count includes case notes occurring on or after this date (in YYYY-MM-DD format).
    example: 2017-09-13
  toDate?:
    type: date-only
    description: Count includes case notes occurring on or before this date (in YYYY-MM-DD format).
    example: 2017-11-05