#%RAML 1.0 DataType
description: Custody Status
properties:
  offenderNo:
    type: string
    description: Display Prisoner Number (UK is NOMS ID)
  locationId:
    type: string
    description: Last Known location ID of a prisoner (if in prison)
  custodyStatus:
    type: string
    description: Custody Status
