#%RAML 1.0 DataType
description: Inmate Detail
properties:
  bookingId:
    type: number
    (javaType): Long
    description: Offender Booking Id
  bookingNo:
    type: string
    description: Booking Number
  offenderNo:
    type: string
    description: Offender Unique Reference
  firstName:
    type: string
    description: First Name
  middleName?:
    type: string
    description: Middle Name(s)
  lastName:
    type: string
    description: Last Name
  agencyId:
    type: string
    description: Identifier of agency to which the offender is associated.
  assignedLivingUnitId?:
    type: number
    (javaType): Long
    description: Identifier of living unit (e.g. cell) that offender is assigned to.
  activeFlag:
    type: boolean
    description: Indicates that the offender is currently in prison
  religion?:
    (deprecated): This field is also available in the profileInformation list. It will be removed in a future release.
    type: string
    description: Religion of the prisoner
  language?:
    type: string
    description: The prisoner's preferred spoken language.
  alertsCodes?:
    type: string[]
    description: List of Alerts
  activeAlertCount?:
    type: number
    (javaType): Long
    description: number of active alerts - Full Details Only
  inactiveAlertCount?:
    type: number
    (javaType): Long
    description: number of inactive alerts - Full Details Only
  alerts?:
    type: Alert[]
    description: List of alert details
  assignedLivingUnit?:
    type: AssignedLivingUnit
    description: Where the offender is staying
  facialImageId?:
    type: number
    (javaType): Long
    description: Image Id Ref of Offender
  dateOfBirth:
    type: date-only
    description: Date of Birth of offender
  age?:
    type: integer
    description: Age of offender - Full Details Only
  physicalAttributes?:
    type: PhysicalAttributes
    description: A set of physical attributes
  physicalCharacteristics?:
    type: PhysicalCharacteristic[]
    description: List of physical characteristics
  profileInformation?:
    type: ProfileInformation[]
    description: List of profile information
  physicalMarks?:
    type: PhysicalMark[]
    description: List of physical marks
  assessments?:
    type: Assessment[]
    description: List of assessments
  csra?:
    type: string
    description: CSRA (Latest assessment with cellSharing=true from list of assessments)
  category?:
    type: string
    description: Category (from list of assessments)
  assignedOfficerId?:
    type: number
    (javaType): Long
    description: Staff Id reference for assigned officer / keyworker
