#%RAML 1.0 DataType
description: Inmate Detail
properties:
  bookingId:
    type: number
    (javaType): Long
    description: Offender Booking Id
  bookingNo:
    type: string
    description: Booking Number
  offenderNo:
    type: string
    description: Offender Unique Reference
  firstName:
    type: string
    description: First Name
  middleName?:
    type: string
    description: Middle Name(s)
  lastName:
    type: string
    description: Last Name
  religion?:
    type: string
    description: Religion of the prisoner
  alertsCodes?:
    type: string[]
    description: List of Alerts
  activeAlertCount:
    type: number
    (javaType): Long
    description: number of active alerts
  inactiveAlertCount:
    type: number
    (javaType): Long
    description: number of inactive alerts
  assignedLivingUnit?:
    type: AssignedLivingUnit
    description: Where the offender is staying
  facialImageId?:
    type: number
    (javaType): Long
    description: Image Id Ref of Offender
  dateOfBirth:
    type: date-only
    description: Date of Birth of offender
  age:
    type: integer
    description: Age of offender
  physicalAttributes?:
    type: PhysicalAttributes
    description: A set of physical attributes
  physicalCharacteristics?:
    type: PhysicalCharacteristic[]
    description: List of physical characteristics
  profileInformation?:
    type: ProfileInformation[]
    description: List of profile information
  physicalMarks?:
    type: PhysicalMark[]
    description: List of physical marks
  assessments?:
    type: Assessment[]
    description: List of assessments
  assignedOfficerId?:
    type: number
    (javaType): Long
    description: Staff Id reference for assigned officer / keyworker
