#%RAML 1.0 DataType
description: Keyworker Details
type: StaffDetail
properties:
  numberAllocated:
    type: int
    description: Current number allocated
  agencyId:
    type: string
    description: The keyworker's agency
