#%RAML 1.0 DataType
description: Key worker allocation details
properties:
  bookingId:
    type: number
    (javaType): Long
    description: Offender Booking Id
  offenderNo:
    type: string
    description: Offender Unique Reference
  firstName:
    type: string
    description: First Name
  middleNames?:
    type: string
    description: Middle Name(s)
  lastName:
    type: string
    description: Last Name
  staffId:
    type: number
    (javaType): Long
    description: The key worker's Staff Id
  agencyId:
    type: string
    description: Agency Id
  assigned:
    type: datetime
    description: Date and time of the allocation
    example: 2017-09-13 09:30:00
  internalLocationDesc:
    type: string
    description: Description of the location within the prison
