#%RAML 1.0 DataType
description: Location Details
properties:
  locationId:
    type: number
    (javaType): Long
    description: Location identifier.
  locationType:
    type: string
    description: Location type.
  description:
    type: string
    description: Location description.
  agencyId:
    type: string
    description: Identifier of Agency this location is associated with.
  parentLocationId?:
    type: number
    (javaType): Long
    description: Identifier of this location's parent location.
  currentOccupancy?:
    type: integer
    description: Current occupancy of location.
  locationPrefix?:
    type: string
    description: Location prefix. Defines search prefix that will constrain search to this location and its subordinate locations.
  operationalCapacity?:
    type: integer
    description: Operational capacity of the location.
  userDescription?:
    type: string
    description: User-friendly location description.
