#%RAML 1.0 DataType
description: Primary Offence
properties:
  mainOffenceDescription:
    type: string
    description: Primary Offence details.
  sentenceLength:
    type: string
    description: Length of sentence in days.
  releaseDate:
    type: date-only
    description: Release date.
