#%RAML 1.0 DataType
description: Prisoner Custody Status
properties:
  offenderNo:
    type: string
    description: Display Prisoner Number (UK is NOMS ID)
  createDateTime:
    type: datetime
    description: Timestamp when the external movement record was created
  fromAgency:
    type: string
    description: Agency travelling from
  fromAgencyDescription:
    type:  string
    description: Description of the agency travelling from
  toAgency:
    type: string
    description: Agency travelling to
  toAgencyDescription:
    type: string
    description: Description of the agency travelling to
  movementType:
    type: string
    description: ADM(ission), REL(ease) or TRN(sfer)
  movementTypeDescription:
    type: string
    description: Description of the movement type
  directionCode:
    type: string
    description: IN or OUT
