#%RAML 1.0 DataType
description: New Offender Booking
properties:
  lastName:
    type: string
    description: The offender's first name.
    maxLength: 35
  firstName:
    type: string
    description: The offender's last name.
    maxLength: 35
  middleName1?:
    type: string
    description: The offender's middle name.
    maxLength: 35
  middleName2?:
    type: string
    description: An additional middle name for the offender.
    maxLength: 35
  title?:
    type: string
    description: A code representing the offender's title (from TITLE reference domain).
    maxLength: 12
    example: MR
  suffix?:
    type: string
    description: A code representing a suffix to apply to offender's name (from SUFFIX reference domain).
    maxLength: 12
    example: JR
  dateOfBirth:
    type: string
    description: The offender's date of birth. Must be specified in YYYY-MM-DD format.
    pattern: ^([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))$
    example: 1977-07-27
  gender:
    type: string
    description: A code representing the offender's gender (from the SEX reference domain).
    maxLength: 12
    example: F
  ethnicity?:
    type: string
    description: A code representing the offender's ethnicity (from the ETHNICITY reference domain).
    maxLength: 12
    example: W1
  offenderNo?:
    type: string
    description: A unique offender number. If set, a new booking will be created for an existing offender. If not set,
                 a new offender and new offender booking will be created (subject to de-duplication checks).
    maxLength: 10
    pattern: ^[A-Z]\d{4}[A-Z]{2}$
    example: AG1694A
  pncNumber?:
    type: string
    description: The offender's PNC (Police National Computer) number.
    maxLength: 20
  croNumber?:
    type: string
    description: The offender's CRO (Criminal Records Office) number.
    maxLength: 20
  externalIdentifier?:
    type: string
    description: An external system identifier for the offender or offender booking. This may be useful if the booking
                 is being created by an external system.
    maxLength: 20
  externalIdentifierType?:
    type: string
    description: A code representing the type of external identifier specified in <i>externalIdentifier</> property
                 (from ID_TYPE reference domain).
    maxLength: 12
    example: YJAF