#%RAML 1.0 DataType
description: New Case Note
properties:
  type:
    type: string
    description: Case Note Type
  subType:
    type: string
    description: Case Note Sub Type
  occurrenceDateTime?:
    type: datetime
    description: Date and Time of when case note contact with offender was made
  text:
    type: string
    description: Case Note Text
