#%RAML 1.0 DataType
description: New Case Note
properties:
  type:
    type: string
    description: Case Note Type
    pattern: \w*
    maxLength: 12
  subType:
    type: string
    description: Case Note Sub Type
    pattern: \w*
    maxLength: 12
  occurrenceDateTime?:
    type: datetime
    description: Date and Time of when case note contact with offender was made
  text:
    type: string
    description: Case Note Text
    maxLength: 4000
