#%RAML 1.0 DataType
description: Next of kin
properties:
  lastName:
    type: string
    description: Surname
  firstName:
    type: string
    description: First Name
  middleName?:
    type: string
    description: Middle Names
  contactType:
    type: string
    description: Contact type
  contactTypeDescription?:
    type: string
    description: Contact type text
  relationship:
    type: string
    description: Relationship to inmate
  relationshipDescription?:
    type: string
    description: Relationship text
  emergencyContact:
    type: boolean
    description: Is an emergency contact
