#%RAML 1.0 DataType
description: Offender Relationship
properties:
  personId?:
    (javaType): Long
    type: number
    description: id of the person contact
  externalRef?:
    type: string
    description: unique external Id
  lastName:
    type: string
    description: Surname
  firstName:
    type: string
    description: First Name
  relationshipType:
    type: string
    description: Relationship to inmate (e.g. COM or POM, etc.)
    example: COM
