#%RAML 1.0 DataType
description: Offender Summary
properties:
  bookingId:
    type: number
    (javaType): Long
    description: A unique booking id.
    example: 57493
  offenderNo:
    type: string
    description: The offender's unique offender number (aka NOMS Number in the UK).
    example: A1234AA
  title?:
    type: string
    description: A code representing the offender's title (from TITLE reference domain).
    example: MR
  suffix?:
    type: string
    description: A code representing a suffix that is applied to offender's name (from SUFFIX reference domain).
    example: JR
  firstName:
    type: string
    description: The offender's first name.
  middleNames?:
    type: string
    description: The offender's middle name(s).
  lastName:
    type: string
    description: The offender's last name.
  currentlyInPrison?:
    type: string
    description: Set to Y or N to indicate if the person is currently in prison. If not set, status is not known.
    example: Y
  agencyLocationId?:
    type: string
    description: Agency Id (if known)
    example: LEI
  agencyLocationDesc?:
    type: string
    description: Agency description (if known)
    example: LEEDS (HMP)
  internalLocationId?:
    type: string
    description: Internal location id (if known)
    example: LEI-RECP
  internalLocationDesc?:
    type: string
    description: Internal location description (if known)
    example: Reception