#%RAML 1.0 DataType
description: Offender Identifier
properties:
  type:
    type: string
    description: Type of offender identifier
  value:
    type: string
    description: The value of the offender identifier
  issuedAuthorityText?:
    type: string
    description: Issuing Authority Information
  issuedDate?:
    type: date-only
    description: Date of issue
  caseloadType?:
    type: string
    description: Related caseload type