#%RAML 1.0 DataType
description: Offender Summary
properties:
  bookingId:
    type: number
    (javaType): Long
    description: Offender Booking Id
  offenderNo:
    type: string
    description: Offender Unique Reference
  title?:
    type: string
    description: Title
  suffix?:
    type: string
    description: Suffix
  firstName:
    type: string
    description: First Name
  middleNames?:
    type: string
    description: Middle Name(s)
  lastName:
    type: string
    description: Last Name
  currentlyInPrison:
    type: string
    description: Flag Y to indicate if the person is currently in prison
  agencyLocationId:
    type: string
    description: Agency Id
  agencyLocationDesc:
    type: string
    description: Agency Description
  internalLocationId:
    type: string
    description: Current ID of the location of the offender in the prison
  internalLocationDesc:
    type: string
    description: Description of the location within the prison
  releaseDate?:
    type: date-only
    description: Release date for the offender