#%RAML 1.0 DataType
description: Offender Key Worker record representation (to facilitate data migration)
properties:
  offenderNo:
    type: string
    description: Offender Unique Reference
  staffId:
    type: number
    (javaType): Long
    description: The key worker's Staff Id
  agencyId:
    type: string
    description: Agency Id
  assigned:
    type: datetime
    description: Date and time allocation was assigned
  expired?:
    type: datetime
    description: Date and time allocation expired
  userId:
    type: string
    description: Username of user who processed allocation
  active:
    type: string
    description: 'Y' to indicate allocation is currently active, 'N' to indicate it is not
  created:
    type: datetime
    description: Date and time allocation record was created
  createdBy:
    type: string
    description: Username of user who created allocation record
  modified?:
    type: datetime
    description: Date and time allocation record was last modified
  modifiedBy?:
    type: string
    description: Username of user who last modified allocation record
