#%RAML 1.0 DataType
description: PersonIdentifier
properties:
  identifierType:
    type: string
    description: The identifier type
    example: EXTERNAL_REL
  identifierValue:
    type: string
    description: The most recent identifier value of that type.
    example: DELIUS_USER
