#%RAML 1.0 DataType
description: Physical Attributes
properties:
  gender:
    type: string
    description: Gender
  ethnicity:
    type: string
    description: Ethnicity
  heightInches:
    type: number
    description: Height in Inches
  heightMeters:
    type: number
    description: Height in Metres
  weightPounds:
    type: number
    description: Weight in Pounds
  weightKg:
    type: number
    description: Weight in Kg