#%RAML 1.0 DataType
description: Prisoner Schedule
properties:
  offenderNo:
    type: string
    description: Offender number (e.g. NOMS Number).
  firstName:
    type: string
    description: Offender first name.
  lastName:
    type: string
    description: Offender last name.
  cellLocation:
    type: String
    description: Offender cell.
  event:
    type: string
    description: Event code.
  eventType:
    type: string
    description: Event type, e.g. VISIT, APP, PRISON_ACT
  eventDescription:
    type: string
    description: Description of event code.
  comment?:
    type: string
    description: Details of event
    maxLength: 4000
  startTime:
    type: datetime
    description: Date and time at which event starts
    example: 2017-09-13 09:30:00
  endTime?:
    type: datetime
    description: Date and time at which event ends
    example: 2017-09-13 11:30:00
