#%RAML 1.0 DataType
description: Prisoner Details
properties:
  offenderNo:
    type: string
    description: The prisoner's unique offender number (aka NOMS Number in the UK).
    example: A1234AB
  title?:
    type: string
    description: The prisoner's title.
    example: Mr
  suffix?:
    type: string
    description: The prisoner's name suffix.
    example: Jr
  firstName:
    type: string
    description: The prisoner's first name.
  middleNames?:
    type: string
    description: The prisoner's middle name(s).
  lastName:
    type: string
    description: The prisoner's last name.
  dateOfBirth:
    type: date-only
    description: The prisoner's date of birth (in YYYY-MM-DD format).
    example: 1970-11-02
  gender:
    type: string
    description: The prisoner's gender.
    example: M
  nationalities?:
    type: string
    description: The prisoner's nationality.
    example: British
  currentlyInPrison:
    type: string
    description: Flag (Y or N) to indicate if prisoner is currently in prison.
    example: Y
  latestBookingId?:
    type: number
    (javaType): Long
    description: ID of prisoner's latest booking.
    example: 67433
  latestLocationId?:
    type: string
    description: Latest location ID of a prisoner (if in prison).
    example: LEI
  latestLocation?:
    type: string
    description: Name of the prison where the prisoner resides (if in prison).
    example: LEEDS (HMP)
  internalLocation?:
    type: string
    description: Name of the location where the prisoner resides (if in prison)
    example: LEI-A-1-003
  pncNumber?:
    type: string
    description: The prisoner's PNC (Police National Computer) number.
    example: PNC1338494
  croNumber?:
    type: string
    description: The prisoner's CRO (Criminal Records Office) number.
    example: CRO3332/343
  ethnicity?:
    type: string
    description: The prisoner's ethnicity.
  birthCountry?:
    type: string
    description: The prisoner's country of birth.
  religion?:
    type: string
    description: The prisoner's religion.
  convictedStatus?:
    type: string
    description: Status code of prisoner's latest conviction.
  imprisonmentStatus?:
    type: string
    description: The prisoner's imprisonment status.
  receptionDate?:
    type: date-only
    description: Date prisoner was received into the prison.
  maritalStatus?:
    type: string
    description: The prisoner's marital status.