#%RAML 1.0 DataType
description: Prisoner Custody Status
properties:
  offenderNo:
    type: string
    description: Display Prisoner Number (UK is NOMS ID)
  createDateTime:
    type: datetime
    description: Timestamp when the external movement record was created
