#%RAML 1.0 DataType
description: Scheduled Event
properties:
  bookingId:
    (javaType): Long
    description: Offender booking id.
    example: 48765
  eventType:
    type: string
    description: Type of scheduled event.
    example: Prison Activity
