#%RAML 1.0 DataType
description: Staff Details
properties:
  agencyId:
    type:
    description: Agency at which staff member is performing role.
    example: MDI
  agencyDescription?:
    type:
    description: Agency description.
    example: LEEDS
  role:
    type: string
    description: A code that defines staff member's role at agency.
    example: KW
  roleDescription?:
    type: string
    description: Description of staff member's role at agency.
    example: Key Worker
