#%RAML 1.0 DataType
description: Staff Details
properties:
  staffId:
    type: number
    (javaType): Long
    description: Unique identifier for staff member.
    example: 16745
  firstName:
    type: string
    description: Staff member's first name.
    example: KIRSTY
  lastName:
    type: string
    description: Staff member's last name.
    example: DAVIES
  email?:
    type: string
    description: Staff member's email address.
    example: kirsty.davies@example.com
  thumbnailId?:
    type: number
    (javaType): Long
    description: Identifier for staff member image.
    example: 4768333
