#%RAML 1.0 DataType
description: Telephone Details
properties:
  number:
    type: string
    description: Telephone number
  type:
    type: string
    description: Telephone type
  ext?:
    type: string
    description: Telephone extention number