#%RAML 1.0 DataType
description: Token
properties:
  token:
    type: string
    description: Token for accessing the API
  issuedAt:
    (javaType): Long
    description: Details of the issued time
  expiration:
    (javaType): Long
    description: Unix time until token expiration
  refreshToken:
    type: string
    description: Token that can be used to refresh the JWT
  refreshExpiration:
    (javaType): Long
    description: Unix time until refresh token expiration
