#%RAML 1.0 DataType
description: Attendance details
properties:
  eventOutcome:
    type: string
    description: Attendance outcome, possible values are the codes in the 'PS_PA_OC' reference domain.
    maxLength: 12
  performance?:
    type: string
    description: Possible values are the codes in the 'PERFORMANCE' reference domain, mandatory for eventOutcome 'ATT'.
    maxLength: 12
  outcomeComment?:
    type: string
    description: Free text comment, maximum length 240 characters.
# Real limit as advised by old-nomis dev team:
    maxLength: 240
