#%RAML 1.0 DataType
description: User Role
properties:
  roleId:
    (javaType): Long
    description: Role Id
  roleCode:
    type: string
  roleName:
    type: string
  parentRoleCode?:
    type: string
