#%RAML 1.0 DataType
description: User Details
properties:
  staffId:
    type: number
    (javaType): Long
    description: Staff Id
  username:
    type: string
  firstName:
    type: string
  lastName:
    type: string
  thumbnailId?:
    type: number
    (javaType): Long
  activeCaseLoadId?:
    type: string
  accountStatus:
    type: string
  lockDate:
    type: datetime
  expiryDate:
    type: datetime
  lockedFlag:
    type: boolean
  expiredFlag:
    type: boolean