#%RAML 0.8
title: Elite2 Public API
baseUri: http://api.elite2.syscon.net/{version}
version: v1
securedBy: [jwt]
schemas:
- httpStatus: !include schemas/output/http-status.schema.json
- pageMetaData: !include schemas/output/page-metadata.schema.json
- userDetails: !include schemas/output/user-details.schema.json
- staffDetails: !include schemas/output/staff-details.schema.json
- authLogin: !include schemas/input/auth-login.schema.json
- authToken: !include schemas/input/auth-token.schema.json
- token: !include schemas/output/token.schema.json
- agency: !include schemas/output/agency.schema.json
- agencies: !include schemas/output/agencies.schema.json
- inmateSummary: !include schemas/output/inmate-summary.schema.json
- inmateSummaries: !include schemas/output/inmate-summaries.schema.json
- inmateDetails: !include schemas/output/inmate-details.schema.json
- location: !include schemas/output/location.schema.json
- locations: !include schemas/output/locations.schema.json
- imageSummary: !include schemas/output/image-summary.schema.json
- imageSummaries: !include schemas/output/image-summaries.schema.json
- imageDetails: !include schemas/output/image-details.schema.json
- imageData: !include schemas/output/image-data.schema.json
- updateCaseNote: !include schemas/input/update-case-note.schema.json
- caseNote: !include schemas/output/case-note.schema.json
- newCaseNote: !include schemas/output/new-case-note.schema.json
- caseNotes: !include schemas/output/case-notes.schema.json
- referenceCode: !include schemas/output/reference-code.schema.json
- referenceCodes: !include schemas/output/reference-codes.schema.json
- referenceDomain: !include schemas/output/reference-domain.schema.json
- referenceDomains: !include schemas/output/reference-domains.schema.json
- caseNoteTypes: !include schemas/output/caseNoteTypes.schema.json
- caseNoteSubTypes: !include schemas/output/caseNoteSubTypes.schema.json
- typeSubtypes: !include schemas/output/caseNote-type-subtype.schema.json
- caseLoad: !include schemas/output/case-load.schema.json
- caseLoads: !include schemas/output/case-loads.schema.json
- alert: !include schemas/output/alert.schema.json
- alerts: !include schemas/output/alerts.schema.json
- alias: !include schemas/output/alias.schema.json
- aliases: !include schemas/output/aliases.schema.json


securitySchemes:
- jwt:
    description: Elite API uses Json Web Token (JWT) to authenticate most requests
    type: x-jwt
    describedBy:
      headers:
        Authorization:
          description: Used to send a valid JWT. Do not use  query string parameter.
          type: string
          example: "Authorization: Bearer eyJpc3MiOiJzY290Y2guaW8iLCJleHAiOjEzMDA4MTkzODAsIm5hbWUiOiJDaHJpcyBTZXZpbGxlamEiLCJhZG1pbiI6dHJ1ZX0"

- basic:
    description: Each request must contain the headers necessary for basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password" credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.

resourceTypes: !include resourceTypes/generic-resource-types.raml

traits: !include traits/generic-traits.raml

/users: !include resources/users.raml
/agencies: !include resources/agencies.raml
/booking: !include resources/booking.raml
/locations: !include resources/locations.raml
/images: !include resources/images.raml
/referenceDomains: !include resources/reference-domains.raml
