package net.syscon.elite.service;

import com.tngtech.java.junit.dataprovider.DataProvider;
import com.tngtech.java.junit.dataprovider.DataProviderRunner;
import com.tngtech.java.junit.dataprovider.UseDataProvider;
import net.syscon.elite.api.support.CustodyStatusCode;
import net.syscon.elite.service.support.CustodyStatusDto;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;

/**
 * Test cases for {@link CustodyStatusCalculator}.
 */
@RunWith(DataProviderRunner.class)
public class CustodyStatusCalculatorTest {

    private CustodyStatusCalculator calculator = new CustodyStatusCalculator();

    @DataProvider
    public static Object[][] custodyStatusRecords() {
        return new Object[][] {
        // Booking_status, active_flag, direction, type, reason
                {  "O",     "Y",      null,    null,     null,        CustodyStatusCode.ACTIVE_IN         },
                {  "O",     "Y",     "OUT",   "CRT",     null,        CustodyStatusCode.ACTIVE_OUT_CRT    },
                {  "O",     "Y",     "OUT",   "TAP",     null,        CustodyStatusCode.ACTIVE_OUT_TAP    },
                {  "O",     "N",      null,   "TRN",     null,        CustodyStatusCode.IN_TRANSIT        },
                {   null,    null,    null,   "REL",    "UAL",        CustodyStatusCode.ACTIVE_UAL        }, // Unlawfully at Large
                {   null,    null,    null,   "REL",    "UAL_ECL",    CustodyStatusCode.ACTIVE_UAL_ECL    }, // Early Conditional Release
                {  "O",     "N",     "OUT",   "REL",    "ESCP",       CustodyStatusCode.ACTIVE_ESCP       }, // Escaped
                {   null,    null,    null,   "REL",    "ESCP",       CustodyStatusCode.ACTIVE_ESCP       }, // Escaped
                {   null,    null,    null,   "REL",     null,        CustodyStatusCode.IN_ACTIVE_OUT     },
                {  "C",      "N",     null,    null,     null,        CustodyStatusCode.OTHER             },
                {   null,    null,    null,    null,     null,        CustodyStatusCode.OTHER             },
                {  "O",     "Y",     "IN",    "ADM",    "N",          CustodyStatusCode.ACTIVE_IN         },
                {  "O",     "N",     "OUT",   "TRN",    "NOTR",       CustodyStatusCode.IN_TRANSIT        },
                {  "O",     "Y",     "IN",    "ADM",    "RECA",       CustodyStatusCode.ACTIVE_IN         },
                {  "O",     "Y",     "OUT",   "CRT",    "CRT",        CustodyStatusCode.ACTIVE_OUT_CRT    },
                {  "O",     "Y",     "OUT",   "TAP",    "C6",         CustodyStatusCode.ACTIVE_OUT_TAP    },

        // combinations taken direct from prod dataset

                {  "O",     "Y",     "IN",        "ADM",     "24",           CustodyStatusCode.ACTIVE_IN         },
                {  "O",     "Y",     "IN",        "ADM",     "25",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "26",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "27",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "29",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "A",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "ADMN",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     null,        "ADM",     "ADMN",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "ADM",     "ADMN",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "B",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "C",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "CONR",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "CRT",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "E",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "ELR",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "ETB",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "F",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "G",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "H",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "I",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     null,        "ADM",     "I",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "IMMIG",        CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "INT",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "ADM",     "INT",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "INTER",        CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "J",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "K",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "L",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "ADM",     "L",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "LICR",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "M",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "N",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "O",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "ADM",     "O",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "P",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "Q",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "R",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "ADM",     "R",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "RECA",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "ADM",     "RECA",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "RMND",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "S",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "SENT",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "T",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "TRN",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "TRNCRT",       CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "TRNTAP",       CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "U",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "V",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "W",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "Y",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "ADM",     "Z",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "CRT",     "19",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "19",           CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "22",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "22",           CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "AP",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "AP",           CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "BAIL",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "BAIL",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "BREACH",       CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "BREACH",       CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "CA",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "CA",           CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "OUT",       "CRT",     "CAP",          CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "COM",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "COM",          CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "CRI",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "CRI",          CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "CRT",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "CRT",          CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "OUT",       "CRT",     "CT",           CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "DC",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "DC",           CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "NA",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "NA",           CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "NEWTON",       CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "NEWTON",       CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "PDH",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "PDH",          CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "PR",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "PR",           CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "PS",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "PS",           CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "REM",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "REM",          CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "SEN",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        "CRT",     "SENT",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "SENT",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "TRIAL",        CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "TRIAL",        CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "VL",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "VL",           CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "VLAP",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "VLAP",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "OUT",       "CRT",     "VLBL",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "VLCH",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "VLCH",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "VLCR",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "VLCR",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "VLCV",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "VLCV",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "VLPD",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "VLPD",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "VLPP",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "VLPP",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "VLPR",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "VLPR",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "VLPS",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "VLPS",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        "CRT",     "VLWT",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "CRT",     "VLWT",         CustodyStatusCode.ACTIVE_OUT_CRT             },
                {  "O",     "Y",     "IN",        null,     "ELR",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        null,     "N",             CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "IN",        null,     "TRNCRT",        CustodyStatusCode.ACTIVE_IN             },
                {  "C",     "Y",     "OUT",       "REL",     "99",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "AR",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "AU",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "BD",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "BL",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "CE",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "CR",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "D1",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "D2",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "D3",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "D4",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "D5",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "D6",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "DA",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "DD",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "DE",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "DEC",          CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "DISC",         CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "DL",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "DS",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "ER",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "ESCP",         CustodyStatusCode.ACTIVE_ESCP             },
                {  "C",     "Y",     "OUT",       "REL",     "ETR",          CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "EX",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "HC",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "HD",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "HE",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "HP",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "HR",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "HU",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "IF",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "IN",        "REL",     "MRG",          CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     null,        "REL",     "MRG",          CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "MRG",          CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "NCS",          CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "NG",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "NP",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "PD",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "PF",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "PX",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "RE",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "REL",          CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "RW",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "OUT",       "REL",     "SC",           CustodyStatusCode.IN_ACTIVE_OUT             },
                {  "C",     "Y",     "IN",        "REL",     "UAL",          CustodyStatusCode.ACTIVE_UAL             },
                {  "C",     "Y",     "OUT",       "REL",     "UAL",          CustodyStatusCode.ACTIVE_UAL             },
                {  "C",     "Y",     "OUT",       "REL",     "UAL_ECL",      CustodyStatusCode.ACTIVE_UAL_ECL             },
                {  "O",     "Y",     "OUT",       "TAP",     "1",            CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "10",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "11",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "12",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "13",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "14",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "14",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "15",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "16",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "17",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "18",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "2",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "2",            CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "20",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "20",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "21",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "21",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "3",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "3",            CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "4",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "4",            CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "5",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "5",            CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "6",            CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "6",            CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "7",            CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "8",            CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "9",            CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "C1",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "C1",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "C2",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "C2",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "C3",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "C3",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "C4",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "C4",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "C5",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "C5",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "C6",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "C6",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "C7",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "C7",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "C9",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "C9",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "EL",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "EL",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "ELR",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "ELR",          CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "ET",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "ET",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "F1",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "F1",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "F2",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "F2",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "F3",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "F3",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "F4",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "F4",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "F6",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "F6",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "F7",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "F7",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "F8",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "F8",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "F9",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "F9",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "FA",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "FA",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "FB",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "FB",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "FC",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "FC",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "FD",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "FD",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "FE",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "FE",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "FF",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "FF",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "FR",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "FR",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "I1",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "I1",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "IM",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "IM",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "IR",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "IR",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "LTX",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "LTX",          CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "OPA",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "OPA",          CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "PAP",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "PAP",          CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "PC",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "PC",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "PWP",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "PWP",          CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "R1",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "R1",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "R2",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "R2",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "R3",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "R3",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "R5",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "R5",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "R6",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "R6",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "R7",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "R7",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "R8",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "R8",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "R9",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "R9",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "RO",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "RO",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "SE",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "SE",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "SP",           CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "SP",           CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "OUT",       "TAP",     "TAP",          CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "UPW",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "UPW",          CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "YMI",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "YMI",          CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "YOTR",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "YOTR",         CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "Y",     "IN",        "TAP",     "YRDR",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "Y",     "OUT",       "TAP",     "YRDR",         CustodyStatusCode.ACTIVE_OUT_TAP             },
                {  "O",     "N",     "OUT",       "TRN",     "28",           CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "N",     "OUT",       "TRN",     "ACCVISIT",     CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "Y",     "IN",        "TRN",     "ADMIN",        CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "N",     "OUT",       "TRN",     "ADMIN",        CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "N",     "OUT",       "TRN",     "APPEALS",      CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "N",     "OUT",       "TRN",     "AS",           CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "Y",     "IN",        "TRN",     "COMP",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "N",     "OUT",       "TRN",     "COMP",         CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "N",     "OUT",       "TRN",     "INT",          CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "N",     "OUT",       "TRN",     "MED",          CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "Y",     "IN",        "TRN",     "NOTR",         CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "N",     "OUT",       "TRN",     "NOTR",         CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "N",     "OUT",       "TRN",     "OJ",           CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "Y",     "IN",        "TRN",     "OTHER",        CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "N",     "OUT",       "TRN",     "OTHER",        CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "N",     "OUT",       "TRN",     "OVCROW",       CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "N",     "OUT",       "TRN",     "PRES",         CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "N",     "OUT",       "TRN",     "PROAT",        CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "N",     "OUT",       "TRN",     "PROD",         CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "Y",     "IN",        "TRN",     "SEC",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "N",     "OUT",       "TRN",     "SEC",          CustodyStatusCode.IN_TRANSIT             },
                {  "O",     "Y",     "IN",        "TRN",     "TRN",          CustodyStatusCode.ACTIVE_IN             },
                {  "O",     "N",     "OUT",       "TRN",     "TRN",          CustodyStatusCode.IN_TRANSIT             }
        };
    }

    @Test
    @UseDataProvider("custodyStatusRecords")
    public void canIdentifyAnOffendersCustodyStatusCorrectly(String booking_status, String active_flag, String direction_code, String movement_type, String movement_reason_code, CustodyStatusCode expectedCustodyStatus) {
        CustodyStatusDto record = CustodyStatusDto
                .builder()
                .bookingStatus(booking_status)
                .activeFlag(active_flag)
                .directionCode(direction_code)
                .movementType(movement_type)
                .movementReasonCode(movement_reason_code)
                .build();

        assertEquals(
                "Identifies correct custody status",
                expectedCustodyStatus,
                calculator.custodyStatusCodeOf(record));
    }

}