/:
  type: { readOnlyCollection: { type: AccessRole, description: List of access roles } }
  get:
    (javaOperationName): getAccessRoles
    description: List of access roles
  post:
    (javaOperationName): createAccessRole
    description: Create new access role.
    body:
      application/json:
        type: AccessRole
    responses:
      201:
        mediaType:
      400:
        body:
          application/json:
            type: ErrorResponse
            description: Invalid request - e.g. role code not provided.
            example: !include ../examples/ouput/400.sample.json
      403:
        body:
          application/json:
            type: ErrorResponse
            description: Forbidden - user not authorised to create an access role.
            example: !include ../examples/ouput/403.sample.json
      409:
        body:
          application/json:
            type: ErrorResponse
            description: A role already exists with the provided role code.
      404:
        body:
          application/json:
            type: ErrorResponse
            description: Parent access role not found.
            example: !include ../examples/ouput/404.sample.json
  put:
    (javaOperationName): updateAccessRole
    description: Update the access role.
    body:
      application/json:
        type: AccessRole
    responses:
      200:
        mediaType:
      400:
        body:
          application/json:
            type: ErrorResponse
            description: Invalid request - e.g. role code not provided.
            example: !include ../examples/ouput/400.sample.json
      404:
        body:
          application/json:
            type: ErrorResponse
            description: Access role not found.
            example: !include ../examples/ouput/404.sample.json
      403:
        body:
          application/json:
            type: ErrorResponse
            description: Forbidden - user not authorised to update an access role.
            example: !include ../examples/ouput/403.sample.json
