description:  The collection of inmates within the system.
type: { get-collection: { collectionSchema: inmateSummaries } }
is: [
  orderable: {fieldsList : "inmateId, bookingId, offenderId, firstName, lastName, alertCodes, agencyId, currentLocationId, or assignedLivingUnitId"},
  pageable
]

/{bookingId}:
  description: The details specific to the specified inmate.
  type: { get-item: { schema: inmateDetail }}

/{bookingId}/movements:
  description: The collection of scheduled movements associated to the inmate.
  type: { get-collection: { collectionSchema: movements } }
  is: [
    orderable: {fieldsList : "moveCategory, moveDateTime, fromAgencyId, toAgencyId, moveType, moveReason, fromLocationId, or toLocation"},
    pageable
  ]
