/usage:
  description: Retrieves list of case notes grouped by type and offender - POST version to allow large offender lists.
  type: { readOnlyCollection: { type: CaseNoteUsage, description: Count of case notes, of specified type and sub-type, for offenders. } }
  get:
    (javaOperationName): getCaseNoteUsageSummary
    queryParameters:
     offenderNo:
        type: array
        description: a list of offender numbers to search.
        example: offenderNo=A1234AA&offenderNo=A1234AB
     staffId?:
        type: integer
        description: Staff Id to filter by
        example: staffId=131231
     numMonths?:
        type: integer
        description: Number of month to look forward (if fromDate only defined), or back (if toDate only defined). Default is 1 month
        default: 1
     fromDate?:
        type: date-only
        description: Only case notes occurring on or after this date (in YYYY-MM-DD format) will be considered.  If not defined then the numMonth before the current date, unless a toDate is defined when it will be numMonths before toDate
        example: 2017-06-01
     toDate?:
        type: date-only
        description: Only case notes occurring on or before this date (in YYYY-MM-DD format) will be considered. If not defined then the current date will be used, unless a fromDate is defined when it will be numMonths after fromDate
        example: 2017-09-01
     type?:
        type: string
        description: Case note type.
     subType?:
        type: stringCaseNoteUsageRequest
        description: Case note sub-type.
  post:
    description: Retrieves list of case notes grouped by type and offender
    (javaOperationName): getCaseNoteUsageSummaryByPost
    body:
      application/json:
        type: CaseNoteUsageRequest
    responses:
      200:
        description: The case note usage list is returned.
        body:
          application/json:
           type: CaseNoteUsage[]
           description: Count of case notes, of specified type and sub-type, for offenders.

/staff-usage:
  description: Count of case notes, of specified type and sub-type, for staff.
  type: { readOnlyCollection: { type: CaseNoteStaffUsage, description: Count of case notes, of specified type and sub-type, for staff. } }
  get:
    (javaOperationName): getCaseNoteStaffUsageSummary
    queryParameters:
     staffId:
        type: array
        description: a list of staffId numbers to use.
        example: staffId=131231&staffId=321423
     numMonths?:
        type: integer
        description: Number of month to look forward (if fromDate only defined), or back (if toDate only defined). Default is 1 month
        default: 1
     fromDate?:
        type: date-only
        description: Only case notes occurring on or after this date (in YYYY-MM-DD format) will be considered.  If not defined then the numMonth before the current date, unless a toDate is defined when it will be numMonths before toDate
        example: 2017-06-01
     toDate?:
        type: date-only
        description: Only case notes occurring on or before this date (in YYYY-MM-DD format) will be considered. If not defined then the current date will be used, unless a fromDate is defined when it will be numMonths after fromDate
        example: 2017-09-01
     type?:
        type: string
        description: Case note type.
     subType?:
        type: string
        description: Case note sub-type.
  post:
    description: Retrieves list of case notes grouped by type/sub-type and staff
    (javaOperationName): getCaseNoteStaffUsageSummaryByPost
    body:
      application/json:
        type: CaseNoteStaffUsageRequest
    responses:
      200:
        description: The case note usage list is returned.
        body:
          application/json:
           type: CaseNoteStaffUsage[]
           description: Count of case notes, of specified type and sub-type, for staff.
