/:
  description: Returns a list of offender nos and their respective custody status.
  (javaOperationName): getPrisonerCustodyStatuses
  type: { readOnlyCollection: { type: PrisonerCustodyStatus } }
  queryParameters:
    custodyStatusCode:
      description: Prisoner with the specified Custody Status
      (JavaType): CustodyStatusCode
    locationId:
      description: A location to limit the results to
      type: string
  is: [
    searchable: {fieldsList : "locationId, custodyStatusCode"},
    sortable: {fieldsList : "locationId, custodyStatusCode"},
  ]

/{offenderNo}:
  description: Returns the custody status for a specific offender no.
  (javaOperationName): getPrisonerCustodyStatus
  type: { readOnlyItem: { type: PrisonerCustodyStatus } }
  uriParameters:
    offenderNo:
      description: The OffenderNo of an offender
      type: string
