/{imageId}:
  (javaOperationName): getImage
  type: {
    readOnlyItem: {
      type: ImageDetail,
      description: Image detail (with image data).
    }
  }
  uriParameters:
    imageId:
      (javaType): Long
      description: The image id of offender

/{imageId}/data:
  (javaOperationName): getImageData
  type: {
    userPicture: {
      description: Image data (as bytes).
    }
  }
  uriParameters:
    imageId:
      (javaType): Long
      description: The image id of offender