/{imageId}:
  description: Details about the specified image including the image itself.
  type: { get-item: { schema: imageDetails }}

/{imageId}/data:
    type:
      get-base:
    get:
      responses:
        200:
          body:
            image/jpeg:

