/{imageId}:
  (javaOperationName): getImage
  type: {
    readOnlyItem: {
      type: ImageDetail,
      description: Details about the specified image including the image itself.
    }
  }
  uriParameters:
    imageId:
      (javaType): Long
      description: The image id of offender

/{imageId}/data:
  (javaOperationName): getImageData
  type: {
    userPicture: {
      description: Image as bytes.
    }
  }
  uriParameters:
    imageId:
      (javaType): Long
      description: The image id of offender