/:
  (javaOperationName): getLocations
  type: { readOnlyCollectionPaged: { type: Location, description: Returns the list of locations viewable by the user } }
  is: [
    searchable: {fieldsList : "locationId, agencyId, locationType, and parentLocationId"},
    sortable: {fieldsList : "locationId, agencyId, locationType, and parentLocationId"},
  ]

/{locationId}:
  (javaOperationName): getLocation
  uriParameters:
    locationId:
      (javaType): Long
      description: The location id of location
  type: { readOnlyItem: { type: Location, description: Returns details about the specified location }}

/{locationId}/inmates:
  (javaOperationName): getOffendersAtLocation
  uriParameters:
    locationId:
      (javaType): Long
      description: The location id of location
  type: { readOnlyCollectionPaged: { type: OffenderBooking, description: The collection of inmates present at the specified location. } }
  is: [
    searchable: {fieldsList : "bookingNo, bookingId, offenderNo, firstName, lastName, agencyId, or assignedLivingUnitId"},
    sortable: {fieldsList : "bookingNo, bookingId, offenderNo, firstName, lastName, agencyId, or assignedLivingUnitId"},
  ]

/groups/{agencyId}/{name}:
  (javaOperationName): getGroup
  uriParameters:
    name:
      type: string
      description: The group name
    agencyId:
      type: string
      description: The prison
  type: { readOnlyCollection: { type: String, description: Returns location codes of cells in this prison belonging to the group. } }
