/:
  (deprecated): Use <b>/users/me/locations</b> instead. This API will be removed or re-purposed in a future release.
  (javaOperationName): getLocations
  type: { readOnlyCollectionPaged: { type: Location, description: List of locations accessible to current user. } }
  is: [
    searchable: {fieldsList : "locationId, agencyId, locationType, and parentLocationId"},
    sortable: {fieldsList : "locationId, agencyId, locationType, and parentLocationId"},
  ]

/{locationId}:
  (javaOperationName): getLocation
  uriParameters:
    locationId:
      (javaType): Long
      description: The location id of location
  type: { readOnlyItem: { type: Location, description: Location detail. } }

/{locationId}/inmates:
  (deprecated): Use <b>/search-offenders/{locationPrefix}</b> instead. This API will be removed in a future release.
  (javaOperationName): getOffendersAtLocation
  uriParameters:
    locationId:
      (javaType): Long
      description: The location id of location
  type: { readOnlyCollectionPaged: { type: OffenderBooking, description: List of offenders at location. } }
  is: [
    searchable: {fieldsList : "bookingNo, bookingId, offenderNo, firstName, lastName, agencyId, or assignedLivingUnitId"},
    sortable: {fieldsList : "bookingNo, bookingId, offenderNo, firstName, lastName, agencyId, or assignedLivingUnitId"},
  ]

/groups/{agencyId}/{name}:
  (javaOperationName): getGroup
  uriParameters:
    name:
      type: string
      description: The group name
    agencyId:
      type: string
      description: The prison
  type: { readOnlyCollection: { type: Location, description: List of cell locations by group at agency location. } }

/groups/{agencyId}:
  (javaOperationName): getAvailableGroups
  uriParameters:
    agencyId:
      type: string
      description: The prison
  type: { readOnlyCollection: { type: String, description: List of all available groups at agency. } }
