/{locationId}:
  (javaOperationName): getLocation
  uriParameters:
    locationId:
      (javaType): Long
      description: The location id of location
  type: { readOnlyItem: { type: Location, description: Location detail. } }

/{locationId}/inmates:
  (javaOperationName): getOffendersAtLocation
  uriParameters:
    locationId:
      (javaType): Long
      description: The location id of location
  type: { readOnlyCollectionPaged: { type: OffenderBooking, description: List of offenders at location. } }
  is: [
    searchable: {fieldsList : "bookingNo, bookingId, offenderNo, firstName, lastName, agencyId, or assignedLivingUnitId"},
    sortable: {fieldsList : "bookingNo, bookingId, offenderNo, firstName, lastName, agencyId, or assignedLivingUnitId"},
  ]

/description/{locationPrefix}/inmates:
  (javaOperationName): getOffendersAtLocationDescription
  uriParameters:
    locationDesc:
      type: string
      description: The location description of location
  get:
    queryParameters:
      keywords?:
        type : string
        description: offender name or id to match
      alerts?:
        type: array
        (javaType): List<String>
        description: alert flags to filter by
        example: ?alerts=XA&alerts=RVR
  type: { readOnlyCollectionPaged: { type: OffenderBooking, description: List of offenders at location. } }
  is: [
    sortable: {fieldsList : "bookingNo, bookingId, offenderNo, firstName, lastName, agencyId, or assignedLivingUnitId"},
  ]

/groups/{agencyId}/{name}:
  (javaOperationName): getLocationGroup
  uriParameters:
    name:
      type: string
      description: The group name
    agencyId:
      type: string
      description: The prison
  type: { readOnlyCollection: { type: Location, description: List of cell locations by group at agency location. } }
