description:  Find sentence details for offenders
type: { readOnlyCollection: { type: OffenderSentenceDetail, description: List of offenders (with associated sentence detail). } }
get:
  queryParameters:
    agencyId?:
      type: string
      description: agency/prison to restrict results, if none provided current active caseload will be used, unless offenderNo list is specified
      example: LEI
    offenderNo?:
      type: array
      description: a list of offender numbers to search.
      example: offenderNo=A1234AA&offenderNo=A1234AB
post:
  description: Retrieves list of offenders (with associated sentence detail) - POST version to allow large offender lists.
  body:
    application/json:
      (javaType): List<String>
      description: The required offender numbers (mandatory)
  responses:
    200:
      description: The list of offenders is returned.
      body:
        application/json:
         type: OffenderSentenceDetail[]
         description: List of offenders (with associated sentence detail).
/eligible-for-home-detention-curfew:
  description:  Find sentence details for offenders, restricted to those eligible for Home Detention Curfew (HDC)
  type: { readOnlyCollection: { type: OffenderSentenceDetail, description: List of offenders (with associated sentence detail). } }
  get:
    queryParameters:
      agencyId?:
        type: string
        description: agency/prison to restrict results, if none provided current active caseload will be used.
        example: LEI
    responses:
      200:
        description: The list of offenders is returned.
        body:
          application/json:
           type: OffenderSentenceDetail[]
           description: List of offenders (with associated sentence detail).



