/{assessmentCode}:
  type: { readOnlyCollection: { type: Assessment, description: Offender assessment detail for multiple offenders. } }
  uriParameters:
    assessmentCode:
      type: string
      description: Assessment Type Code
  get:
    queryParameters:
      offenderNo:
        type: array
        (javaType): List<String>
        description: The required offender numbers
        example: offenderNo=A1234AA&offenderNo=A1234AB
  post:
    description: Retrieves Offender assessment details for multiple offenders - POST version to allow large offender lists.
    body:
      application/json:
        (javaType): List<String>
        description: The required offender numbers (mandatory)
    responses:
      200:
        description: The assessment list is returned.
        body:
          application/json:
           type: Assessment[]
           description: Offender assessment detail for multiple offenders.

/csra/list:
  post:
    type: { readOnlyCollection: { type: Assessment, description: Offender CRSAs for multiple offenders. } }
    description: Retrieves Offender CRSAs for multiple offenders - POST version to allow large offender lists.
    body:
      application/json:
        (javaType): List<String>
        description: The required offender numbers (mandatory)
    responses:
      200:
        description: The CSRA assessment list is returned, 1 per offender.
        body:
          application/json:
           type: Assessment[]
           description: Offender assessment detail for multiple offenders.
