description:  Find release date for offenders
type: { readOnlyCollectionPaged: { type: OffenderRelease, description: List of offenders (with associated release detail). } }
get:
  queryParameters:
    offenderNo?:
      type: array
      description: a list of offender numbers to search.
      example: offenderNo=A1234AA&offenderNo=A1234AB
    toDate?:
      description: Filter results to only display releases before a defined date, if not defined it will use 3 months from now
      type: string
      example: fromDate=2017-02-28
is: [
    sortable: {fieldsList : "offenderNo, lastName, firstName, agencyLocationId, internalLocationDesc, releaseDate"},
  ]