/alertTypes:
  (javaOperationName): getAlertTypes
  description: Give all Alert types
  type: { readOnlyCollectionPaged: { type: ReferenceCode } }
  get:
    queryParameters:
      includeSubTypes:
        description: Include the Subtypes in the response
        type: boolean
        default: false
  is: [
    searchable: {fieldsList: "code, description, activeFlag and parentCode"},
    sortable: {fieldsList: "code"}
  ]

/alertTypes/{alertType}:
  (javaOperationName): getAlertType
  description: Return Alert Type for specific Alert type
  type: { readOnlyItem : { type: ReferenceCode, description: Get Alert Type for specified type }}
  
/alertTypes/{alertType}/codes:
  (javaOperationName): getAlertTypesByType
  description: Give all Alert Codes for specific Alert type
  type: { readOnlyCollectionPaged : { type: ReferenceCode }}
  is: [
    searchable: {fieldsList: "code, description, activeFlag and parentCode"},
    sortable: {fieldsList: "code"}
  ]
  
/alertTypes/{alertType}/codes/{alertCode}:
  (javaOperationName): getAlertTypeCode
  description: Give specific code details of alerts.
  type: { readOnlyItem : { type: ReferenceCode, description: Get Alert Types  for specified parent alert code }}

/caseNoteSources:
  (javaOperationName): getCaseNoteSources
  description: Give all Case Note Sources
  type: { readOnlyCollectionPaged : { type: ReferenceCode }}
  is: [
    searchable: {fieldsList: "code, description, activeFlag and parentCode"},
    sortable: {fieldsList: "code"}
  ]

/caseNoteSources/{sourceCode}:
  (javaOperationName): getCaseNoteSource
  description: Get the Case Note Source
  type: { readOnlyItem : { type: ReferenceCode, description: Get Case Note Source for specified source }}

/caseNoteTypes:
  (javaOperationName): getCaseNoteTypes
  description: Give all Case Note Types
  type: { readOnlyCollectionPaged : { type: ReferenceCode }}
  get:
    queryParameters:
      includeSubTypes:
        description: Include the Subtypes in the response
        type: boolean
        default: false
  is: [
    searchable: {fieldsList: "code, description, activeFlag and parentCode"},
    sortable: {fieldsList: "code"}
  ]

/caseNoteTypes/{typeCode}:
  (javaOperationName): getCaseNoteType
  description: Get the Case Note Type
  type: { readOnlyItem : { type: ReferenceCode, description: Get Case Note Type for specified note type } }

/caseNoteSubTypes/{typeCode}:
  (javaOperationName): getCaseNoteSubTypes
  description: Give all Case Note SubTypes
  type: { readOnlyCollectionPaged : { type: ReferenceCode }}

/caseNoteSubTypes/{typeCode}/subTypes/{subTypeCode}:
  (javaOperationName): getCaseNoteSubType
  description: Get the Case Note SubType
  type: { readOnlyItem : { type: ReferenceCode, description: Get Case Note Subtype for specified type and subtype }}
