/alertTypes:
  (javaOperationName): getAlertTypes
  type: { readOnlyCollectionPaged: { type: ReferenceCode, description: List of alert types (with alert codes). } }
  is: [
    sortable: {fieldsList: "code, description"}
  ]

/caseNoteSources:
  (javaOperationName): getCaseNoteSources
  type: { readOnlyCollectionPaged : { type: ReferenceCode, description: List of case note source codes. } }
  is: [
    sortable: {fieldsList: "code, description"}
  ]

/caseNoteTypes:
  (javaOperationName): getCaseNoteTypes
  type: { readOnlyCollection : { type: ReferenceCode, description: List of all used case note types (with sub-types). } }

/domains/{domain}:
  (javaOperationName): getReferenceCodesByDomain
  type: { readOnlyCollectionPaged : { type: ReferenceCode, description: List of reference codes for reference domain. } }
  uriParameters:
    domain:
      type: string
      description: The domain identifier/name.
  get:
    queryParameters:
      withSubCodes?:
        description: Specify whether or not to return reference codes with their associated sub-codes.
        type: boolean
        default: false
        example: true
  is: [
    sortable: {fieldsList: "code, description"}
  ]

/domains/{domain}/codes/{code}:
  (javaOperationName): getReferenceCodeByDomainAndCode
  type: { readOnlyItem : { type: ReferenceCode, description: Reference code detail for reference domain and code (with sub-codes). } }
  uriParameters:
    domain:
      type: string
      description: The domain identifier/name.
    code:
      type: string
      description: The reference code.
  get:
    queryParameters:
      withSubCodes?:
        description: Specify whether or not to return the reference code with its associated sub-codes.
        type: boolean
        default: false
        example: true

/scheduleReasons:
  (javaOperationName): getScheduleReasons
  type: { readOnlyCollection : { type: ReferenceCode, description: Get possible reason codes for created event. } }
  get:
    queryParameters:
      eventType:
        description: Specify event type.
        type: string
        example: APP (appointment)
