
/{agencyId}/groups/{name}:
  (javaOperationName): getGroupEvents
  uriParameters:
    agencyId:
      type: string
      description: The prison.
    name:
      type: string
      description: The location list name.
  get:
    queryParameters:
      date?:
        type : date-only
        description: Date of whereabouts list, default today
      timeSlot?:
        type : enum
        (javaType): TimeSlot
        description: AM, PM or ED
  type: { readOnlyCollection: { type: PrisonerSchedule, description: Get all events for given date for prisoners in listed cells, sorted by start time. } }

/{agencyId}/locations/{locationId}/usage/{usage}:
  (javaOperationName): getLocationEvents
  uriParameters:
    agencyId:
      type: string
      description: The prison.
    locationId:
      (javaType): Long
      description: The location id where event is held.
    usage:
      type: string
      description: The locationUsage code from the location object.
  get:
    queryParameters:
      date?:
        type : date-only
        description: Date of whereabouts list, default today
      timeSlot?:
        type : enum
        (javaType): TimeSlot
        description: AM, PM or ED
  type: { readOnlyCollection: { type: PrisonerSchedule, description: Get all Prisoner events for given date at location. } }
  is: [
      sortable: {fieldsList : "cellLocation or lastName"},
  ]
