/{staffId}:
  (javaOperationName): getStaffDetail
  type: { readOnlyItem: { type: StaffDetail, description: Staff detail. } }
  uriParameters:
    staffId:
      type: number
      (javaType): Long
      description: The staff id of the staff member.

/roles/{agencyId}/position/{position}/role/{role}:
  (javaOperationName): getStaffByAgencyPositionRole
  type: { readOnlyCollectionPaged: { type: StaffLocationRole, description: Get active staff members within agency who are currently assigned the specified position and/or role. } }
  is: [ sortable: { fieldsList: "firstName, lastName" } ]
  uriParameters:
    agencyId:
      type: string
      description: The agency (prison) id.
      example: MDI
    position:
      type: string
      description: The staff position.
      example: AO
    role:
      type: string
      description: The staff role.
      example: HDCP
  get:
    queryParameters:
      nameFilter?:
        type: string
        description: Filter results by first name and/or last name of staff member.
        example: Kirsty
      staffId?:
        type: number
        (javaType): Long
        description: The staff id of a staff member.

/roles/{agencyId}/role/{role}:
  (javaOperationName): getStaffByAgencyRole
  type: { readOnlyCollectionPaged: { type: StaffLocationRole, description: Get active staff members within agency who are currently assigned the specified role. } }
  is: [ sortable: { fieldsList: "firstName, lastName" } ]
  uriParameters:
    agencyId:
      type: string
      description: The agency (prison) id.
      example: MDI
    role:
      type: string
      description: The staff role.
      example: KW
  get:
    queryParameters:
      nameFilter?:
        type: string
        description: Filter results by first name and/or last name of staff member. Supplied filter term is matched to start of staff member's first and last name.
        example: John
      staffId?:
        type: number
        (javaType): Long
        description: The staff id of a staff member.
