/me/locations:
  (javaOperationName): getMyLocations
  description: Returns list of locations associated with current user.
  type: { readOnlyCollection: { type: Location, description: List of locations accessible to current user. } }
  
/{username}:
  (javaOperationName): getUserDetails
  type: { readOnlyItem: { type: UserDetail,  description: User detail. } }
  uriParameters:
    username:
      description: The username of the user.

/staff/{staffId}:
  (javaOperationName): getStaffDetail
  type: { readOnlyItem: { type: StaffDetail, description: Staff detail. } }
  uriParameters:
    staffId:
      (javaType): Long
      description: The staff id of the staff member.

/me:
  (javaOperationName): getMyUserInformation
  type: { readOnlyItem: { type: UserDetail, description: Current user detail. } }

/me/bookingAssignments:
  (javaOperationName): getMyAssignments
  description: Offender Assignments for this logged in user
  type: { readOnlyCollectionPaged: { type: OffenderBooking, description: List of offender bookings assigned to current user. } }

/me/roles:
  (javaOperationName): getMyRoles
  description: Get the logged in users roles
  type: { readOnlyCollection: { type: UserRole, description: List of roles for current user. } }

/me/caseLoads:
  (javaOperationName): getMyCaseLoads
  description: Returns the list of caseloads associated to the user
  type: { readOnlyCollection: { type: CaseLoad, description: List of caseloads accessible to current user. } }
  
/me/caseNoteTypes:
  (javaOperationName): getMyCaseNoteTypes
  type: { readOnlyCollection: { type: ReferenceCode, description: List of all case note types (with sub-types) accessible to current user (and based on working caseload). } }
  is: [
    sortable: {fieldsList : "code, activeFlag, description"},
  ]

/me/activeCaseLoad:
  (javaOperationName): updateMyActiveCaseLoad
  description: The active caseload associated to the user
  put:
    description: Update working caseload for current user.
    body:
      application/json:
        type: CaseLoad
    responses:
      401:
        body:
          application/json:
            type: ErrorResponse
            description: Invalid username or password
            example:  !include ../examples/ouput/401.sample.json
      403:
        body:
          application/json:
            type: ErrorResponse
            description: the user does not have permission to view the caseload.
            example:  !include ../examples/ouput/403.sample.json
