CREATE SEQUENCE OFFENDER_ID START WITH 1 ;
CREATE SEQUENCE OFFENDER_BOOK_ID START WITH 1 ;

CREATE TABLE OFFENDERS
(
  OFFENDER_ID                   DECIMAL(10, 0),
  OFFENDER_NAME_SEQ             DECIMAL(12, 0),
  ID_SOURCE_CODE                VARCHAR(12),
  LAST_NAME                     VARCHAR(35),
  NAME_TYPE                     VARCHAR(12),
  FIRST_NAME                    VARCHAR(35),
  MIDDLE_NAME                   VARCHAR(35),
  BIRTH_DATE                    DATE,
  SEX_CODE                      VARCHAR(12),
  SUFFIX                        VARCHAR(12),
  LAST_NAME_SOUNDEX             VARCHAR(6),
  BIRTH_PLACE                   VARCHAR(25),
  BIRTH_COUNTRY_CODE            VARCHAR(12),
  CREATE_DATE                   DATE,
  LAST_NAME_KEY                 VARCHAR(35),
  ALIAS_OFFENDER_ID             DECIMAL(10, 0),
  FIRST_NAME_KEY                VARCHAR(35),
  MIDDLE_NAME_KEY               VARCHAR(35),
  OFFENDER_ID_DISPLAY           VARCHAR(10),
  ROOT_OFFENDER_ID              DECIMAL(10, 0),
  CASELOAD_TYPE                 VARCHAR(12),
  MODIFY_USER_ID                VARCHAR(32),
  MODIFY_DATETIME               TIMESTAMP(6),
  ALIAS_NAME_TYPE               VARCHAR(12),
  PARENT_OFFENDER_ID            DECIMAL(10, 0),
  UNIQUE_OBLIGATION_FLAG        VARCHAR(1)  DEFAULT NULL,
  SUSPENDED_FLAG                VARCHAR(1)  DEFAULT NULL,
  SUSPENDED_DATE                DATE,
  RACE_CODE                     VARCHAR(12),
  REMARK_CODE                   VARCHAR(12),
  ADD_INFO_CODE                 VARCHAR(12),
  BIRTH_COUNTY                  VARCHAR(20),
  BIRTH_STATE                   VARCHAR(20),
  MIDDLE_NAME_2                 VARCHAR(35),
  TITLE                         VARCHAR(12),
  AGE                           DECIMAL(3, 0),
  CREATE_USER_ID                VARCHAR(40) DEFAULT USER,
  LAST_NAME_ALPHA_KEY           VARCHAR(1)  DEFAULT NULL,
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  NAME_SEQUENCE                 VARCHAR(12),
  SINGLE_OFFENDER_IDENTITY_ID   VARCHAR(36),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE OFFENDERS ALTER OFFENDER_ID SET NOT NULL;
ALTER TABLE OFFENDERS ALTER ID_SOURCE_CODE SET NOT NULL;
ALTER TABLE OFFENDERS ALTER LAST_NAME SET NOT NULL;
ALTER TABLE OFFENDERS ALTER SEX_CODE SET NOT NULL;
ALTER TABLE OFFENDERS ALTER CREATE_DATE SET NOT NULL;
ALTER TABLE OFFENDERS ALTER LAST_NAME_KEY SET NOT NULL;
ALTER TABLE OFFENDERS ALTER OFFENDER_ID_DISPLAY SET NOT NULL;
ALTER TABLE OFFENDERS ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE OFFENDERS ALTER CREATE_USER_ID SET NOT NULL;


CREATE TABLE OFFENDER_BOOKINGS
(
  OFFENDER_BOOK_ID              DECIMAL(10, 0) PRIMARY KEY,
  BOOKING_BEGIN_DATE            DATE,
  BOOKING_END_DATE              DATE,
  BOOKING_NO                    VARCHAR(14),
  OFFENDER_ID                   DECIMAL(10, 0),
  AGY_LOC_ID                    VARCHAR(6),
  LIVING_UNIT_ID                DECIMAL(10, 0),
  DISCLOSURE_FLAG               VARCHAR(1)  DEFAULT 'Y',
  IN_OUT_STATUS                 VARCHAR(12),
  ACTIVE_FLAG                   VARCHAR(1)  DEFAULT 'N',
  BOOKING_STATUS                VARCHAR(12),
  YOUTH_ADULT_CODE              VARCHAR(12),
  FINGER_PRINTED_STAFF_ID       DECIMAL(10, 0),
  SEARCH_STAFF_ID               DECIMAL(10, 0),
  PHOTO_TAKING_STAFF_ID         DECIMAL(10, 0),
  ASSIGNED_STAFF_ID             DECIMAL(10, 0),
  CREATE_AGY_LOC_ID             VARCHAR(6),
  BOOKING_TYPE                  VARCHAR(12),
  BOOKING_CREATED_DATE          DATE,
  ROOT_OFFENDER_ID              DECIMAL(10, 0),
  AGENCY_IML_ID                 DECIMAL(10, 0),
  SERVICE_FEE_FLAG              VARCHAR(1)  DEFAULT 'N',
  EARNED_CREDIT_LEVEL           VARCHAR(12),
  EKSTRAND_CREDIT_LEVEL         VARCHAR(12),
  INTAKE_AGY_LOC_ID             VARCHAR(6),
  ACTIVITY_DATE                 DATE,
  INTAKE_CASELOAD_ID            VARCHAR(6),
  INTAKE_USER_ID                VARCHAR(32),
  CASE_OFFICER_ID               DECIMAL(6, 0),
  CASE_DATE                     DATE,
  CASE_TIME                     DATE,
  COMMUNITY_ACTIVE_FLAG         VARCHAR(1)  DEFAULT 'N',
  CREATE_INTAKE_AGY_LOC_ID      VARCHAR(6),
  COMM_STAFF_ID                 DECIMAL(10, 0),
  COMM_STATUS                   VARCHAR(12),
  COMMUNITY_AGY_LOC_ID          VARCHAR(6),
  NO_COMM_AGY_LOC_ID            DECIMAL(6, 0),
  COMM_STAFF_ROLE               VARCHAR(12),
  AGY_LOC_ID_LIST               VARCHAR(80),
  STATUS_REASON                 VARCHAR(32),
  TOTAL_UNEXCUSED_ABSENCES      DECIMAL(6, 0),
  REQUEST_NAME                  VARCHAR(240),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  RECORD_USER_ID                VARCHAR(30),
  INTAKE_AGY_LOC_ASSIGN_DATE    DATE,
  BOOKING_SEQ                   DECIMAL(6, 0),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

CREATE UNIQUE INDEX OFFENDER_BOOKINGS_PK ON OFFENDER_BOOKINGS (OFFENDER_BOOK_ID);

ALTER TABLE OFFENDER_BOOKINGS ALTER OFFENDER_BOOK_ID SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER BOOKING_BEGIN_DATE SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER OFFENDER_ID SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER DISCLOSURE_FLAG SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER IN_OUT_STATUS SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER YOUTH_ADULT_CODE SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER BOOKING_SEQ SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE OFFENDER_BOOKINGS ALTER CREATE_USER_ID SET NOT NULL;


CREATE TABLE OFFENDER_PHYSICAL_ATTRIBUTES
(
  OFFENDER_BOOK_ID              DECIMAL(10, 0),
  ATTRIBUTE_SEQ                 DECIMAL(6, 0),
  HEIGHT_FT                     DECIMAL(6, 0),
  HEIGHT_IN                     DECIMAL(6, 0),
  HEIGHT_CM                     DECIMAL(6, 0),
  WEIGHT_LBS                    DECIMAL(6, 0),
  WEIGHT_KG                     DECIMAL(6, 0),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);


CREATE TABLE OFFENDER_IDENTIFYING_MARKS
(
  OFFENDER_BOOK_ID              DECIMAL(10, 0),
  ID_MARK_SEQ                   DECIMAL(6, 0),
  BODY_PART_CODE                VARCHAR(12),
  MARK_TYPE                     VARCHAR(12),
  SIDE_CODE                     VARCHAR(12),
  PART_ORIENTATION_CODE         VARCHAR(12),
  COMMENT_TEXT                  VARCHAR(240),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);


CREATE TABLE OFFENDER_PROFILE_DETAILS
(
  OFFENDER_BOOK_ID              DECIMAL(10, 0),
  PROFILE_SEQ                   DECIMAL(6, 0),
  PROFILE_TYPE                  VARCHAR(12),
  PROFILE_CODE                  VARCHAR(40),
  LIST_SEQ                      DECIMAL(6, 0),
  COMMENT_TEXT                  VARCHAR(240),
  CASELOAD_TYPE                 VARCHAR(12),
  MODIFY_USER_ID                VARCHAR(32),
  MODIFY_DATETIME               TIMESTAMP(6),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);


CREATE TABLE OFFENDER_ASSESSMENTS
(
  OFFENDER_BOOK_ID              DECIMAL(10, 0),
  ASSESSMENT_SEQ                DECIMAL(6, 0),
  ASSESSMENT_DATE               DATE,
  ASSESSMENT_TYPE_ID            DECIMAL(10, 0),
  SCORE                         DECIMAL(8, 2),
  ASSESS_STATUS                 VARCHAR(12),
  CALC_SUP_LEVEL_TYPE           VARCHAR(12),
  ASSESS_STAFF_ID               DECIMAL(10, 0),
  ASSESS_COMMENT_TEXT           VARCHAR(4000),
  OVERRIDE_REASON_TEXT          VARCHAR(40),
  PLACE_AGY_LOC_ID              VARCHAR(6),
  OVERRIDED_SUP_LEVEL_TYPE      VARCHAR(12),
  OVERRIDE_COMMENT_TEXT         VARCHAR(240),
  OVERRIDE_STAFF_ID             DECIMAL(10, 0),
  EVALUATION_DATE               DATE,
  NEXT_REVIEW_DATE              DATE,
  EVALUATION_RESULT_CODE        VARCHAR(12),
  REVIEW_SUP_LEVEL_TYPE         VARCHAR(12),
  REVIEW_PLACEMENT_TEXT         VARCHAR(240),
  REVIEW_COMMITTE_CODE          VARCHAR(12),
  COMMITTE_COMMENT_TEXT         VARCHAR(240),
  REVIEW_PLACE_AGY_LOC_ID       VARCHAR(6),
  REVIEW_SUP_LEVEL_TEXT         VARCHAR(240),
  MODIFY_USER_ID                VARCHAR(32),
  ASSESS_COMMITTE_CODE          VARCHAR(12),
  CREATION_DATE                 DATE,
  CREATION_USER                 VARCHAR(32),
  APPROVED_SUP_LEVEL_TYPE       VARCHAR(12),
  ASSESSMENT_CREATE_LOCATION    VARCHAR(6),
  ASSESSOR_STAFF_ID             DECIMAL(10, 0),
  MODIFY_DATETIME               TIMESTAMP(6),
  OVERRIDE_USER_ID              VARCHAR(32),
  OVERRIDE_REASON               VARCHAR(12),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);


CREATE TABLE ASSESSMENTS
(
  ASSESSMENT_ID                 DECIMAL(10, 0),
  ASSESSMENT_CLASS              VARCHAR(12),
  PARENT_ASSESSMENT_ID          DECIMAL(10, 0),
  ASSESSMENT_CODE               VARCHAR(20),
  DESCRIPTION                   VARCHAR(300),
  LIST_SEQ                      DECIMAL(6, 0),
  ACTIVE_FLAG                   VARCHAR(1)  DEFAULT 'Y',
  UPDATE_ALLOWED_FLAG           VARCHAR(1)  DEFAULT 'Y',
  EFFECTIVE_DATE                DATE,
  EXPIRY_DATE                   DATE,
  SCORE                         DECIMAL(8, 2),
  MUTUAL_EXCLUSIVE_FLAG         VARCHAR(1)  DEFAULT 'N',
  DETERMINE_SUP_LEVEL_FLAG      VARCHAR(1)  DEFAULT 'N',
  REQUIRE_EVALUATION_FLAG       VARCHAR(1)  DEFAULT 'N',
  REQUIRE_APPROVAL_FLAG         VARCHAR(1)  DEFAULT 'N',
  REVIEW_CYCLE_DAYS             DECIMAL(3, 0),
  CASELOAD_TYPE                 VARCHAR(12),
  REVIEW_FLAG                   VARCHAR(1)  DEFAULT 'N',
  ASSESS_COMMENT                VARCHAR(240),
  HIGH_VALUE                    DECIMAL(5, 2),
  LOW_VALUE                     DECIMAL(5, 2),
  SEARCH_CRITERIA_FLAG          VARCHAR(1)  DEFAULT 'N',
  OVERRIDEABLE_FLAG             VARCHAR(1)  DEFAULT 'N',
  ASSESSMENT_TYPE               VARCHAR(12),
  CALCULATE_TOTAL_FLAG          VARCHAR(1)  DEFAULT 'N',
  MEASURE                       VARCHAR(12),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  CREATE_DATE                   DATE,
  MODIFY_USER_ID                VARCHAR(32),
  MODIFY_DATETIME               TIMESTAMP(6),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CELL_SHARING_ALERT_FLAG       VARCHAR(1)  DEFAULT 'N',
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256),
  TOTAL_PERCENT                 DECIMAL(6, 2),
  REVERSE_SCORE                 DECIMAL(8, 2),
  SCREEN_CODE                   VARCHAR(40)
);


CREATE TABLE PROFILE_TYPES
(
  PROFILE_TYPE                  VARCHAR(12),
  PROFILE_CATEGORY              VARCHAR(12),
  DESCRIPTION                   VARCHAR(40),
  LIST_SEQ                      DECIMAL(6, 0),
  MANDATORY_FLAG                VARCHAR(1)  DEFAULT 'Y',
  UPDATED_ALLOWED_FLAG          VARCHAR(1)  DEFAULT 'Y',
  CODE_VALUE_TYPE               VARCHAR(12),
  ACTIVE_FLAG                   VARCHAR(1)  DEFAULT 'Y',
  EXPIRY_DATE                   DATE,
  MODIFY_USER_ID                VARCHAR(32),
  MODIFIED_DATE                 DATE,
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);


CREATE TABLE PROFILE_CODES
(
  PROFILE_TYPE                  VARCHAR(12),
  PROFILE_CODE                  VARCHAR(12),
  DESCRIPTION                   VARCHAR(40),
  LIST_SEQ                      DECIMAL(6, 0),
  UPDATE_ALLOWED_FLAG           VARCHAR(1)  DEFAULT 'Y',
  ACTIVE_FLAG                   VARCHAR(1)  DEFAULT 'Y',
  EXPIRY_DATE                   DATE,
  USER_ID                       VARCHAR(32),
  MODIFIED_DATE                 DATE,
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);
