CREATE SEQUENCE INTERNAL_LOCATION_ID START WITH 1 ;

CREATE TABLE AGENCY_LOCATIONS
(
  AGY_LOC_ID                    VARCHAR(6),
  DESCRIPTION                   VARCHAR(40),
  AGENCY_LOCATION_TYPE          VARCHAR(12),
  DISTRICT_CODE                 VARCHAR(12),
  UPDATED_ALLOWED_FLAG          VARCHAR(1)  DEFAULT 'Y',
  ABBREVIATION                  VARCHAR(12),
  DEACTIVATION_DATE             DATE,
  CONTACT_NAME                  VARCHAR(40),
  PRINT_QUEUE                   VARCHAR(240),
  JURISDICTION_CODE             VARCHAR(12),
  BAIL_OFFICE_FLAG              VARCHAR(1)  DEFAULT 'Y',
  LIST_SEQ                      DECIMAL(6, 0),
  HOUSING_LEV_1_CODE            VARCHAR(12),
  HOUSING_LEV_2_CODE            VARCHAR(12),
  HOUSING_LEV_3_CODE            VARCHAR(12),
  HOUSING_LEV_4_CODE            VARCHAR(12),
  PROPERTY_LEV_1_CODE           VARCHAR(12),
  PROPERTY_LEV_2_CODE           VARCHAR(12),
  PROPERTY_LEV_3_CODE           VARCHAR(12),
  LAST_BOOKING_NO               DECIMAL(10, 0),
  COMMISSARY_PRIVILEGE          VARCHAR(12),
  BUSINESS_HOURS                VARCHAR(40),
  ADDRESS_TYPE                  VARCHAR(12),
  SERVICE_REQUIRED_FLAG         VARCHAR(1)  DEFAULT NULL,
  ACTIVE_FLAG                   VARCHAR(1)  DEFAULT NULL,
  DISABILITY_ACCESS_CODE        VARCHAR(12),
  INTAKE_FLAG                   VARCHAR(1)  DEFAULT NULL,
  SUB_AREA_CODE                 VARCHAR(12),
  AREA_CODE                     VARCHAR(12),
  NOMS_REGION_CODE              VARCHAR(12),
  GEOGRAPHIC_REGION_CODE        VARCHAR(12),
  JUSTICE_AREA_CODE             VARCHAR(12),
  CJIT_CODE                     VARCHAR(12),
  LONG_DESCRIPTION              VARCHAR(3000),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE AGENCY_LOCATIONS ALTER AGY_LOC_ID SET NOT NULL;
ALTER TABLE AGENCY_LOCATIONS ALTER DESCRIPTION SET NOT NULL;
ALTER TABLE AGENCY_LOCATIONS ALTER UPDATED_ALLOWED_FLAG SET NOT NULL;
ALTER TABLE AGENCY_LOCATIONS ALTER BAIL_OFFICE_FLAG SET NOT NULL;
ALTER TABLE AGENCY_LOCATIONS ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE AGENCY_LOCATIONS ALTER CREATE_USER_ID SET NOT NULL;


CREATE TABLE AGENCY_INTERNAL_LOCATIONS
(
  INTERNAL_LOCATION_ID          DECIMAL(10, 0),
  INTERNAL_LOCATION_CODE        VARCHAR(12),
  AGY_LOC_ID                    VARCHAR(6),
  INTERNAL_LOCATION_TYPE        VARCHAR(12),
  DESCRIPTION                   VARCHAR(240),
  SECURITY_LEVEL_CODE           VARCHAR(12),
  CAPACITY                      DECIMAL(5, 0),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  PARENT_INTERNAL_LOCATION_ID   DECIMAL(10, 0),
  ACTIVE_FLAG                   VARCHAR(1)  DEFAULT 'Y',
  LIST_SEQ                      DECIMAL(6, 0),
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  CNA_NO                        DECIMAL(10, 0),
  CERTIFIED_FLAG                VARCHAR(1)  DEFAULT 'N',
  DEACTIVATE_DATE               DATE,
  REACTIVATE_DATE               DATE,
  DEACTIVATE_REASON_CODE        VARCHAR(12),
  COMMENT_TEXT                  VARCHAR(240),
  USER_DESC                     VARCHAR(40),
  ACA_CAP_RATING                DECIMAL(5, 0),
  UNIT_TYPE                     VARCHAR(12),
  OPERATION_CAPACITY            DECIMAL(5, 0),
  NO_OF_OCCUPANT                DECIMAL(10, 0)     DEFAULT 0,
  TRACKING_FLAG                 VARCHAR(1)  DEFAULT 'N',
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

CREATE UNIQUE INDEX AGENCY_INTERNAL_LOCATIONS_UK ON AGENCY_INTERNAL_LOCATIONS (AGY_LOC_ID, DESCRIPTION);

ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER INTERNAL_LOCATION_ID SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER INTERNAL_LOCATION_CODE SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER AGY_LOC_ID SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER INTERNAL_LOCATION_TYPE SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER DESCRIPTION SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER ACTIVE_FLAG SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER CERTIFIED_FLAG SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER TRACKING_FLAG SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE AGENCY_INTERNAL_LOCATIONS ALTER CREATE_USER_ID SET NOT NULL;


CREATE TABLE CASELOAD_AGENCY_LOCATIONS
(
  CASELOAD_ID                   VARCHAR(6),
  AGY_LOC_ID                    VARCHAR(6),
  UPDATE_ALLOWED_FLAG           VARCHAR(1)  DEFAULT 'Y',
  CREATE_DATETIME               TIMESTAMP(6)      DEFAULT now(),
  CREATE_USER_ID                VARCHAR(32) DEFAULT USER,
  MODIFY_DATETIME               TIMESTAMP(6),
  MODIFY_USER_ID                VARCHAR(32),
  AUDIT_TIMESTAMP               TIMESTAMP(6),
  AUDIT_USER_ID                 VARCHAR(32),
  AUDIT_MODULE_NAME             VARCHAR(65),
  AUDIT_CLIENT_USER_ID          VARCHAR(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR(256)
);

ALTER TABLE CASELOAD_AGENCY_LOCATIONS ALTER CASELOAD_ID SET NOT NULL;
ALTER TABLE CASELOAD_AGENCY_LOCATIONS ALTER AGY_LOC_ID SET NOT NULL;
ALTER TABLE CASELOAD_AGENCY_LOCATIONS ALTER UPDATE_ALLOWED_FLAG SET NOT NULL;
ALTER TABLE CASELOAD_AGENCY_LOCATIONS ALTER CREATE_DATETIME SET NOT NULL;
ALTER TABLE CASELOAD_AGENCY_LOCATIONS ALTER CREATE_USER_ID SET NOT NULL;
