FIND_LOCATION {
  SELECT A.INTERNAL_LOCATION_ID LOCATION_ID,
         A.INTERNAL_LOCATION_TYPE LOCATION_TYPE,
         A.DESCRIPTION,
         A.PARENT_INTERNAL_LOCATION_ID PARENT_LOCATION_ID,
         A.NO_OF_OCCUPANT CURRENT_OCCUPANCY,
         A.AGY_LOC_ID AGENCY_ID,
         A.USER_DESC USER_DESCRIPTION
  FROM AGENCY_INTERNAL_LOCATIONS A
         INNER JOIN CASELOAD_AGENCY_LOCATIONS C ON A.AGY_LOC_ID = C.AGY_LOC_ID
         INNER JOIN STAFF_USER_ACCOUNTS SUA ON C.CASELOAD_ID = SUA.WORKING_CASELOAD_ID
  WHERE A.ACTIVE_FLAG = 'Y'
    AND A.INTERNAL_LOCATION_ID = :locationId
    AND SUA.USERNAME = :username
}

GET_LOCATION {
  SELECT A.INTERNAL_LOCATION_ID LOCATION_ID,
         A.INTERNAL_LOCATION_TYPE LOCATION_TYPE,
         A.DESCRIPTION,
         A.PARENT_INTERNAL_LOCATION_ID PARENT_LOCATION_ID,
         A.NO_OF_OCCUPANT CURRENT_OCCUPANCY,
         A.AGY_LOC_ID AGENCY_ID,
         A.USER_DESC USER_DESCRIPTION
  FROM AGENCY_INTERNAL_LOCATIONS A
  WHERE A.ACTIVE_FLAG = 'Y'
    AND A.INTERNAL_LOCATION_ID = :locationId
}

FIND_LOCATIONS_BY_AGENCY_AND_TYPE {
  SELECT A.INTERNAL_LOCATION_ID LOCATION_ID,
         A.AGY_LOC_ID AGENCY_ID,
         A.INTERNAL_LOCATION_TYPE LOCATION_TYPE,
         A.DESCRIPTION,
         A.USER_DESC USER_DESCRIPTION,
         A.PARENT_INTERNAL_LOCATION_ID PARENT_LOCATION_ID,
         A.NO_OF_OCCUPANT CURRENT_OCCUPANCY
  FROM AGENCY_INTERNAL_LOCATIONS A
  WHERE A.ACTIVE_FLAG = 'Y'
    AND A.AGY_LOC_ID = :agencyId
    AND A.INTERNAL_LOCATION_TYPE = :locationType
}
