type:
  get-collection:
    responseSchemaCollection: <<responseSchemaCollection>>
    responseExampleCollection: <<responseExampleCollection>>
get:
  headers:
    ConfigDataHeader:
       displayName: ConfigDataHeader
       required: true
       example: "test01:10,test02:N"