#%RAML 1.0
title: New API
version: v1
baseUri: http://api.samplehost.com
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number

traits:
  searchable:
      queryParameters:
        query:
          description: |
            JSON array [{"field1","value1","operator1"},{"field2","value2","operator2"},...,{"fieldN","valueN","operatorN"}] <<description>>
          example: |
            <<example>>
  orderable:
    queryParameters:
      orderBy:
        description: |
          Order by field: <<fieldsList>>
        type: string
        required: false
      order:
        description: Order
        enum: [desc, asc]
        default: desc
        required: false
  pageable:
    queryParameters:
      offset:
        description: Skip over a number of elements by specifying an offset value for the query
        type: integer
        required: false
        example: 20
        default: 0
      limit:
        description: Limit the number of elements on the response
        type: integer
        required: false
        example: 80
        default: 10

# add authentication

/agencies:
  description: The collection of agencies in the system.
  get:
    is: [pageable]
    description: Returns the list of agencies viewable by the user
    securedBy: [oauth_2_0]
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "name" : "Pretrial Center",
                  "agencyId" : "1"
                },
                {
                  "name" : "Intake Center",
                  "agencyId" : "2"
                },
                {
                  "name" : "Springfield Prison",
                  "agencyId" : "3"
                },
                {
                  "name" : "Downtown Courts",
                  "agencyId" : "4"
                }
              ]

/locations:
  description: The collection of internal locations within an agency.
  get:
    description: Returns a list of locations for the specified agency.
    is: [
          searchable: {description : "", example : ""},
          orderable: {fieldsList : ""},
          pageable
        ]
    securedBy: [oauth_2_0]
    responses: 
      200:
        body:
          application/json:
            example: |
              [
                {
                  "name" : "Center Block",
                  "type": "Tier",
                  "housingLevel" : "1",
                  "capacity" : "50",
                  "locationId" : "1"
                },
                {
                  "name" : "North Wing",
                  "type": "Wing",
                  "housingLevel" : "2",
                  "capacity" : "25",
                  "parentLocationId" : "1",
                  "locationId" : "2"
                },
                {
                  "name" : "Cell 1",
                  "type": "Cell",
                  "housingLevel" : "3",
                  "capacity" : "1",
                  "parentLocationId" : "2",
                  "locationId" : "3"
                },
                {
                  "name" : "Downtown Courts",
                  "locationId" : "4"
                }
              ]

/locations/{locationId}:
  description: Returns details about the specified location
  get:
