#%RAML 1.0
title: New API
version: v1
baseUri: http://api.samplehost.com

traits: !include traits/traits.raml

# add authentication

/agencies:
  description: The collection of agencies in the system.
  get:
    is: [pageable]
    description: Returns the list of agencies viewable by the user
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "name" : "Pretrial Center",
                  "agencyId" : "1"
                },
                {
                  "name" : "Intake Center",
                  "agencyId" : "2"
                },
                {
                  "name" : "Springfield Prison",
                  "agencyId" : "3"
                },
                {
                  "name" : "Downtown Courts",
                  "agencyId" : "4"
                }
              ]

/locations:
  description: The collection of internal locations within an agency.
  get:
    description: Returns a list of locations for the specified agency.
    is: [
          searchable: {description : "", example : ""},
          orderable: {fieldsList : ""},
          pageable
        ]
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "name" : "Center Block",
                  "type": "Tier",
                  "housingLevel" : "1",
                  "capacity" : "50",
                  "agencyId" : "3",
                  "locationId" : "1"
                },
                {
                  "name" : "North Wing",
                  "type": "Wing",
                  "housingLevel" : "2",
                  "capacity" : "25",
                  "agencyId" : "3",
                  "parentLocationId" : "1",
                  "locationId" : "2"
                },
                {
                  "name" : "Cell 1",
                  "type": "Cell",
                  "housingLevel" : "3",
                  "capacity" : "1",
                  "agencyId" : "3",
                  "parentLocationId" : "2",
                  "locationId" : "3"
                },
                {
                  "name" : "Holding Pend",
                  "agencyId" : "4",
                  "locationId" : "4"
                }
              ]

/locations/{locationId}:
  description: Returns details about the specified location
  get:
    description: Returns details of the specified location.

/locations/{locationId}/movements:
  description: The collection of scheduled movements associated to the location.
  get:
    description: Returns the scheduled movements associated to the location.
    is: [
          searchable: {description : "", example : ""},
          orderable: {fieldsList : ""},
          pageable
        ]

/locations/{locationId}/inmates:
  description: The collection of inmates present at the specified location.
  get:
    description: Returns the inmates currently located at the location.
    is: [
          searchable: {description : "", example : ""},
          orderable: {fieldsList : ""},
          pageable
        ]

/locations/{locationId}/bedAssignments:
  description: The collection of assignable beds at the specified location. This method is only valid for living unit locations.
  get:
    description: Returns the assignable beds associated to the location.
    is: [
          searchable: {description : "", example : ""},
          orderable: {fieldsList : ""},
          pageable
        ]
    responses:
      200:
        # outline response
      404:
        description: Returned if the location does not support assignable beds. (i.e. not a living unit)

/inmates:
  description: The collection of inmates within the system.
  get:
    description: Returns the within the system.
    is: [
          searchable: {description : "", example : ""},
          orderable: {fieldsList : ""},
          pageable
        ]

/inmates/{inmateId}:
  description: The details specific to the specified inmate.
  get:
    description: Returns the inmate's details.

/inmates/{inmateId}/movements:
  description: The collection of scheduled movements associated to the inmate.
  get:
    description: Returns the scheduled movements associated to the inmate.
    is: [
          searchable: {description : "", example : ""},
          orderable: {fieldsList : ""},
          pageable
        ]
