CREATE TABLE OFFENDER_IDENTIFYING_MARKS
(
  "OFFENDER_BOOK_ID"              NUMBER(10, 0)                             NOT NULL,
  "ID_MARK_SEQ"                   NUMBER(6, 0)                              NOT NULL,
  "BODY_PART_CODE"                VARCHAR2(12 CHAR)                         NOT NULL,
  "MARK_TYPE"                     VARCHAR2(12 CHAR)                         NOT NULL,
  "SIDE_CODE"                     VARCHAR2(12 CHAR),
  "PART_ORIENTATION_CODE"         VARCHAR2(12 CHAR),
  "COMMENT_TEXT"                  VARCHAR2(240 CHAR),
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp    NOT NULL,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER            NOT NULL,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),

  CONSTRAINT OFFENDER_IDENTIFYING_MARKS PRIMARY KEY (OFFENDER_BOOK_ID, ID_MARK_SEQ),

  CONSTRAINT OFF_IM_OFF_BKG_F1 FOREIGN KEY (OFFENDER_BOOK_ID) REFERENCES OFFENDER_BOOKINGS(OFFENDER_BOOK_ID)
);