CREATE TABLE STAFF_LOCATION_ROLES
(   CAL_AGY_LOC_ID        VARCHAR2(6)                          NOT NULL,
    SAC_STAFF_ID          NUMBER(6)                            NOT NULL,
    FROM_DATE             DATE                                 NOT NULL,
    TO_DATE               DATE,
    POSITION              VARCHAR2(12)                         NOT NULL,
    ROLE                  VARCHAR2(12)                         NOT NULL,
    SCHEDULE_TYPE         VARCHAR2(12),
    HOURS_PER_WEEK        NUMBER(4,2),
    SUPERVISOR_AGY_LOC_ID VARCHAR2(6),
    SUPERVISOR_STAFF_ID   NUMBER(6),
    SUPERVISOR_FROM_DATE  DATE,
    SUPERVISOR_POSITION   VARCHAR2(12),
    SUPERVISOR_ROLE       VARCHAR2(12),
    STAFF_UNIT            VARCHAR2(12),
    CREATE_DATETIME       TIMESTAMP(9)   DEFAULT SYSTIMESTAMP  NOT NULL,
    CREATE_USER_ID        VARCHAR2(32)   DEFAULT user          NOT NULL,
    MODIFY_DATETIME       TIMESTAMP (9)  DEFAULT SYSTIMESTAMP,
    MODIFY_USER_ID        VARCHAR2(32),
    SEAL_FLAG             VARCHAR2(1),
    CONSTRAINT CHK_DATES CHECK (from_date <= nvl(to_date,from_date)),
    CONSTRAINT STAFF_LOCATION_ROLES_PK PRIMARY KEY (SAC_STAFF_ID, CAL_AGY_LOC_ID, FROM_DATE, POSITION, ROLE),
    CONSTRAINT STAFF_LR_STAFF_LR_FK1 FOREIGN KEY (SUPERVISOR_STAFF_ID, SUPERVISOR_AGY_LOC_ID, SUPERVISOR_FROM_DATE, SUPERVISOR_POSITION, SUPERVISOR_ROLE) REFERENCES STAFF_LOCATION_ROLES
);

CREATE INDEX STAFF_LOCATION_ROLES_NI1 ON STAFF_LOCATION_ROLES (SAC_STAFF_ID);
CREATE INDEX STAFF_LOCATION_ROLES_NI2 ON STAFF_LOCATION_ROLES (CAL_AGY_LOC_ID, FROM_DATE, TO_DATE);
CREATE INDEX STAFF_LOCATION_ROLES_NI3 ON STAFF_LOCATION_ROLES (SUPERVISOR_STAFF_ID, SUPERVISOR_AGY_LOC_ID, SUPERVISOR_FROM_DATE, SUPERVISOR_POSITION, SUPERVISOR_ROLE);
