CREATE TABLE REFERENCE_CODES
(
	DOMAIN                          VARCHAR2(12)                        NOT NULL,
	CODE                            VARCHAR2(12)                        NOT NULL,
	DESCRIPTION                     VARCHAR2(40)                        NOT NULL,
	LIST_SEQ                        NUMBER(6),
	ACTIVE_FLAG                     VARCHAR2(1)   DEFAULT 'Y'           NOT NULL,
	SYSTEM_DATA_FLAG                VARCHAR2(1)   DEFAULT 'Y'           NOT NULL,
	MODIFY_USER_ID                  VARCHAR2(32),
	EXPIRED_DATE                    DATE,
	NEW_CODE                        VARCHAR2(12),
	PARENT_CODE                     VARCHAR2(12),
	PARENT_DOMAIN                   VARCHAR2(12),
	CREATE_DATETIME                 TIMESTAMP(9)  DEFAULT SYSTIMESTAMP  NOT NULL,
	CREATE_USER_ID                  VARCHAR2(32)  DEFAULT USER          NOT NULL,
	MODIFY_DATETIME                 TIMESTAMP(9)  DEFAULT SYSTIMESTAMP,
	SEAL_FLAG                       VARCHAR2(1)
);

ALTER TABLE REFERENCE_CODES ADD PRIMARY KEY (DOMAIN, CODE);
ALTER TABLE REFERENCE_CODES ADD UNIQUE (DOMAIN, CODE, DESCRIPTION, ACTIVE_FLAG);
ALTER TABLE REFERENCE_CODES ADD FOREIGN KEY (DOMAIN) REFERENCES REFERENCE_DOMAINS;
