CREATE TABLE OMS_ROLES
(
  "ROLE_ID"                       NUMBER(10, 0),
  "ROLE_NAME"                     VARCHAR2(30 CHAR),
  "ROLE_SEQ"                      NUMBER(3, 0),
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "ROLE_CODE"                     VARCHAR2(30 CHAR),
  "PARENT_ROLE_CODE"              VARCHAR2(30 CHAR),
  "SEAL_FLAG"                     VARCHAR2(1 CHAR)
);

ALTER TABLE OMS_ROLES
  ADD CONSTRAINT USER_GROUPS_PK PRIMARY KEY (ROLE_ID);

ALTER TABLE OMS_ROLES
  ADD CONSTRAINT OMS_ROLES_UK UNIQUE (ROLE_CODE);

ALTER TABLE OMS_ROLES
  ADD CONSTRAINT USER_GROUPS_UK UNIQUE (ROLE_NAME);

ALTER TABLE OMS_ROLES
  ADD CONSTRAINT OMS_ROLES_OMS_ROLES_FK FOREIGN KEY (PARENT_ROLE_CODE) REFERENCES OMS_ROLES(ROLE_CODE);

CREATE INDEX OMS_ROLES_NI1
  ON OMS_ROLES (PARENT_ROLE_CODE);

ALTER TABLE "OMS_ROLES" ALTER "ROLE_ID" SET NOT NULL;
ALTER TABLE "OMS_ROLES" ALTER "ROLE_NAME" SET NOT NULL;
ALTER TABLE "OMS_ROLES" ALTER "CREATE_DATETIME" SET NOT NULL;
ALTER TABLE "OMS_ROLES" ALTER "CREATE_USER_ID" SET NOT NULL;
ALTER TABLE "OMS_ROLES" ALTER "ROLE_CODE" SET NOT NULL;
