#%RAML 1.0 DataType
description: Assessment
properties:
  bookingId:
    type: number
    (javaType): Long
    description: Offender Booking Id
  offenderNo:
    type: string
    description: Offender Number
  classificationCode:
    type: string
    description: Classification code
  classification:
    type: string
    description: Classification description
  assessmentCode:
    type: string
    description: Assessment Code
  assessmentDescription:
    type: string
    description: Assessment Desc
  cellSharingAlertFlag:
    type: boolean
    description: Cell Sharing Alert Flag
  assessmentDate:
    type: date-only
    description: Assessment Date
  nextReviewDate:
    type: date-only
    description: Next Review Date