#%RAML 1.0 DataType
description: Establishment roll count in and out numbers
properties:
  in:
    type: integer
    description: Number of prisoners arrived so far on given date
  out:
    type: integer
    description: Number of prisoners that have left so far on given date
