#%RAML 1.0 DataType
description: Reference Code
properties:
  domain:
    type: string
    description: Reference data item domain.
    example: MOVE_RSN
  code:
    type: string
    description: Reference data item code.
    example: SE
  description:
    type: string
    description: Reference data item description.
    example: Other Security Escort
  parentDomain?:
    type: string
    description: Parent reference data item domain.
    example: MOVE_TYPE
  parentCode?:
    type: string
    description: Parent reference data item code.
    example: TAP
  activeFlag:
    type: string
    description: Reference data item active indicator flag.
    example: Y
  subCodes?:
     type: ReferenceCode[]
     description: List of subordinate reference data items associated with this reference data item.