#%RAML 1.0 DataType
description: Agency Details
properties:
  agencyId:
   type: string
   description: Agency identifier.
  description:
   type: string
   description: Agency description.
  agencyType:
   type: string
   description: Agency type.