#%RAML 1.0 DataType
properties:
  locationId:
    type: integer
  locationType:
    type: string
  description:
    type: string
  parentLocationId:
    type: integer
  currentOccupancy:
    type: integer