#%RAML 1.0 DataType
properties:
  locationId:
    type: integer
  agencyId:
    type: string
  locationType:
    type: string
  description:
    type: string
  parentLocationId:
    type: integer
  operationalCapacity?:
    type: integer
  currentOccupancy:
    type: integer
  livingUnit:
    type: boolean
  housingUnitType?:
    type: string
  activeCountStatusCode?:
    enum: [I, R, C]
  activeCountId?:
    type: integer