#%RAML 1.0 DataType
description: Location Inmate Count
properties:
  conductByUserId:
    (javaType): Long
    description: Who did the count (staff ID)
  enteredByUserId:
    (javaType): Long
    description: Staff Id
  inmateCount:
    type: integer
    description: The number of inmates
  countReasonCode:
    type: string
    description: Reason for count
  comment?:
    type: string
    description: Comments
