#%RAML 1.0 DataType
description: Prisoner Details
properties:
  offenderNo:
   type: string
   description: Display Prisoner Number (UK is NOMS ID)
  title:
   type: string
   description: Title of the prisoner (e.g Mr)
  suffix:
   type: string
   description: Initials of prisoner
  firstName:
   type: string
   description: First name of the prisoner
  middleNames:
   type: string
   description: Middle name(s) of the prisoner
  lastName:
   type: string
   description: Last name of the prisoner
  dateOfBirth:
   type: date-only
   description: Date of Birth of prisoner in YYYY-MM-DD format
  gender:
   type: string
   description: Gender of the prisoner
  nationalities:
   type: string
   description: Nationality of the prisoner
  currentlyInPrison:
   type: string
   description: Flag to indicate if the person is currently in prison
  latestLocationId:
   type: string
   description: Latest location ID of a prisoner (if in prison)
  latestLocation:
   type: string
   description: Name of the prison where the prisoner resides (if in prison)
  pncNumber:
   type: string
   description: PNC Number
  croNumber:
   type: string
   description: CRO Number
  ethnicity:
   type: string
   description: Ethnicity of the prisoner
  birthCountry:
   type: string
   description: Country of birth of the prisoner
  religion:
   type: string
   description: Religion of the prisoner
  convictedStatus:
   type: string
   description: Status code of latest conviction
  imprisonmentStatus:
   type: string
   description: Imprisonment Status
  receptionDate:
   type: date-only
   description: Date received into the prison
  releaseDate:
   type: date-only
   description: Date of release from prison
  maritalStatus:
   type: string
   description: Marital Status
