#%RAML 1.0 DataType
properties:
  nomsId: string
  firstName: string
  middleNames: string
  lastName: string
  dateOfBirth: date-only
  gender: string
  nationalities: string
  pncNumber: string
  croNumber: string
  paroleNumbers: string
  ethnicity: string
  birthCountry: string
  religion: string
  receptionDate: date-only
  maritalStatus: string
