#%RAML 1.0 DataType
description: Prisoner Details
properties:
  offenderNo:
   type: string
   description:
  title:
   type: string
   description:
  suffix:
   type: string
   description:
  firstName:
   type: string
   description:
  middleNames:
   type: string
   description:
  lastName:
   type: string
   description:
  dateOfBirth:
   type: date-only
   description:
  gender:
   type: string
   description:
  nationalities:
   type: string
   description:
  currentlyInPrison:
   type: string
   description:
  latestLocationId:
   type: string
   description:
  latestLocation:
   type: string
   description:
  pncNumber:
   type: string
   description:
  croNumber:
   type: string
   description:
  ethnicity:
   type: string
   description:
  birthCountry:
   type: string
   description:
  religion:
   type: string
   description:
  convictedStatus:
   type: string
   description:
  imprisonmentStatus:
   type: string
   description:
  receptionDate:
   type: date-only
   description:
  releaseDate:
   type: date-only
   description:
  maritalStatus:
   type: string
   description:
