#%RAML 1.0 DataType
description: Reference Domain
properties:
  domainId:
    type: string
    description: Unique Domain Id for reference domain
    required: true
  description:
    type: string
    description: Description of the reference domain
    required: true
  parentDomainId:
    type: string
    description: Parent domain Id for this reference domain
