#%RAML 1.0 DataType
description: Sentence Details
properties:
  bookingId:
    type: integer
    description: Offender booking id.
  sentenceStartDate:
    type: date-only
    description: Sentence start date.
  additionalDaysAdded?:
    type: integer
    description: ADA - days added to sentence term due to adjustments.
  sentenceEndDate?:
    type: date-only
    description: SED - sentence end date.
  daysRemaining:
    type: integer
    description: Number of days remaining to release (from current date).
  conditionalReleaseDate?:
    type: date-only
    description: CRD - conditional release date for offender.
  automaticReleaseDate?:
    type: date-only
    description: ARD - automatic (unconditional) release date for offender.
  nonParoleDate?:
    type: date-only
    description: NPD - non-parole date for offender.
  paroleEligibilityDate?:
    type: date-only
    description: PED - date on which offender is eligible for parole.
  licenceExpiryDate?:
    type: date-only
    description: LED - date on which offender licence expires.
  homeDetentionCurfewEligibilityDate?:
    type: date-only
    description: HDCED - date on which offender will be eligible for home detention curfew.
  earlyTermDate?:
    type: date-only
    description: ETD - early term date for offender.
  midTermDate?:
    type: date-only
    description: MTD - mid term date for offender.
  lateTermDate?:
    type: date-only
    description: LTD - late term date for offender.
  releaseDate:
    type: date-only
    description: release date for offender (one of ARD, CRD, NPD, ETD, MTD or LTD).