#%RAML 1.0 DataType
description: Staff Details
properties:
  staffId:
    (javaType): Long
    description: Staff Id
  firstName:
    type: string
  lastName:
    type: string
  email?:
    type: string
  thumbnailId?:
    (javaType): Long
