INSERT INTO STATUTES (STATUTE_CODE, DESCRIPTION, LEGISLATING_BODY_CODE, ACTIVE_FLAG, LIST_SEQ, UPDATE_ALLOWED_FLAG) VALUES ('COML', 'Statute common law', 'UK', 'Y', 2, 'Y');
INSERT INTO STATUTES (STATUTE_CODE, DESCRIPTION, LEGISLATING_BODY_CODE, ACTIVE_FLAG, LIST_SEQ, UPDATE_ALLOWED_FLAG) VALUES ('STAT', 'Statute XXXX', 'UK', 'Y', 2, 'Y');

INSERT INTO OFFENCES (OFFENCE_CODE, STATUTE_CODE, DESCRIPTION, SEVERITY_RANKING, ACTIVE_FLAG, HO_CODE) VALUES ('COML025', 'COML', 'Murder', '700', 'Y', '815/90');
INSERT INTO OFFENCES (OFFENCE_CODE, STATUTE_CODE, DESCRIPTION, SEVERITY_RANKING, ACTIVE_FLAG, HO_CODE) VALUES ('STAT001', 'STAT', 'Test offence 1', '700', 'Y', '815/90');
