-- Active and inactive court case (for booking id -5)
INSERT INTO OFFENDER_CASES (CASE_ID, CASE_INFO_NUMBER, OFFENDER_BOOK_ID, CASE_TYPE, CASE_STATUS, BEGIN_DATE, AGY_LOC_ID,  STATUS_UPDATE_REASON, LIDS_CASE_NUMBER, CASE_SEQ) VALUES (-259951, 'TS9951A', -5, 'A', 'A', TO_DATE('2017-08-31', 'YYYY-MM-DD'), 'LEI', 'A', 1, 2);
INSERT INTO OFFENDER_CASES (CASE_ID, CASE_INFO_NUMBER, OFFENDER_BOOK_ID, CASE_TYPE, CASE_STATUS, BEGIN_DATE, AGY_LOC_ID,  STATUS_UPDATE_REASON, LIDS_CASE_NUMBER, CASE_SEQ) VALUES (-259952, 'TS9951A', -5, 'A', 'I', TO_DATE('2017-08-31', 'YYYY-MM-DD'), 'LEI', 'A', 1, 3);
