INSERT INTO STATUTES (STATUTE_CODE, DESCRIPTION, LEGISLATING_BODY_CODE, ACTIVE_FLAG, LIST_SEQ, UPDATE_ALLOWED_FLAG) VALUES ('COML', 'Statute common law', 'UK', 'Y', 2, 'Y');

INSERT INTO OFFENCES (OFFENCE_CODE, STATUTE_CODE, DESCRIPTION, SEVERITY_RANKING, ACTIVE_FLAG, HO_CODE, EXPIRY_DATE) VALUES ('COML025', 'COML', 'Murder', '700', 'Y', '815/90', NULL);
INSERT INTO OFFENCES (OFFENCE_CODE, STATUTE_CODE, DESCRIPTION, SEVERITY_RANKING, ACTIVE_FLAG, HO_CODE, EXPIRY_DATE) VALUES ('COML026', 'COML', 'Manslaughter', '700', 'N', '815/90', TO_DATE('2023-01-01', 'YYYY-MM-DD'));
