DELETE FROM AGENCY_INCIDENT_CHARGES WHERE agency_incident_id = -3003;
DELETE FROM AGENCY_INCIDENT_PARTIES WHERE agency_incident_id = -3003;
DELETE FROM AGENCY_INCIDENTS WHERE agency_incident_id = -3003;
