-- Test data for recall and classification fields
-- This file populates test sentences with various recall and classification combinations

-- Insert test offender bookings if they don't exist
INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, AGY_LOC_ID, LIVING_UNIT_ID, ROOT_OFFENDER_ID, BOOKING_STATUS, STATUS_REASON, BOOKING_TYPE, IN_OUT_STATUS, ACTIVE_FLAG, BOOKING_SEQ)
SELECT -1, DATE '2020-01-01', 'A00001', -1, 'LEI', -1, -1, 'O', 'ADM', 'INST', 'IN', 'Y', 1 
FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_BOOKINGS WHERE OFFENDER_BOOK_ID = -1);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, AGY_LOC_ID, LIVING_UNIT_ID, ROOT_OFFENDER_ID, BOOKING_STATUS, STATUS_REASON, BOOKING_TYPE, IN_OUT_STATUS, ACTIVE_FLAG, BOOKING_SEQ)
SELECT -2, DATE '2020-01-01', 'A00002', -2, 'LEI', -2, -2, 'O', 'ADM', 'INST', 'IN', 'Y', 1 
FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_BOOKINGS WHERE OFFENDER_BOOK_ID = -2);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, AGY_LOC_ID, LIVING_UNIT_ID, ROOT_OFFENDER_ID, BOOKING_STATUS, STATUS_REASON, BOOKING_TYPE, IN_OUT_STATUS, ACTIVE_FLAG, BOOKING_SEQ)
SELECT -3, DATE '2020-01-01', 'A00003', -3, 'LEI', -3, -3, 'O', 'ADM', 'INST', 'IN', 'Y', 1 
FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_BOOKINGS WHERE OFFENDER_BOOK_ID = -3);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, AGY_LOC_ID, LIVING_UNIT_ID, ROOT_OFFENDER_ID, BOOKING_STATUS, STATUS_REASON, BOOKING_TYPE, IN_OUT_STATUS, ACTIVE_FLAG, BOOKING_SEQ)
SELECT -4, DATE '2020-01-01', 'A00004', -4, 'LEI', -4, -4, 'O', 'ADM', 'INST', 'IN', 'Y', 1 
FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_BOOKINGS WHERE OFFENDER_BOOK_ID = -4);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, AGY_LOC_ID, LIVING_UNIT_ID, ROOT_OFFENDER_ID, BOOKING_STATUS, STATUS_REASON, BOOKING_TYPE, IN_OUT_STATUS, ACTIVE_FLAG, BOOKING_SEQ)
SELECT -5, DATE '2020-01-01', 'A00005', -5, 'LEI', -5, -5, 'O', 'ADM', 'INST', 'IN', 'Y', 1 
FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_BOOKINGS WHERE OFFENDER_BOOK_ID = -5);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, AGY_LOC_ID, LIVING_UNIT_ID, ROOT_OFFENDER_ID, BOOKING_STATUS, STATUS_REASON, BOOKING_TYPE, IN_OUT_STATUS, ACTIVE_FLAG, BOOKING_SEQ)
SELECT -6, DATE '2020-01-01', 'A00006', -6, 'LEI', -6, -6, 'O', 'ADM', 'INST', 'IN', 'Y', 1 
FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_BOOKINGS WHERE OFFENDER_BOOK_ID = -6);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, AGY_LOC_ID, LIVING_UNIT_ID, ROOT_OFFENDER_ID, BOOKING_STATUS, STATUS_REASON, BOOKING_TYPE, IN_OUT_STATUS, ACTIVE_FLAG, BOOKING_SEQ)
SELECT -7, DATE '2020-01-01', 'A00007', -7, 'LEI', -7, -7, 'O', 'ADM', 'INST', 'IN', 'Y', 1 
FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_BOOKINGS WHERE OFFENDER_BOOK_ID = -7);

-- Insert test court cases
INSERT INTO OFFENDER_CASES (CASE_ID, OFFENDER_BOOK_ID, CASE_INFO_NUMBER, CASE_SEQ, CASE_STATUS, CASE_TYPE, BEGIN_DATE, AGY_LOC_ID)
SELECT -1, -1, 'TEST001', 1, 'A', 'A', DATE '2020-01-01', 'COURT1' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_CASES WHERE CASE_ID = -1);

INSERT INTO OFFENDER_CASES (CASE_ID, OFFENDER_BOOK_ID, CASE_INFO_NUMBER, CASE_SEQ, CASE_STATUS, CASE_TYPE, BEGIN_DATE, AGY_LOC_ID)
SELECT -2, -2, 'TEST002', 1, 'A', 'A', DATE '2020-01-01', 'COURT1' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_CASES WHERE CASE_ID = -2);

INSERT INTO OFFENDER_CASES (CASE_ID, OFFENDER_BOOK_ID, CASE_INFO_NUMBER, CASE_SEQ, CASE_STATUS, CASE_TYPE, BEGIN_DATE, AGY_LOC_ID)
SELECT -3, -3, 'TEST003', 1, 'A', 'A', DATE '2020-01-01', 'COURT1' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_CASES WHERE CASE_ID = -3);

INSERT INTO OFFENDER_CASES (CASE_ID, OFFENDER_BOOK_ID, CASE_INFO_NUMBER, CASE_SEQ, CASE_STATUS, CASE_TYPE, BEGIN_DATE, AGY_LOC_ID)
SELECT -4, -4, 'TEST004', 1, 'A', 'A', DATE '2020-01-01', 'COURT1' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_CASES WHERE CASE_ID = -4);

INSERT INTO OFFENDER_CASES (CASE_ID, OFFENDER_BOOK_ID, CASE_INFO_NUMBER, CASE_SEQ, CASE_STATUS, CASE_TYPE, BEGIN_DATE, AGY_LOC_ID)
SELECT -5, -5, 'TEST005', 1, 'A', 'A', DATE '2020-01-01', 'COURT1' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_CASES WHERE CASE_ID = -5);

INSERT INTO OFFENDER_CASES (CASE_ID, OFFENDER_BOOK_ID, CASE_INFO_NUMBER, CASE_SEQ, CASE_STATUS, CASE_TYPE, BEGIN_DATE, AGY_LOC_ID)
SELECT -6, -6, 'TEST006', 1, 'A', 'A', DATE '2020-01-01', 'COURT1' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_CASES WHERE CASE_ID = -6);

INSERT INTO OFFENDER_CASES (CASE_ID, OFFENDER_BOOK_ID, CASE_INFO_NUMBER, CASE_SEQ, CASE_STATUS, CASE_TYPE, BEGIN_DATE, AGY_LOC_ID)
SELECT -7, -7, 'TEST007', 1, 'A', 'A', DATE '2020-01-01', 'COURT1' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM OFFENDER_CASES WHERE CASE_ID = -7);

-- Insert test court orders
INSERT INTO ORDERS (ORDER_ID, OFFENDER_BOOK_ID, CASE_ID, COURT_DATE, OUTCOME_REASON_CODE, ISSUED_BY_COURT, COURT_EVENT_ID, ORDER_STATUS, ORDER_TYPE)
SELECT -1, -1, -1, DATE '2020-01-01', 'CONV', 'Y', -1, 'A', 'S' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ORDERS WHERE ORDER_ID = -1);

INSERT INTO ORDERS (ORDER_ID, OFFENDER_BOOK_ID, CASE_ID, COURT_DATE, OUTCOME_REASON_CODE, ISSUED_BY_COURT, COURT_EVENT_ID, ORDER_STATUS, ORDER_TYPE)
SELECT -2, -2, -2, DATE '2020-01-01', 'CONV', 'Y', -2, 'A', 'S' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ORDERS WHERE ORDER_ID = -2);

INSERT INTO ORDERS (ORDER_ID, OFFENDER_BOOK_ID, CASE_ID, COURT_DATE, OUTCOME_REASON_CODE, ISSUED_BY_COURT, COURT_EVENT_ID, ORDER_STATUS, ORDER_TYPE)
SELECT -3, -3, -3, DATE '2020-01-01', 'CONV', 'Y', -3, 'A', 'S' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ORDERS WHERE ORDER_ID = -3);

INSERT INTO ORDERS (ORDER_ID, OFFENDER_BOOK_ID, CASE_ID, COURT_DATE, OUTCOME_REASON_CODE, ISSUED_BY_COURT, COURT_EVENT_ID, ORDER_STATUS, ORDER_TYPE)
SELECT -4, -4, -4, DATE '2020-01-01', 'CONV', 'Y', -4, 'A', 'S' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ORDERS WHERE ORDER_ID = -4);

INSERT INTO ORDERS (ORDER_ID, OFFENDER_BOOK_ID, CASE_ID, COURT_DATE, OUTCOME_REASON_CODE, ISSUED_BY_COURT, COURT_EVENT_ID, ORDER_STATUS, ORDER_TYPE)
SELECT -5, -5, -5, DATE '2020-01-01', 'CONV', 'Y', -5, 'A', 'S' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ORDERS WHERE ORDER_ID = -5);

INSERT INTO ORDERS (ORDER_ID, OFFENDER_BOOK_ID, CASE_ID, COURT_DATE, OUTCOME_REASON_CODE, ISSUED_BY_COURT, COURT_EVENT_ID, ORDER_STATUS, ORDER_TYPE)
SELECT -6, -6, -6, DATE '2020-01-01', 'CONV', 'Y', -6, 'A', 'S' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ORDERS WHERE ORDER_ID = -6);

INSERT INTO ORDERS (ORDER_ID, OFFENDER_BOOK_ID, CASE_ID, COURT_DATE, OUTCOME_REASON_CODE, ISSUED_BY_COURT, COURT_EVENT_ID, ORDER_STATUS, ORDER_TYPE)
SELECT -7, -7, -7, DATE '2020-01-01', 'CONV', 'Y', -7, 'A', 'S' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ORDERS WHERE ORDER_ID = -7);

-- Insert test sentences with recall and classification data

-- Booking -1: Mixed sentences for comprehensive test
INSERT INTO OFFENDER_SENTENCES (OFFENDER_BOOK_ID, SENTENCE_SEQ, ORDER_ID, CASE_ID, SENTENCE_STATUS, SENTENCE_CALC_TYPE, SENTENCE_CATEGORY, START_DATE, IS_RECALLABLE, SENTENCE_CLASSIFICATION)
VALUES (-1, 1, -1, -1, 'A', 'ADIMP_ORA', '2003', DATE '2020-01-01', 'Y', 'STANDARD');

INSERT INTO OFFENDER_SENTENCES (OFFENDER_BOOK_ID, SENTENCE_SEQ, ORDER_ID, CASE_ID, SENTENCE_STATUS, SENTENCE_CALC_TYPE, SENTENCE_CATEGORY, START_DATE, IS_RECALLABLE, SENTENCE_CLASSIFICATION)
VALUES (-1, 2, -1, -1, 'A', 'FTR_ORA', '2003', DATE '2020-01-01', 'Y', 'RECALL');

-- Booking -2: Standard Determinate Sentence
INSERT INTO OFFENDER_SENTENCES (OFFENDER_BOOK_ID, SENTENCE_SEQ, ORDER_ID, CASE_ID, SENTENCE_STATUS, SENTENCE_CALC_TYPE, SENTENCE_CATEGORY, START_DATE, IS_RECALLABLE, SENTENCE_CLASSIFICATION)
VALUES (-2, 1, -2, -2, 'A', 'ADIMP_ORA', '2003', DATE '2020-01-01', 'Y', 'STANDARD');

-- Booking -3: Fixed Term Recall
INSERT INTO OFFENDER_SENTENCES (OFFENDER_BOOK_ID, SENTENCE_SEQ, ORDER_ID, CASE_ID, SENTENCE_STATUS, SENTENCE_CALC_TYPE, SENTENCE_CATEGORY, START_DATE, IS_RECALLABLE, SENTENCE_CLASSIFICATION)
VALUES (-3, 1, -3, -3, 'A', 'FTR_ORA', '2003', DATE '2020-01-01', 'Y', 'RECALL');

-- Booking -4: Fine (not recallable)
INSERT INTO OFFENDER_SENTENCES (OFFENDER_BOOK_ID, SENTENCE_SEQ, ORDER_ID, CASE_ID, SENTENCE_STATUS, SENTENCE_CALC_TYPE, SENTENCE_CATEGORY, START_DATE, FINE_AMOUNT, IS_RECALLABLE, SENTENCE_CLASSIFICATION)
VALUES (-4, 1, -4, -4, 'A', 'A/FINE', '2003', DATE '2020-01-01', 500.00, 'N', 'FINE');

-- Booking -5: Extended Sentence
INSERT INTO OFFENDER_SENTENCES (OFFENDER_BOOK_ID, SENTENCE_SEQ, ORDER_ID, CASE_ID, SENTENCE_STATUS, SENTENCE_CALC_TYPE, SENTENCE_CATEGORY, START_DATE, IS_RECALLABLE, SENTENCE_CLASSIFICATION)
VALUES (-5, 1, -5, -5, 'A', 'CUR_ORA', '2003', DATE '2020-01-01', 'Y', 'EXTENDED');

-- Booking -6: Multiple sentences (Standard, Life, Fine)
INSERT INTO OFFENDER_SENTENCES (OFFENDER_BOOK_ID, SENTENCE_SEQ, ORDER_ID, CASE_ID, SENTENCE_STATUS, SENTENCE_CALC_TYPE, SENTENCE_CATEGORY, START_DATE, IS_RECALLABLE, SENTENCE_CLASSIFICATION)
VALUES (-6, 1, -6, -6, 'A', 'ADIMP', '2020', DATE '2020-01-01', 'Y', 'STANDARD');

INSERT INTO OFFENDER_SENTENCES (OFFENDER_BOOK_ID, SENTENCE_SEQ, ORDER_ID, CASE_ID, SENTENCE_STATUS, SENTENCE_CALC_TYPE, SENTENCE_CATEGORY, START_DATE, IS_RECALLABLE, SENTENCE_CLASSIFICATION)
VALUES (-6, 2, -6, -6, 'A', 'LIFE', '2003', DATE '2020-01-01', 'Y', 'INDETERMINATE');

INSERT INTO OFFENDER_SENTENCES (OFFENDER_BOOK_ID, SENTENCE_SEQ, ORDER_ID, CASE_ID, SENTENCE_STATUS, SENTENCE_CALC_TYPE, SENTENCE_CATEGORY, START_DATE, FINE_AMOUNT, IS_RECALLABLE, SENTENCE_CLASSIFICATION)
VALUES (-6, 3, -6, -6, 'A', 'A/FINE', '2003', DATE '2020-01-01', 250.00, 'N', 'FINE');

-- Booking -7: Sentence with null classification
INSERT INTO OFFENDER_SENTENCES (OFFENDER_BOOK_ID, SENTENCE_SEQ, ORDER_ID, CASE_ID, SENTENCE_STATUS, SENTENCE_CALC_TYPE, SENTENCE_CATEGORY, START_DATE, IS_RECALLABLE, SENTENCE_CLASSIFICATION)
VALUES (-7, 1, -7, -7, 'A', 'TEST', 'TEST', DATE '2020-01-01', 'N', NULL);