INSERT INTO STAFF_MEMBERS (STAFF_ID, ASSIGNED_CASELOAD_ID, WORKING_CASELOAD_ID, USER_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME)
VALUES (-1, 'LEI', 'LEI', 'ELITE2_API_USER', 'USER', 'ELITE2', 'API');
INSERT INTO STAFF_MEMBERS (STAFF_ID, ASSIGNED_CASELOAD_ID, WORKING_CASELOAD_ID, USER_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME)
VALUES (-2, 'LEI', 'LEI', 'MWILLIS_GEN', 'WILLIS', 'JOHN', 'MICHAEL');

INSERT INTO STAFF_USER_ACCOUNTS (USERNAME, STAFF_ID, WORKING_CASELOAD_ID) VALUES ('ELITE2_API_USER', -1, 'LEI');
INSERT INTO STAFF_USER_ACCOUNTS (USERNAME, STAFF_ID, WORKING_CASELOAD_ID) VALUES ('MWILLIS_GEN', -2, 'LEI');

INSERT INTO STAFF_MEMBER_ROLES (STAFF_ID, ROLE_ID, ROLE_CODE) VALUES (-1, -1, 'ADMIN');

INSERT INTO INTERNET_ADDRESSES (INTERNET_ADDRESS_ID, OWNER_ID, OWNER_CLASS, INTERNET_ADDRESS_CLASS, INTERNET_ADDRESS)
VALUES (-1, -1, 'STF', 'EMAIL', 'elite2-api-user@syscon.net');
INSERT INTO INTERNET_ADDRESSES (INTERNET_ADDRESS_ID, OWNER_ID, OWNER_CLASS, INTERNET_ADDRESS_CLASS, INTERNET_ADDRESS)
VALUES (-2, -2, 'STF', 'EMAIL', 'Michael.Willis@syscon.net');

INSERT INTO USER_CASELOAD_ROLES (ROLE_ID, USERNAME, CASELOAD_ID)
VALUES (-1, 'ELITE2_API_USER', 'LEI');
INSERT INTO USER_CASELOAD_ROLES (ROLE_ID, USERNAME, CASELOAD_ID)
VALUES (-2, 'MWILLIS_GEN', 'LEI');

INSERT INTO OMS_ROLES (ROLE_ID, ROLE_NAME, ROLE_SEQ, ROLE_CODE, PARENT_ROLE_CODE)
VALUES ( -1, 'Administrator', 1, 'ADMIN', null);
INSERT INTO OMS_ROLES (ROLE_ID, ROLE_NAME, ROLE_SEQ, ROLE_CODE, PARENT_ROLE_CODE)
VALUES ( -2, 'Wing Officer', 1, 'WING_OFF', null);
