INSERT INTO AGENCY_LOCATIONS (AGY_LOC_ID, DESCRIPTION, AGENCY_LOCATION_TYPE, ACTIVE_FLAG) VALUES ('LT1', 'Licence Test Prison', 'INST', 'Y');
INSERT INTO AGENCY_LOCATIONS (AGY_LOC_ID, DESCRIPTION, AGENCY_LOCATION_TYPE, ACTIVE_FLAG) VALUES ('LT2', 'Licence Auto Test Prison', 'INST', 'Y');

INSERT INTO AGENCY_LOCATIONS (AGY_LOC_ID, DESCRIPTION, AGENCY_LOCATION_TYPE, ACTIVE_FLAG) VALUES ('COURT1', 'Court 1', 'CRT', 'Y');

INSERT INTO CASELOADS (CASELOAD_ID, DESCRIPTION, CASELOAD_TYPE, LIST_SEQ, TRUST_ACCOUNTS_FLAG, ACCESS_PROPERTY_FLAG, ACTIVE_FLAG, CASELOAD_FUNCTION) VALUES ('LT1', 'Licence Test Prison', 'INST', 1, 'N', 'Y', 'Y', 'DUMMY');
INSERT INTO CASELOADS (CASELOAD_ID, DESCRIPTION, CASELOAD_TYPE, LIST_SEQ, TRUST_ACCOUNTS_FLAG, ACCESS_PROPERTY_FLAG, ACTIVE_FLAG, CASELOAD_FUNCTION) VALUES ('LT2', 'Licence Auto Test Prison', 'INST', 2, 'N', 'Y', 'Y', 'DUMMY');


INSERT INTO CASELOAD_AGENCY_LOCATIONS (CASELOAD_ID, AGY_LOC_ID) VALUES ('LT1', 'LT1');
INSERT INTO CASELOAD_AGENCY_LOCATIONS (CASELOAD_ID, AGY_LOC_ID) VALUES ('LT1', 'OUT');
INSERT INTO CASELOAD_AGENCY_LOCATIONS (CASELOAD_ID, AGY_LOC_ID) VALUES ('LT1', 'TRN');

INSERT INTO CASELOAD_AGENCY_LOCATIONS (CASELOAD_ID, AGY_LOC_ID) VALUES ('LT2', 'LT2');
INSERT INTO CASELOAD_AGENCY_LOCATIONS (CASELOAD_ID, AGY_LOC_ID) VALUES ('LT2', 'OUT');
INSERT INTO CASELOAD_AGENCY_LOCATIONS (CASELOAD_ID, AGY_LOC_ID) VALUES ('LT2', 'TRN');


