--Wings LT1
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, USER_DESC) VALUES (-11, 'A', 'WING', 'LT1', 'LT1-A', null, 'House Block A');

--Wings LT2
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, USER_DESC) VALUES (-21, 'A', 'WING', 'LT2', 'LT2-A', null, 'Wing A');


-- Landings for all each agency, there are 2 landings for each wing except in LT1 where there are 3 landings

-- Landings LT1
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111, '1', 'LAND', 'LT2', 'LT1-A-1', -11, 0);


-- Landings LT2
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211, '1', 'LAND', 'LT2', 'LT2-A-1', -21, 0);



--
-- Cells for each prison, 5 Cells per landing.
--

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111001, '001', 'CELL', 'LT1', 'LT1-A-1-1', -111, 1);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111002, '002', 'CELL', 'LT1', 'LT1-A-1-2', -111, 1);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111003, '003', 'CELL', 'LT1', 'LT1-A-1-3', -111, 1);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111004, '004', 'CELL', 'LT1', 'LT1-A-1-4', -111, 1);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111005, '005', 'CELL', 'LT1', 'LT1-A-1-5', -111, 1);

INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211001, '001', 'CELL', 'LT2', 'LT2-A-1-1', -211, 1);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211002, '002', 'CELL', 'LT2', 'LT2-A-1-2', -211, 1);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211003, '003', 'CELL', 'LT2', 'LT2-A-1-3', -211, 1);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211004, '004', 'CELL', 'LT2', 'LT2-A-1-4', -211, 1);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211005, '005', 'CELL', 'LT2', 'LT2-A-1-5', -211, 1);
