INSERT INTO PERSONS (PERSON_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME) VALUES (-1, 'SMITH', 'JESSY', NULL);

INSERT INTO PERSONS (PERSON_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME) VALUES (-2, 'JONES', 'JESSY', NULL);


INSERT INTO OFFENDER_CONTACT_PERSONS (OFFENDER_BOOK_ID, PERSON_ID, CONTACT_TYPE, RELATIONSHIP_TYPE, EMERGENCY_CONTACT_FLAG, NEXT_OF_KIN_FLAG, ACTIVE_FLAG, OFFENDER_CONTACT_PERSON_ID)
VALUES
  (-1, -1, 'O', 'COM', 'N', 'N', 'Y', -100);

INSERT INTO OFFENDER_CONTACT_PERSONS (OFFENDER_BOOK_ID, PERSON_ID, CONTACT_TYPE, RELATIONSHIP_TYPE, EMERGENCY_CONTACT_FLAG, NEXT_OF_KIN_FLAG, ACTIVE_FLAG, OFFENDER_CONTACT_PERSON_ID)
VALUES
  (-2, -2, 'O', 'COM', 'N', 'N', 'Y', -101);

INSERT INTO PERSON_IDENTIFIERS (PERSON_ID,ID_SEQ,IDENTIFIER_TYPE,IDENTIFIER)
VALUES (-1, 1, 'EXTERNAL_REL', 'RO_USER');


INSERT INTO PERSON_IDENTIFIERS (PERSON_ID,ID_SEQ,IDENTIFIER_TYPE,IDENTIFIER)
VALUES (-2, 1, 'EXTERNAL_REL', 'RO_USER_TEST');