--Wings AG1
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-11, 'A', 'WING', 'AG1', 'AG1-A', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-12, 'B', 'WING', 'AG1', 'AG1-B', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-13, 'C', 'WING', 'AG1', 'AG1-C', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-14, 'D', 'WING', 'AG1', 'AG1-D', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-15, 'E', 'WING', 'AG1', 'AG1-E', null, 0);

--Wings AG2
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-21, 'A', 'WING', 'AG2', 'AG2-A', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-22, 'B', 'WING', 'AG2', 'AG2-B', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-23, 'C', 'WING', 'AG2', 'AG2-C', null, 0);

--Wings AG3
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-31, 'A', 'WING', 'AG3', 'AG3-A', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-32, 'B', 'WING', 'AG3', 'AG3-B', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-33, 'C', 'WING', 'AG3', 'AG3-C', null, 0);

--Wings AG4
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-41, 'A', 'WING', 'AG4', 'AG4-A', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-42, 'B', 'WING', 'AG4', 'AG4-B', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-43, 'C', 'WING', 'AG4', 'AG4-C', null, 0);

--Wings AG5
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-51, 'A', 'WING', 'AG5', 'AG5-A', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-52, 'B', 'WING', 'AG5', 'AG5-B', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-53, 'C', 'WING', 'AG5', 'AG5-C', null, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-54, 'D', 'WING', 'AG5', 'AG5-D', null, 0);

-- Landings for all each agency, there are 2 landings for each wing except in AG1 where there are 3 landings

-- Landings AG1
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111, '1', 'LAND', 'AG1', 'AG1-A-1', -11, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-112, '2', 'LAND', 'AG1', 'AG1-A-2', -11, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-113, '3', 'LAND', 'AG1', 'AG1-A-3', -11, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-121, '1', 'LAND', 'AG1', 'AG1-B-1', -12, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-122, '2', 'LAND', 'AG1', 'AG1-B-2', -12, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-123, '3', 'LAND', 'AG1', 'AG1-B-3', -12, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-131, '1', 'LAND', 'AG1', 'AG1-C-1', -13, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-132, '2', 'LAND', 'AG1', 'AG1-C-2', -13, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-133, '3', 'LAND', 'AG1', 'AG1-C-3', -13, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-141, '1', 'LAND', 'AG1', 'AG1-D-1', -14, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-142, '2', 'LAND', 'AG1', 'AG1-D-2', -14, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-143, '3', 'LAND', 'AG1', 'AG1-D-3', -14, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-151, '1', 'LAND', 'AG1', 'AG1-E-1', -15, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-152, '2', 'LAND', 'AG1', 'AG1-E-2', -15, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-153, '3', 'LAND', 'AG1', 'AG1-E-3', -15, 0);


-- Landings AG2
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211, '1', 'LAND', 'AG2', 'AG2-A-1', -21, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-212, '2', 'LAND', 'AG2', 'AG2-A-2', -21, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-221, '1', 'LAND', 'AG2', 'AG2-B-1', -22, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-222, '2', 'LAND', 'AG2', 'AG2-B-2', -22, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-231, '1', 'LAND', 'AG2', 'AG2-C-1', -23, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-232, '2', 'LAND', 'AG2', 'AG2-C-2', -23, 0);


-- Landings AG3
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-311, '1', 'LAND', 'AG3', 'AG3-A-1', -31, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-312, '2', 'LAND', 'AG3', 'AG3-A-2', -31, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-321, '1', 'LAND', 'AG3', 'AG3-B-1', -32, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-322, '2', 'LAND', 'AG3', 'AG3-B-2', -32, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-331, '1', 'LAND', 'AG3', 'AG3-C-1', -33, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-332, '2', 'LAND', 'AG3', 'AG3-C-2', -33, 0);


-- Landings AG4
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-411, '1', 'LAND', 'AG4', 'AG4-A-1', -41, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-412, '2', 'LAND', 'AG4', 'AG4-A-2', -41, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-421, '1', 'LAND', 'AG4', 'AG4-B-1', -42, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-422, '2', 'LAND', 'AG4', 'AG4-B-2', -42, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-431, '1', 'LAND', 'AG4', 'AG4-C-1', -43, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-432, '2', 'LAND', 'AG4', 'AG4-C-2', -43, 0);


-- Landings AG5
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-511, '1', 'LAND', 'AG5', 'AG5-A-1', -51, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-512, '2', 'LAND', 'AG5', 'AG5-A-2', -51, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-521, '1', 'LAND', 'AG5', 'AG5-B-1', -52, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-522, '2', 'LAND', 'AG5', 'AG5-B-2', -52, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-531, '1', 'LAND', 'AG5', 'AG5-C-1', -53, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-532, '2', 'LAND', 'AG5', 'AG5-C-2', -53, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-541, '1', 'LAND', 'AG5', 'AG5-D-1', -54, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-542, '2', 'LAND', 'AG5', 'AG5-D-2', -54, 0);

--
-- Cells for each agency, 5 Cells per landing.
--

-- Cells AG1 Wing A Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111001, '001', 'CELL', 'AG1', 'AG1-A-1-001', -111, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111002, '002', 'CELL', 'AG1', 'AG1-A-1-002', -111, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111003, '003', 'CELL', 'AG1', 'AG1-A-1-003', -111, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111004, '004', 'CELL', 'AG1', 'AG1-A-1-004', -111, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-111005, '005', 'CELL', 'AG1', 'AG1-A-1-005', -111, 0);

-- Cells AG1 Wing A Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-112001, '001', 'CELL', 'AG1', 'AG1-A-2-001', -112, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-112002, '002', 'CELL', 'AG1', 'AG1-A-2-002', -112, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-112003, '003', 'CELL', 'AG1', 'AG1-A-2-003', -112, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-112004, '004', 'CELL', 'AG1', 'AG1-A-2-004', -112, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-112005, '005', 'CELL', 'AG1', 'AG1-A-2-005', -112, 0);

-- Cells AG1 Wing A Land 3 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-113001, '001', 'CELL', 'AG1', 'AG1-A-3-001', -113, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-113002, '002', 'CELL', 'AG1', 'AG1-A-3-002', -113, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-113003, '003', 'CELL', 'AG1', 'AG1-A-3-003', -113, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-113004, '004', 'CELL', 'AG1', 'AG1-A-3-004', -113, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-113005, '005', 'CELL', 'AG1', 'AG1-A-3-005', -113, 0);

-- Cells AG1 Wing B Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-121001, '001', 'CELL', 'AG1', 'AG1-B-1-001', -121, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-121002, '002', 'CELL', 'AG1', 'AG1-B-1-002', -121, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-121003, '003', 'CELL', 'AG1', 'AG1-B-1-003', -121, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-121004, '004', 'CELL', 'AG1', 'AG1-B-1-004', -121, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-121005, '005', 'CELL', 'AG1', 'AG1-B-1-005', -121, 0);

-- Cells AG1 Wing B Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-122001, '001', 'CELL', 'AG1', 'AG1-B-2-001', -122, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-122002, '002', 'CELL', 'AG1', 'AG1-B-2-002', -122, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-122003, '003', 'CELL', 'AG1', 'AG1-B-2-003', -122, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-122004, '004', 'CELL', 'AG1', 'AG1-B-2-004', -122, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-122005, '005', 'CELL', 'AG1', 'AG1-B-2-005', -122, 0);

-- Cells AG1 Wing B Land 3 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-123001, '001', 'CELL', 'AG1', 'AG1-B-3-001', -123, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-123002, '002', 'CELL', 'AG1', 'AG1-B-3-002', -123, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-123003, '003', 'CELL', 'AG1', 'AG1-B-3-003', -123, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-123004, '004', 'CELL', 'AG1', 'AG1-B-3-004', -123, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-123005, '005', 'CELL', 'AG1', 'AG1-B-3-005', -123, 0);

-- Cells AG1 Wing C Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-131001, '001', 'CELL', 'AG1', 'AG1-C-1-001', -131, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-131002, '002', 'CELL', 'AG1', 'AG1-C-1-002', -131, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-131003, '003', 'CELL', 'AG1', 'AG1-C-1-003', -131, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-131004, '004', 'CELL', 'AG1', 'AG1-C-1-004', -131, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-131005, '005', 'CELL', 'AG1', 'AG1-C-1-005', -131, 0);

-- Cells AG1 Wing C Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-132001, '001', 'CELL', 'AG1', 'AG1-C-2-001', -132, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-132002, '002', 'CELL', 'AG1', 'AG1-C-2-002', -132, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-132003, '003', 'CELL', 'AG1', 'AG1-C-2-003', -132, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-132004, '004', 'CELL', 'AG1', 'AG1-C-2-004', -132, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-132005, '005', 'CELL', 'AG1', 'AG1-C-2-005', -132, 0);

-- Cells AG1 Wing C Land 3 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-133001, '001', 'CELL', 'AG1', 'AG1-C-3-001', -133, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-133002, '002', 'CELL', 'AG1', 'AG1-C-3-002', -133, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-133003, '003', 'CELL', 'AG1', 'AG1-C-3-003', -133, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-133004, '004', 'CELL', 'AG1', 'AG1-C-3-004', -133, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-133005, '005', 'CELL', 'AG1', 'AG1-C-3-005', -133, 0);

-- Cells AG1 Wing D Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-141001, '001', 'CELL', 'AG1', 'AG1-D-1-001', -141, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-141002, '002', 'CELL', 'AG1', 'AG1-D-1-002', -141, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-141003, '003', 'CELL', 'AG1', 'AG1-D-1-003', -141, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-141004, '004', 'CELL', 'AG1', 'AG1-D-1-004', -141, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-141005, '005', 'CELL', 'AG1', 'AG1-D-1-005', -141, 0);

-- Cells AG1 Wing D Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-142001, '001', 'CELL', 'AG1', 'AG1-D-2-001', -142, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-142002, '002', 'CELL', 'AG1', 'AG1-D-2-002', -142, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-142003, '003', 'CELL', 'AG1', 'AG1-D-2-003', -142, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-142004, '004', 'CELL', 'AG1', 'AG1-D-2-004', -142, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-142005, '005', 'CELL', 'AG1', 'AG1-D-2-005', -142, 0);

-- Cells AG1 Wing D Land 3 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-143001, '001', 'CELL', 'AG1', 'AG1-D-3-001', -143, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-143002, '002', 'CELL', 'AG1', 'AG1-D-3-002', -143, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-143003, '003', 'CELL', 'AG1', 'AG1-D-3-003', -143, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-143004, '004', 'CELL', 'AG1', 'AG1-D-3-004', -143, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-143005, '005', 'CELL', 'AG1', 'AG1-D-3-005', -143, 0);

-- Cells AG1 Wing E Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-151001, '001', 'CELL', 'AG1', 'AG1-E-1-001', -151, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-151002, '002', 'CELL', 'AG1', 'AG1-E-1-002', -151, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-151003, '003', 'CELL', 'AG1', 'AG1-E-1-003', -151, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-151004, '004', 'CELL', 'AG1', 'AG1-E-1-004', -151, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-151005, '005', 'CELL', 'AG1', 'AG1-E-1-005', -151, 0);

-- Cells AG1 Wing E Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-152001, '001', 'CELL', 'AG1', 'AG1-E-2-001', -152, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-152002, '002', 'CELL', 'AG1', 'AG1-E-2-002', -152, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-152003, '003', 'CELL', 'AG1', 'AG1-E-2-003', -152, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-152004, '004', 'CELL', 'AG1', 'AG1-E-2-004', -152, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-152005, '005', 'CELL', 'AG1', 'AG1-E-2-005', -152, 0);

-- Cells AG1 Wing E Land 3 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-153001, '001', 'CELL', 'AG1', 'AG1-E-3-001', -153, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-153002, '002', 'CELL', 'AG1', 'AG1-E-3-002', -153, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-153003, '003', 'CELL', 'AG1', 'AG1-E-3-003', -153, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-153004, '004', 'CELL', 'AG1', 'AG1-E-3-004', -153, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-153005, '005', 'CELL', 'AG1', 'AG1-E-3-005', -153, 0);


-- Agency AG2

-- Cells AG2 Wing A Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211001, '001', 'CELL', 'AG2', 'AG2-A-1-001', -211, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211002, '002', 'CELL', 'AG2', 'AG2-A-1-002', -211, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211003, '003', 'CELL', 'AG2', 'AG2-A-1-003', -211, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211004, '004', 'CELL', 'AG2', 'AG2-A-1-004', -211, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-211005, '005', 'CELL', 'AG2', 'AG2-A-1-005', -211, 0);

-- Cells AG2 Wing A Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-212001, '001', 'CELL', 'AG2', 'AG2-A-2-001', -212, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-212002, '002', 'CELL', 'AG2', 'AG2-A-2-002', -212, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-212003, '003', 'CELL', 'AG2', 'AG2-A-2-003', -212, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-212004, '004', 'CELL', 'AG2', 'AG2-A-2-004', -212, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-212005, '005', 'CELL', 'AG2', 'AG2-A-2-005', -212, 0);

-- Cells AG2 Wing B Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-221001, '001', 'CELL', 'AG2', 'AG2-B-1-001', -221, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-221002, '002', 'CELL', 'AG2', 'AG2-B-1-002', -221, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-221003, '003', 'CELL', 'AG2', 'AG2-B-1-003', -221, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-221004, '004', 'CELL', 'AG2', 'AG2-B-1-004', -221, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-221005, '005', 'CELL', 'AG2', 'AG2-B-1-005', -221, 0);

-- Cells AG2 Wing B Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-222001, '001', 'CELL', 'AG2', 'AG2-B-2-001', -222, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-222002, '002', 'CELL', 'AG2', 'AG2-B-2-002', -222, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-222003, '003', 'CELL', 'AG2', 'AG2-B-2-003', -222, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-222004, '004', 'CELL', 'AG2', 'AG2-B-2-004', -222, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-222005, '005', 'CELL', 'AG2', 'AG2-B-2-005', -222, 0);

-- Cells AG2 Wing C Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-231001, '001', 'CELL', 'AG2', 'AG2-C-1-001', -231, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-231002, '002', 'CELL', 'AG2', 'AG2-C-1-002', -231, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-231003, '003', 'CELL', 'AG2', 'AG2-C-1-003', -231, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-231004, '004', 'CELL', 'AG2', 'AG2-C-1-004', -231, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-231005, '005', 'CELL', 'AG2', 'AG2-C-1-005', -231, 0);

-- Cells AG2 Wing C Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-232001, '001', 'CELL', 'AG2', 'AG2-C-2-001', -232, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-232002, '002', 'CELL', 'AG2', 'AG2-C-2-002', -232, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-232003, '003', 'CELL', 'AG2', 'AG2-C-2-003', -232, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-232004, '004', 'CELL', 'AG2', 'AG2-C-2-004', -232, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-232005, '005', 'CELL', 'AG2', 'AG2-C-2-005', -232, 0);


-- Agency AG3

-- Cells AG3 Wing A Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-311001, '001', 'CELL', 'AG3', 'AG3-A-1-001', -311, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-311002, '002', 'CELL', 'AG3', 'AG3-A-1-002', -311, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-311003, '003', 'CELL', 'AG3', 'AG3-A-1-003', -311, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-311004, '004', 'CELL', 'AG3', 'AG3-A-1-004', -311, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-311005, '005', 'CELL', 'AG3', 'AG3-A-1-005', -311, 0);

-- Cells AG3 Wing A Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-312001, '001', 'CELL', 'AG3', 'AG3-A-2-001', -312, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-312002, '002', 'CELL', 'AG3', 'AG3-A-2-002', -312, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-312003, '003', 'CELL', 'AG3', 'AG3-A-2-003', -312, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-312004, '004', 'CELL', 'AG3', 'AG3-A-2-004', -312, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-312005, '005', 'CELL', 'AG3', 'AG3-A-2-005', -312, 0);

-- Cells AG3 Wing B Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-321001, '001', 'CELL', 'AG3', 'AG3-B-1-001', -321, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-321002, '002', 'CELL', 'AG3', 'AG3-B-1-002', -321, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-321003, '003', 'CELL', 'AG3', 'AG3-B-1-003', -321, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-321004, '004', 'CELL', 'AG3', 'AG3-B-1-004', -321, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-321005, '005', 'CELL', 'AG3', 'AG3-B-1-005', -321, 0);

-- Cells AG3 Wing B Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-322001, '001', 'CELL', 'AG3', 'AG3-B-2-001', -322, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-322002, '002', 'CELL', 'AG3', 'AG3-B-2-002', -322, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-322003, '003', 'CELL', 'AG3', 'AG3-B-2-003', -322, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-322004, '004', 'CELL', 'AG3', 'AG3-B-2-004', -322, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-322005, '005', 'CELL', 'AG3', 'AG3-B-2-005', -322, 0);

-- Cells AG3 Wing C Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-331001, '001', 'CELL', 'AG3', 'AG3-C-1-001', -331, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-331002, '002', 'CELL', 'AG3', 'AG3-C-1-002', -331, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-331003, '003', 'CELL', 'AG3', 'AG3-C-1-003', -331, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-331004, '004', 'CELL', 'AG3', 'AG3-C-1-004', -331, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-331005, '005', 'CELL', 'AG3', 'AG3-C-1-005', -331, 0);

-- Cells AG3 Wing C Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-332001, '001', 'CELL', 'AG3', 'AG3-C-2-001', -332, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-332002, '002', 'CELL', 'AG3', 'AG3-C-2-002', -332, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-332003, '003', 'CELL', 'AG3', 'AG3-C-2-003', -332, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-332004, '004', 'CELL', 'AG3', 'AG3-C-2-004', -332, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-332005, '005', 'CELL', 'AG3', 'AG3-C-2-005', -332, 0);


-- Agency AG4

-- Cells AG4 Wing A Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-411001, '001', 'CELL', 'AG4', 'AG4-A-1-001', -411, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-411002, '002', 'CELL', 'AG4', 'AG4-A-1-002', -411, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-411003, '003', 'CELL', 'AG4', 'AG4-A-1-003', -411, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-411004, '004', 'CELL', 'AG4', 'AG4-A-1-004', -411, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-411005, '005', 'CELL', 'AG4', 'AG4-A-1-005', -411, 0);

-- Cells AG4 Wing A Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-412001, '001', 'CELL', 'AG4', 'AG4-A-2-001', -412, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-412002, '002', 'CELL', 'AG4', 'AG4-A-2-002', -412, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-412003, '003', 'CELL', 'AG4', 'AG4-A-2-003', -412, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-412004, '004', 'CELL', 'AG4', 'AG4-A-2-004', -412, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-412005, '005', 'CELL', 'AG4', 'AG4-A-2-005', -412, 0);

-- Cells AG4 Wing B Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-421001, '001', 'CELL', 'AG4', 'AG4-B-1-001', -421, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-421002, '002', 'CELL', 'AG4', 'AG4-B-1-002', -421, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-421003, '003', 'CELL', 'AG4', 'AG4-B-1-003', -421, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-421004, '004', 'CELL', 'AG4', 'AG4-B-1-004', -421, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-421005, '005', 'CELL', 'AG4', 'AG4-B-1-005', -421, 0);

-- Cells AG4 Wing B Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-422001, '001', 'CELL', 'AG4', 'AG4-B-2-001', -422, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-422002, '002', 'CELL', 'AG4', 'AG4-B-2-002', -422, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-422003, '003', 'CELL', 'AG4', 'AG4-B-2-003', -422, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-422004, '004', 'CELL', 'AG4', 'AG4-B-2-004', -422, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-422005, '005', 'CELL', 'AG4', 'AG4-B-2-005', -422, 0);

-- Cells AG4 Wing C Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-431001, '001', 'CELL', 'AG4', 'AG4-C-1-001', -431, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-431002, '002', 'CELL', 'AG4', 'AG4-C-1-002', -431, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-431003, '003', 'CELL', 'AG4', 'AG4-C-1-003', -431, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-431004, '004', 'CELL', 'AG4', 'AG4-C-1-004', -431, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-431005, '005', 'CELL', 'AG4', 'AG4-C-1-005', -431, 0);

-- Cells AG4 Wing C Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-432001, '001', 'CELL', 'AG4', 'AG4-C-2-001', -432, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-432002, '002', 'CELL', 'AG4', 'AG4-C-2-002', -432, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-432003, '003', 'CELL', 'AG4', 'AG4-C-2-003', -432, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-432004, '004', 'CELL', 'AG4', 'AG4-C-2-004', -432, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-432005, '005', 'CELL', 'AG4', 'AG4-C-2-005', -432, 0);


-- Agency AG5

-- Cells AG5 Wing A Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-511001, '001', 'CELL', 'AG5', 'AG5-A-1-001', -511, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-511002, '002', 'CELL', 'AG5', 'AG5-A-1-002', -511, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-511003, '003', 'CELL', 'AG5', 'AG5-A-1-003', -511, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-511004, '004', 'CELL', 'AG5', 'AG5-A-1-004', -511, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-511005, '005', 'CELL', 'AG5', 'AG5-A-1-005', -511, 0);

-- Cells AG5 Wing A Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-512001, '001', 'CELL', 'AG5', 'AG5-A-2-001', -512, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-512002, '002', 'CELL', 'AG5', 'AG5-A-2-002', -512, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-512003, '003', 'CELL', 'AG5', 'AG5-A-2-003', -512, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-512004, '004', 'CELL', 'AG5', 'AG5-A-2-004', -512, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-512005, '005', 'CELL', 'AG5', 'AG5-A-2-005', -512, 0);

-- Cells AG5 Wing B Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-521001, '001', 'CELL', 'AG5', 'AG5-B-1-001', -521, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-521002, '002', 'CELL', 'AG5', 'AG5-B-1-002', -521, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-521003, '003', 'CELL', 'AG5', 'AG5-B-1-003', -521, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-521004, '004', 'CELL', 'AG5', 'AG5-B-1-004', -521, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-521005, '005', 'CELL', 'AG5', 'AG5-B-1-005', -521, 0);

-- Cells AG5 Wing B Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-522001, '001', 'CELL', 'AG5', 'AG5-B-2-001', -522, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-522002, '002', 'CELL', 'AG5', 'AG5-B-2-002', -522, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-522003, '003', 'CELL', 'AG5', 'AG5-B-2-003', -522, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-522004, '004', 'CELL', 'AG5', 'AG5-B-2-004', -522, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-522005, '005', 'CELL', 'AG5', 'AG5-B-2-005', -522, 0);

-- Cells AG5 Wing C Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-531001, '001', 'CELL', 'AG5', 'AG5-C-1-001', -531, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-531002, '002', 'CELL', 'AG5', 'AG5-C-1-002', -531, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-531003, '003', 'CELL', 'AG5', 'AG5-C-1-003', -531, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-531004, '004', 'CELL', 'AG5', 'AG5-C-1-004', -531, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-531005, '005', 'CELL', 'AG5', 'AG5-C-1-005', -531, 0);

-- Cells AG5 Wing C Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-532001, '001', 'CELL', 'AG5', 'AG5-C-2-001', -532, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-532002, '002', 'CELL', 'AG5', 'AG5-C-2-002', -532, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-532003, '003', 'CELL', 'AG5', 'AG5-C-2-003', -532, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-532004, '004', 'CELL', 'AG5', 'AG5-C-2-004', -532, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-532005, '005', 'CELL', 'AG5', 'AG5-C-2-005', -532, 0);
                                                                                                                                                                              
-- Cells AG5 Wing D Land 1 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-541001, '001', 'CELL', 'AG5', 'AG5-D-1-001', -541, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-541002, '002', 'CELL', 'AG5', 'AG5-D-1-002', -541, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-541003, '003', 'CELL', 'AG5', 'AG5-D-1-003', -541, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-541004, '004', 'CELL', 'AG5', 'AG5-D-1-004', -541, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-541005, '005', 'CELL', 'AG5', 'AG5-D-1-005', -541, 0);

-- Cells AG5 Wing D Land 2 Cells 001-005
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-542001, '001', 'CELL', 'AG5', 'AG5-D-2-001', -542, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-542002, '002', 'CELL', 'AG5', 'AG5-D-2-002', -542, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-542003, '003', 'CELL', 'AG5', 'AG5-D-2-003', -542, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-542004, '004', 'CELL', 'AG5', 'AG5-D-2-004', -542, 0);
INSERT INTO AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID, INTERNAL_LOCATION_CODE, INTERNAL_LOCATION_TYPE, AGY_LOC_ID, DESCRIPTION, PARENT_INTERNAL_LOCATION_ID, NO_OF_OCCUPANT) VALUES (-542005, '005', 'CELL', 'AG5', 'AG5-D-2-005', -542, 0);
