
--------------------------------
-- OFFENDER_SENT_CALCULATIONS --
--------------------------------

-- Single record with CRD calc date and SED calc date - release date should match CRD calc date
-- Record also has APD
INSERT INTO OFFENDER_SENT_CALCULATIONS (OFFENDER_SENT_CALCULATION_ID, OFFENDER_BOOK_ID, CALCULATION_DATE, APD_CALCULATED_DATE, APD_OVERRIDED_DATE, HDCED_CALCULATED_DATE, HDCED_OVERRIDED_DATE, ETD_CALCULATED_DATE, ETD_OVERRIDED_DATE, MTD_CALCULATED_DATE, MTD_OVERRIDED_DATE, LTD_CALCULATED_DATE, LTD_OVERRIDED_DATE, ARD_CALCULATED_DATE, ARD_OVERRIDED_DATE, CRD_CALCULATED_DATE, CRD_OVERRIDED_DATE, PED_CALCULATED_DATE, PED_OVERRIDED_DATE, NPD_CALCULATED_DATE, NPD_OVERRIDED_DATE, PRRD_CALCULATED_DATE, PRRD_OVERRIDED_DATE, LED_CALCULATED_DATE, LED_OVERRIDED_DATE, SED_CALCULATED_DATE, SED_OVERRIDED_DATE, CALC_REASON_CODE)
VALUES (-1, -1, '2017-08-28', '2018-09-27', null, null, null, null, null, null, null, null, null, null, null, '2019-03-24', null, null, null, null, null, null, null, null, null, '2020-03-24', null, 'NEW');

