CREATE USER OFFICER1 PASSWORD 'password';
CREATE USER OFFICER2 PASSWORD 'password';
CREATE USER OFFICER3 PASSWORD 'password';
CREATE USER OFFICER4 PASSWORD 'password';
CREATE USER OFFICER5 PASSWORD 'password';
CREATE USER ADMINSTAFF PASSWORD 'password';