---
# Per environment values which override defaults in prison-api/values.yaml
generic-service:
  replicaCount: 2

  service:
    enabled: true

  ingress:
    enabled: true
    host: prison-api-dev.prison.service.justice.gov.uk
    tlsSecretName: prison-api-cert

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 5
    SPRING_REPLICA_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 20
    SMOKE_TEST_AWARE: true
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
