---
# Per environment values which override defaults in prison-api/values.yaml
generic-service:
  ingress:
    host: prison-api.prison.service.justice.gov.uk

  allowlist:
    groups:
      - internal
      - prum-prod
      - mod-platform-live # oasys-api-client
      - delius-prod

    # copied from unilink client in HMPPS Auth
    unilink-prod-1: "18.130.83.42/32"
    unilink-prod-2: "51.104.212.188/32"
    unilink-prod-3: "51.132.159.34/32"
    unilink-prod-4: "51.132.208.80/32"
    unilink-prod-5: "52.56.132.127/32"
    unilink-prod-6: "51.132.208.67/32"
    unilink-prod-7: "51.132.208.122/32"
    unilink-prod-8: "51.132.208.113/32"
    unilink-prod-9: "20.50.98.17/32"
    unilink-prod-10: "20.50.97.130/32"
    unilink-prod-11: "20.49.147.12/32"
    unilink-prod-12: "20.49.147.10/32"
    unilink-prod-13: "20.26.218.189/32"
    unilink-prod-14: "51.155.55.241/32"
    unilink-prod-15: "34.142.69.222/32"
    unilink-prod-16: "35.234.149.158/32"
    unilink-prod-17: "20.108.124.58/32"

    # copied from curious-sync-client / meganexus client
    curious-prod-1: "51.142.161.93/32"

    # in-cell-client kainos new logic app ip address
    pfs-azure-logicapps: "20.68.51.129/32"

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
