---
# Per environment values which override defaults in prison-api/values.yaml
generic-service:
  ingress:
    host: prison-api.prison.service.justice.gov.uk

  allowlist:
    groups:
      - internal
      - prum-prod
      - mod-platform-live # oasys-api-client
      - delius-prod
      - unilink-api
      - unilink-api-prod

    # copied from curious-sync-client / meganexus client and see #meganexus-collaboration
    curious-prod-1: "51.142.161.93/32"
    curious-prod-2: "51.140.252.153/32"

    # in-cell-client kainos new logic app ip address
    pfs-azure-logicapps: "20.68.51.129/32"

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
