---
# Per environment values which override defaults in prison-api/values.yaml
generic-service:
  service:
    enabled: true

  ingress:
    enabled: true
    host: prison-api.prison.service.justice.gov.uk
    tlsSecretName: prison-api-cert
    modsecurity_enabled: true

  env:
    JAVA_OPTS: "-Xmx1024m"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"

generic-prometheus-alerts:
  applicationAlertsEnabled: true
  ingressAlertsEnabled: true
