---
# Per environment values which override defaults in prison-api/values.yaml
generic-service:
  replicaCount: 2

  service:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 1024Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

  ingress:
    enabled: true
    host: prison-api-preprod.prison.service.justice.gov.uk
    tlsSecretName: prison-api-cert
    modsecurity_enabled: true

    modsecurity_snippet: |
      SecRuleEngine On
      # team here grants access to the OpenSearch logs to delve into the cause of the blockage
      SecDefaultAction "phase:2,pass,log,tag:github_team=dps-tech"
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
      # Missing User Agent Header
      SecRuleRemoveById 920320
      # Request Missing an Accept Header
      SecRuleRemoveById 920300
      # Restrict file extension
      SecRuleRemoveById 920440
      # SQL Injection Attack: Common Injection Testing Detected
      SecRuleRemoveById 942110
      # Found User-Agent associated with scripting/generic HTTP client
      SecRuleRemoveById 913101
      SecRuleUpdateTargetById 932150 "!ARGS:/keywords/"
      SecRuleUpdateTargetById 933210 "!ARGS:/.*description/"
      SecRuleUpdateTargetById 942100 "!ARGS:/.*description/"
      SecRuleUpdateTargetById 942330 "!ARGS:/keywords/"
      SecRuleUpdateTargetById 942130 "!ARGS:/text/"
      SecRuleUpdateTargetById 942130 "!ARGS:/.*comment/"
      SecRuleUpdateTargetById 942130 "!ARGS:/statement/"
      SecRuleUpdateTargetById 942130 "!ARGS:/.*description/"
      SecRuleUpdateTargetById 942150 "!ARGS:/outcomeComment/"
      SecRuleUpdateTargetById 942230 "!ARGS:/.*description/"
      SecRuleUpdateTargetById 942410 "!ARGS:/outcomeComment/"
      # Change default denial to be a 406 so that we can tell easily that it is modsecurity doing the blocking
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"

  env:
    JAVA_OPTS: "-Xmx1024m"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json


generic-prometheus-alerts:
  applicationAlertsEnabled: true
  ingressAlertsEnabled: true
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
