---
# Per environment values which override defaults in prison-api/values.yaml
generic-service:
  ingress:
    host: prison-api.prison.service.justice.gov.uk

  allowlist:
    groups:
      - internal
      - prum-prod
      - mod-platform-live # oasys-api-client
      - delius-prod

    # copied from unilink client in HMPPS Auth
    unilink-prod-1: "18.130.83.42/32"
    unilink-prod-2: "51.104.212.188/32"
    unilink-prod-3: "51.132.159.34/32"
    unilink-prod-4: "51.132.208.80/32"
    unilink-prod-5: "52.56.132.127/32"
    unilink-prod-6: "51.132.208.67/32"
    unilink-prod-7: "51.132.208.122/32"
    unilink-prod-8: "51.132.208.113/32"
    unilink-prod-9: "20.50.98.17/32"
    unilink-prod-10: "20.50.97.130/32"
    unilink-prod-11: "20.49.147.12/32"
    unilink-prod-12: "20.49.147.10/32"
    unilink-prod-13: "20.26.218.189/32"
    unilink-prod-14: "51.155.55.241/32"
    unilink-prod-15: "34.142.69.222/32"
    unilink-prod-16: "35.234.149.158/32"
    unilink-prod-17: "20.108.124.58/32"

    # copied from curious-sync-client / meganexus client
    curious-prod-1: "51.142.161.93/32"

    # azure logic apps in microsoft azure for in-cell-client / kainos
    kainos-azure-logic-apps-1: "51.140.74.14/32"
    kainos-azure-logic-apps-2: "51.140.73.85/32"
    kainos-azure-logic-apps-3: "51.140.78.44/32"
    kainos-azure-logic-apps-4: "51.140.137.190/32"
    kainos-azure-logic-apps-5: "51.140.153.135/32"
    kainos-azure-logic-apps-6: "51.140.28.225/32"
    kainos-azure-logic-apps-7: "51.140.142.28/32"
    kainos-azure-logic-apps-8: "51.140.158.24/32"
    kainos-azure-logic-apps-9: "20.108.102.142/32"
    kainos-azure-logic-apps-10: "20.108.102.123/32"
    kainos-azure-logic-apps-11: "20.90.204.228/32"
    kainos-azure-logic-apps-12: "20.90.204.188/32"
    kainos-azure-logic-apps-13: "20.108.146.132/32"
    kainos-azure-logic-apps-14: "20.90.223.4/32"
    kainos-azure-logic-apps-15: "20.26.15.70/32"
    kainos-azure-logic-apps-16: "20.26.13.151/32"
    kainos-azure-logic-apps-17: "4.159.24.241/32"
    kainos-azure-logic-apps-18: "4.250.55.134/32"
    kainos-azure-logic-apps-19: "4.159.24.255/32"
    kainos-azure-logic-apps-20: "4.250.55.217/32"
    kainos-azure-logic-apps-21: "172.165.88.82/32"
    kainos-azure-logic-apps-22: "4.250.82.111/32"
    kainos-azure-logic-apps-23: "4.158.106.101/32"
    kainos-azure-logic-apps-24: "4.158.105.106/32"
    kainos-azure-logic-apps-25: "4.250.51.127/32"
    kainos-azure-logic-apps-26: "4.250.49.230/32"
    kainos-azure-logic-apps-27: "4.159.26.128/32"
    kainos-azure-logic-apps-28: "172.166.86.30/32"
    kainos-azure-logic-apps-29: "4.159.26.151/32"
    kainos-azure-logic-apps-30: "4.159.26.77/32"
    kainos-azure-logic-apps-31: "4.159.59.140/32"
    kainos-azure-logic-apps-32: "4.159.59.13/32"
    kainos-azure-logic-apps-33: "51.140.74.150/32"
    kainos-azure-logic-apps-34: "51.140.80.51/32"
    kainos-azure-logic-apps-35: "51.140.61.124/32"
    kainos-azure-logic-apps-36: "51.105.77.96/27"
    kainos-azure-logic-apps-37: "51.140.148.0/28"
    kainos-azure-logic-apps-38: "20.90.129.0/27"
    kainos-azure-logic-apps-39: "20.90.129.32/28"
    kainos-azure-logic-apps-40: "20.90.125.211"
    kainos-azure-logic-apps-41: "20.90.124.134"

    # in-cell-client kainos new logic app ip address
    pfs-azure-logicapps: "20.68.51.129/32"

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
