---
# Per environment values which override defaults in prison-api/values.yaml
generic-service:
  replicaCount: 2

  resources:
    requests:
      cpu: 100m
      memory: 1024Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

  ingress:
    host: prison-api-preprod.prison.service.justice.gov.uk

  allowlist:
    groups:
      - internal
      - prum-test
      - mod-platform-non-live # oasys-api-client
      - delius-preprod
      - delius-stage

    # copied from unilink client in HMPPS Auth
    unilink-preprod-1: "18.130.83.42/32"
    unilink-preprod-2: "51.104.212.188/32"
    unilink-preprod-3: "51.132.159.34/32"
    unilink-preprod-4: "51.132.208.80/32"
    unilink-preprod-5: "52.56.132.127/32"
    unilink-preprod-6: "51.132.208.67/32"
    unilink-preprod-7: "51.132.208.122/32"
    unilink-preprod-8: "51.132.208.113/32"
    unilink-preprod-9: "20.50.98.17/32"
    unilink-preprod-10: "20.50.97.130/32"
    unilink-preprod-11: "20.49.147.12/32"
    unilink-preprod-12: "20.49.147.10/32"
    unilink-preprod-13: "20.26.218.189/32"
    unilink-preprod-14: "51.11.58.30/32"

    # copied from curious-sync-client / meganexus client
    curious-preprod-1: "20.49.246.49/32"
    # meganexus office address
    curious-preprod-2: "202.189.235.70/32"

    # in-cell-client kainos new logic app ip address
    pfs-azure-logicapps: "20.68.51.129/32"

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json


generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
