---
# Per environment values which override defaults in prison-api/values.yaml
generic-service:
  replicaCount: 2

  resources:
    requests:
      cpu: 100m
      memory: 1024Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

  ingress:
    host: prison-api-preprod.prison.service.justice.gov.uk

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform
      - prum-test
      - mod-platform-non-live # oasys-api-client
      - delius-preprod
      - delius-stage
      - unilink-api
      - unilink-api-preprod

    # copied from curious-sync-client / meganexus client
    curious-preprod-1: "20.49.246.49/32"
    # meganexus office address
    curious-preprod-2: "202.189.235.70/32"

    # in-cell-client kainos new logic app ip address
    pfs-azure-logicapps: "20.68.51.129/32"

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json


generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
