INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-1, 'SEQ', 'ANDERSON', 'BORIS', 'ARTHUR', 'M', systimestamp, 'ANDERSON', 'A1234AA', -1, 'W1', 'CN');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-2, 'SEQ', 'ANDERSON', 'EVE', 'GILLIAN', 'F', systimestamp, 'ANDERSON', 'A1234AB', -2, 'W2', 'MAID');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-3, 'SEQ', 'BATES', 'JOHN', 'NORMAN', 'M', systimestamp, 'BATES', 'A1234AC', -3, 'W1', 'CN');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-4, 'SEQ', 'CHAPLIN', 'JAMES', 'CHARLES', 'M', systimestamp, 'CHAPLIN', 'A1234AD', -4, 'W1', null);

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-5, 'SEQ', 'DUCK', null, 'DONALD', 'M', systimestamp, 'DUCK', 'A1234AE', -5, 'W1', -12);

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-6, 'SEQ', 'ANDREWS', null, 'ANTHONY', 'M', systimestamp, 'ANDREWS', 'A1234AF', -6, 'W1', 'CN');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-7, 'SEQ', 'SMITH', 'DAVID', 'GILES', 'M', systimestamp, 'SMITH', 'A1234AG', -7, 'W1', null);

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-8, 'SEQ', 'TRUMP', null, 'DONALD', 'M', systimestamp, 'TRUMP', 'A1234AH', -8, 'W1', 'CN');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-9, 'SEQ', 'THOMPSON', 'JAMES', 'CHESTER', 'M', systimestamp, 'THOMPSON', 'A1234AI', -9, 'M2', null);

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-10, 'SEQ', 'SMITH', 'JOSEPH', 'DANIEL', 'M', systimestamp, 'SMITH', 'A1234AJ', -10, 'W1', null);

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-11, 'SEQ', 'SMITH', null, 'DARIUS', 'M', systimestamp, 'SMITH', 'A1234AK', -11, 'W1', null);

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-12, 'SEQ', 'SMELLEY', 'JOHN', 'DANIEL', 'M', systimestamp, 'SMELLEY', 'A1234AL', -12, 'W2', null);

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-13, 'SEQ', 'SMILEY', null, 'DANNY', 'M', systimestamp, 'SMILEY', 'A1234AM', -12, 'W2', 'NICK');

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-14, 'SEQ', 'THOMSON', null, 'CHESNEY', 'M', systimestamp, 'THOMSON', 'A1234AN', -9, 'M2', null);

INSERT INTO OFFENDERS (OFFENDER_ID, ID_SOURCE_CODE, LAST_NAME, MIDDLE_NAME, FIRST_NAME, SEX_CODE, CREATE_DATE, LAST_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, RACE_CODE, ALIAS_NAME_TYPE)
VALUES (-15, 'SEQ', 'THOMPSON', null, 'CHARLEY', 'M', systimestamp, 'THOMPSON', 'A1234AO', -9, 'W1', 'A');

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-1, systimestamp,  'A00111', -1, 'N', 'IN', 'Y', 'N', 'LEI', -1, -3, -3);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-2, systimestamp,  'A00112', -2, 'N', 'IN', 'Y', 'N', 'LEI', -2, null, -19);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-3, systimestamp,  'A00113', -3, 'N', 'IN', 'Y', 'N', 'LEI', -3, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-4, systimestamp,  'A00114', -4, 'N', 'IN', 'Y', 'N', 'LEI', -4, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-5, systimestamp,  'A00115', -5, 'N', 'IN', 'Y', 'N', 'LEI', -5, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-6, systimestamp,  'A00116', -6, 'N', 'IN', 'Y', 'N', 'LEI', -6, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-7, systimestamp,  'A00117', -7, 'N', 'IN', 'Y', 'N', 'LEI', -7, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-8, systimestamp,  'A00118', -8, 'N', 'IN', 'Y', 'N', 'LEI', -8, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-9, systimestamp,  'A00119', -9, 'N', 'IN', 'Y', 'N', 'LEI', -9, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-10, systimestamp,  'A00120', -10, 'N', 'IN', 'Y', 'N', 'LEI', -10, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-11, systimestamp,  'A00121', -11, 'N', 'IN', 'Y', 'N', 'LEI', -11, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-12, systimestamp,  'A00122', -12, 'N', 'IN', 'Y', 'N', 'LEI', -12, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-13, systimestamp,  'A00123', -13, 'N', 'IN', 'Y', 'N', 'LEI', -12, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-14, systimestamp,  'A00124', -14, 'N', 'IN', 'Y', 'N', 'LEI', -9, null, null);

INSERT INTO OFFENDER_BOOKINGS (OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_NO, OFFENDER_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, YOUTH_ADULT_CODE, AGY_LOC_ID, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, LIVING_UNIT_ID)
VALUES (-15, systimestamp,  'A00125', -15, 'N', 'IN', 'Y', 'N', 'LEI', -9, null, null);
