INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'A', 'Social Care', 12, 'Y', 'N', null, null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'C', 'Child Communication Measures', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'H', 'Self Harm', 1, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'L', 'Care Leaver', 11, 'Y', 'N', null, null, null, 'L', null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'M', 'Medical', 5, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'O', 'Other', 10, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'P', 'MAPPP Case', 4, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'R', 'Risk', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'S', 'Sexual Offence', 7, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'T', 'Hold Against Transfer', 8, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'V', 'Vulnerability', 6, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'W', 'Warrant', 9, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ALERT', 'X', 'Security', 2, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'W1', 'White: British', 1, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'W2', 'White: Irish', 1, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'M1', 'Mixed: White and Black Caribbean', 2, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'M2', 'Mixed: White and Black African', 2, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'A1', 'Asian/Asian British: Indian', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('ETHNICITY', 'A2', 'Asian/Asian British: Pakistani', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NAME_TYPE', 'A', 'Alias Name', 2, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NAME_TYPE', 'CN', 'Common Name', 1, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NAME_TYPE', 'MAID', 'Maiden Name', 4, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NAME_TYPE', 'NICK', 'Nickname', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NOTE_SOURCE', 'AUTO', 'System', null, 'Y', 'Y', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NOTE_SOURCE', 'COMM', 'Community', null, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NOTE_SOURCE', 'EXT', 'External', null, 'Y', 'Y', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('NOTE_SOURCE', 'INST', 'Prison', null, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('SEX', 'F', 'Female', 2, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('SEX', 'M', 'Male', 1, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('SEX', 'NK', 'Not Known / Not Recorded', 3, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('SEX', 'NS', 'Not Specified (Indeterminate)', 4, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN)
VALUES ('SEX', 'REF', 'Refused', 5, 'Y', 'N', 'OMS_OWNER', null, null, null, null);

INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'CHAP', 'Chaplaincy', 22, 'Y', 'N', null, 'AGY_LOC_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'CVM', 'Custodial Violence Management Model', 99, 'Y', 'N', null, 'AGY_LOC_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'KW', 'Key Worker', 1, 'Y', 'N', null, 'AGY_LOC_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'MCHECK', 'Management Check', 99, 'Y', 'Y', null, 'AGY_LOC_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'TRNG', 'Training', 99, 'Y', 'Y', null, 'AGY_LOC_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CPS', 'Core Programme Session', 17, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'POEM', 'Post Programme Evaluation Measure', 8, 'N', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'POPEM', 'Post Programme Evaluation Measure', 8, 'N', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'POS1', 'Post Programme OM Session one', 11, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'POS2', 'Post Programme OM Session two', 12, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'POS3', 'Post Programme OM Session three', 13, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'POS4', 'Post Programme OM Session four', 14, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'POS5', 'Post Programme OM Session five', 15, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'POS6', 'Post Programme OM Session six', 16, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPEM', 'Pre-Programme Evaluation Measure', 7, 'N', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPR', 'Post Programme Review meeting', 9, 'N', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPREP', 'Post Programme Report', 10, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPREPC', 'Post Programme Report Completed', 10, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPRM', 'Post Programme Review Meeting', null, 'N', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPS1', 'Pre Programme OM Session one', 1, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPS2', 'Pre Programme OM Session two', 2, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPS3', 'Pre Programme OM Session three', 3, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPS4', 'Pre Programme OM Session four', 4, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPS5', 'Pre Programme OM Session five', 5, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PPS6', 'Pre Programme OM Session six', 6, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PRPEM', 'Pre-Programme Evaluation Measure', 7, 'N', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SOU', 'Statement Of Understanding Signed', 99, 'Y', 'N', 'ACP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ACTIVE', 'Made Active', 99, 'Y', 'N', 'ALERT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'INACTIVE', 'Made Inactive', 99, 'Y', 'N', 'ALERT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ACP', 'Accredited Programme', 2, 'Y', 'Y', 'ALL', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SA', 'Specified Activity', 1, 'Y', 'Y', 'ALL', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SEN', 'Sentence/Licence', 3, 'Y', 'Y', 'ALL', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'OUTCOME', 'Outcome of Schedule', 99, 'Y', 'N', 'APP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'AREH-C', 'Alcohol Rehab - community', null, 'Y', 'N', 'ATR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'AREH-R', 'Alcohol Rehab - residential', null, 'Y', 'N', 'ATR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ATEST', 'Alcohol Test', null, 'Y', 'N', 'ATR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ATRCC', 'Case conference', null, 'N', 'N', 'ATR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ATREA', 'Alcohol Treatment Session', null, 'Y', 'N', 'ATR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ATRIATP', 'Initial Appointment with treatment provi', null, 'Y', 'N', 'ATR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ATRRTO', 'Report to Office', null, 'Y', 'N', 'ATR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ATRRTTP', 'Report To Treatment Provider', null, 'Y', 'N', 'ATR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TCOUN', 'Alcohol Counselling Session', null, 'Y', 'N', 'ATR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BAN', 'Breach Action Needed.', 99, 'N', 'N', 'BR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BRCA', 'Court Appearance', 1, 'Y', 'N', 'BR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BREACH', '2nd UA/UB Recorded Breach Action Requird', 99, 'Y', 'N', 'BR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BREA_OUTCOME', 'Breach Outcome', 99, 'Y', 'N', 'BR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BRP', 'Breach Report Sent to Breach Unit/Court', 99, 'Y', 'N', 'BR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BRWLTR', 'Warning letter', null, 'Y', 'N', 'BR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CCD', 'Confirm Court Date', 99, 'Y', 'N', 'BR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FTB', 'Fast track breach initiated.', null, 'Y', 'N', 'BR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RECALL', '3rd UA/UB on licence, recall required', null, 'Y', 'N', 'BR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SB', 'Standard breach initiated.', null, 'Y', 'N', 'BR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BERSERILL', 'Bereavement/Serious illness', 23, 'Y', 'N', 'CHAP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'COMLINKS', 'Community Links', 23, 'Y', 'N', 'CHAP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FAITH', 'Faith Specific Action', 23, 'Y', 'N', 'CHAP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FAMMAR', 'Family Contacts/Marriage', 23, 'Y', 'N', 'CHAP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'OPV', 'OPV Requests', 23, 'Y', 'N', 'CHAP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RECSTAT', 'Reception/Statutory Duty', 23, 'Y', 'N', 'CHAP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FWD', 'Forwarded', null, 'Y', 'N', 'CNOTE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'COM_IN', 'Communication IN', 22, 'Y', 'Y', 'COMMS', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'COM_OUT', 'Communication OUT', 22, 'Y', 'Y', 'COMMS', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CR_GOV', 'CR GOV Function test', 99, 'Y', 'N', 'CR1', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CR_HMPS', 'CR HMPS Function test', 99, 'Y', 'N', 'CR1', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CR_NPS', 'CR NPS Function test', 99, 'Y', 'N', 'CR1', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CR_COMPLETE', 'CR PSR Completed test', 99, 'Y', 'N', 'CR2', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CR_REPORT', 'CR PSR Court Report test', 99, 'Y', 'N', 'CR2', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'APP', 'Appeal Hearing', 8, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BAIL', 'Bail Application', 7, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'COM', 'Committal Hearing', 3, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CRT', 'Court Appearance', 1, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CRTCA', 'Court Appearance', 1, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CRTPSI', 'Post Sentence Interview', null, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CRT_OUTCOME', 'Court Outcome', 99, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FSEN', 'For Sentence', 2, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NEW', 'Newton Hearing', 9, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PDH', 'Plea and Directions Hearing', 4, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PSI', 'Post Sentence Interview', 1, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PSR_COMPLET', 'PSR Completed', 99, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PSR_REQ', 'PSR Required', 99, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PTR', 'Pre Trial Review', 6, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TRA', 'Trial', 5, 'Y', 'N', 'CRT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CVMDOC', 'CVM Document Saved', 99, 'Y', 'N', 'CVM', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DCOUN', 'Drug Counselling Session', null, 'Y', 'N', 'DRR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DREH-R', 'Drug Rehab - residential', null, 'Y', 'N', 'DRR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DRRIATP', 'Initial Appointment w.Treatment Provider', null, 'Y', 'N', 'DRR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DRRRTO', 'Report to Office', null, 'Y', 'N', 'DRR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DRRRTTP', 'Report To Treatment Provider', null, 'Y', 'N', 'DRR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DTEST', 'Drug Test', null, 'Y', 'N', 'DRR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DTREA', 'Drug Treatment Session', null, 'Y', 'N', 'DRR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'EMPTARACH', 'Employment Retention Target Achieved', 99, 'Y', 'N', 'EMPLOYMENT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'GAINEDEMP', 'Offender Gained Employment', 99, 'Y', 'N', 'EMPLOYMENT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ABSENCE', 'Absence', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'AMENDOUT', 'FTA or FTC not amended within 7 days', null, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BREACH_EN', 'Second UA/UB Recorded Breach', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CFUA', 'Confirm First Warning', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CSUA', 'Confirm 2nd UA/UB + Breach Action Taken', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CSUA2', 'ACO Warning Letter', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FIRSTFTA', 'First FTA or FTC recorded', null, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FTA1LTR', 'Explanation Letter following 1st FTA/FTC', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FTA2LTR', 'Explanation Letter following 2nd FTA/FTC', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FTA3LTR', 'Explanation Letter following 3rd FTA/FTC', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_HWL', 'Approved Premises Warning Letter', 99, 'Y', 'Y', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RW1', 'Rescind Warning', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RW2', 'Rescind Warning following Second FTA/FTC', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RW3', 'Rescind Warning following Third FTA/ FTC', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SECONDFTA', 'FTA/FTC Entered When UA/UB Exists', 99, 'Y', 'N', 'EN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ETERTO', 'Report to Office', null, 'Y', 'N', 'ETE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ETERTTP', 'Report to Third Party', null, 'Y', 'N', 'ETE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NOTPAID', 'Not To Be Paid', 14, 'Y', 'N', 'FARES', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TOBEPAID', 'To Be Paid', 10, 'Y', 'N', 'FARES', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BYACO', 'By ACO', 6, 'Y', 'N', 'FILEINSP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BYINSP', 'By Inspector', 12, 'Y', 'N', 'FILEINSP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BYSPO', 'By SPO', 6, 'Y', 'N', 'FILEINSP', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HIST', 'History Sheet Entry', 99, 'N', 'N', 'GEN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'APPHDC', 'HDC Approval', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CLOSE', 'Close', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'COMING_DUE', 'CR Coming Due test', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DECSN_TAKEN', 'Decision Taken', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC', 'HDC', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDCELIGIBLE', 'Offender is eligible for HDC Considerati', null, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDCINFOUPDAT', 'HDC Info Update', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDCINPDONE', 'HDC Seconded Probation Comments Complete', null, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDCINTPROB', 'HDC Seconded Probation Comments Due', null, 'N', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_BRD_DONE', 'HDC Board Recommendation Made', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_BRD_DUE', 'HDC Board Decision Required', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_COM_DUE', 'HDC Coming Due', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_DECISION', 'HDC Decision', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_ELIGIBLE', 'Offender Eligible for HDC Consideration', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_GOV_DONE', 'HDC Decision Made', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_GOV_DUE', 'HDC Gov Decision Required', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_INFO_COM', 'HDC Info Completed', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_INP_DONE', 'HDC Seconded Prob Comments Complete', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_INP_DUE', 'HDC Seconded Probation Comments Due', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_OM_DONE', 'OM/OS HDC Report Completed', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_OM_DUE', 'HDC OM/OS Report Due', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_PO_DONE', 'HDC Personal Officer Comments Completed', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_PO_DUE', 'HDC Personal Officer Comments Required', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_REP_COMP', 'HDC Report Completed', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_REP_DUE', 'HDC Report Due', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HDC_REP_ODUE', 'HDC Report Overdue', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'OPEN', 'Open', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'OUTCOME2', 'FTA or FTC Entered when UA or UB exists', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PDR', 'Pre Discharge Function test', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REF_PROB', 'Referral Probation', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SENTENCE', 'Sentence', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'VLU', 'VLU Function test', 99, 'Y', 'N', 'HDC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'LTRFO', 'From Offender', 2, 'Y', 'N', 'LTR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'LTRFTP', 'From Third Party', 4, 'Y', 'N', 'LTR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'LTRTO', 'To Offender', 1, 'Y', 'N', 'LTR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'LTRTTP', 'To Third Party', 3, 'Y', 'N', 'LTR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_COM', 'Letter - Changes of OM', 5, 'Y', 'Y', 'LTR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_UPWSD', 'Letter Instructing offender not to rep.', 1, 'Y', 'Y', 'LTR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PSRAPP', 'Court Report Appointment Letter', 1, 'Y', 'Y', 'LTR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'MHTIATP', 'Initial Appointment w.Treatment Provider', null, 'Y', 'N', 'MHT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'MHTRTO', 'Report to Office', null, 'Y', 'N', 'MHT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'MHTRTTP', 'Report To Treatment Provider', null, 'Y', 'N', 'MHT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BEHAVEWARN', 'Behaviour Warning', 18, 'Y', 'Y', 'NEG', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'IEP_WARN', 'IEP Warning', 18, 'Y', 'Y', 'NEG', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NEG_GEN', 'General Entry', 18, 'Y', 'Y', 'NEG', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'WORKWARN', 'Work Effort Warning', 18, 'Y', 'Y', 'NEG', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NEWS', 'News from Home', 20, 'Y', 'Y', 'OBSERVE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'OBS_GEN', 'General Entry', 20, 'Y', 'Y', 'OBSERVE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'THREAT_PR', 'Threats to Prisoners', 20, 'Y', 'Y', 'OBSERVE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'THREAT_ST', 'Threats to Staff', 20, 'Y', 'Y', 'OBSERVE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ASSIGN', 'Assigned or Re-Assigned', null, 'Y', 'N', 'OM', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ASSIGN_OM', 'Assign/Reassign Offender Manager', 99, 'Y', 'N', 'OM', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'APV', 'Hostel or Approved Premises Visit', 7, 'Y', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CRI', 'Court Report Interview', 1, 'Y', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HV', 'Home Visit', 3, 'Y', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'MAPPA', 'MAPPA meeting', 5, 'Y', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PACC', 'Case conference', 5, 'N', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PAIAOM', 'Initial Appointment with OM', 1, 'Y', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PARTO', 'Report to Office', null, 'Y', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PARTTP', 'Report to Third Party', null, 'Y', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PAWTP', 'With Third Party', null, 'Y', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PV', 'Prison Visit', 6, 'Y', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'VLI', 'Video Link Interview', 6, 'Y', 'N', 'PA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PAV', 'Visit', 99, 'Y', 'N', 'PADVIS', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'APPPAROLE', 'Parole Approval', 99, 'Y', 'N', 'PAROLE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PARINFOUPDAT', 'Parole Info Update', 101, 'Y', 'N', 'PAROLE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PAR_DECISION', 'Parole Decision', 101, 'Y', 'N', 'PAROLE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PAR_INFO_COM', 'Parole Info Completed', 101, 'Y', 'N', 'PAROLE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PAR_REP_COMP', 'Parole Report Completed', 101, 'Y', 'N', 'PAROLE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PAR_REP_DUE', 'Parole Report Due', 101, 'Y', 'N', 'PAROLE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PAR_REP_ODUE', 'Parole Report Overdue', 101, 'Y', 'N', 'PAROLE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'IEP_ENC', 'IEP Encouragement', 19, 'Y', 'Y', 'POS', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'POS_GEN', 'General Entry', 19, 'Y', 'Y', 'POS', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'QUAL_ATT', 'Quality Attitude', 19, 'Y', 'Y', 'POS', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'QUAL_WK', 'Quality Work', 19, 'Y', 'Y', 'POS', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RELEASE', 'Release', 99, 'Y', 'N', 'PRISON', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'COMPLETED', 'Completed', 99, 'Y', 'N', 'PSR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PSR_CMP_ALRT', 'PSR Complete Alert', 99, 'Y', 'N', 'PSR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PSR_REQUIRED', 'PSR Required', 99, 'Y', 'N', 'PSR', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'APPRECALL', 'Recall Approval', 99, 'Y', 'N', 'REC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'COR', 'Confirmation of recall.', null, 'Y', 'N', 'REC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PAR_COM_DUE', 'Parole Coming Due', 101, 'Y', 'N', 'REC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RDP', 'Recall Documents Prepared', null, 'Y', 'N', 'REC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RECR', 'Recall Required', 99, 'N', 'N', 'REC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RECRP', 'Recall Report Prepared', 99, 'Y', 'N', 'REC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RECWLTR', 'Warning letter', null, 'Y', 'N', 'REC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REC_DECISION', 'Recall Decision', 100, 'Y', 'N', 'REC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RI', 'Recall initiated', null, 'Y', 'N', 'REC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PRE_DIS_DONE', 'Pre-Release Report Complete', 99, 'Y', 'N', 'RELEASE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PRE_DIS_DUE', 'Pre-Release Report Due', 99, 'Y', 'N', 'RELEASE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RELINFOUPDAT', 'Pre Release Report Update', 100, 'Y', 'N', 'RELEASE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REL_INFO_COM', 'Info Completed', 100, 'Y', 'N', 'RELEASE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REL_REP_COMP', 'Pre Release Report Completed', 100, 'Y', 'N', 'RELEASE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REL_REP_DUE', 'Pre Release Report Due', null, 'Y', 'N', 'RELEASE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REL_REP_ODUE', 'Pre Release Report Overdue', 100, 'Y', 'N', 'RELEASE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BRCOMP', 'Breach Report Completed', 3, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'BREREP', 'Breach Report', 3, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CRCOMP', 'Court Report Completed', 1, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CRTREPCOMP', 'Court Report Completed', null, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CRTREPREQ', 'Court Report Request', 99, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CRTREPREQ2', 'Court Report Request', null, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CRTREV', 'Court Review Report Completed', 5, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DEFSENCOMP', 'Deferred Sentence Report Completed', null, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DEFSENT', 'Deferred Sentence Report Completed', 4, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'DRRASS', 'DRR Suitability Assessment Completed', 9, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FTPSR', 'Fast Track PSR Completed', 1, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'LSP1F', 'Post Sentence Report LSP1F Completed', 8, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'LSP3E', 'Lifer Progress Report Completed', 99, 'Y', 'Y', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_BIR', 'Bail Information Report Completed', 99, 'Y', 'Y', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_CPR', 'Community Order Completion/Progress Rep.', 99, 'Y', 'Y', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PARCOMP', 'Parole Report Completed', 6, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PARREP', 'Parole Report', 6, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'POE', 'Personal Officer Entry', 99, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PRCOMP', 'Parole Report Completed', 2, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REPORT_COMPL', 'Court Report Completed', 99, 'N', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REPORT_DONE', 'Court Report Completed', 99, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REPORT_DUE', 'Court Report Requested', 99, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'STDPSR', 'Standard Delivery PSR Completed', 2, 'Y', 'N', 'REPORT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REP_GEN', 'General Report', 21, 'Y', 'Y', 'REPORTS', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REP_IEP', 'IEP Report', 21, 'Y', 'Y', 'REPORTS', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REP_WNG', 'Wing Conduct Report', 21, 'Y', 'Y', 'REPORTS', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REQTERM', 'Requirement Terminated', 99, 'Y', 'N', 'REQUIREMENT', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ROTLUPDATE', 'ROTL Info Update', 102, 'Y', 'N', 'ROTL', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ROTL_INF_COM', 'ROTL Info Completed', 102, 'Y', 'N', 'ROTL', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ROTL_REP_DUE', 'ROTL Report Due', 102, 'Y', 'N', 'ROTL', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ROTL_REP_ODU', 'ROTL Report Overdue', 102, 'Y', 'N', 'ROTL', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SAITP', 'Initial Appointment with Activity Provid', null, 'Y', 'N', 'SA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SARTO', 'Report to Office', null, 'Y', 'N', 'SA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SARTTP', 'Report to Third Party', null, 'Y', 'N', 'SA', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'COMMENCE', 'Commencement', 99, 'Y', 'N', 'SENTENCE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'IMPOSED', 'Imposed', 99, 'Y', 'N', 'SENTENCE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SENTERM', 'Terminated', 99, 'Y', 'N', 'SENTENCE', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ISPCOMP', 'Initial Sentence Plan Completed', 1, 'Y', 'N', 'SUPPLAN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_LSP', 'Lifer Sentence Plan', 4, 'Y', 'Y', 'SUPPLAN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RSPCOMP', 'Review Sentence Plan Completed', 2, 'Y', 'N', 'SUPPLAN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TSPCOMP', 'Termination Sentence Plan Completed', 3, 'Y', 'N', 'SUPPLAN', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SUPREQTERM', 'Terminated', 99, 'Y', 'N', 'SUPREQ', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TCFO', 'From Offender', null, 'Y', 'N', 'TC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TCFTP', 'From Third Party', null, 'Y', 'N', 'TC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TCTO', 'To Offender', null, 'Y', 'N', 'TC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TCTTP', 'To Third Party', null, 'Y', 'N', 'TC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FROMTOL', 'From/ To Location', 99, 'Y', 'N', 'TRANSFER', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FROMTO', 'From/To', 99, 'Y', 'N', 'TRANSOFFICER', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'UPCFO', 'From Offender', null, 'Y', 'N', 'UPC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'UPCRTO', 'Report to Office', null, 'Y', 'N', 'UPC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'UPCRTTP', 'Unscheduled Visit to Third Party', null, 'Y', 'N', 'UPC', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'UWTERM', 'Terminated', 99, 'Y', 'N', 'UW', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'WORK_SESSION', 'Work Session', null, 'Y', 'N', 'UW', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'INFO_COMPLET', 'CR Victim Complete test', 99, 'Y', 'N', 'VICTIM', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'INFO_UPDATE', 'CR Victim Request test', 99, 'Y', 'N', 'VICTIM', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ABSENT', 'Absence', 99, 'Y', 'N', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ASSESSMENT', 'Assessment', 99, 'Y', 'N', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'CONS_WRK', 'Consolidation Work', 99, 'Y', 'N', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'GEN_VISIT', 'General Visit', 99, 'Y', 'N', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'MCHECK', 'Management Check', 99, 'Y', 'Y', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'OSE', 'Offender Supervisor Entry', 99, 'Y', 'N', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PROG_FIN', 'Programme Finish', 99, 'Y', 'N', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'PROG_START', 'Programme Start', 99, 'Y', 'N', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'RE-VISIT', 'Re-Visit', 99, 'Y', 'N', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TRNG', 'Allocated (State Course in Case Notes)', 99, 'N', 'Y', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TRNGALL', 'ALLOCATED (State Course in Case Notes)', 99, 'Y', 'Y', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TRNGCOM', 'COMPLETED (State Course in Case Notes)', 99, 'Y', 'Y', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TRNGREM', 'REMOVED(Put Reason/Course in Case Notes)', 99, 'Y', 'Y', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TSP_SESSION', 'TSP ''Catch up'' Session', 99, 'Y', 'N', null, 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'MISC', 'Miscellaneous', 99, 'Y', 'Y', 'MIGRATION', 'TASK_TYPE');
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REQ', 'Requested', 99, 'Y', 'N', 'ALL', null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ADMISSION', 'Admission', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'END', 'Ended', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FO', 'From Offender', null, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'FTP', 'From Third Party', null, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'GS', 'Group Session', null, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'HIS', 'History Sheet Entry', null, 'N', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'INI', 'Initial Appointment with OM', null, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'ITP', 'Initial Appointment with Treatment Provi', null, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'LETTER', 'Letter', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'MM', 'MAPPA meeting', null, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_ACC', 'Accident and Incident Report Form', 99, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_IAP', 'SFL - Individual Action Plan', 99, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_LCW2', 'Confirm Second Letter', 99, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_PSD', 'Application to Amend PSD', 99, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_REV', 'Application to revoke comm. sentence', 99, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'NPS_SFO', 'Serious Further Offence Notification', 99, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'OMREF', 'Offender Manager Referral sent', null, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REF', 'Referral Made', 99, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REQUEST', 'Request', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'REQUIRED', 'Required', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'SCHEDULED', 'Scheduled', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TO', 'To Offender', null, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'TTP', 'To Third Party', null, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_SUBTYPE', 'WTP', 'With Third Party', null, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'PADVIS', 'Personal Advisor', 10, 'Y', 'N', 'O', null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'ACP', 'Accredited Programme', 10, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'ALERT', 'Alert', 16, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'ALL', 'Allocation', 1, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'AP', 'Approved Premises', 99, 'N', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'APP', 'Appointment', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'ATR', 'Alcohol Treatment Requirement', 12, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'BR', 'Breach', 7, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'CNOTE', 'Case Note', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'COMMS', 'Communication', 35, 'N', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'CRT', 'Court', 15, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'DISCHARGE', 'Discharge', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'DRR', 'Drug Rehabilitation Requirement', 11, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'DSPD', 'DSPD Offender', null, 'N', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'EMPLOYMENT', 'Employment Status', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'EN', 'Enforcement', 6, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'ETE', 'Education, Training and Employment', 9, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'FARES', 'Fares', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'FILEINSP', 'File Review Inspection', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'FTA', 'FTA', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'GEN', 'General', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'HDC', 'Home Detention Curfew', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'INST', 'Institution', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'LTR', 'Letter', 4, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'MHT', 'Mental Health Treatment Requirement', 13, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'MIGRATION', 'Migration', 99, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'NEG', 'Negative Behaviour', 31, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'OBSERVE', 'Observations', 33, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'OM', 'Offender Management', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'PA', 'Planned Appointments', 1, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'PAROLE', 'Parole', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'POS', 'Positive Behaviour', 32, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'PRISON', 'Prison', 19, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'REC', 'Recall', 8, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'RELEASE', 'Release', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'REPORT', 'Report', 3, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'REPORTS', 'Reports', 34, 'Y', 'Y', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'REQUIREMENT', 'Requirement', 21, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'ROTL', 'Release on Temporary Licence', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'RR', 'Release Report', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'SA', 'Specified Activity Requirement', 14, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'SENTENCE', 'Sentence', 20, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'SUPERVISION', 'Supervision', 99, 'N', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'SUPPLAN', 'Supervision Plan', 2, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'SUPREQ', 'Supervision Requirement', 21, 'N', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'TC', 'Telephone call', 5, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'TRANSFER', 'Prison Transfer', 17, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'TRANSOFFICER', 'Change of Supervisor', 18, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'UPC', 'Unplanned contact', 1, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'UW', 'Unpaid Work', 3, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'VICTIM', 'Victim', 99, 'Y', 'N', null, null);
INSERT INTO REFERENCE_CODES (DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, PARENT_CODE, PARENT_DOMAIN) VALUES ('TASK_TYPE', 'VLU', 'VLU', null, 'N', 'N', null, null);
