CREATE TABLE AGENCY_INCIDENT_PARTIES (
    AGENCY_INCIDENT_ID NUMBER(10,0),
    PARTY_SEQ NUMBER(6,0) DEFAULT 1 ,
    INCIDENT_ROLE VARCHAR2(12),
    OFFENDER_BOOK_ID NUMBER(10,0),
    STAFF_ID NUMBER(10,0),
    PERSON_ID NUMBER(10,0),
    DISPOSITION_TYPE VARCHAR2(12),
    DISPOSITION_DATE DATE,
    OIC_INCIDENT_ID NUMBER(10,0),
    COMMENT_TEXT VARCHAR2(240),
    CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
    CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
    ACTION_CODE VARCHAR2(12),
    PARTY_ADDED_DATE DATE,
    MODIFY_DATETIME TIMESTAMP,
    MODIFY_USER_ID VARCHAR2(32),
    AUDIT_TIMESTAMP TIMESTAMP,
    AUDIT_USER_ID VARCHAR2(32),
    AUDIT_MODULE_NAME VARCHAR2(65),
    AUDIT_CLIENT_USER_ID VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO VARCHAR2(256),
    CONSTRAINT AGENCY_INCIDENT_PARTIES_PK PRIMARY KEY (AGENCY_INCIDENT_ID,PARTY_SEQ),
    CONSTRAINT AGENCY_INCIDENT_PARTIES_UK1 UNIQUE (OIC_INCIDENT_ID),
    CONSTRAINT AGY_INCP_AGY_INC_F1 FOREIGN KEY (AGENCY_INCIDENT_ID) REFERENCES AGENCY_INCIDENTS(AGENCY_INCIDENT_ID),
    CONSTRAINT AGY_INCP_STAFF_F1 FOREIGN KEY (STAFF_ID) REFERENCES STAFF_MEMBERS(STAFF_ID),
    CONSTRAINT AGY_INC_PTY_OFF_BKG_FK FOREIGN KEY (OFFENDER_BOOK_ID) REFERENCES OFFENDER_BOOKINGS(OFFENDER_BOOK_ID),
    CONSTRAINT AGY_INC_PTY_PER_FK FOREIGN KEY (PERSON_ID) REFERENCES PERSONS(PERSON_ID)
);
CREATE INDEX AGENCY_INCIDENT_PARTIES_NI1 ON AGENCY_INCIDENT_PARTIES (OFFENDER_BOOK_ID);
CREATE UNIQUE INDEX AGENCY_INCIDENT_PARTIES_PK ON AGENCY_INCIDENT_PARTIES (AGENCY_INCIDENT_ID,PARTY_SEQ);
CREATE UNIQUE INDEX AGENCY_INCIDENT_PARTIES_UK1 ON AGENCY_INCIDENT_PARTIES (OIC_INCIDENT_ID);
CREATE INDEX AGY_INCP_STAFF_F1 ON AGENCY_INCIDENT_PARTIES (STAFF_ID);
CREATE INDEX AGY_INC_PTY_PER_FK ON AGENCY_INCIDENT_PARTIES (PERSON_ID);
