create table ASSESSMENT_SUPERVISIONS(
    ASSESSMENT_ID NUMBER(10, 0) NOT NULL
  , SUPERVISION_LEVEL_TYPE VARCHAR2(12 CHAR) NOT NULL
  , LIST_SEQ NUMBER(6, 0)
  , MINI_SCORE NUMBER(6, 2) NOT NULL
  , MAX_SCORE NUMBER(6, 2) NOT NULL
  , EFFECTIVE_DATE DATE NOT NULL
  , EXPIRY_DATE DATE
  , MODIFY_USER_ID VARCHAR2(32 CHAR)
  , UPDATE_ALLOWED_FLAG VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL
  , ACTIVE_FLAG VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL
  , CREATE_DATETIME TIMESTAMP(9) DEFAULT systimestamp NOT NULL
  , CREATE_USER_ID VARCHAR2(32 CHAR) DEFAULT USER NOT NULL
  , MODIFY_DATETIME TIMESTAMP(9)
  , AUDIT_TIMESTAMP TIMESTAMP(9)
  , AUDIT_USER_ID VARCHAR2(32 CHAR)
  , AUDIT_MODULE_NAME VARCHAR2(65 CHAR)
  , AUDIT_CLIENT_USER_ID VARCHAR2(64 CHAR)
  , AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39 CHAR)
  , AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64 CHAR)
  , AUDIT_ADDITIONAL_INFO VARCHAR2(256 CHAR),
      constraint OFFENDER_SUPERVISIONS_PK
        primary key (SUPERVISION_LEVEL_TYPE, ASSESSMENT_ID),
    constraint OFF_SUP_ASS_FK
      foreign key (ASSESSMENT_ID) references ASSESSMENTS
)