CREATE TABLE AGENCY_INCIDENTS (
    REPORTED_STAFF_ID NUMBER(10,0),
    AGENCY_INCIDENT_ID NUMBER(10,0),
    INCIDENT_DATE DATE,
    INTERNAL_LOCATION_ID NUMBER(10,0),
    INCIDENT_TIME DATE,
    INCIDENT_TYPE VARCHAR2(12),
    INCIDENT_STATUS VARCHAR2(12),
    CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
    CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
    MODIFY_USER_ID VARCHAR2(32),
    MODIFY_DATETIME TIMESTAMP,
    LOCK_FLAG VARCHAR2(1) DEFAULT 'N' ,
    INCIDENT_DETAILS VARCHAR2(4000),
    REPORT_DATE DATE,
    REPORT_TIME DATE,
    AGY_LOC_ID VARCHAR2(6),
    AUDIT_TIMESTAMP TIMESTAMP,
    AUDIT_USER_ID VARCHAR2(32),
    AUDIT_MODULE_NAME VARCHAR2(65),
    AUDIT_CLIENT_USER_ID VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO VARCHAR2(256),
    CONSTRAINT AGENCY_INCIDENTS_PK PRIMARY KEY (AGENCY_INCIDENT_ID),
    CONSTRAINT AGY_INC_AGY_INTL_F1 FOREIGN KEY (INTERNAL_LOCATION_ID) REFERENCES AGENCY_INTERNAL_LOCATIONS(INTERNAL_LOCATION_ID),
    CONSTRAINT AGY_INC_AGY_LOC_FK FOREIGN KEY (AGY_LOC_ID) REFERENCES AGENCY_LOCATIONS(AGY_LOC_ID)
);
CREATE UNIQUE INDEX AGENCY_INCIDENTS_PK ON AGENCY_INCIDENTS (AGENCY_INCIDENT_ID);
CREATE INDEX AGY_INC_AGY_INTL_F1 ON AGENCY_INCIDENTS (INTERNAL_LOCATION_ID);
CREATE INDEX AGY_INC_AGY_LOC_FK ON AGENCY_INCIDENTS (AGY_LOC_ID);
