
  CREATE TABLE "OFFENDER_ADJUSTMENT_TXNS"
   (    "TXN_ID" NUMBER(10,0) NOT NULL,
    "TXN_ENTRY_SEQ" NUMBER(6,0) NOT NULL,
    "OFFENDER_ID" NUMBER(10,0) NOT NULL,
    "OFFENDER_DEDUCTION_ID" NUMBER(10,0) NOT NULL,
    "TXN_POSTING_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "ADJUSTMENT_DATE" DATE NOT NULL,
    "ADJUSTMENT_AMOUNT" NUMBER(11,2),
    "ADJUSTMENT_REASON_CODE" VARCHAR2(12 CHAR),
    "ADJUSTMENT_TEXT" VARCHAR2(40 CHAR),
    "ADJUSTMENT_USER_ID" VARCHAR2(32 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_ADJUSTMENT_TXNS_PK" PRIMARY KEY ("TXN_ID", "TXN_ENTRY_SEQ")
  );

  CREATE INDEX "OFFENDER_ADJUSTMENT_TXNS_FK10" ON "OFFENDER_ADJUSTMENT_TXNS" ("OFFENDER_ID");


  CREATE INDEX "OFFENDER_ADJUSTMENT_TXNS_NI1" ON "OFFENDER_ADJUSTMENT_TXNS" ("OFFENDER_DEDUCTION_ID");


  CREATE UNIQUE INDEX "OFFENDER_ADJUSTMENT_TXNS_PK" ON "OFFENDER_ADJUSTMENT_TXNS" ("TXN_ID", "TXN_ENTRY_SEQ");
