
  CREATE TABLE "OFFENDER_TEAM_ASSIGNMENTS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "FUNCTION_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "TEAM_ID" NUMBER(10,0) NOT NULL,
    "ASSIGNMENT_DATE" DATE NOT NULL,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_TEAM_ASSIGNMENTS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "FUNCTION_TYPE")
  );

  CREATE UNIQUE INDEX "OFFENDER_TEAM_ASSIGNMENTS_PK" ON "OFFENDER_TEAM_ASSIGNMENTS" ("OFFENDER_BOOK_ID", "FUNCTION_TYPE");


  CREATE INDEX "OFFENDER_TEAM_ASSIGNMENTS_FK1" ON "OFFENDER_TEAM_ASSIGNMENTS" ("TEAM_ID");
