
  CREATE TABLE "IWP_DOCUMENTS"
   (    "DOCUMENT_ID" NUMBER NOT NULL,
    "OFFENDER_BOOK_ID" NUMBER(10,0),
    "DOCUMENT_NAME" VARCHAR2(50 CHAR) NOT NULL,
    "TEMPLATE_ID" NUMBER NOT NULL,
    "COMMENT_TEXT" VARCHAR2(256 CHAR),
    "ACTIVE_FLAG" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    "LOCATION" VARCHAR2(256 CHAR),
    "OBJECT_ID" VARCHAR2(100 CHAR),
    "OBJECT_TYPE" VARCHAR2(12 CHAR),
    "DOCUMENT_STATUS" VARCHAR2(12 CHAR) NOT NULL,
    "DOCUMENT_BODY" BLOB,
    "DATE_CREATED" DATE DEFAULT trunc(sysdate) NOT NULL,
    "DATE_MODIFIED" DATE,
    "USER_CREATED" VARCHAR2(32 CHAR) DEFAULT user NOT NULL,
    "USER_MODIFIED" VARCHAR2(32 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "IWP_DOCUMENTS_CHK2" CHECK (offender_book_id IS NOT NULL OR (object_id IS NOT NULL AND object_type IS NOT NULL)),
     CONSTRAINT "IWP_DOCUMENTS_PK" PRIMARY KEY ("DOCUMENT_ID")
  );

  CREATE INDEX "IWP_DOCUMENTS_FK9" ON "IWP_DOCUMENTS" ("OFFENDER_BOOK_ID");


  CREATE UNIQUE INDEX "IWP_DOCUMENTS_PK" ON "IWP_DOCUMENTS" ("DOCUMENT_ID");
