CREATE TABLE OIC_HEARINGS (
    OIC_HEARING_ID NUMBER(10,0),
    OIC_HEARING_TYPE VARCHAR2(12),
    OIC_INCIDENT_ID NUMBER(10,0),
    SCHEDULE_DATE DATE,
    SCHEDULE_TIME DATE,
    HEARING_DATE DATE,
    HEARING_TIME DATE,
    HEARING_STAFF_ID NUMBER(10,0),
    VISIT_JUSTICE_TEXT VARCHAR2(40),
    COMMENT_TEXT VARCHAR2(240),
    TAPE_NUMBER VARCHAR2(12),
    CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
    CREATE_USER_ID VARCHAR2(32) DEFAULT USER,
    MODIFY_DATETIME TIMESTAMP,
    MODIFY_USER_ID VARCHAR2(32),
    INTERNAL_LOCATION_ID NUMBER(10,0),
    REPRESENTATIVE_TEXT VARCHAR2(240),
    EVENT_ID NUMBER(10,0),
    AUDIT_TIMESTAMP TIMESTAMP,
    AUDIT_USER_ID VARCHAR2(32),
    AUDIT_MODULE_NAME VARCHAR2(65),
    AUDIT_CLIENT_USER_ID VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO VARCHAR2(256),
    EVENT_STATUS VARCHAR2(12) DEFAULT 'SCH',
    CONSTRAINT OIC_HEARINGS_PK PRIMARY KEY (OIC_HEARING_ID),
    CONSTRAINT OIC_HEAR_AGY_INT_LOC_FK FOREIGN KEY (INTERNAL_LOCATION_ID) REFERENCES AGENCY_INTERNAL_LOCATIONS(INTERNAL_LOCATION_ID),
    CONSTRAINT OIC_HR_AGY_INC_PTY_FK FOREIGN KEY (OIC_INCIDENT_ID) REFERENCES AGENCY_INCIDENT_PARTIES(OIC_INCIDENT_ID)
);
CREATE INDEX OH_NI1 ON OIC_HEARINGS (OIC_INCIDENT_ID);
CREATE UNIQUE INDEX OIC_HEARINGS_PK ON OIC_HEARINGS (OIC_HEARING_ID);
CREATE INDEX OIC_HEARINGS_X01 ON OIC_HEARINGS (HEARING_DATE);
CREATE INDEX OIC_HEAR_AGY_INT_LOC_FK ON OIC_HEARINGS (INTERNAL_LOCATION_ID);
