CREATE TABLE OFFENDER_GANG_AFFILIATIONS
(
    GANG_CODE                     VARCHAR2(12)                      NOT NULL,
    OFFENDER_BOOK_ID              NUMBER(10, 0)                     NOT NULL,
    COMMENT_TEXT                  VARCHAR2(4000)                    NULL,
    CREATE_DATETIME               TIMESTAMP    DEFAULT systimestamp NOT NULL,
    CREATE_USER_ID                VARCHAR2(32) DEFAULT USER         NOT NULL,
    MODIFY_DATETIME               TIMESTAMP                         NULL,
    MODIFY_USER_ID                VARCHAR2(32)                      NULL,
    AUDIT_TIMESTAMP               TIMESTAMP                         NULL,
    AUDIT_USER_ID                 VARCHAR2(32)                      NULL,
    AUDIT_MODULE_NAME             VARCHAR2(65)                      NULL,
    AUDIT_CLIENT_USER_ID          VARCHAR2(64)                      NULL,
    AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39)                      NULL,
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64)                      NULL,
    AUDIT_ADDITIONAL_INFO         VARCHAR2(256)                     NULL,
    CONSTRAINT OFFENDER_GANG_AFFILIATIONS PRIMARY KEY (OFFENDER_BOOK_ID, GANG_CODE),
    CONSTRAINT OFFENDER_GANG_AFFILIATIONS_FK1 FOREIGN KEY (GANG_CODE) REFERENCES GANGS (GANG_CODE),
    CONSTRAINT OFF_GA_OFF_BKG_F1 FOREIGN KEY (OFFENDER_BOOK_ID) REFERENCES OFFENDER_BOOKINGS (OFFENDER_BOOK_ID)
);
CREATE UNIQUE INDEX OFFENDER_GANG_AFFILIATIONS ON OFFENDER_GANG_AFFILIATIONS (OFFENDER_BOOK_ID, GANG_CODE);
CREATE INDEX OFFENDER_GANG_AFFILIATIONS_FK1 ON OFFENDER_GANG_AFFILIATIONS (GANG_CODE);