
  CREATE TABLE "OFFENDER_GANG_INVESTS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "GANG_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "INVESTIGATE_SEQ" NUMBER(6,0) NOT NULL,
    "MEMBERSHIP_STATUS" VARCHAR2(12 CHAR) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "MODIFIED_DATE" DATE NOT NULL,
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_GANG_INVESTIGATIONS" PRIMARY KEY ("OFFENDER_BOOK_ID", "GANG_CODE", "MEMBERSHIP_STATUS")
  );

  CREATE UNIQUE INDEX "OFFENDER_GANG_INVESTIGATIONS" ON "OFFENDER_GANG_INVESTS" ("OFFENDER_BOOK_ID", "GANG_CODE", "MEMBERSHIP_STATUS");


  CREATE INDEX "OFFENDER_GANG_INVESTS_NI1" ON "OFFENDER_GANG_INVESTS" ("GANG_CODE");
