CREATE TABLE ORDER_PURPOSES (
	ORDER_ID NUMBER(10,0) NOT NULL,
	ORDER_PARTY_CODE VARCHAR2(12) NOT NULL,
	PURPOSE_CODE VARCHAR2(12) NOT NULL,
	CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
	CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
	MODIFY_DATETIME TIMESTAMP,
	MODIFY_USER_ID VARCHAR2(32),
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR2(32),
	AUDIT_MODULE_NAME VARCHAR2(65),
	AUDIT_CLIENT_USER_ID VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO VARCHAR2(256),
	CONSTRAINT ORDER_PURPOSES_PK PRIMARY KEY (ORDER_ID,ORDER_PARTY_CODE,PURPOSE_CODE),
	CONSTRAINT ORDER_PURPOSES_ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
CREATE UNIQUE INDEX ORDER_PURPOSES_PK ON ORDER_PURPOSES (ORDER_ID,ORDER_PARTY_CODE,PURPOSE_CODE);