
  CREATE TABLE "OFFENDER_MILITARY_RECORDS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "MILITARY_SEQ" NUMBER(6,0) NOT NULL,
    "WAR_ZONE_CODE" VARCHAR2(12 CHAR),
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE,
    "MILITARY_DISCHARGE_CODE" VARCHAR2(12 CHAR),
    "MILITARY_BRANCH_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "DESCRIPTION" VARCHAR2(240 CHAR),
    "UNIT_NUMBER" VARCHAR2(20 CHAR),
    "ENLISTMENT_LOCATION" VARCHAR2(40 CHAR),
    "DISCHARGE_LOCATION" VARCHAR2(40 CHAR),
    "SELECTIVE_SERVICES_FLAG" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    "MILITARY_RANK_CODE" VARCHAR2(12 CHAR),
    "SERVICE_NUMBER" VARCHAR2(12 CHAR),
    "DISCIPLINARY_ACTION_CODE" VARCHAR2(6 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_MILITARY_RECORDS" PRIMARY KEY ("OFFENDER_BOOK_ID", "MILITARY_SEQ")
  );

  CREATE UNIQUE INDEX "OFFENDER_MILITARY_RECORDS" ON "OFFENDER_MILITARY_RECORDS" ("OFFENDER_BOOK_ID", "MILITARY_SEQ");
