
  CREATE TABLE "CASE_ASSOCIATED_PERSONS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0),
    "CASE_ID" NUMBER(10,0),
    "PERSON_ID" NUMBER(10,0),
    "CREATE_USER_ID" VARCHAR2(40 CHAR) DEFAULT USER NOT NULL,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CASE_INVOLVEMENT" VARCHAR2(12 CHAR),
    "MODIFY_USER_ID" VARCHAR2(40 CHAR),
    "MODIFY_DATETIME" TIMESTAMP (9),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "CASE_ASSOCIATED_PERSONS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "CASE_ID", "PERSON_ID")
  );

  CREATE INDEX "CASE_ASSOCIATED_PERSONS_NI1" ON "CASE_ASSOCIATED_PERSONS" ("OFFENDER_BOOK_ID");


  CREATE INDEX "CASE_ASSOCIATED_PERSONS_NI2" ON "CASE_ASSOCIATED_PERSONS" ("CASE_ID");


  CREATE INDEX "CASE_ASSOCIATED_PERSONS_NI3" ON "CASE_ASSOCIATED_PERSONS" ("PERSON_ID");


  CREATE UNIQUE INDEX "CASE_ASSOCIATED_PERSONS_PK" ON "CASE_ASSOCIATED_PERSONS" ("OFFENDER_BOOK_ID", "CASE_ID", "PERSON_ID");
