
  CREATE TABLE "OFFENDER_LICENCE_SENTENCES"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "SENTENCE_SEQ" NUMBER(6,0) NOT NULL,
    "CASE_ID" NUMBER(10,0) NOT NULL,
    "LICENCE_SENTENCE_SEQ" NUMBER(6,0) NOT NULL,
    "CREATION_DATE" DATE,
    "CREATION_USER" VARCHAR2(32 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_LICENCE_SENTENCES_FK2" FOREIGN KEY ("OFFENDER_BOOK_ID", "SENTENCE_SEQ")
      REFERENCES "OFFENDER_SENTENCES" ("OFFENDER_BOOK_ID", "SENTENCE_SEQ"),
     CONSTRAINT "OFFENDER_LICENCE_SENTENCES_FK3" FOREIGN KEY ("OFFENDER_BOOK_ID", "LICENCE_SENTENCE_SEQ")
      REFERENCES "OFFENDER_SENTENCES" ("OFFENDER_BOOK_ID", "SENTENCE_SEQ"),
     CONSTRAINT "OFFENDER_LICENCE_SENTENCES_FK9" FOREIGN KEY ("OFFENDER_BOOK_ID")
      REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID"),
     CONSTRAINT "OFFENDER_LICENCE_SENTENCES_FK1" FOREIGN KEY ("CASE_ID")
      REFERENCES "OFFENDER_CASES" ("CASE_ID")
  );

  CREATE INDEX "OFFENDER_LICENCE_SENTENCES_FK1" ON "OFFENDER_LICENCE_SENTENCES" ("CASE_ID");


  CREATE INDEX "OFFENDER_LICENCE_SENTENCES_FK2" ON "OFFENDER_LICENCE_SENTENCES" ("OFFENDER_BOOK_ID", "SENTENCE_SEQ");


  CREATE INDEX "OFFENDER_LICENCE_SENTENCES_FK3" ON "OFFENDER_LICENCE_SENTENCES" ("OFFENDER_BOOK_ID", "LICENCE_SENTENCE_SEQ");
