
  CREATE TABLE "OFFENDER_SUBSTANCE_TREATMENTS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "TREATMENT_SEQ" NUMBER(6,0) DEFAULT 1 NOT NULL,
    "SUBSTANCE_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "TREATMENT_FROM_DATE" DATE NOT NULL,
    "FROM_DATE_FLAG" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    "ROOT_OFFENDER_ID" NUMBER(10,0) NOT NULL,
    "CASELOAD_TYPE" VARCHAR2(12 CHAR),
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "TO_DATE_FLAG" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    "TREATMENT_TO_DATE" DATE,
    "TREATMENT_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "TREATMENT_PLACE" VARCHAR2(40 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_SUBS_TREATMENTS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "TREATMENT_SEQ", "SUBSTANCE_TYPE")
  );

  CREATE INDEX "OFF_ST_OFF_SU_F1" ON "OFFENDER_SUBSTANCE_TREATMENTS" ("OFFENDER_BOOK_ID", "SUBSTANCE_TYPE");


  CREATE UNIQUE INDEX "OFFENDER_SUBS_TREATMENTS_PK" ON "OFFENDER_SUBSTANCE_TREATMENTS" ("OFFENDER_BOOK_ID", "TREATMENT_SEQ", "SUBSTANCE_TYPE");
