CREATE TABLE OFFENDER_INTER_MVMT_LOCATIONS (
    OFFENDER_IML_ID NUMBER(10,0) NOT NULL,
    OFFENDER_BOOK_ID NUMBER(10,0) NOT NULL,
    AGENCY_LOCATION_ID VARCHAR2(6) NOT NULL,
    AGENCY_IML_ID NUMBER(10,0) NOT NULL,
    MOVEMENT_DATE DATE NOT NULL,
    MOVEMENT_TIME DATE NOT NULL,
    FROM_AGENCY_IML_ID NUMBER(10,0),
    CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
    CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
    MODIFY_DATETIME TIMESTAMP,
    MODIFY_USER_ID VARCHAR2(32),
    MOVEMENT_TYPE VARCHAR2(12),
    MOVEMENT_REASON_CODE VARCHAR2(12),
    EVENT_ID NUMBER(10,0),
    AUDIT_TIMESTAMP TIMESTAMP,
    AUDIT_USER_ID VARCHAR2(32),
    AUDIT_MODULE_NAME VARCHAR2(65),
    AUDIT_CLIENT_USER_ID VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO VARCHAR2(256),
    CONSTRAINT OFFENDER_INTER_MVMT_LOC_PK PRIMARY KEY (OFFENDER_IML_ID),
    CONSTRAINT OFF_IL_AGY_LOC_FK1 FOREIGN KEY (AGENCY_LOCATION_ID) REFERENCES AGENCY_LOCATIONS(AGY_LOC_ID),
    CONSTRAINT OFF_IML_AGY_INT_LOC_FK1 FOREIGN KEY (AGENCY_IML_ID) REFERENCES AGENCY_INTERNAL_LOCATIONS(INTERNAL_LOCATION_ID),
    CONSTRAINT OFF_IML_AGY_INT_LOC_FK2 FOREIGN KEY (FROM_AGENCY_IML_ID) REFERENCES AGENCY_INTERNAL_LOCATIONS(INTERNAL_LOCATION_ID),
    CONSTRAINT OFF_INTER_MVMT_LOCATIONS_FK9 FOREIGN KEY (OFFENDER_BOOK_ID) REFERENCES OFFENDER_BOOKINGS(OFFENDER_BOOK_ID)
);
CREATE INDEX OFFENDER_INTER_MVMT_LOC_NI1 ON OFFENDER_INTER_MVMT_LOCATIONS (AGENCY_LOCATION_ID,MOVEMENT_DATE);
CREATE INDEX OFFENDER_INTER_MVMT_LOC_NI2 ON OFFENDER_INTER_MVMT_LOCATIONS (OFFENDER_BOOK_ID,MOVEMENT_DATE);
CREATE INDEX OFFENDER_INTER_MVMT_LOC_NI3 ON OFFENDER_INTER_MVMT_LOCATIONS (EVENT_ID);
CREATE UNIQUE INDEX OFFENDER_INTER_MVMT_LOC_PK ON OFFENDER_INTER_MVMT_LOCATIONS (OFFENDER_IML_ID);
CREATE INDEX OFF_IML_AGY_INT_LOC_FK1 ON OFFENDER_INTER_MVMT_LOCATIONS (AGENCY_IML_ID);
CREATE INDEX OFF_IML_AGY_INT_LOC_FK2 ON OFFENDER_INTER_MVMT_LOCATIONS (FROM_AGENCY_IML_ID);
