
  CREATE TABLE "OFFENDER_TRUST_ACCOUNTS_TEMP"
   (    "CASELOAD_ID" VARCHAR2(6 CHAR) NOT NULL,
    "OFFENDER_ID" NUMBER(10,0) NOT NULL,
    "SESSION_ID" NUMBER(10,0) NOT NULL,
    "ACCOUNT_CLOSED_FLAG" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    "HOLD_BALANCE" NUMBER(11,2),
    "CURRENT_BALANCE" NUMBER(11,2),
    "MODIFY_DATE" DATE NOT NULL,
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "LIST_SEQ" NUMBER(6,0) DEFAULT 99,
    "NOTIFY_DATE" DATE,
    "OFFENDER_BOOK_ID" NUMBER(10,0),
    "LAST_NAME" VARCHAR2(35 CHAR),
    "FIRST_NAME" VARCHAR2(35 CHAR),
    "MOVEMENT_DATE" DATE,
    "AGY_LOC_ID" VARCHAR2(6 CHAR),
    "OFFENDER_ID_DISPLAY" VARCHAR2(10 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_TRUST_ACCTS_TEMP_PK" PRIMARY KEY ("OFFENDER_ID", "CASELOAD_ID", "SESSION_ID")
  );

  CREATE UNIQUE INDEX "OFFENDER_TRUST_ACCTS_TEMP_PK" ON "OFFENDER_TRUST_ACCOUNTS_TEMP" ("OFFENDER_ID", "CASELOAD_ID", "SESSION_ID");


  CREATE INDEX "OFF_TRUST_ACCOUNTS_TEMP_FK9" ON "OFFENDER_TRUST_ACCOUNTS_TEMP" ("OFFENDER_BOOK_ID");
