
  CREATE TABLE "OIC_HEARING_NOTICES"
   (    "OIC_HEARING_ID" NUMBER(10,0) NOT NULL,
    "OIC_NOTICE_SEQ" NUMBER(7,0) NOT NULL,
    "DELIVERY_DATE" DATE,
    "DELIVERY_TIME" DATE,
    "DELIVERY_STAFF_ID" NUMBER(10,0),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OIC_HEARING_NOTICES_PK" PRIMARY KEY ("OIC_HEARING_ID", "OIC_NOTICE_SEQ")
  );

  CREATE UNIQUE INDEX "OIC_HEARING_NOTICES_PK" ON "OIC_HEARING_NOTICES" ("OIC_HEARING_ID", "OIC_NOTICE_SEQ");


  CREATE INDEX "OIC_HN_OIC_STAFF_FK" ON "OIC_HEARING_NOTICES" ("DELIVERY_STAFF_ID");
