
  CREATE TABLE "MERGE_TRANSACTION_LOGS"
   (    "MERGE_TRANSACTION_ID" NUMBER(10,0) NOT NULL,
    "LOG_TIMESTAMP" TIMESTAMP (9) NOT NULL,
    "LOG_TEXT" VARCHAR2(4000 CHAR) NOT NULL,
    "LOG_LEVEL" VARCHAR2(60 CHAR) NOT NULL,
    "LOG_MSG_PART" NUMBER(22,0) DEFAULT 1 NOT NULL,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "MERGE_TRANSACTION_LOGS_PK" PRIMARY KEY ("MERGE_TRANSACTION_ID", "LOG_TIMESTAMP", "LOG_MSG_PART")
  );

  CREATE UNIQUE INDEX "MERGE_TRANSACTION_LOGS_PK" ON "MERGE_TRANSACTION_LOGS" ("MERGE_TRANSACTION_ID", "LOG_TIMESTAMP", "LOG_MSG_PART");
