
  CREATE TABLE "OFFENDER_GANG_EVIDENCES"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "GANG_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "OFF_GANG_EVIDENCE_SEQ" NUMBER(6,0) NOT NULL,
    "GANG_EVIDENCE_CODE" VARCHAR2(12 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_GANG_EVIDENCES_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "OFF_GANG_EVIDENCE_SEQ", "GANG_CODE")
  );

  CREATE INDEX "OFFENDER_GANG_EVIDENCES_FK1" ON "OFFENDER_GANG_EVIDENCES" ("GANG_CODE", "OFFENDER_BOOK_ID");


  CREATE UNIQUE INDEX "OFFENDER_GANG_EVIDENCES_PK" ON "OFFENDER_GANG_EVIDENCES" ("OFFENDER_BOOK_ID", "OFF_GANG_EVIDENCE_SEQ", "GANG_CODE");
