
CREATE TABLE WORK_FLOW_LOGS
(
  WORK_FLOW_ID                  NUMBER(10)                             NOT NULL CONSTRAINT WORK_FL_WORK_FLOW_PK REFERENCES WORK_FLOWS,
  WORK_FLOW_SEQ                 NUMBER(6)                              NOT NULL,
  WORK_ACTION_CODE              VARCHAR2(12 CHAR)                      NOT NULL,
  WORK_ACTION_DATE              DATE,
  ACTION_USER_ID                NUMBER(6),
  WORK_FLOW_STATUS              VARCHAR2(12 CHAR)                      NOT NULL,
  CREATE_DATE                   DATE,
  LOCATE_AGY_LOC_ID             VARCHAR2(6 CHAR) CONSTRAINT WORK_FL_AGY_LOC_F1 REFERENCES AGENCY_LOCATIONS,
  CREATE_USER_ID                VARCHAR2(32 CHAR) DEFAULT USER         NOT NULL,
  CREATE_DATETIME               TIMESTAMP(9)      DEFAULT SYSTIMESTAMP NOT NULL,
  MODIFY_DATETIME               TIMESTAMP(9),
  MODIFY_USER_ID                VARCHAR2(32 CHAR),
  AUDIT_TIMESTAMP               TIMESTAMP(9),
  AUDIT_USER_ID                 VARCHAR2(32 CHAR),
  AUDIT_MODULE_NAME             VARCHAR2(65 CHAR),
  AUDIT_CLIENT_USER_ID          VARCHAR2(64 CHAR),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39 CHAR),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64 CHAR),
  AUDIT_ADDITIONAL_INFO         VARCHAR2(256 CHAR),
  CONSTRAINT WORK_FLOW_LOGS_PK PRIMARY KEY (WORK_FLOW_ID, WORK_FLOW_SEQ)
);

COMMENT ON TABLE WORK_FLOW_LOGS IS 'THE DETAILED EVENT LOG OF THE WOK FLOW';
COMMENT ON COLUMN WORK_FLOW_LOGS.WORK_FLOW_ID IS 'WORK FLOW OBJECT ID';
COMMENT ON COLUMN WORK_FLOW_LOGS.WORK_ACTION_CODE IS 'ACTION CODE ON THE OBJECT (SUCH AS VERIFIY, REVIEW ..)';
COMMENT ON COLUMN WORK_FLOW_LOGS.WORK_ACTION_DATE IS 'THE ACTION DATE ON THE WORK FLOW OBJECTS';
COMMENT ON COLUMN WORK_FLOW_LOGS.ACTION_USER_ID IS 'USER WHO PERFORM THE ACTION ON THE WORK FLOW OBJECT';
COMMENT ON COLUMN WORK_FLOW_LOGS.WORK_FLOW_STATUS IS 'THE ACTION OF THE STATUS (REQUESTED, CANCELLED, DONE)';
COMMENT ON COLUMN WORK_FLOW_LOGS.CREATE_DATE IS 'CREATE DATE OF THE RECORD';
COMMENT ON COLUMN WORK_FLOW_LOGS.CREATE_USER_ID IS 'THE USER WHO CREATES THE RECORD';
COMMENT ON COLUMN WORK_FLOW_LOGS.CREATE_DATETIME IS 'THE TIMESTAMP WHEN THE RECORD IS CREATED';
COMMENT ON COLUMN WORK_FLOW_LOGS.MODIFY_DATETIME IS 'THE TIMESTAMP WHEN THE RECORD IS MODIFIED';
COMMENT ON COLUMN WORK_FLOW_LOGS.MODIFY_USER_ID IS 'THE USER WHO MODIFIES THE RECORD';

CREATE INDEX WORK_FL_AGY_LOC_F1 ON WORK_FLOW_LOGS (LOCATE_AGY_LOC_ID)


