
  CREATE TABLE "OFF_CASE_NOTE_RECIPIENTS"
   (    "CASE_NOTE_ID" NUMBER(10,0) NOT NULL,
    "TEAM_ID" NUMBER(10,0) NOT NULL,
    "STAFF_ID" NUMBER(10,0),
    "OFF_CASE_NOTE_RECIPIENT_ID" NUMBER(10,0) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFF_CASE_NOTE_RECIPIENTS_PK" PRIMARY KEY ("OFF_CASE_NOTE_RECIPIENT_ID")
  );

  CREATE INDEX "OFF_CASE_NOTE_RECIPIENTS_NI2" ON "OFF_CASE_NOTE_RECIPIENTS" ("STAFF_ID");


  CREATE INDEX "OFF_CASE_NOTE_RECIPIENTS_NI3" ON "OFF_CASE_NOTE_RECIPIENTS" ("TEAM_ID");


  CREATE INDEX "OFF_CASE_NOTE_RECIPIENTS_NI1" ON "OFF_CASE_NOTE_RECIPIENTS" ("CASE_NOTE_ID");


  CREATE UNIQUE INDEX "OFF_CASE_NOTE_RECIPIENTS_PK" ON "OFF_CASE_NOTE_RECIPIENTS" ("OFF_CASE_NOTE_RECIPIENT_ID");
