
  CREATE TABLE "OFFENDER_PAYMENT_PROFILES"
   (    "OFFENDER_PAYMENT_PROFILE_ID" NUMBER(10,0) NOT NULL,
    "OFFENDER_ID" NUMBER(10,0) NOT NULL,
    "CASELOAD_ID" VARCHAR2(6 CHAR) NOT NULL,
    "TXN_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "PAYMENT_MODE" VARCHAR2(12 CHAR) NOT NULL,
    "ADVANCE_AMOUNT" NUMBER(11,2),
    "START_DATE" DATE DEFAULT sysdate NOT NULL,
    "ADVANCE_DATE" DATE,
    "PAYMENT_AMOUNT" NUMBER(11,2),
    "END_DATE" DATE,
    "REFERENCE_TEXT" VARCHAR2(40 CHAR),
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "RECORD_USER_ID" VARCHAR2(30 CHAR) DEFAULT user,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_PAYMENT_PROFILES_PK" PRIMARY KEY ("OFFENDER_PAYMENT_PROFILE_ID")
  );

  CREATE INDEX "OFFENDER_PAYMENT_PROFILES_NI1" ON "OFFENDER_PAYMENT_PROFILES" ("CASELOAD_ID", "START_DATE");


  CREATE INDEX "OFFENDER_PAYMENT_PROFILES_NI2" ON "OFFENDER_PAYMENT_PROFILES" ("OFFENDER_ID", "CASELOAD_ID", "TXN_TYPE", "PAYMENT_MODE", "START_DATE");


  CREATE UNIQUE INDEX "OFFENDER_PAYMENT_PROFILES_PK" ON "OFFENDER_PAYMENT_PROFILES" ("OFFENDER_PAYMENT_PROFILE_ID");
