
  CREATE TABLE "OFFENDER_CASE_IDENTIFIERS"
   (    "IDENTIFIER_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "CASE_ID" NUMBER(10,0) NOT NULL,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "IDENTIFIER_NO" VARCHAR2(240 CHAR) NOT NULL,
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_CASE_IDENTIFIERS_PK" PRIMARY KEY ("IDENTIFIER_NO", "IDENTIFIER_TYPE", "CASE_ID")
  );

  CREATE INDEX "OFFENDER_CASE_IDENTIFIERS_NI2" ON "OFFENDER_CASE_IDENTIFIERS" ("CASE_ID");


  CREATE UNIQUE INDEX "OFFENDER_CASE_IDENTIFIERS_PK" ON "OFFENDER_CASE_IDENTIFIERS" ("IDENTIFIER_NO", "IDENTIFIER_TYPE", "CASE_ID");
