
  CREATE TABLE "OFFENDER_NA_DETAILS"
   (    "OFFENDER_ID" NUMBER(10,0) NOT NULL,
    "NS_OFFENDER_ID" NUMBER(10,0) NOT NULL,
    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "NS_OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "TYPE_SEQ" NUMBER(3,0) NOT NULL,
    "NS_REASON_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "NS_LEVEL_CODE" VARCHAR2(12 CHAR),
    "NS_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "NS_EFFECTIVE_DATE" DATE NOT NULL,
    "NS_EXPIRY_DATE" DATE,
    "AUTHORIZED_STAFF" VARCHAR2(60 CHAR),
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "RECIP_NS_REASON_CODE" VARCHAR2(12 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_NA_DETAILS_PK" PRIMARY KEY ("OFFENDER_ID", "NS_OFFENDER_ID", "TYPE_SEQ")
  );

  CREATE UNIQUE INDEX "OFFENDER_NA_DETAILS_PK" ON "OFFENDER_NA_DETAILS" ("OFFENDER_ID", "NS_OFFENDER_ID", "TYPE_SEQ");


  CREATE INDEX "OFFENDER_NA_DETAILS_N1" ON "OFFENDER_NA_DETAILS" ("NS_OFFENDER_BOOK_ID");


  CREATE INDEX "OFFENDER_NA_DETAILS_N2" ON "OFFENDER_NA_DETAILS" ("OFFENDER_BOOK_ID");
