CREATE TABLE "ACCOUNT_CODES"
(
  "REC_ACCOUNT_CODE"              NUMBER(6, 0),
  "ACCOUNT_CODE"                  NUMBER(6, 0)                      NOT NULL ,
  "ACCOUNT_NAME"                  VARCHAR2(40 CHAR)                 NOT NULL ,
  "POSTING_STATUS_FLAG"           VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ,
  "ACCOUNT_TYPE"                  VARCHAR2(12 CHAR),
  "SUB_ACCOUNT_TYPE"              VARCHAR2(12 CHAR),
  "TXN_POSTING_TYPE"              VARCHAR2(12 CHAR),
  "ALL_CASELOAD_FLAG"             VARCHAR2(1 CHAR) DEFAULT 'Y'      NOT NULL ,
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "MODIFY_DATE"                   DATE                              NOT NULL ,
  "LIST_SEQ"                      NUMBER(6, 0) DEFAULT 99,
  "CASELOAD_TYPE"                 VARCHAR2(12 CHAR),
  "PARENT_ACCOUNT_CODE"           NUMBER(6, 0),
  "CREATE_DATETIME"               TIMESTAMP(9) DEFAULT systimestamp NOT NULL ,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER    NOT NULL ,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "AUDIT_TIMESTAMP"               TIMESTAMP(9),
  "AUDIT_USER_ID"                 VARCHAR2(32 CHAR),
  "AUDIT_MODULE_NAME"             VARCHAR2(65 CHAR),
  "AUDIT_CLIENT_USER_ID"          VARCHAR2(64 CHAR),
  "AUDIT_CLIENT_IP_ADDRESS"       VARCHAR2(39 CHAR),
  "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
  "AUDIT_ADDITIONAL_INFO"         VARCHAR2(256 CHAR),
  CONSTRAINT "ACCOUNT_CODES_PK" PRIMARY KEY ("ACCOUNT_CODE"),
  CONSTRAINT "AC_CODE_AC_CODE_F5" FOREIGN KEY ("PARENT_ACCOUNT_CODE")
  REFERENCES "ACCOUNT_CODES" ("ACCOUNT_CODE")
);


COMMENT ON COLUMN "ACCOUNT_CODES"."ACCOUNT_CODE" IS 'General ledger account code.';

COMMENT ON COLUMN "ACCOUNT_CODES"."ACCOUNT_NAME" IS 'Account Description';

COMMENT ON COLUMN "ACCOUNT_CODES"."POSTING_STATUS_FLAG" IS 'Y/N flag indicating if account is a posting account.';

COMMENT ON COLUMN "ACCOUNT_CODES"."ACCOUNT_TYPE" IS 'Reference Code [ACCOUNT_TYPE ]';

COMMENT ON COLUMN "ACCOUNT_CODES"."SUB_ACCOUNT_TYPE" IS 'Reference Code ( SUB_AC_TYPE).';

COMMENT ON COLUMN "ACCOUNT_CODES"."TXN_POSTING_TYPE" IS 'Reference ( AC_TXN_TYPE ) Account Posting Type';

COMMENT ON COLUMN "ACCOUNT_CODES"."ALL_CASELOAD_FLAG" IS 'Apply for All Caseload';

COMMENT ON COLUMN "ACCOUNT_CODES"."MODIFY_USER_ID" IS 'The user who modifies the record';

COMMENT ON COLUMN "ACCOUNT_CODES"."MODIFY_DATE" IS 'Modify Date';

COMMENT ON COLUMN "ACCOUNT_CODES"."LIST_SEQ" IS 'The sequence in which the data should be shown';

COMMENT ON COLUMN "ACCOUNT_CODES"."CASELOAD_TYPE" IS 'The Case Load Type';

COMMENT ON COLUMN "ACCOUNT_CODES"."PARENT_ACCOUNT_CODE" IS 'Parent_code to Account_code';

COMMENT ON COLUMN "ACCOUNT_CODES"."CREATE_DATETIME" IS 'The timestamp when the record is created';

COMMENT ON COLUMN "ACCOUNT_CODES"."CREATE_USER_ID" IS 'The user who creates the record';

COMMENT ON COLUMN "ACCOUNT_CODES"."MODIFY_DATETIME" IS 'The timestamp when the record is modified ';

COMMENT ON TABLE "ACCOUNT_CODES" IS 'All information encompassed by the chart of accounts for OMS Trust.';


CREATE INDEX "ACCOUNT_CODES_NI1"
  ON "ACCOUNT_CODES" ("CASELOAD_TYPE", "SUB_ACCOUNT_TYPE");


CREATE INDEX "AC_CODE_AC_CODE_F5"
  ON "ACCOUNT_CODES" ("PARENT_ACCOUNT_CODE");


