
  CREATE TABLE "OFFENDER_FINE_PAYMENTS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "PAYMENT_SEQ" NUMBER(6,0) NOT NULL,
    "PAYMENT_DATE" DATE NOT NULL,
    "PAYMENT_AMOUNT" NUMBER(11,2) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "WEEKEND_DAYS" NUMBER(6,0),
    "STAFF_ID" NUMBER(10,0) NOT NULL,
    "PAYMENT_STATUS" VARCHAR2(12 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFF_FINEPA_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "PAYMENT_SEQ")
  );

  CREATE INDEX "OFF_FINE_PAY_STAFF_MEM_FK" ON "OFFENDER_FINE_PAYMENTS" ("STAFF_ID");


  CREATE UNIQUE INDEX "OFF_FINEPA_PK" ON "OFFENDER_FINE_PAYMENTS" ("OFFENDER_BOOK_ID", "PAYMENT_SEQ");
