
  CREATE TABLE "HDC_REQUEST_REFERRALS"
   (    "HDC_REQUEST_REFERRAL_ID" NUMBER(10,0) NOT NULL,
    "REFERRAL_TO" VARCHAR2(12 CHAR) NOT NULL,
    "REFERRED_BY" VARCHAR2(12 CHAR) NOT NULL,
    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "RESPONSE_DUE_DATE" DATE,
    "REFERRAL_INFORMATION" VARCHAR2(240 CHAR),
    "STAFF_ID" NUMBER(10,0),
    "CONTACT_OF_ADDR_BY_LETTER" VARCHAR2(1 CHAR) DEFAULT NULL,
    "CONTACT_OF_ADDR_BY_VISIT" VARCHAR2(1 CHAR) DEFAULT NULL,
    "CONTACT_OF_ADDR_BY_TELEPHONE" VARCHAR2(1 CHAR) DEFAULT NULL,
    "REFERRAL_DATE" DATE NOT NULL,
    "VICTIM_ISSUES_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "OFFENDER_CURFEW_ID" NUMBER(10,0) NOT NULL,
    "RECEIVED_DATE" DATE,
    "RESPONSE_DATE" DATE,
    "RESPONSE_STAFF_ID" NUMBER(10,0),
    "PARENT_HDC_REQUEST_REFERRAL_ID" NUMBER(10,0),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "MESSAGE_ID" VARCHAR2(64 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "HDC_REQUEST_REFERRALS_PK" PRIMARY KEY ("HDC_REQUEST_REFERRAL_ID")
  );

  CREATE INDEX "HDC_REQ_REF_HDC_REQ_REF_FK" ON "HDC_REQUEST_REFERRALS" ("PARENT_HDC_REQUEST_REFERRAL_ID");


  CREATE INDEX "HDC_REQ_REF_OFF_CURFEW_FK" ON "HDC_REQUEST_REFERRALS" ("OFFENDER_CURFEW_ID");


  CREATE INDEX "HDC_REQ_REF_NI1" ON "HDC_REQUEST_REFERRALS" ("OFFENDER_BOOK_ID");


  CREATE INDEX "HDC_REQ_REF_NI2" ON "HDC_REQUEST_REFERRALS" ("STAFF_ID");


  CREATE UNIQUE INDEX "HDC_REQUEST_REFERRALS_PK" ON "HDC_REQUEST_REFERRALS" ("HDC_REQUEST_REFERRAL_ID");
