
  CREATE TABLE "OFFENDER_REHAB_PROVIDERS"
   (    "OFFENDER_REHAB_PROVIDER_ID" NUMBER(10,0),
    "OFFENDER_REHAB_DECISION_ID" NUMBER(10,0) NOT NULL,
    "PROVIDER_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "ACTIVE_FLAG" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    "COMMENT_TEXT" VARCHAR2(4000 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_REHAB_PROVIDERS_PK" PRIMARY KEY ("OFFENDER_REHAB_PROVIDER_ID"),
     CONSTRAINT "OFF_REHAB_PROV_REHAB_DEC_FK" FOREIGN KEY ("OFFENDER_REHAB_DECISION_ID")
      REFERENCES "OFFENDER_REHAB_DECISIONS" ("OFFENDER_REHAB_DECISION_ID"),
     CONSTRAINT "OFF_REHAB_PROV_REHAB_PROV_FK" FOREIGN KEY ("PROVIDER_CODE")
      REFERENCES "REHABILITATION_PROVIDERS" ("PROVIDER_CODE")
  );

  CREATE INDEX "OFFENDER_REHAB_PROVIDERS_NI1" ON "OFFENDER_REHAB_PROVIDERS" ("OFFENDER_REHAB_DECISION_ID");


  CREATE INDEX "OFFENDER_REHAB_PROVIDERS_NI2" ON "OFFENDER_REHAB_PROVIDERS" ("PROVIDER_CODE");


  CREATE UNIQUE INDEX "OFFENDER_REHAB_PROVIDERS_PK" ON "OFFENDER_REHAB_PROVIDERS" ("OFFENDER_REHAB_PROVIDER_ID");
