
  CREATE TABLE "OFFENDER_LICENCE_CONDITIONS"
   (    "OFFENDER_LICENCE_CONDITION_ID" NUMBER(10,0),
    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "SENTENCE_SEQ" NUMBER(6,0) NOT NULL,
    "PARAGRAPH_ID" NUMBER(10,0) NOT NULL,
    "INCLUDE_FLAG" VARCHAR2(1 CHAR) DEFAULT 'Y',
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_LICENCE_CONDITIONS_PK" PRIMARY KEY ("OFFENDER_LICENCE_CONDITION_ID")
  );

  CREATE INDEX "OFFENDER_LICENCE_CONDITION_NI1" ON "OFFENDER_LICENCE_CONDITIONS" ("OFFENDER_BOOK_ID", "SENTENCE_SEQ");


  CREATE INDEX "OFFENDER_LICENCE_CONDITION_NI2" ON "OFFENDER_LICENCE_CONDITIONS" ("PARAGRAPH_ID");


  CREATE UNIQUE INDEX "OFFENDER_LICENCE_CONDITIONS_PK" ON "OFFENDER_LICENCE_CONDITIONS" ("OFFENDER_LICENCE_CONDITION_ID");
