
  CREATE TABLE "OFFENDER_BOOKING_EVENTS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "EVENT_SEQ" NUMBER(6,0) DEFAULT 1 NOT NULL,
    "BOOKING_EVENT_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "REASON_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "FROM_AGY_LOC_ID" VARCHAR2(6 CHAR),
    "TO_AGY_LOC_ID" VARCHAR2(6 CHAR) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "EVENT_DATE" DATE,
    "EVENT_TIME" DATE,
    "EVENT_USER" VARCHAR2(32 CHAR),
    "CREATION_USER" VARCHAR2(32 CHAR),
    "CREATION_DATE" DATE,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_BOOKING_EVENTS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "EVENT_SEQ")
  );

  CREATE UNIQUE INDEX "OFFENDER_BOOKING_EVENTS_PK" ON "OFFENDER_BOOKING_EVENTS" ("OFFENDER_BOOK_ID", "EVENT_SEQ");
