
  CREATE TABLE "OFFENDER_REHAB_DECISIONS"
   (    "OFFENDER_REHAB_DECISION_ID" NUMBER(10,0),
    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "DECISION_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "DECISION_DATE" DATE,
    "COMMENT_TEXT" VARCHAR2(4000 CHAR),
    "STAFF_ID" NUMBER(10,0) NOT NULL,
    "RECORD_DATETIME" DATE NOT NULL,
    "ACTIVE_FLAG" VARCHAR2(1 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_REHAB_DECISIONS_PK" PRIMARY KEY ("OFFENDER_REHAB_DECISION_ID"),
     CONSTRAINT "OFF_REHAB_DEC_OFF_BKG_FK" FOREIGN KEY ("OFFENDER_BOOK_ID")
      REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID"),
     CONSTRAINT "OFF_REHAB_DEC_STF_MEM_FK" FOREIGN KEY ("STAFF_ID")
      REFERENCES "STAFF_MEMBERS" ("STAFF_ID")
  );

  CREATE INDEX "OFFENDER_REHAB_DECISIONS_NI1" ON "OFFENDER_REHAB_DECISIONS" ("OFFENDER_BOOK_ID");


  CREATE INDEX "OFFENDER_REHAB_DECISIONS_NI2" ON "OFFENDER_REHAB_DECISIONS" ("STAFF_ID");


  CREATE UNIQUE INDEX "OFFENDER_REHAB_DECISIONS_PK" ON "OFFENDER_REHAB_DECISIONS" ("OFFENDER_REHAB_DECISION_ID");
