
  CREATE TABLE "OFFENDER_PAY_STATUSES"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE,
    "SPECIAL_PAY_TYPE_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_PAY_STATUSES_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "START_DATE")
  );

  CREATE UNIQUE INDEX "OFFENDER_PAY_STATUSES_PK" ON "OFFENDER_PAY_STATUSES" ("OFFENDER_BOOK_ID", "START_DATE");


  CREATE INDEX "OFFENDER_PAY_STATUSES_FK1" ON "OFFENDER_PAY_STATUSES" ("OFFENDER_BOOK_ID");
