CREATE TABLE OFFENDER_PRG_OBLIGATION_HTY (
	OFFENDER_PRG_OBLIGATION_HTY_ID NUMBER(10,0) NOT NULL,
	OFFENDER_PRG_OBLIGATION_ID NUMBER(10,0) NOT NULL,
	STATUS VARCHAR2(12) NOT NULL,
	STATUS_CHANGE_DATE DATE NOT NULL,
	STATUS_CHANGE_REASON VARCHAR2(12),
	CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
	CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
	MODIFY_DATETIME TIMESTAMP,
	MODIFY_USER_ID VARCHAR2(32),
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR2(32),
	AUDIT_MODULE_NAME VARCHAR2(65),
	AUDIT_CLIENT_USER_ID VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO VARCHAR2(256),
	CONSTRAINT OFFENDER_PRG_OBLIGATION_HTY_PK PRIMARY KEY (OFFENDER_PRG_OBLIGATION_HTY_ID),
	CONSTRAINT OFF_PRG_OHTY_OFF_PRG_OBL_FK FOREIGN KEY (OFFENDER_PRG_OBLIGATION_ID) REFERENCES OFFENDER_PRG_OBLIGATIONS(OFFENDER_PRG_OBLIGATION_ID)
);
CREATE INDEX OFFENDER_PRG_OBLIGATION_HTY_N1 ON OFFENDER_PRG_OBLIGATION_HTY (OFFENDER_PRG_OBLIGATION_ID);
CREATE UNIQUE INDEX OFFENDER_PRG_OBLIGATION_HTY_PK ON OFFENDER_PRG_OBLIGATION_HTY (OFFENDER_PRG_OBLIGATION_HTY_ID);
