
  CREATE TABLE "OFFENDER_FREEZE_DISBURSEMENTS"
   (    "OFFENDER_FREEZE_ID" NUMBER(10,0) NOT NULL,
    "CASELOAD_ID" VARCHAR2(6 CHAR) NOT NULL,
    "OFFENDER_ID" NUMBER(10,0) NOT NULL,
    "FROM_DATE" DATE NOT NULL,
    "TO_DATE" DATE NOT NULL,
    "FREEZE_REASON_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_FREEZE_DIS_PK" PRIMARY KEY ("OFFENDER_FREEZE_ID")
  );

  CREATE INDEX "OFFENDER_FREEZE_DISBURSE_NI1" ON "OFFENDER_FREEZE_DISBURSEMENTS" ("OFFENDER_ID", "CASELOAD_ID");


  CREATE UNIQUE INDEX "OFFENDER_FREEZE_DIS_PK" ON "OFFENDER_FREEZE_DISBURSEMENTS" ("OFFENDER_FREEZE_ID");
