
  CREATE TABLE "OFFENDER_VSC_SENTENCE_TERMS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "SENTENCE_SEQ" NUMBER(6,0) NOT NULL,
    "TERM_SEQ" NUMBER(6,0) NOT NULL,
    "SENTENCE_TERM_CODE" VARCHAR2(12 CHAR) NOT NULL,
    "YEARS" NUMBER(3,0),
    "MONTHS" NUMBER(3,0),
    "WEEKS" NUMBER(3,0),
    "DAYS" NUMBER(6,0),
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE,
    "LIFE_SENTENCE_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N',
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "HOURS" NUMBER(3,0),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_VSC_SENTENCE_TERMS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "SENTENCE_SEQ", "TERM_SEQ")
  );

  CREATE UNIQUE INDEX "OFFENDER_VSC_SENTENCE_TERMS_PK" ON "OFFENDER_VSC_SENTENCE_TERMS" ("OFFENDER_BOOK_ID", "SENTENCE_SEQ", "TERM_SEQ");
