
  CREATE TABLE "LOCKED_MODULES"
   (    "MODULE_NAME" VARCHAR2(20 CHAR) NOT NULL,
    "CASELOAD_ID" VARCHAR2(6 CHAR) NOT NULL,
    "USER_ID" VARCHAR2(32 CHAR) NOT NULL,
    "LOCKED_DATE" DATE NOT NULL,
    "OFFENDER_ID" NUMBER(10,0),
    "SESSION_ID" NUMBER(10,0),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "LOCKED_MODULES_PK" PRIMARY KEY ("MODULE_NAME", "CASELOAD_ID")
  );

  CREATE UNIQUE INDEX "LOCKED_MODULES_PK" ON "LOCKED_MODULES" ("MODULE_NAME", "CASELOAD_ID");
