
  CREATE TABLE "HDC_BOARD_DECISIONS"
   (    "DECISION_SEQ" NUMBER(6,0) NOT NULL,
    "HDC_REQUEST_REFERRAL_ID" NUMBER(10,0) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(4000 CHAR) NOT NULL,
    "BOARD_ATTENDEES" VARCHAR2(240 CHAR) NOT NULL,
    "CHAIR_STAFF_ID" NUMBER(10,0) NOT NULL,
    "BOARD_RECOMMENDATION" VARCHAR2(12 CHAR),
    "ATTACH_COMMENT_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "SUCCESSFUL_ROTL_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "OFFENDING_BEHAVIOUR_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "HOME_CIRCUMSTANCES_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "MEDICAL_OFFICER_COMMENT_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "PROBATION_COMMENT_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "THROUGHCARE_TEAM_COMMENT_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "WING_OFFICER_COMMENT_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "LIKELY_TO_FAIL_CURFEW_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "REOFFENDING_PROBABILITY_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "NO_SUITABLE_ACCOMMODATION_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "THREAT_TO_PUBLIC_SAFETY_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "OTHER_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "MESSAGE_ID" VARCHAR2(64 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "HDC_BOARD_DECISIONS_PK" PRIMARY KEY ("HDC_REQUEST_REFERRAL_ID", "DECISION_SEQ")
  );

  CREATE INDEX "HDC_BOARDS_DESC_NI1" ON "HDC_BOARD_DECISIONS" ("CHAIR_STAFF_ID");


  CREATE UNIQUE INDEX "HDC_BOARD_DECISIONS_PK" ON "HDC_BOARD_DECISIONS" ("HDC_REQUEST_REFERRAL_ID", "DECISION_SEQ");
