
  CREATE TABLE "OFFENDER_OGRS3_RISK_PREDICTORS"
   (    "OFF_OGRS3_RISK_PREDICTOR_ID" NUMBER(10,0) NOT NULL,
    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "CURRENT_CONVICTION_AGE" NUMBER(3,0) NOT NULL,
    "FOLLOW_UP_AGE" NUMBER(3,0) NOT NULL,
    "NO_OF_PREVIOUS_SANCTIONS" NUMBER(3,0) NOT NULL,
    "FIRST_SANCTION_AGE" NUMBER(3,0) NOT NULL,
    "OFFENCE_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "ONE_YEAR_RISK" NUMBER(3,0),
    "TWO_YEAR_RISK" NUMBER(3,0),
    "RISK_BAND_CODE" VARCHAR2(12 CHAR),
    "RECORD_DATE" DATE,
    "RECORD_STAFF_ID" NUMBER(10,0),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFF_OGRS3_RISK_PREDICTOR_PK" PRIMARY KEY ("OFF_OGRS3_RISK_PREDICTOR_ID")
  );

  CREATE INDEX "OFF_OGRS3_RP_OFF_BKG_F1" ON "OFFENDER_OGRS3_RISK_PREDICTORS" ("OFFENDER_BOOK_ID");


  CREATE INDEX "OFF_OGRS3_RP_OGR_BD_F1" ON "OFFENDER_OGRS3_RISK_PREDICTORS" ("RISK_BAND_CODE");


  CREATE INDEX "OFF_OGRS3_RP_OGRS3_OGP_F1" ON "OFFENDER_OGRS3_RISK_PREDICTORS" ("OFFENCE_TYPE");


  CREATE INDEX "OFF_OGRS3_RP_SM_F1" ON "OFFENDER_OGRS3_RISK_PREDICTORS" ("RECORD_STAFF_ID");


  CREATE UNIQUE INDEX "OFF_OGRS3_RISK_PREDICTOR_PK" ON "OFFENDER_OGRS3_RISK_PREDICTORS" ("OFF_OGRS3_RISK_PREDICTOR_ID");
