
  CREATE TABLE "OFFENDER_SUBSTANCE_DETAILS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "ROOT_OFFENDER_ID" NUMBER(10,0) NOT NULL,
    "SUBSTANCE_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "SEQ_NUMBER" NUMBER(3,0) NOT NULL,
    "USE_PERIOD" VARCHAR2(32 CHAR),
    "USE_LEVEL" VARCHAR2(12 CHAR) NOT NULL,
    "CASELOAD_TYPE" VARCHAR2(32 CHAR),
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "SOURCE_OF_INFO" VARCHAR2(12 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_SUBSTANCE_DETAILS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "SUBSTANCE_TYPE", "SEQ_NUMBER")
  );

  CREATE UNIQUE INDEX "OFFENDER_SUBSTANCE_DETAILS_PK" ON "OFFENDER_SUBSTANCE_DETAILS" ("OFFENDER_BOOK_ID", "SUBSTANCE_TYPE", "SEQ_NUMBER");
