CREATE TABLE REHABILITATION_PROVIDERS (
    PROVIDER_CODE VARCHAR2(12) NOT NULL,
    DESCRIPTION VARCHAR2(240) NOT NULL,
    PROVIDER_TYPE VARCHAR2(12) NOT NULL,
    LIST_SEQ NUMBER(4,0),
    ACTIVE_FLAG VARCHAR2(1) DEFAULT 'Y' ,
    EXPIRY_DATE DATE,
    CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
    CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
    MODIFY_DATETIME TIMESTAMP,
    MODIFY_USER_ID VARCHAR2(32),
    AUDIT_TIMESTAMP TIMESTAMP,
    AUDIT_USER_ID VARCHAR2(32),
    AUDIT_MODULE_NAME VARCHAR2(65),
    AUDIT_CLIENT_USER_ID VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO VARCHAR2(256),
    CONSTRAINT REHABILITATION_PROVIDERS_PK PRIMARY KEY (PROVIDER_CODE)
);
CREATE UNIQUE INDEX REHABILITATION_PROVIDERS_PK ON REHABILITATION_PROVIDERS (PROVIDER_CODE);
