
  CREATE TABLE "SYSTEM_REPORT_REQUESTS"
   (    "SYSTEM_REPORT_REQUEST_ID" NUMBER(10,0) NOT NULL,
    "OFFENDER_ID" NUMBER(10,0),
    "SYSTEM_REPORT_ID" NUMBER(10,0) NOT NULL,
    "FROM_DATE" DATE,
    "TO_DATE" DATE,
    "SUBMITTED_DATE" DATE NOT NULL,
    "REQUESTED_BY_STAFF_ID" NUMBER(10,0) NOT NULL,
    "COMPLETED_DATE" DATE,
    "REQUEST_STATUS_CODE" VARCHAR2(10 CHAR) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "REQUEST_OUTPUT" BLOB,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "SYSTEM_REPORT_REQUESTS_PK" PRIMARY KEY ("SYSTEM_REPORT_REQUEST_ID")
  );

  CREATE UNIQUE INDEX "SYSTEM_REPORT_REQUESTS_PK" ON "SYSTEM_REPORT_REQUESTS" ("SYSTEM_REPORT_REQUEST_ID");


  CREATE INDEX "SYSTEM_REPORT_REQUESTS_FK1" ON "SYSTEM_REPORT_REQUESTS" ("SYSTEM_REPORT_ID");


  CREATE INDEX "SYSTEM_REPORT_REQUESTS_FK2" ON "SYSTEM_REPORT_REQUESTS" ("OFFENDER_ID");
