
  CREATE TABLE "OFFENDER_RELEASE_DETAILS_HTY"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "RELEASE_DETAIL_SEQ" NUMBER(10,0) NOT NULL,
    "RELEASE_DATE" DATE,
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "MOVEMENT_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "MOVEMENT_REASON_CODE" VARCHAR2(12 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
    "EVENT_ID" NUMBER(10,0) NOT NULL,
    "EVENT_STATUS" VARCHAR2(12 CHAR) NOT NULL,
    "APPROVED_RELEASE_DATE" DATE,
    "AUTO_RELEASE_DATE" DATE,
    "DTO_APPROVED_DATE" DATE,
    "DTO_MID_TERM_DATE" DATE,
    "VERIFIED_FLAG" VARCHAR2(1 CHAR),
     CONSTRAINT "OFFENDER_REL_DETAILS_HTY_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "RELEASE_DETAIL_SEQ")
  );

  CREATE UNIQUE INDEX "OFFENDER_REL_DETAILS_HTY_PK" ON "OFFENDER_RELEASE_DETAILS_HTY" ("OFFENDER_BOOK_ID", "RELEASE_DETAIL_SEQ");
