CREATE TABLE WORK_FLOWS
(
    WORK_FLOW_ID                  NUMBER(10)                             NOT NULL CONSTRAINT WORK_FLOWS_PK PRIMARY KEY,
    OBJECT_CODE                   VARCHAR2(12 CHAR)                      NOT NULL,
    OBJECT_ID                     NUMBER(10)                             NOT NULL,
    OBJECT_SEQ                    NUMBER(6),
    CREATE_DATETIME               TIMESTAMP(9)      DEFAULT SYSTIMESTAMP NOT NULL,
    CREATE_USER_ID                VARCHAR2(32 CHAR) DEFAULT USER         NOT NULL,
    MODIFY_DATETIME               TIMESTAMP(9),
    MODIFY_USER_ID                VARCHAR2(32 CHAR),
    AUDIT_TIMESTAMP               TIMESTAMP(9),
    AUDIT_USER_ID                 VARCHAR2(32 CHAR),
    AUDIT_MODULE_NAME             VARCHAR2(65 CHAR),
    AUDIT_CLIENT_USER_ID          VARCHAR2(64 CHAR),
    AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39 CHAR),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64 CHAR),
    AUDIT_ADDITIONAL_INFO         VARCHAR2(256 CHAR)
);

COMMENT ON TABLE WORK_FLOWS IS 'THE GENERIC WORK FLOW OBJECTS';
COMMENT ON COLUMN WORK_FLOWS.OBJECT_CODE IS 'THE WORK FLOW OBJECT ( THE ALIAS OF THE TABLE)';
COMMENT ON COLUMN WORK_FLOWS.OBJECT_ID IS 'THE FIRST KEY FOR THE MODULE OBJECTS';
COMMENT ON COLUMN WORK_FLOWS.OBJECT_SEQ IS '2RD COMPONENT OF THE PRIMARY KEY';
COMMENT ON COLUMN WORK_FLOWS.CREATE_DATETIME IS 'THE TIMESTAMP WHEN THE RECORD IS CREATED';
COMMENT ON COLUMN WORK_FLOWS.CREATE_USER_ID IS 'THE USER WHO CREATES THE RECORD';
COMMENT ON COLUMN WORK_FLOWS.MODIFY_DATETIME IS 'THE TIMESTAMP WHEN THE RECORD IS MODIFIED';
COMMENT ON COLUMN WORK_FLOWS.MODIFY_USER_ID IS 'THE USER WHO MODIFIES THE RECORD';

CREATE INDEX WORK_FLOWS_NI1 ON WORK_FLOWS (OBJECT_ID, OBJECT_SEQ, OBJECT_CODE);


