
  CREATE TABLE "OFFENDER_DATA_CORRECTIONS_HTY"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "CORRECTION_DATE" DATE NOT NULL,
    "CORRECTION_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "REFERENCE_NO" NUMBER(10,0),
    "COMMENT_TEXT" VARCHAR2(4000 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
    "ACTION_CODE" VARCHAR2(12 CHAR),
    "AGY_LOC_ID" VARCHAR2(6 CHAR),
    "CORRECTION_DATA" BLOB,
     CONSTRAINT "OFF_DATA_CORRECTIONS_HTY_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "CORRECTION_TYPE", "CORRECTION_DATE"),
     CONSTRAINT "OFF_DATA_CORRECTIONS_HTY_FK" FOREIGN KEY ("OFFENDER_BOOK_ID")
      REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID")
  );

  CREATE UNIQUE INDEX "OFF_DATA_CORRECTIONS_HTY_UI" ON "OFFENDER_DATA_CORRECTIONS_HTY" ("OFFENDER_BOOK_ID", "CORRECTION_TYPE", "CORRECTION_DATE");
  CREATE INDEX "OFF_DATA_CORRECTIONS_HTY_NI" ON "OFFENDER_DATA_CORRECTIONS_HTY" ("OFFENDER_BOOK_ID");
