
  CREATE TABLE "OFFENDER_FIXED_TERM_RECALLS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "RETURN_TO_CUSTODY_DATE" DATE NOT NULL,
    "STAFF_ID" NUMBER(10,0) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(4000 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
    "RECALL_LENGTH" NUMBER(12,0) DEFAULT 28 NOT NULL,
     CONSTRAINT "OFF_FIXED_TERM_RECALLS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID")
  );

  CREATE UNIQUE INDEX "OFF_FIXED_TERM_RECALLS_PK" ON "OFFENDER_FIXED_TERM_RECALLS" ("OFFENDER_BOOK_ID");


  CREATE INDEX "OFF_FIXED_TERM_RECALLS_NI1" ON "OFFENDER_FIXED_TERM_RECALLS" ("STAFF_ID");
