
  CREATE TABLE "OFFENDER_SENTENCE_UA_EVENTS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "SENTENCE_SEQ" NUMBER(6,0) NOT NULL,
    "EVENT_ID" NUMBER(10,0) NOT NULL,
    "UNACCPETABLE_ABSENCE_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N',
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
    "COUNTED_FLAG" VARCHAR2(1 CHAR) NOT NULL,
    "EVENT_DATE" DATE NOT NULL,
     CONSTRAINT "OFFENDER_SENTENCE_UA_EVENTS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "SENTENCE_SEQ", "EVENT_ID")
  );

  CREATE INDEX "OFFENDER_SENTENCE_UA_EVENTS_NI" ON "OFFENDER_SENTENCE_UA_EVENTS" ("EVENT_ID");


  CREATE UNIQUE INDEX "OFFENDER_SENTENCE_UA_EVENTS_PK" ON "OFFENDER_SENTENCE_UA_EVENTS" ("OFFENDER_BOOK_ID", "SENTENCE_SEQ", "EVENT_ID");
