
  CREATE TABLE "OFFENDER_ASSESSMENT_ITEMS"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "ASSESSMENT_SEQ" NUMBER(6,0) NOT NULL,
    "ITEM_SEQ" NUMBER(6,0) NOT NULL,
    "ASSESSMENT_ID" NUMBER(10,0) NOT NULL,
    "SCORE" NUMBER(8,2) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(4000 CHAR),
    "PARENT_ASSESSMENT_ID" NUMBER(10,0),
    "RANK" NUMBER(2,0),
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "CREATE_DATE" DATE,
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "MODIFY_DATETIME" TIMESTAMP (9),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_ASSESSMENT_ITEMS_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "ASSESSMENT_SEQ", "ITEM_SEQ")
  );

  CREATE INDEX "OFFENDER_ASSESSMENT_ITEMS_NI1" ON "OFFENDER_ASSESSMENT_ITEMS" ("ASSESSMENT_ID");


  CREATE INDEX "OFFENDER_ASSESSMENT_ITEMS_NI2" ON "OFFENDER_ASSESSMENT_ITEMS" ("PARENT_ASSESSMENT_ID");


  CREATE UNIQUE INDEX "OFFENDER_ASSESSMENT_ITEMS_PK" ON "OFFENDER_ASSESSMENT_ITEMS" ("OFFENDER_BOOK_ID", "ASSESSMENT_SEQ", "ITEM_SEQ");
