
  CREATE TABLE "OFFENDER_SUBSTANCE_USES"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "ROOT_OFFENDER_ID" NUMBER(10,0) NOT NULL,
    "SUBSTANCE_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "AGE_USED" NUMBER(3,0),
    "CASELOAD_TYPE" VARCHAR2(12 CHAR),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "MODIFY_DATETIME" TIMESTAMP (9),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_SUBSTANCE_USES_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "SUBSTANCE_TYPE")
  );

  CREATE UNIQUE INDEX "OFFENDER_SUBSTANCE_USES_PK" ON "OFFENDER_SUBSTANCE_USES" ("OFFENDER_BOOK_ID", "SUBSTANCE_TYPE");
