
  CREATE TABLE "OFFENDER_DAMAGE_OBLIGATIONS"
   (    "OFFENDER_DMG_OBLIGATION_ID" NUMBER(20,0) NOT NULL,
    "OFFENDER_ID" NUMBER(10,0) NOT NULL,
    "REFERENCE_NO" VARCHAR2(20 CHAR) NOT NULL,
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE NOT NULL,
    "AGY_LOC_ID" VARCHAR2(6 CHAR) NOT NULL,
    "AMOUNT_TO_PAY" NUMBER(11,2) NOT NULL,
    "PAID_AMOUNT" NUMBER(11,2),
    "OBLIGATION_STATUS" VARCHAR2(12 CHAR) NOT NULL,
    "COMMENT_TEXT" VARCHAR2(4000 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_DAMAGE_OBLIGATIONS_PK" PRIMARY KEY ("OFFENDER_DMG_OBLIGATION_ID"),
  );

  CREATE UNIQUE INDEX "OFFENDER_DAMAGE_OBLIGATIONS_PK" ON "OFFENDER_DAMAGE_OBLIGATIONS" ("OFFENDER_DMG_OBLIGATION_ID");


  CREATE INDEX "OFFENDER_DMG_OBLIGATIONS_NI1" ON "OFFENDER_DAMAGE_OBLIGATIONS" ("OFFENDER_ID");


  CREATE INDEX "OFFENDER_DMG_OBLIGATIONS_NI2" ON "OFFENDER_DAMAGE_OBLIGATIONS" ("AGY_LOC_ID");
