
  CREATE TABLE "TASK_ASSIGNMENT_HTY"
   (    "TASK_ASSIGNMENT_HTY_ID" NUMBER(10,0) NOT NULL,
    "TASK_ASSIGNMENT_ID" NUMBER(10,0),
    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "WORK_ID" NUMBER(10,0) NOT NULL,
    "ASSIGNMENT_DATE" DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    "ASSIGNMENT_STATUS" VARCHAR2(12 CHAR) DEFAULT 'PEN',
    "TEAM_ID" NUMBER(10,0) NOT NULL,
    "STAFF_ID" NUMBER(10,0),
    "TEAM_MEMBER_ID" NUMBER(10,0),
    "DUE_DATE" DATE,
    "DETAILS" VARCHAR2(4000 CHAR),
    "COMPLETION_DATE" DATE,
    "COMPLETE_REASON_CODE" VARCHAR2(12 CHAR),
    "COMPLETE_COMMENT_TEXT" VARCHAR2(240 CHAR),
    "COMPLETE_USER_ID" VARCHAR2(30 CHAR),
    "MESSAGE_ID" VARCHAR2(64 CHAR),
    "ORIGINAL_MESSAGE_ID" VARCHAR2(64 CHAR),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
    "TRIGGER_NAME" VARCHAR2(12 CHAR),
    "WORKFLOW_HISTORY_ID" NUMBER(32,0),
    "EVENT_DATE" DATE,
     CONSTRAINT "WORK_ASSIGNMENT_HTY_PK" PRIMARY KEY ("TASK_ASSIGNMENT_HTY_ID")
  );

  CREATE UNIQUE INDEX "WORK_ASSIGNMENT_HTY_PK" ON "TASK_ASSIGNMENT_HTY" ("TASK_ASSIGNMENT_HTY_ID");
  CREATE INDEX "TASK_ASSIGNMENT_HTY_NI1" ON "TASK_ASSIGNMENT_HTY" ("TASK_ASSIGNMENT_ID", "TRIGGER_NAME");
  CREATE INDEX "TASK_ASSIGNMENT_HTY_NI2" ON "TASK_ASSIGNMENT_HTY" ("OFFENDER_BOOK_ID");
  CREATE INDEX "WORK_ASSGN_HTY_STF_FK" ON "TASK_ASSIGNMENT_HTY" ("STAFF_ID");
  CREATE INDEX "WORK_ASSGN_HTY_TEAM_FK" ON "TASK_ASSIGNMENT_HTY" ("TEAM_ID");
  CREATE INDEX "WORK_ASSGN_HTY_TEAM_MEMBR_FK" ON "TASK_ASSIGNMENT_HTY" ("TEAM_MEMBER_ID");
  CREATE INDEX "WRK_ASSGN_HTY_WORK_FK" ON "TASK_ASSIGNMENT_HTY" ("WORK_ID");
