
  CREATE TABLE "OIC_HEARING_COMMENTS"
   (    "OIC_HEARING_ID" NUMBER(10,0) NOT NULL,
    "HEARING_COMMENT_SEQ" NUMBER(6,0) DEFAULT 1 NOT NULL,
    "COMMENT_TEXT" VARCHAR2(4000 CHAR) NOT NULL,
    "MODIFY_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER,
    "MODIFY_DATETIME" TIMESTAMP (9) DEFAULT SYSDATE,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OIC_HEARING_COMMENTS_PK" PRIMARY KEY ("OIC_HEARING_ID", "HEARING_COMMENT_SEQ")
  );

  CREATE UNIQUE INDEX "OIC_HEARING_COMMENTS_PK" ON "OIC_HEARING_COMMENTS" ("OIC_HEARING_ID", "HEARING_COMMENT_SEQ");
