
  CREATE TABLE "OFFENDER_LIDS_REMAND_DAYS"
   (    "LIDS_REMAND_DAY_ID" NUMBER(10,0) NOT NULL,
    "LIDS_KEY_DATE_ID" NUMBER(10,0) NOT NULL,
    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "NOMREMANDCOFDAYS" NUMBER(5,0) NOT NULL,
    "NOMREMANDCASENO" NUMBER(5,0) NOT NULL,
    "NOMREMANDOFFENCENO" NUMBER(5,0) NOT NULL,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_LIDS_REMAND_DAYS_PK" PRIMARY KEY ("LIDS_REMAND_DAY_ID")
  );

  CREATE UNIQUE INDEX "OFFENDER_LIDS_REMAND_DAYS_PK" ON "OFFENDER_LIDS_REMAND_DAYS" ("LIDS_REMAND_DAY_ID");


  CREATE INDEX "OFFENDER_LIDS_REMAND_DAYS_FK1" ON "OFFENDER_LIDS_REMAND_DAYS" ("LIDS_KEY_DATE_ID");


  CREATE INDEX "OFFENDER_LIDS_REMAND_DAYS_FK2" ON "OFFENDER_LIDS_REMAND_DAYS" ("OFFENDER_BOOK_ID");
