
  CREATE TABLE "OFFENDER_CASE_ASSOCIATIONS"
   (    "CASE_ID" NUMBER(10,0) NOT NULL,
    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "COMPANION_ID" NUMBER(10,0) NOT NULL,
    "ASSOCIATED_OFF_BOOK_ID" NUMBER(10,0) NOT NULL,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_CASE_ASSOCIATIONS_PK" PRIMARY KEY ("ASSOCIATED_OFF_BOOK_ID", "CASE_ID")
  );

  CREATE INDEX "OFFENDER_CASE_ASSOCIATIONS_FK9" ON "OFFENDER_CASE_ASSOCIATIONS" ("OFFENDER_BOOK_ID");


  CREATE INDEX "OFFENDER_CASE_ASSOCIATIONS_NI1" ON "OFFENDER_CASE_ASSOCIATIONS" ("CASE_ID");


  CREATE UNIQUE INDEX "OFFENDER_CASE_ASSOCIATIONS_PK" ON "OFFENDER_CASE_ASSOCIATIONS" ("ASSOCIATED_OFF_BOOK_ID", "CASE_ID");
