
  CREATE TABLE "HDC_GOVERNOR_DECISIONS"
   (    "DECISION_SEQ" NUMBER(6,0) NOT NULL,
    "HDC_REQUEST_REFERRAL_ID" NUMBER(10,0),
    "COMMENT_TEXT" VARCHAR2(4000 CHAR) NOT NULL,
    "CREATE_USER_ID" VARCHAR2(40 CHAR) DEFAULT USER NOT NULL,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "GOVERNORS_DECISION" VARCHAR2(12 CHAR),
    "GOVERNORS_STAFF_ID" NUMBER(10,0),
    "ATTACH_COMMENT_FLAG" VARCHAR2(1 CHAR) DEFAULT NULL,
    "REFERRAL_TO" VARCHAR2(12 CHAR),
    "REFERRED_STAFF_ID" NUMBER(10,0),
    "MODIFY_USER_ID" VARCHAR2(40 CHAR),
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MESSAGE_ID" VARCHAR2(64 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "HDC_GOVERNOR_DECISIONS_PK" PRIMARY KEY ("HDC_REQUEST_REFERRAL_ID", "DECISION_SEQ")
  );

  CREATE INDEX "HDC_GOV_DESC_NI1" ON "HDC_GOVERNOR_DECISIONS" ("GOVERNORS_STAFF_ID");


  CREATE INDEX "HDC_GOV_DESC_NI2" ON "HDC_GOVERNOR_DECISIONS" ("REFERRED_STAFF_ID");


  CREATE UNIQUE INDEX "HDC_GOVERNOR_DECISIONS_PK" ON "HDC_GOVERNOR_DECISIONS" ("HDC_REQUEST_REFERRAL_ID", "DECISION_SEQ");
