
  CREATE TABLE "OFFENDER_DEDUCTION_RECEIPTS"
   (    "LIST_SEQ" NUMBER(6,0),
    "RECEIPT_PERCENTAGE" NUMBER(5,2),
    "RECEIPT_TXN_TYPE" VARCHAR2(6 CHAR) NOT NULL,
    "OFFENDER_DEDUCTION_ID" NUMBER(10,0) NOT NULL,
    "FLAT_RATE" NUMBER(11,2),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_DEDUCTION_RECEIPTS_PK" PRIMARY KEY ("OFFENDER_DEDUCTION_ID", "RECEIPT_TXN_TYPE")
  );

  CREATE UNIQUE INDEX "OFFENDER_DEDUCTION_RECEIPTS_PK" ON "OFFENDER_DEDUCTION_RECEIPTS" ("OFFENDER_DEDUCTION_ID", "RECEIPT_TXN_TYPE");


  CREATE INDEX "OFF_DR_TXN_TYPE_F1" ON "OFFENDER_DEDUCTION_RECEIPTS" ("RECEIPT_TXN_TYPE");
