
  CREATE TABLE "OFFENDER_DISCHARGE_BALANCES"
   (    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "EVENT_ID" NUMBER(10,0) NOT NULL,
    "DISCHARGE_DATE" DATE NOT NULL,
    "PRIVATE_CASH" NUMBER(13,2),
    "SPENDS" NUMBER(13,2),
    "SAVINGS" NUMBER(13,2),
    "ADVANCES" NUMBER(13,2),
    "HOLDS" NUMBER(13,2),
    "TAB_AMOUNT" NUMBER(13,2),
    "SUBSISTENCE_GRANT" NUMBER(13,2),
    "TRAVEL_GRANT" NUMBER(13,2),
    "DISCHARGE_GRANT" NUMBER(13,2),
    "OPAY_INCLUDE_FLAG" VARCHAR2(1 CHAR),
    "OUTSTANDING_PAY" NUMBER(13,2),
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "OFFENDER_DISCHARGE_BALANCES_PK" PRIMARY KEY ("OFFENDER_BOOK_ID", "EVENT_ID", "DISCHARGE_DATE"),
     CONSTRAINT "OFFENDER_DISCHARGE_BALANCE_FK1" FOREIGN KEY ("OFFENDER_BOOK_ID")
      REFERENCES "OFFENDER_BOOKINGS" ("OFFENDER_BOOK_ID")
  );

  CREATE UNIQUE INDEX "OFFENDER_DISCHARGE_BALANCE_PK" ON "OFFENDER_DISCHARGE_BALANCES" ("OFFENDER_BOOK_ID", "EVENT_ID", "DISCHARGE_DATE");


  CREATE INDEX "OFFENDER_DISCHARGE_BALANCE_UK1" ON "OFFENDER_DISCHARGE_BALANCES" ("EVENT_ID", "OFFENDER_BOOK_ID");
