
  CREATE TABLE "OFFENDER_VISIT_BALANCE_ADJS"
   (    "OFFENDER_VISIT_BALANCE_ADJ_ID" NUMBER(10,0) NOT NULL,
    "OFFENDER_BOOK_ID" NUMBER(10,0) NOT NULL,
    "REMAINING_VO" NUMBER(6,0),
    "PREVIOUS_REMAINING_VO" NUMBER(6,0),
    "REMAINING_PVO" NUMBER(6,0),
    "PREVIOUS_REMAINING_PVO" NUMBER(6,0),
    "ADJUST_REASON_CODE" VARCHAR2(12 CHAR),
    "AUTHORISED_STAFF_ID" NUMBER(10,0),
    "ENDORSED_STAFF_ID" NUMBER(10,0),
    "ADJUST_DATE" DATE,
    "COMMENT_TEXT" VARCHAR2(240 CHAR),
    "EXPIRY_BALANCE" NUMBER(3,0),
    "EXPIRY_DATE" DATE,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
    "EXPIRY_STATUS" VARCHAR2(3 CHAR),
     CONSTRAINT "OFFENDER_VISIT_BALANCE_ADJS_PK" PRIMARY KEY ("OFFENDER_VISIT_BALANCE_ADJ_ID")
  );

  CREATE INDEX "OFF_VIS_BA_OFF_VIS_BAL_FK" ON "OFFENDER_VISIT_BALANCE_ADJS" ("OFFENDER_BOOK_ID");


  CREATE INDEX "OFF_VIS_BA_STF_FK" ON "OFFENDER_VISIT_BALANCE_ADJS" ("AUTHORISED_STAFF_ID");


  CREATE INDEX "OFF_VIS_BA_STF_FK2" ON "OFFENDER_VISIT_BALANCE_ADJS" ("ENDORSED_STAFF_ID");


  CREATE UNIQUE INDEX "OFFENDER_VISIT_BALANCE_ADJS_PK" ON "OFFENDER_VISIT_BALANCE_ADJS" ("OFFENDER_VISIT_BALANCE_ADJ_ID");
