  CREATE TABLE "BENEFICIARY_TRANSACTIONS"
   (    "TXN_ID" NUMBER(10,0) NOT NULL,
    "TXN_ENTRY_SEQ" NUMBER(6,0) NOT NULL,
    "GL_ENTRY_SEQ" NUMBER(6,0) NOT NULL,
    "BEN_ENTRY_SEQ" NUMBER(6,0) NOT NULL,
    "OFFENDER_DEDUCTION_ID" NUMBER(10,0) NOT NULL,
    "ACCOUNT_CODE" NUMBER(6,0) NOT NULL,
    "PERSON_ID" NUMBER(10,0),
    "CORPORATE_ID" NUMBER(10,0),
    "TXN_POST_USAGE" VARCHAR2(12 CHAR) NOT NULL,
    "TXN_ENTRY_DATE" DATE NOT NULL,
    "TXN_ENTRY_TIME" DATE NOT NULL,
    "TXN_ENTRY_AMOUNT" NUMBER(11,2) NOT NULL,
    "CASELOAD_ID" VARCHAR2(12 CHAR) NOT NULL,
    "TXN_TYPE" VARCHAR2(12 CHAR) NOT NULL,
    "TXN_ENTRY_DESC" VARCHAR2(240 CHAR) NOT NULL,
    "CHECK_CLEARED_DATE" DATE,
    "REV_TXN_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N',
    "REV_TXN_ID" NUMBER(10,0),
    "REV_TXN_ENTRY_SEQ" NUMBER(6,0),
    "REV_GL_ENTRY_SEQ" NUMBER(6,0),
    "REV_BEN_ENTRY_SEQ" NUMBER(6,0),
    "MODIFY_USER_ID" VARCHAR2(32 CHAR),
    "MODIFY_DATE" DATE NOT NULL,
    "UNKNOWN_BEN_ID" NUMBER(10,0),
    "BENEFICIARY_CLEARED_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N',
    "RECEIPT_TXN_TYPE" VARCHAR2(6 CHAR) NOT NULL,
    "BENEFICIARY_ID" NUMBER(10,0) NOT NULL,
    "CREATE_DATETIME" TIMESTAMP (9) DEFAULT systimestamp NOT NULL,
    "CREATE_USER_ID" VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    "MODIFY_DATETIME" TIMESTAMP (9),
    "AUDIT_TIMESTAMP" TIMESTAMP (9),
    "AUDIT_USER_ID" VARCHAR2(32 CHAR),
    "AUDIT_MODULE_NAME" VARCHAR2(65 CHAR),
    "AUDIT_CLIENT_USER_ID" VARCHAR2(64 CHAR),
    "AUDIT_CLIENT_IP_ADDRESS" VARCHAR2(39 CHAR),
    "AUDIT_CLIENT_WORKSTATION_NAME" VARCHAR2(64 CHAR),
    "AUDIT_ADDITIONAL_INFO" VARCHAR2(256 CHAR),
     CONSTRAINT "BEN_TXN_CK1" CHECK (       PERSON_ID IS NOT NULL       OR       CORPORATE_ID IS NOT NULL       OR       UNKNOWN_BEN_ID IS NOT NULL       ),
     CONSTRAINT "BENE_TRANSACTION_PK" PRIMARY KEY ("TXN_ID", "TXN_ENTRY_SEQ", "GL_ENTRY_SEQ", "BEN_ENTRY_SEQ"),
     CONSTRAINT "BEN_TXN_OFF_BNC_FK1" FOREIGN KEY ("BENEFICIARY_ID")
      REFERENCES "OFFENDER_BENEFICIARIES" ("BENEFICIARY_ID")
   );


CREATE INDEX BENEFICARY_TRANSACTIONS_NI2 ON BENEFICIARY_TRANSACTIONS (UNKNOWN_BEN_ID);
CREATE INDEX BENEFICARY_TRANSACTIONS_NI3 ON BENEFICIARY_TRANSACTIONS (OFFENDER_DEDUCTION_ID);
CREATE INDEX BENEFICARY_TRANSACTIONS_NI4 ON BENEFICIARY_TRANSACTIONS (CORPORATE_ID);
CREATE INDEX BENEFICARY_TRANSACTIONS_NI5 ON BENEFICIARY_TRANSACTIONS (PERSON_ID);
CREATE INDEX BENEFICIARY_TRANSACTIONS_NI1 ON BENEFICIARY_TRANSACTIONS (ACCOUNT_CODE);
CREATE INDEX BENE_TRANSACTION_PK ON BENEFICIARY_TRANSACTIONS (TXN_ID,TXN_ENTRY_SEQ,GL_ENTRY_SEQ,BEN_ENTRY_SEQ);
CREATE INDEX BEN_TXN_OFF_BNC_FK1 ON BENEFICIARY_TRANSACTIONS (BENEFICIARY_ID);
CREATE INDEX BEN_TXN_TXN_TYP_FK1 ON BENEFICIARY_TRANSACTIONS (RECEIPT_TXN_TYPE);
