CREATE TABLE HDC_PROB_STAFF_COMMENTS (
	HDC_REQUEST_REFERRAL_ID NUMBER(10,0) NOT NULL,
	COMMENT_SEQ NUMBER(5,0) NOT NULL,
	COMMENT_TEXT VARCHAR2(4000) NOT NULL,
	SUITABLE_FLAG VARCHAR2(1) NOT NULL,
	STAFF_ID NUMBER(10,0),
	DATE_CREATED DATE,
	CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
	CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
	MODIFY_DATETIME TIMESTAMP,
	MODIFY_USER_ID VARCHAR2(32),
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR2(32),
	AUDIT_MODULE_NAME VARCHAR2(65),
	AUDIT_CLIENT_USER_ID VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO VARCHAR2(256),
	CONSTRAINT HDC_PROB_STAFF_COMMENTS_PK PRIMARY KEY (HDC_REQUEST_REFERRAL_ID,COMMENT_SEQ),
	CONSTRAINT HDC_PROB_STAF_COM_REQ_REFER_FK FOREIGN KEY (HDC_REQUEST_REFERRAL_ID) REFERENCES HDC_REQUEST_REFERRALS(HDC_REQUEST_REFERRAL_ID),
	CONSTRAINT HDC_PROB_STAF_COM_STAFF_MEM_FK FOREIGN KEY (STAFF_ID) REFERENCES STAFF_MEMBERS(STAFF_ID)
);
CREATE UNIQUE INDEX HDC_PROB_STAFF_COMMENTS_PK ON HDC_PROB_STAFF_COMMENTS (HDC_REQUEST_REFERRAL_ID,COMMENT_SEQ);
CREATE INDEX HDC_PROB_STAFF_COMM_NI1 ON HDC_PROB_STAFF_COMMENTS (STAFF_ID);
