CREATE TABLE INCIDENT_QUESTIONNAIRE_HTY (
	INCIDENT_QUESTIONNAIRE_ID NUMBER(10,0) NOT NULL,
	INCIDENT_CASE_ID NUMBER(10,0) NOT NULL,
	QUESTIONNAIRE_ID NUMBER(10,0) NOT NULL,
	CHANGE_DATE DATE NOT NULL,
	CHANGE_STAFF_ID NUMBER(10,0) NOT NULL,
	CREATE_DATETIME TIMESTAMP DEFAULT systimestamp NOT NULL,
	CREATE_USER_ID VARCHAR2(32) DEFAULT USER NOT NULL,
	MODIFY_DATETIME TIMESTAMP,
	MODIFY_USER_ID VARCHAR2(32),
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR2(32),
	AUDIT_MODULE_NAME VARCHAR2(65),
	AUDIT_CLIENT_USER_ID VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO VARCHAR2(256),
	CONSTRAINT INCIDENT_QUESTIONNAIRE_HTY_PK PRIMARY KEY (INCIDENT_QUESTIONNAIRE_ID),
	CONSTRAINT INC_QUE_HTY_INC_CASE_FK FOREIGN KEY (INCIDENT_CASE_ID) REFERENCES INCIDENT_CASES(INCIDENT_CASE_ID),
	CONSTRAINT INC_QUE_HTY_QUE_FK FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRES(QUESTIONNAIRE_ID)
);
CREATE INDEX INCIDENT_QUESTIONNAIRE_HTY_NI1 ON INCIDENT_QUESTIONNAIRE_HTY (INCIDENT_CASE_ID);
CREATE UNIQUE INDEX INCIDENT_QUESTIONNAIRE_HTY_PK ON INCIDENT_QUESTIONNAIRE_HTY (INCIDENT_QUESTIONNAIRE_ID);
CREATE INDEX INC_QUE_HTY_QUE_FK ON INCIDENT_QUESTIONNAIRE_HTY (QUESTIONNAIRE_ID);
