CREATE TABLE OFFENDER_CSIP_ATTENDEES (
	REVIEW_ID NUMBER(10,0) NOT NULL,
	ATTENDEE_ID NUMBER(10,0) NOT NULL,
	ATTENDEE_NAME VARCHAR2(100),
	ATTENDEE_ROLE VARCHAR2(50),
	ATTENDED VARCHAR2(1) DEFAULT 'N',
	CONTRIBUTION VARCHAR2(500),
	CREATE_DATETIME TIMESTAMP DEFAULT systimestamp,
	CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
	MODIFY_DATETIME TIMESTAMP,
	MODIFY_USER_ID VARCHAR2(32),
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR2(32),
	AUDIT_MODULE_NAME VARCHAR2(65),
	AUDIT_CLIENT_USER_ID VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO VARCHAR2(256),
	CONSTRAINT OFF_CSIP_ATTENDEES_PK PRIMARY KEY (ATTENDEE_ID),
	CONSTRAINT OFF_CSIP_ATT_CSIP_RVW FOREIGN KEY (REVIEW_ID) REFERENCES OFFENDER_CSIP_REVIEWS(REVIEW_ID)
);
CREATE INDEX OFFENDER_CSIP_ATTENDEES_X01 ON OFFENDER_CSIP_ATTENDEES (REVIEW_ID);
CREATE UNIQUE INDEX OFF_CSIP_ATTENDEES_PK ON OFFENDER_CSIP_ATTENDEES (ATTENDEE_ID);
