CREATE TABLE OFFENDER_TRANSACTION_DETAILS (
	TXN_DETAIL_ID NUMBER(10,0),
	TXN_ID NUMBER(10,0) NOT NULL,
	TXN_ENTRY_SEQ NUMBER(6,0) NOT NULL,
	CALENDAR_DATE DATE NOT NULL,
	PAY_TYPE_CODE VARCHAR2(12) NOT NULL,
	EVENT_ID NUMBER(10,0),
	PAY_AMOUNT NUMBER,
	PIECE_WORK NUMBER,
	BONUS_PAY NUMBER,
	CREATE_DATETIME TIMESTAMP DEFAULT systimestamp,
	CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
	MODIFY_DATETIME TIMESTAMP,
	MODIFY_USER_ID VARCHAR2(32),
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR2(32),
	AUDIT_MODULE_NAME VARCHAR2(65),
	AUDIT_CLIENT_USER_ID VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO VARCHAR2(256),
	CONSTRAINT OFFENDER_TXN_DETAILS_PK PRIMARY KEY (TXN_DETAIL_ID),
	CONSTRAINT OFFENDER_TXN_DETAILS_FK FOREIGN KEY (TXN_ID,TXN_ENTRY_SEQ) REFERENCES OFFENDER_TRANSACTIONS(TXN_ID,TXN_ENTRY_SEQ)
);
CREATE INDEX OFFENDER_TXN_DETAILS_FK ON OFFENDER_TRANSACTION_DETAILS (TXN_ID,TXN_ENTRY_SEQ);
CREATE UNIQUE INDEX OFFENDER_TXN_DETAILS_PK ON OFFENDER_TRANSACTION_DETAILS (TXN_DETAIL_ID);
