create table INCIDENT_CASE_REQUIREMENTS
(
  INCIDENT_CASE_ID              NUMBER(10,0)                          NOT NULL,
  REQUIREMENT_SEQ               NUMBER(6,0)     DEFAULT 1             NOT NULL,
  RECORD_STAFF_ID               NUMBER(10,0)                          NOT NULL,
  RECORD_DATE                   DATE            DEFAULT SYSDATE       NOT NULL,
  COMMENT_TEXT                  VARCHAR2(240),
  AGY_LOC_ID                    VARCHAR2(6),
  CREATE_DATETIME               TIMESTAMP       DEFAULT systimestamp  NOT NULL,
  CREATE_USER_ID                VARCHAR2(32)    DEFAULT USER          NOT NULL,
  MODIFY_DATETIME               TIMESTAMP,
  MODIFY_USER_ID                VARCHAR2(32),
  AUDIT_TIMESTAMP               TIMESTAMP,
  AUDIT_USER_ID                 VARCHAR2(32),
  AUDIT_MODULE_NAME             VARCHAR2(65),
  AUDIT_CLIENT_USER_ID          VARCHAR2(64),
  AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
  AUDIT_ADDITIONAL_INFO         VARCHAR2(256),

  CONSTRAINT INCIDENT_CASE_REQUIREMENTS_PK PRIMARY KEY (INCIDENT_CASE_ID,REQUIREMENT_SEQ),
  CONSTRAINT INC_CASE_REQ_AGY_LOC_FK FOREIGN KEY (AGY_LOC_ID) REFERENCES AGENCY_LOCATIONS(AGY_LOC_ID),
  CONSTRAINT INC_CASE_REQ_INC_CASE_FK1 FOREIGN KEY (INCIDENT_CASE_ID) REFERENCES INCIDENT_CASES(INCIDENT_CASE_ID),
  CONSTRAINT INC_CASE_REQ_STF_FK FOREIGN KEY (RECORD_STAFF_ID) REFERENCES STAFF_MEMBERS(STAFF_ID)
);
CREATE UNIQUE INDEX INCIDENT_CASE_REQUIREMENTS_PK ON INCIDENT_CASE_REQUIREMENTS (INCIDENT_CASE_ID,REQUIREMENT_SEQ);
CREATE INDEX INC_CASE_REQ_AGY_LOC_FK ON INCIDENT_CASE_REQUIREMENTS (AGY_LOC_ID);
CREATE INDEX INC_CASE_REQ_STF_FK ON INCIDENT_CASE_REQUIREMENTS (RECORD_STAFF_ID);
