CREATE TABLE LIVING_UNIT_PROFILES (
  PROFILE_ID NUMBER(10,0),
  LIVING_UNIT_ID NUMBER(10,0) NOT NULL,
  AGY_LOC_ID VARCHAR2(6 CHAR) NOT NULL,
  DESCRIPTION VARCHAR2(240 CHAR) NOT NULL,
  INT_LOCATION_PROFILE_TYPE VARCHAR2(12 CHAR) NOT NULL,
  INT_LOCATION_PROFILE_CODE VARCHAR2(12 CHAR) NOT NULL
);

