CREATE TABLE OFFENDER_VO_VISITORS (
	OFFENDER_VO_VISITOR_ID NUMBER(10,0) NOT NULL,
	OFFENDER_VISIT_ORDER_ID NUMBER(10,0) NOT NULL,
	PERSON_ID NUMBER(10,0) NOT NULL,
	GROUP_LEADER_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL,
	CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
	CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
	MODIFY_DATETIME TIMESTAMP,
	MODIFY_USER_ID VARCHAR2(32),
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR2(32),
	AUDIT_MODULE_NAME VARCHAR2(65),
	AUDIT_CLIENT_USER_ID VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO VARCHAR2(256),
	CONSTRAINT VISIT_ORDER_VISITORS_PK PRIMARY KEY (OFFENDER_VO_VISITOR_ID),
	CONSTRAINT OFF_VO_VISR_OFF_VIS_ORD_FK FOREIGN KEY (OFFENDER_VISIT_ORDER_ID) REFERENCES OFFENDER_VISIT_ORDERS(OFFENDER_VISIT_ORDER_ID) ON DELETE CASCADE,
	CONSTRAINT OFF_VO_VISR_PER_FK FOREIGN KEY (PERSON_ID) REFERENCES PERSONS(PERSON_ID)
);
CREATE INDEX OFFENDER_VO_VISITORS_NI1 ON OFFENDER_VO_VISITORS (OFFENDER_VISIT_ORDER_ID);
CREATE INDEX OFFENDER_VO_VISITORS_NI2 ON OFFENDER_VO_VISITORS (PERSON_ID);
CREATE INDEX OFFENDER_VO_VISITORS_X01 ON OFFENDER_VO_VISITORS (OFFENDER_VISIT_ORDER_ID,GROUP_LEADER_FLAG,PERSON_ID);
CREATE UNIQUE INDEX VISIT_ORDER_VISITORS_PK ON OFFENDER_VO_VISITORS (OFFENDER_VO_VISITOR_ID);
