CREATE TABLE OFFENDER_SENT_COND_STATUSES (
	OFFENDER_SENT_CONDITION_ID NUMBER(10,0) NOT NULL,
	STATUS_UPDATE_REASON VARCHAR2(12) NOT NULL,
	STATUS_UPDATE_COMMENT VARCHAR2(400),
	STATUS_UPDATE_DATE DATE DEFAULT sysdate ,
	STATUS_UPDATE_STAFF_ID NUMBER(10,0) NOT NULL,
	OFFENDER_SENT_COND_STATUS_ID NUMBER(10,0) NOT NULL,
	CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
	CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
	MODIFY_DATETIME TIMESTAMP,
	MODIFY_USER_ID VARCHAR2(32),
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR2(32),
	AUDIT_MODULE_NAME VARCHAR2(65),
	AUDIT_CLIENT_USER_ID VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO VARCHAR2(256),
	CONSTRAINT OFFENDER_SENT_COND_STATUSES_PK PRIMARY KEY (OFFENDER_SENT_COND_STATUS_ID),
	CONSTRAINT OFF_SENT_CSTS_LGL_UPD_RSN_FK FOREIGN KEY (STATUS_UPDATE_REASON) REFERENCES LEGAL_UPDATE_REASONS(UPDATE_REASON_CODE),
	CONSTRAINT OFF_SENT_CSTS_OFF_SENT_COND_FK FOREIGN KEY (OFFENDER_SENT_CONDITION_ID) REFERENCES OFFENDER_SENT_CONDITIONS(OFFENDER_SENT_CONDITION_ID)
);
CREATE UNIQUE INDEX OFFENDER_SENT_COND_STATUSES_PK ON OFFENDER_SENT_COND_STATUSES (OFFENDER_SENT_COND_STATUS_ID);
CREATE INDEX OFF_SENT_CSTS_LGL_UPD_RSN_FK ON OFFENDER_SENT_COND_STATUSES (STATUS_UPDATE_REASON);
CREATE INDEX OFF_SENT_CSTS_OFF_SENT_COND_FK ON OFFENDER_SENT_COND_STATUSES (OFFENDER_SENT_CONDITION_ID);
