CREATE TABLE CURFEW_ADDRESS_OCCUPANTS (
	CURFEW_ADDRESS_ID NUMBER(10,0) NOT NULL,
	OCCUPANT_SEQ NUMBER(6,0) NOT NULL,
	PERSON_ID NUMBER(10,0) NOT NULL,
	OCCUPANT_RELATIONSHIP_CODE VARCHAR2(12),
	AGE NUMBER,
	CONTACT_FLAG VARCHAR2(1) DEFAULT NULL,
	PHONE_NO VARCHAR2(40),
	EXT_NO VARCHAR2(7),
	CONTACT_TEXT VARCHAR2(240),
	COMMENT_TEXT VARCHAR2(240),
	CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
	CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
	MODIFY_DATETIME TIMESTAMP,
	MODIFY_USER_ID VARCHAR2(32),
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR2(32),
	AUDIT_MODULE_NAME VARCHAR2(65),
	AUDIT_CLIENT_USER_ID VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO VARCHAR2(256),
	CONSTRAINT CURFEW_ADDR_OCCUPANTS_PK PRIMARY KEY (CURFEW_ADDRESS_ID,OCCUPANT_SEQ),
	CONSTRAINT CUR_ADDR_OCCP_PER_FK FOREIGN KEY (PERSON_ID) REFERENCES PERSONS(PERSON_ID),
	CONSTRAINT CUR_ADDR_OCC_CUR_ADDR_FK FOREIGN KEY (CURFEW_ADDRESS_ID) REFERENCES CURFEW_ADDRESSES(CURFEW_ADDRESS_ID)
);
CREATE INDEX CURFEW_ADDRESS_OCCUPANTS_NI1 ON CURFEW_ADDRESS_OCCUPANTS (PERSON_ID);
CREATE UNIQUE INDEX CURFEW_ADDR_OCCUPANTS_PK ON CURFEW_ADDRESS_OCCUPANTS (CURFEW_ADDRESS_ID,OCCUPANT_SEQ);
