CREATE TABLE OFFENDER_BELIEFS (
  OFFENDER_BOOK_ID NUMBER(10,0) NOT NULL,
  ROOT_OFFENDER_ID NUMBER(10,0) NOT NULL,
  BELIEF_ID NUMBER(10,0) NOT NULL,
  BELIEF_CODE VARCHAR2(12) NOT NULL,
  EFFECTIVE_DATE DATE,
  END_DATE DATE,
  CHANGE_REASON VARCHAR2(1) DEFAULT 'N',
  COMMENTS VARCHAR2(4000),
  VERIFIED_FLAG VARCHAR2(1) DEFAULT 'N',
  CREATE_DATETIME TIMESTAMP DEFAULT systimestamp NOT NULL,
  CREATE_USER_ID VARCHAR2(32) DEFAULT USER NOT NULL,
  MODIFY_DATETIME TIMESTAMP,
  MODIFY_USER_ID VARCHAR2(32),
  AUDIT_TIMESTAMP TIMESTAMP,
  AUDIT_USER_ID VARCHAR2(32),
  AUDIT_MODULE_NAME VARCHAR2(65),
  AUDIT_CLIENT_USER_ID VARCHAR2(64),
  AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
  AUDIT_ADDITIONAL_INFO VARCHAR2(256),
  CONSTRAINT OFF_BEL_PK PRIMARY KEY (BELIEF_ID)
);
CREATE UNIQUE INDEX OFF_BEL_PK ON OFFENDER_BELIEFS (BELIEF_ID);

