CREATE TABLE LINK_CASE_TXNS (
	CASE_ID NUMBER(10,0) NOT NULL,
	COMBINED_CASE_ID NUMBER(10,0) NOT NULL,
	OFFENDER_CHARGE_ID NUMBER(10,0) NOT NULL,
	CREATE_DATETIME TIMESTAMP DEFAULT systimestamp ,
	CREATE_USER_ID VARCHAR2(32) DEFAULT USER ,
	MODIFY_DATETIME TIMESTAMP,
	MODIFY_USER_ID VARCHAR2(32),
	AUDIT_TIMESTAMP TIMESTAMP,
	AUDIT_USER_ID VARCHAR2(32),
	AUDIT_MODULE_NAME VARCHAR2(65),
	AUDIT_CLIENT_USER_ID VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO VARCHAR2(256),
	EVENT_ID NUMBER(10,0),
	CONSTRAINT LINK_CASE_TXNS_PK PRIMARY KEY (CASE_ID,COMBINED_CASE_ID,OFFENDER_CHARGE_ID),
	CONSTRAINT LINK_CASE_TXNS_FK3 FOREIGN KEY (EVENT_ID) REFERENCES COURT_EVENTS(EVENT_ID),
	CONSTRAINT LINK_CASE_TXN_OFF_CASE_FK1 FOREIGN KEY (CASE_ID) REFERENCES OFFENDER_CASES(CASE_ID),
	CONSTRAINT LINK_CASE_TXN_OFF_CASE_FK2 FOREIGN KEY (COMBINED_CASE_ID) REFERENCES OFFENDER_CASES(CASE_ID),
	CONSTRAINT LINK_CASE_TXN_OFF_CHG_FK FOREIGN KEY (OFFENDER_CHARGE_ID) REFERENCES OFFENDER_CHARGES(OFFENDER_CHARGE_ID)
);
CREATE INDEX LINK_CASE_TXNS_FK3 ON LINK_CASE_TXNS (EVENT_ID);
CREATE UNIQUE INDEX LINK_CASE_TXNS_PK ON LINK_CASE_TXNS (CASE_ID,COMBINED_CASE_ID,OFFENDER_CHARGE_ID);
CREATE INDEX LINK_CASE_TXNS_UN1 ON LINK_CASE_TXNS (COMBINED_CASE_ID);
CREATE INDEX LINK_CASE_TXN_OFF_CHG_FK ON LINK_CASE_TXNS (OFFENDER_CHARGE_ID);
