CREATE TABLE INCIDENT_QUE_RESPONSE_HTY (
  INCIDENT_QUESTIONNAIRE_ID NUMBER(10,0) NOT NULL,
  QUESTION_SEQ NUMBER(6,0) NOT NULL,
  RESPONSE_SEQ NUMBER(6,0) NOT NULL,
  RESPONSE_DATE DATE,
  RESPONSE_COMMENT_TEXT VARCHAR2(240),
  RECORD_STAFF_ID NUMBER(10,0) NOT NULL,
  QUESTIONNAIRE_ANS_ID NUMBER(10,0),
  CREATE_DATETIME TIMESTAMP DEFAULT systimestamp NOT NULL,
  CREATE_USER_ID VARCHAR2(32) DEFAULT USER NOT NULL,
  MODIFY_DATETIME TIMESTAMP,
  MODIFY_USER_ID VARCHAR2(32),
  AUDIT_TIMESTAMP TIMESTAMP,
  AUDIT_USER_ID VARCHAR2(32),
  AUDIT_MODULE_NAME VARCHAR2(65),
  AUDIT_CLIENT_USER_ID VARCHAR2(64),
  AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
  AUDIT_ADDITIONAL_INFO VARCHAR2(256),
  CONSTRAINT INCIDENT_QUE_RESPONSE_PK PRIMARY KEY (INCIDENT_QUESTIONNAIRE_ID,QUESTION_SEQ,RESPONSE_SEQ),
  CONSTRAINT INC_QUE_RESP_HTY_QUE_ANS_FK FOREIGN KEY (QUESTIONNAIRE_ANS_ID) REFERENCES QUESTIONNAIRE_ANSWERS(QUESTIONNAIRE_ANS_ID),
  CONSTRAINT INC_QUE_RH_INC_QUE_HTY_FK FOREIGN KEY (INCIDENT_QUESTIONNAIRE_ID,QUESTION_SEQ) REFERENCES INCIDENT_QUE_QUESTION_HTY(INCIDENT_QUESTIONNAIRE_ID,QUESTION_SEQ)
);
CREATE UNIQUE INDEX INCIDENT_QUE_RESPONSE_HTY_PK ON INCIDENT_QUE_RESPONSE_HTY (INCIDENT_QUESTIONNAIRE_ID,QUESTION_SEQ,RESPONSE_SEQ);
CREATE INDEX INC_QUE_RESP_HTY_QUE_ANS_FK ON INCIDENT_QUE_RESPONSE_HTY (QUESTIONNAIRE_ANS_ID);

