CREATE TABLE OFFENDER_IMMIGRATION_APPEALS
(
	OFFENDER_IMMIGRATION_APPEAL_ID              NUMBER(10,0),
	ROOT_OFFENDER_ID                            NUMBER(10,0),
	HEARING_DATE                                DATE,
	APPEAL_OUTCOME                              VARCHAR2(12),
	CREATE_DATETIME                             TIMESTAMP DEFAULT systimestamp,
	CREATE_USER_ID                              VARCHAR2(32) DEFAULT USER ,
	MODIFY_DATETIME                             TIMESTAMP,
	MODIFY_USER_ID                              VARCHAR2(32),
	AUDIT_TIMESTAMP                             TIMESTAMP,
	AUDIT_USER_ID                               VARCHAR2(32),
	AUDIT_MODULE_NAME                           VARCHAR2(65),
	AUDIT_CLIENT_USER_ID                        VARCHAR2(64),
	AUDIT_CLIENT_IP_ADDRESS                     VARCHAR2(39),
	AUDIT_CLIENT_WORKSTATION_NAME               VARCHAR2(64),
	AUDIT_ADDITIONAL_INFO                       VARCHAR2(256),
	CONSTRAINT OFF_IMMIGRATION_APPEALS_PK PRIMARY KEY (OFFENDER_IMMIGRATION_APPEAL_ID),
	CONSTRAINT OFF_IMMIGRATION_APPEALS_FK1 FOREIGN KEY (ROOT_OFFENDER_ID) REFERENCES OFFENDERS(OFFENDER_ID)
);
CREATE INDEX OFF_IMMIGRATION_APPEALS_IX ON OFFENDER_IMMIGRATION_APPEALS (ROOT_OFFENDER_ID);
CREATE UNIQUE INDEX OFF_IMMIGRATION_APPEALS_PK ON OFFENDER_IMMIGRATION_APPEALS (OFFENDER_IMMIGRATION_APPEAL_ID);
