CREATE USER API_PROXY_USER PASSWORD 'pw';

CREATE SCHEMA AUTHORIZATION API_PROXY_USER;
CREATE TABLE API_PROXY_USER.REFRESH_METADATA
(
    LAST_REFRESH_DATE  timestamp(6) default systimestamp,
    SOURCE_BACKUP_DATE timestamp(6)
)
;
