CREATE TABLE VISITOR_RESTRICTIONS
(
    PERSON_ID NUMBER(10, 0)
    , VISIT_RESTRICTION_TYPE VARCHAR2(12 CHAR) NOT NULL
    , EFFECTIVE_DATE DATE NOT NULL
    , EXPIRY_DATE DATE
    , COMMENT_TXT VARCHAR2(240 CHAR)
    , CREATE_DATETIME TIMESTAMP(9) DEFAULT systimestamp NOT NULL
    , CREATE_USER_ID VARCHAR2(32 CHAR) DEFAULT USER NOT NULL
    , MODIFY_DATETIME TIMESTAMP(9)
    , MODIFY_USER_ID VARCHAR2(32 CHAR)
    , VISITOR_RESTRICTION_ID NUMBER(10, 0) NOT NULL
    , ENTERED_STAFF_ID NUMBER(10, 0)
    , OFFENDER_ID NUMBER(10, 0)
    , AUDIT_TIMESTAMP TIMESTAMP(9)
    , AUDIT_USER_ID VARCHAR2(32 CHAR)
    , AUDIT_MODULE_NAME VARCHAR2(65 CHAR)
    , AUDIT_CLIENT_USER_ID VARCHAR2(64 CHAR)
    , AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39 CHAR)
    , AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64 CHAR)
    , AUDIT_ADDITIONAL_INFO VARCHAR2(256 CHAR)
    , CONSTRAINT VISITOR_RESTRICTIONS_PK PRIMARY KEY (VISITOR_RESTRICTION_ID ),
    CONSTRAINT VISITOR_RESTRICTION_PER_FK FOREIGN KEY(PERSON_ID) REFERENCES PERSONS (PERSON_ID)
) ;
CREATE INDEX VISITOR_RESTRICTIONS_NI1 ON VISITOR_RESTRICTIONS (PERSON_ID ASC);
CREATE UNIQUE INDEX VISITOR_RESTRICTIONS_PK ON VISITOR_RESTRICTIONS (VISITOR_RESTRICTION_ID ASC);