-- This migration adds new columns to store explicit recall eligibility and sentence classification

-- Add fields to SENTENCE_CALC_TYPES lookup table
ALTER TABLE SENTENCE_CALC_TYPES ADD IS_RECALLABLE VARCHAR(1);
ALTER TABLE SENTENCE_CALC_TYPES ADD CONSTRAINT CHK_SCT_IS_RECALLABLE CHECK (IS_RECALLABLE IN ('Y', 'N'));
ALTER TABLE SENTENCE_CALC_TYPES ADD SENTENCE_CLASSIFICATION VARCHAR(20);

-- Add fields to OFFENDER_SENTENCES table
ALTER TABLE OFFENDER_SENTENCES ADD IS_RECALLABLE VARCHAR(1);
ALTER TABLE OFFENDER_SENTENCES ADD CONSTRAINT CHK_OS_IS_RECALLABLE CHECK (IS_RECALLABLE IN ('Y', 'N'));
ALTER TABLE OFFENDER_SENTENCES ADD SENTENCE_CLASSIFICATION VARCHAR(20);

-- Create indexes for performance
CREATE INDEX OS_IS_RECALLABLE_IDX ON OFFENDER_SENTENCES(IS_RECALLABLE);
CREATE INDEX OS_SENT_CLASS_IDX ON OFFENDER_SENTENCES(SENTENCE_CLASSIFICATION);