CREATE TABLE SPLASH_CONDITIONS
(
    SPLASH_CONDITION_ID           NUMBER(38, 0),
    SPLASH_ID                     NUMBER(38, 0),
    CONDITION_TYPE                VARCHAR2(12),
    CONDITION_VALUE               VARCHAR2(100),
    BLOCK_ACCESS_YORN             VARCHAR2(1)  DEFAULT 'N',
    CREATE_DATETIME               TIMESTAMP    DEFAULT systimestamp,
    CREATE_USER_ID                VARCHAR2(32) DEFAULT USER,
    MODIFY_DATETIME               TIMESTAMP,
    MODIFY_USER_ID                VARCHAR2(32),
    AUDIT_TIMESTAMP               TIMESTAMP,
    AUDIT_USER_ID                 VARCHAR2(32),
    AUDIT_MODULE_NAME             VARCHAR2(65),
    AUDIT_CLIENT_USER_ID          VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO         VARCHAR2(256),
    CONSTRAINT SPLASH_CONDITIONS_PK PRIMARY KEY (SPLASH_CONDITION_ID),
    CONSTRAINT SPLASH_CONDITIONS_UK1 UNIQUE (SPLASH_ID, CONDITION_TYPE, CONDITION_VALUE),
    CONSTRAINT SYS_C00551447 CHECK ("SPLASH_CONDITION_ID" IS NOT NULL),
    CONSTRAINT SYS_C00551448 CHECK ("SPLASH_ID" IS NOT NULL),
    CONSTRAINT SYS_C00551449 CHECK ("CONDITION_TYPE" IS NOT NULL),
    CONSTRAINT SYS_C00551465 CHECK ("CREATE_DATETIME" IS NOT NULL),
    CONSTRAINT SYS_C00551466 CHECK ("CREATE_USER_ID" IS NOT NULL),
    CONSTRAINT SYS_C00587261 CHECK ("BLOCK_ACCESS_YORN" IS NOT NULL),
    CONSTRAINT SPLASH_CONDITIONS_FK1 FOREIGN KEY (SPLASH_ID) REFERENCES SPLASH_SCREENS (SPLASH_ID)
);
CREATE UNIQUE INDEX SPLASH_CONDITIONS_PK ON SPLASH_CONDITIONS (SPLASH_CONDITION_ID);
CREATE UNIQUE INDEX SPLASH_CONDITIONS_UK1 ON SPLASH_CONDITIONS (SPLASH_ID, CONDITION_TYPE, CONDITION_VALUE);