CREATE TABLE AGY_INT_LOC_PROFILES (
  INTERNAL_LOCATION_ID NUMBER(10,0) NOT NULL,
  INT_LOC_PROFILE_TYPE VARCHAR2(12 CHAR) NOT NULL,
  INT_LOC_PROFILE_CODE VARCHAR2(12 CHAR) NOT NULL,
  CREATE_DATETIME TIMESTAMP DEFAULT systimestamp NOT NULL,
  CREATE_USER_ID VARCHAR2(32) DEFAULT USER NOT NULL,
  MODIFY_DATETIME TIMESTAMP,
  MODIFY_USER_ID VARCHAR2(32),
  AUDIT_TIMESTAMP TIMESTAMP,
  AUDIT_USER_ID VARCHAR2(32),
  AUDIT_MODULE_NAME VARCHAR2(65),
  AUDIT_CLIENT_USER_ID VARCHAR2(64),
  AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
  AUDIT_ADDITIONAL_INFO VARCHAR2(256),
  CONSTRAINT AGY_INT_LOC_PROFILES_PK primary key (INTERNAL_LOCATION_ID, INT_LOC_PROFILE_TYPE, INT_LOC_PROFILE_CODE),
  CONSTRAINT AGY_INT_LOC_PROF_AGY_INT_LOC_F FOREIGN KEY (INTERNAL_LOCATION_ID)  REFERENCES AGENCY_INTERNAL_LOCATIONS (INTERNAL_LOCATION_ID)
);

