CREATE TABLE SERVICE_AGENCY_SWITCHES (
        SERVICE_NAME VARCHAR2(40) NOT NULL,
        AGY_LOC_ID VARCHAR2(6) NOT NULL,
        CREATE_DATETIME TIMESTAMP(9) DEFAULT systimestamp NOT NULL,
        CREATE_USER_ID VARCHAR2(32) DEFAULT USER NOT NULL,
        MODIFY_DATETIME TIMESTAMP(9),
        MODIFY_USER_ID VARCHAR2(32),
        CONSTRAINT SERVICE_AGENCY_SWITCHES_PK PRIMARY KEY (SERVICE_NAME, AGY_LOC_ID),
        CONSTRAINT SERVICE_AGENCY_SWITCHES_FK1 FOREIGN KEY (SERVICE_NAME) REFERENCES EXTERNAL_SERVICES (SERVICE_NAME),
        CONSTRAINT SERVICE_AGENCY_SWITCHES_FK2 FOREIGN KEY (AGY_LOC_ID) REFERENCES AGENCY_LOCATIONS (AGY_LOC_ID)
);