CREATE TABLE AGY_LOC_ESTABLISHMENTS
(
    AGY_LOC_ID VARCHAR2(6 CHAR) NOT NULL,
    ESTABLISHMENT_TYPE VARCHAR2(12 CHAR) NOT NULL,
    CREATE_DATETIME TIMESTAMP(9) DEFAULT systimestamp NOT NULL,
    CREATE_USER_ID VARCHAR2(32 CHAR) DEFAULT USER NOT NULL,
    MODIFY_DATETIME TIMESTAMP(9),
    MODIFY_USER_ID VARCHAR2(32 CHAR),
    AUDIT_TIMESTAMP TIMESTAMP(9),
    AUDIT_USER_ID VARCHAR2(32 CHAR),
    AUDIT_MODULE_NAME VARCHAR2(65 CHAR),
    AUDIT_CLIENT_USER_ID VARCHAR2(64 CHAR),
    AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39 CHAR),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64 CHAR),
    AUDIT_ADDITIONAL_INFO VARCHAR2(256 CHAR),
    CONSTRAINT "AGY_LOC_ESTABLISHMENTS_PK" PRIMARY KEY ("AGY_LOC_ID", "ESTABLISHMENT_TYPE"),
    CONSTRAINT "AGY_LOC_EST_AGY_LOC_FK" FOREIGN KEY ("AGY_LOC_ID") REFERENCES "AGENCY_LOCATIONS" ("AGY_LOC_ID")
);

COMMENT ON TABLE "AGY_LOC_ESTABLISHMENTS" IS 'Categorisation of an establishment (prison).';

COMMENT ON COLUMN "AGY_LOC_ESTABLISHMENTS"."AGY_LOC_ID" IS 'FK to Agency Location';

COMMENT ON COLUMN "AGY_LOC_ESTABLISHMENTS"."ESTABLISHMENT_TYPE" IS 'Reference Code (AGY_EST_TYPE)';

