create schema API_OWNER;

create table API_OWNER.API_OFFENDER_EVENTS
(
    API_EVENT_ID NUMBER(38) not null,
    EVENT_TIMESTAMP TIMESTAMP(9) default systimestamp not null,
    AGY_LOC_ID VARCHAR2(6) not null,
    ROOT_OFFENDER_ID NUMBER(10) not null,
    NOMS_ID VARCHAR2(10) not null,
    EVENT_TYPE VARCHAR2(100) not null,
    CREATE_DATETIME TIMESTAMP(9) default systimestamp not null,
    CREATE_USER_ID VARCHAR2(32) default user not null,
    MODIFY_DATETIME TIMESTAMP(9),
    MODIFY_USER_ID VARCHAR2(32),
    AUDIT_TIMESTAMP TIMESTAMP(9),
    AUDIT_USER_ID VARCHAR2(32),
    AUDIT_MODULE_NAME VARCHAR2(65),
    AUDIT_CLIENT_USER_ID VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO VARCHAR2(256),
    EVENT_DATA_1 VARCHAR2(4000),
    EVENT_DATA_2 VARCHAR2(4000),
    EVENT_DATA_3 VARCHAR2(4000)
);
