-- This migration adds new columns to store explicit recall eligibility and sentence classification

-- Add fields to SENTENCE_CALC_TYPES lookup table
ALTER TABLE SENTENCE_CALC_TYPES ADD (
    IS_RECALLABLE VARCHAR2(1) DEFAULT 'N' NOT NULL CONSTRAINT CHK_SCT_IS_RECALLABLE CHECK (IS_RECALLABLE IN ('Y', 'N')),
    SENTENCE_CLASSIFICATION VARCHAR2(20)
);

COMMENT ON COLUMN SENTENCE_CALC_TYPES.IS_RECALLABLE IS 'Whether sentences of this calculation type are eligible for recall';
COMMENT ON COLUMN SENTENCE_CALC_TYPES.SENTENCE_CLASSIFICATION IS 'Classification of sentence: STANDARD, EXTENDED, INDETERMINATE, RECALL, DTO, FINE, OTHER';

-- Add fields to OFFENDER_SENTENCES table
ALTER TABLE OFFENDER_SENTENCES ADD (
    IS_RECALLABLE VARCHAR2(1) DEFAULT 'N' NOT NULL CONSTRAINT CHK_OS_IS_RECALLABLE CHECK (IS_RECALLABLE IN ('Y', 'N')),
    SENTENCE_CLASSIFICATION VARCHAR2(20)
);

COMMENT ON COLUMN OFFENDER_SENTENCES.IS_RECALLABLE IS 'Whether this specific sentence is eligible for recall';
COMMENT ON COLUMN OFFENDER_SENTENCES.SENTENCE_CLASSIFICATION IS 'Classification of this sentence: STANDARD, EXTENDED, INDETERMINATE, RECALL, DTO, FINE, OTHER';

-- Create indexes for performance
CREATE INDEX OS_IS_RECALLABLE_IDX ON OFFENDER_SENTENCES(IS_RECALLABLE);
CREATE INDEX OS_SENT_CLASS_IDX ON OFFENDER_SENTENCES(SENTENCE_CLASSIFICATION);