CREATE TABLE SPLASH_SCREEN_FUNCS
(
    FUNCTION_NAME                 VARCHAR2(100),
    DESCRIPTION                   VARCHAR2(100),
    CREATE_DATETIME               TIMESTAMP    DEFAULT systimestamp,
    CREATE_USER_ID                VARCHAR2(32) DEFAULT USER,
    MODIFY_DATETIME               TIMESTAMP,
    MODIFY_USER_ID                VARCHAR2(32),
    AUDIT_TIMESTAMP               TIMESTAMP,
    AUDIT_USER_ID                 VARCHAR2(32),
    AUDIT_MODULE_NAME             VARCHAR2(65),
    AUDIT_CLIENT_USER_ID          VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS       VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO         VARCHAR2(256),
    CONSTRAINT SPLASH_SCREEN_FUNCS_PK PRIMARY KEY (FUNCTION_NAME),
    CONSTRAINT SYS_C00551437 CHECK ("FUNCTION_NAME" IS NOT NULL),
    CONSTRAINT SYS_C00551438 CHECK ("DESCRIPTION" IS NOT NULL),
    CONSTRAINT SYS_C00551461 CHECK ("CREATE_DATETIME" IS NOT NULL),
    CONSTRAINT SYS_C00551462 CHECK ("CREATE_USER_ID" IS NOT NULL)
);
CREATE UNIQUE INDEX SPLASH_SCREEN_FUNCS_PK ON SPLASH_SCREEN_FUNCS (FUNCTION_NAME);