CREATE TABLE "OFFENCE_INDICATORS"
(
  "OFFENCE_CODE"                  VARCHAR2(25 CHAR)                 NOT NULL ,
  "STATUTE_CODE"                  VARCHAR2(12 CHAR)                 NOT NULL ,
  "INDICATOR_CODE"                VARCHAR2(1000 CHAR)               NOT NULL ,
  CONSTRAINT "OFFENCE_INDICATORS_PK" PRIMARY KEY ("OFFENCE_CODE", "STATUTE_CODE", "INDICATOR_CODE")
);

