create table HDC_STATUS_REASONS
(
  HDC_STATUS_REASON_ID NUMBER(10) not null constraint HDC_STATUS_REASONS_PK primary key,
  HDC_STATUS_TRACKING_ID NUMBER(10) not null constraint HDC_STATUS_REASONS_FK1 references HDC_STATUS_TRACKINGS,
  STATUS_REASON_CODE VARCHAR2(12 char) not null,
  REASON_SOURCE VARCHAR2(12 char),
  CREATE_DATETIME TIMESTAMP(9) default systimestamp not null,
  CREATE_USER_ID VARCHAR2(32 char) default USER not null,
  MODIFY_DATETIME TIMESTAMP(9),
  MODIFY_USER_ID VARCHAR2(32 char),
  AUDIT_TIMESTAMP TIMESTAMP(9),
  AUDIT_USER_ID VARCHAR2(32 char),
  AUDIT_MODULE_NAME VARCHAR2(65 char),
  AUDIT_CLIENT_USER_ID VARCHAR2(64 char),
  AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39 char),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64 char),
  AUDIT_ADDITIONAL_INFO VARCHAR2(256 char)
);

comment on table HDC_STATUS_REASONS is 'This table tracks the reason for a HDC status change';
