CREATE TABLE OFFENDER_PRG_PRF_PAY_BANDS
(
    OFF_PRGREF_ID                  NUMBER(10)                        NOT NULL,
    START_DATE                     DATE                              NOT NULL,
    END_DATE                       DATE,
    PAY_BAND_CODE                  VARCHAR2(12)                      NOT NULL,
    CREATE_DATETIME                TIMESTAMP(9) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATE_USER_ID                 VARCHAR2(32) DEFAULT USER         NOT NULL,
    MODIFY_DATETIME                TIMESTAMP(9),
    MODIFY_USER_ID                 VARCHAR2(32),
    AUDIT_TIMESTAMP                TIMESTAMP(9),
    AUDIT_USER_ID                  VARCHAR2(32),
    AUDIT_MODULE_NAME              VARCHAR2(65),
    AUDIT_CLIENT_USER_ID           VARCHAR2(64),
    AUDIT_CLIENT_IP_ADDRESS        VARCHAR2(39),
    AUDIT_CLIENT_WORKSTATION_NAME  VARCHAR2(64),
    AUDIT_ADDITIONAL_INFO          VARCHAR2(256),
    CONSTRAINT OFFENDER_PRG_PRF_PAY_BANDS_PK PRIMARY KEY (OFF_PRGREF_ID, START_DATE)
);
COMMENT ON TABLE OFFENDER_PRG_PRF_PAY_BANDS IS 'This row identifies the payment bands associated with an offender for a prison activity';
COMMENT ON COLUMN OFFENDER_PRG_PRF_PAY_BANDS.OFF_PRGREF_ID IS 'The associated identifier to the offenders program profile';
COMMENT ON COLUMN OFFENDER_PRG_PRF_PAY_BANDS.START_DATE IS 'The start date on which the payment band starts';
COMMENT ON COLUMN OFFENDER_PRG_PRF_PAY_BANDS.END_DATE IS 'The end date on which the payment band starts';
COMMENT ON COLUMN OFFENDER_PRG_PRF_PAY_BANDS.PAY_BAND_CODE IS 'The identified payment band for the period';

ALTER TABLE OFFENDER_PRG_PRF_PAY_BANDS ADD CONSTRAINT OFFENDER_PRG_PRF_BANDS_FK1 FOREIGN KEY (OFF_PRGREF_ID) REFERENCES OFFENDER_PROGRAM_PROFILES  (OFF_PRGREF_ID);
