CREATE TABLE COURSE_ACTIVITY_PAY_RATES (
  CRS_ACTY_ID                    NUMBER(10)                        NOT NULL,
  IEP_LEVEL                      VARCHAR2(12)                      NOT NULL,
  PAY_BAND_CODE                  VARCHAR2(12)                      NOT NULL,
  HALF_DAY_RATE                  NUMBER(11, 3)                     NOT NULL,
  START_DATE                     DATE                              NOT NULL,
  END_DATE                       DATE,
  COMMENT_TEXT                   VARCHAR2(240),
  CREATE_DATETIME                TIMESTAMP(9) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATE_USER_ID                 VARCHAR2(32) DEFAULT USER         NOT NULL,
  MODIFY_DATETIME                TIMESTAMP(9),
  MODIFY_USER_ID                 VARCHAR2(32),
  AUDIT_TIMESTAMP                TIMESTAMP(9),
  AUDIT_USER_ID                  VARCHAR2(32),
  AUDIT_MODULE_NAME              VARCHAR2(65),
  AUDIT_CLIENT_USER_ID           VARCHAR2(64),
  AUDIT_CLIENT_IP_ADDRESS        VARCHAR2(39),
  AUDIT_CLIENT_WORKSTATION_NAME  VARCHAR2(64),
  AUDIT_ADDITIONAL_INFO          VARCHAR2(256),
  CONSTRAINT COURSE_ACTIVITY_PAY_RATES_PK PRIMARY KEY (CRS_ACTY_ID, IEP_LEVEL, PAY_BAND_CODE, START_DATE)
);

COMMENT ON TABLE COURSE_ACTIVITY_PAY_RATES IS 'This row identifies the prisoner pay rates for a prison activity';
COMMENT ON COLUMN COURSE_ACTIVITY_PAY_RATES.CRS_ACTY_ID IS 'The associated course activity';
COMMENT ON COLUMN COURSE_ACTIVITY_PAY_RATES.IEP_LEVEL IS 'The IEP level the the rate relates too';
COMMENT ON COLUMN COURSE_ACTIVITY_PAY_RATES.PAY_BAND_CODE IS 'Code to describe the pay band level';
COMMENT ON COLUMN COURSE_ACTIVITY_PAY_RATES.HALF_DAY_RATE IS 'The half daily rate that applies';
COMMENT ON COLUMN COURSE_ACTIVITY_PAY_RATES.START_DATE IS 'The start date for this record to come into affected';
COMMENT ON COLUMN COURSE_ACTIVITY_PAY_RATES.END_DATE IS 'The end date for this record to be affected';
COMMENT ON COLUMN COURSE_ACTIVITY_PAY_RATES.COMMENT_TEXT IS 'Free text comment';

ALTER TABLE COURSE_ACTIVITY_PAY_RATES ADD CONSTRAINT COURSE_ACTIVITY_PAY_RATES_FK1 FOREIGN KEY (CRS_ACTY_ID) REFERENCES COURSE_ACTIVITIES (CRS_ACTY_ID);
