create table HDC_CALC_EXCLUSION_REASONS
(
  HDC_CALC_EXCLUSION_REASON_ID NUMBER(10) not null constraint HDC_CALC_EXCLUSION_REASONS_PK primary key,
  OFFENDER_SENT_CALCULATION_ID NUMBER(10) not null constraint HDC_CALC_EXCLUSION_REASONS_FK1 references OFFENDER_SENT_CALCULATIONS,
  OFFENCE_CODE VARCHAR2(25 char),
  STATUTE_CODE VARCHAR2(12 char),
  REASON_CODE VARCHAR2(20 char),
  CREATE_DATETIME TIMESTAMP(9) default systimestamp not null,
  CREATE_USER_ID VARCHAR2(32 char) default USER not null,
  MODIFY_DATETIME TIMESTAMP(9),
  MODIFY_USER_ID VARCHAR2(32 char),
  AUDIT_TIMESTAMP TIMESTAMP(9),
  AUDIT_USER_ID VARCHAR2(32 char),
  AUDIT_MODULE_NAME VARCHAR2(65 char),
  AUDIT_CLIENT_USER_ID VARCHAR2(64 char),
  AUDIT_CLIENT_IP_ADDRESS VARCHAR2(39 char),
  AUDIT_CLIENT_WORKSTATION_NAME VARCHAR2(64 char),
  AUDIT_ADDITIONAL_INFO VARCHAR2(256 char),
  OFFENDER_BOOK_ID NUMBER(10) not null constraint HDC_CALC_EXCLUSION_REASONS_FK3 references OFFENDER_BOOKINGS,
  constraint HDC_CALC_EXCLUSION_REASONS_FK2 foreign key (OFFENCE_CODE, STATUTE_CODE) references OFFENCES
);

comment on table HDC_CALC_EXCLUSION_REASONS is 'This table details the reason for HDC exculion';

create index HDC_CALC_EXCLUSION_REASONS_FK3 on HDC_CALC_EXCLUSION_REASONS (OFFENDER_BOOK_ID);

create index HDC_CALC_EXCLUSION_REASONS_FK2 on HDC_CALC_EXCLUSION_REASONS (OFFENCE_CODE, STATUTE_CODE);

create index HDC_CALC_EXCLUSION_REASONS_FK1 on HDC_CALC_EXCLUSION_REASONS (OFFENDER_SENT_CALCULATION_ID);
