#%RAML 1.0 DataType
description: Case Note Amendment
properties:
  creationDateTime:
    type: datetime
    description: Date and Time of Case Note creation
  authorName:
    type: string
    description: Name of the user amending the case note (lastname, firstname)
  additionalNoteText:
    type: string
    description: Additional Case Note Information

