#%RAML 1.0 DataType
description: Case Note Type Usage
properties:
  caseNoteType:
    type: string
    description: Case Note Type
  caseNoteSubType:
    type: string
    description: Case Note Sub Type
  offenderNo:
    type: string
    description: Offender No
  numCaseNotes:
    type: integer
    description: Number of case notes of this type/subtype
  latestCaseNote:
    type: datetime
    description: Last case note of this type
