#%RAML 1.0 DataType
description: Physical Attributes
properties:
  gender:
    type: string
    description: Gender
  raceCode:
    type: string
    description: Ethnicity Code
  ethnicity:
    type: string
    description: Ethnicity
  heightFeet:
    type: integer
    description: Height in Feet
  heightInches:
    type: integer
    description: Height in Inches
  heightMetres:
    type: number
    description: Height in Metres (to 2dp)
  heightCentimetres:
    type: integer
    description: Height in Centimetres
  weightPounds:
    type: integer
    description: Weight in Pounds
  weightKilograms:
    type: integer
    description: Weight in Kilograms