#%RAML 1.0 DataType
description: Reference Domain
properties:
  domain:
    type: string
    description: Reference domain name
    example: AREA
  description:
    type: string
    description: Reference domain description.
    example: Probation Area
  domainStatus:
    type: string
    description: Reference domain status.
    example: ACTIVE
  ownerCode:
    type: string
    description: Reference domain owner.
    example: ADMIN
  applnCode:
    type: string
    description: Application that uses reference domain.
    example: OMS
  parentDomain?:
    type: string
    description: Parent domain for reference domain.
    example: INST_AREA