#%RAML 1.0 DataType
description: Staff User Role
type: UserRole

properties:
  username:
    type: string
    description: Staff username
    example: KEITH_GEN
  staffId:
    type: number
    (javaType): Long
    description: Staff Id
    example: 123232