CREATE TABLE CASELOAD_AGENCY_LOCATIONS
(
  "CASELOAD_ID"                   VARCHAR2(6 CHAR),
  "AGY_LOC_ID"                    VARCHAR2(6 CHAR),
  "UPDATE_ALLOWED_FLAG"           VARCHAR2(1 CHAR)  DEFAULT 'Y',
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "SEAL_FLAG"                     VARCHAR2(1 CHAR)
);

CREATE UNIQUE INDEX "CASELOAD_AGENCY_LOCATIONS_PK" ON "CASELOAD_AGENCY_LOCATIONS" ("CASELOAD_ID", "AGY_LOC_ID");

ALTER TABLE "CASELOAD_AGENCY_LOCATIONS" ALTER "CASELOAD_ID" SET NOT NULL;
ALTER TABLE "CASELOAD_AGENCY_LOCATIONS" ALTER "AGY_LOC_ID" SET NOT NULL;
ALTER TABLE "CASELOAD_AGENCY_LOCATIONS" ALTER "UPDATE_ALLOWED_FLAG" SET NOT NULL;
ALTER TABLE "CASELOAD_AGENCY_LOCATIONS" ALTER "CREATE_DATETIME" SET NOT NULL;
ALTER TABLE "CASELOAD_AGENCY_LOCATIONS" ALTER "CREATE_USER_ID" SET NOT NULL;
