CREATE TABLE STAFF_ACCESSIBLE_CASELOADS
(
  CASELOAD_ID         VARCHAR2(6)                        NOT NULL,
  STAFF_ID            NUMBER(6)                          NOT NULL,
  UPDATE_ALLOWED_FLAG VARCHAR2(1)  DEFAULT 'Y'           NOT NULL,
  CREATE_DATETIME     TIMESTAMP(9) DEFAULT SYSTIMESTAMP  NOT NULL,
  CREATE_USER_ID      VARCHAR2(32) DEFAULT user          NOT NULL,
  MODIFY_DATETIME     TIMESTAMP(9) DEFAULT SYSTIMESTAMP,
  MODIFY_USER_ID      VARCHAR2(32),
  SEAL_FLAG           VARCHAR2(1),
  CONSTRAINT STAFF_ACCESSIBLE_CASELOADS_PK
  PRIMARY KEY (STAFF_ID, CASELOAD_ID)
);
CREATE INDEX STAFF_AC_CSLD_F1
  ON STAFF_ACCESSIBLE_CASELOADS (CASELOAD_ID);

CREATE INDEX STAFF_ACCESSIBLE_CASELOADS_NI1
  ON STAFF_ACCESSIBLE_CASELOADS (STAFF_ID);