CREATE TABLE INTERNET_ADDRESSES
(
  "INTERNET_ADDRESS_ID"           NUMBER(10, 0),
  "OWNER_CLASS"                   VARCHAR2(12 CHAR),
  "OWNER_ID"                      NUMBER(10, 0),
  "OWNER_SEQ"                     NUMBER(6, 0),
  "OWNER_CODE"                    VARCHAR2(12 CHAR),
  "INTERNET_ADDRESS_CLASS"        VARCHAR2(12 CHAR) DEFAULT 'EMAIL',
  "INTERNET_ADDRESS"              VARCHAR2(240 CHAR),
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "SEAL_FLAG"                     VARCHAR2(1 CHAR)
);

ALTER TABLE "INTERNET_ADDRESSES" ALTER "INTERNET_ADDRESS_ID" SET NOT NULL;
ALTER TABLE "INTERNET_ADDRESSES" ALTER "OWNER_CLASS" SET NOT NULL;
ALTER TABLE "INTERNET_ADDRESSES" ALTER "INTERNET_ADDRESS_CLASS" SET NOT NULL;
ALTER TABLE "INTERNET_ADDRESSES" ALTER "INTERNET_ADDRESS" SET NOT NULL;
ALTER TABLE "INTERNET_ADDRESSES" ALTER "CREATE_DATETIME" SET NOT NULL;
ALTER TABLE "INTERNET_ADDRESSES" ALTER "CREATE_USER_ID" SET NOT NULL;
