CREATE TABLE OMS_ROLES
(
  "ROLE_ID"                       NUMBER(10, 0),
  "ROLE_NAME"                     VARCHAR2(30 CHAR),
  "ROLE_SEQ"                      NUMBER(3, 0),
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "ROLE_CODE"                     VARCHAR2(30 CHAR),
  "PARENT_ROLE_CODE"              VARCHAR2(30 CHAR),
  "SEAL_FLAG"                     VARCHAR2(1 CHAR)
);

CREATE UNIQUE INDEX "USER_GROUPS_PK" ON "OMS_ROLES" ("ROLE_ID");
CREATE UNIQUE INDEX "OMS_ROLES_UK" ON "OMS_ROLES" ("ROLE_CODE");

ALTER TABLE "OMS_ROLES" ALTER "ROLE_ID" SET NOT NULL;
ALTER TABLE "OMS_ROLES" ALTER "ROLE_NAME" SET NOT NULL;
ALTER TABLE "OMS_ROLES" ALTER "CREATE_DATETIME" SET NOT NULL;
ALTER TABLE "OMS_ROLES" ALTER "CREATE_USER_ID" SET NOT NULL;
ALTER TABLE "OMS_ROLES" ALTER "ROLE_CODE" SET NOT NULL;
