CREATE TABLE SYSTEM_PROFILES
(
  "PROFILE_TYPE"                  VARCHAR2(12 CHAR),
  "PROFILE_CODE"                  VARCHAR2(12 CHAR),
  "DESCRIPTION"                   VARCHAR2(80 CHAR),
  "PROFILE_VALUE"                 VARCHAR2(40 CHAR),
  "PROFILE_VALUE_2"               VARCHAR2(12 CHAR),
  "MODIFY_USER_ID"                VARCHAR2(32 CHAR),
  "OLD_TABLE_NAME"                VARCHAR2(50 CHAR),
  "CREATE_DATETIME"               TIMESTAMP(9)      DEFAULT systimestamp,
  "CREATE_USER_ID"                VARCHAR2(32 CHAR) DEFAULT USER,
  "MODIFY_DATETIME"               TIMESTAMP(9),
  "SEAL_FLAG"                     VARCHAR2(1 CHAR)
);

ALTER TABLE "SYSTEM_PROFILES" ALTER "PROFILE_TYPE" SET NOT NULL;
ALTER TABLE "SYSTEM_PROFILES" ALTER "PROFILE_CODE" SET NOT NULL;
ALTER TABLE "SYSTEM_PROFILES" ALTER "CREATE_DATETIME" SET NOT NULL;
ALTER TABLE "SYSTEM_PROFILES" ALTER "CREATE_USER_ID" SET NOT NULL;
