name: Security OWASP dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "46 8 * * MON-FRI" # Every weekday at 08:46 UTC
jobs:
  security-kotlin-owasp-check:
    name: Kotlin security OWASP dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_owasp.yml@v0.5 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
